#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_US_JTF_ocp_APC_Wheeled_01_apc_qav",
            "ghost_US_JTF_ocp_APC_Wheeled_01_mgs_QAV",
            "ghost_US_JTF_ocp_APC_Wheeled_01_mgs_up_QAV",
            "ghost_US_JTF_ocp_APC_Wheeled_01_shorad_QAV",
            "ghost_US_JTF_ocp_Aegis_B_D_CommandoMortar_RF",
            "ghost_US_JTF_ocp_Aegis_B_D_GMG_01_A_F",
            "ghost_US_JTF_ocp_Aegis_B_D_GMG_01_F",
            "ghost_US_JTF_ocp_Aegis_B_D_GMG_01_high_F",
            "ghost_US_JTF_ocp_Aegis_B_D_HMG_01_A_F",
            "ghost_US_JTF_ocp_Aegis_B_D_HMG_01_F",
            "ghost_US_JTF_ocp_Aegis_B_D_HMG_01_high_F",
            "ghost_US_JTF_ocp_Aegis_B_D_HeavyGunner_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Helicrew_F",
            "ghost_US_JTF_ocp_Aegis_B_D_LSV_01_AT_F",
            "ghost_US_JTF_ocp_Aegis_B_D_LSV_01_armed_F",
            "ghost_US_JTF_ocp_Aegis_B_D_LSV_01_light_F",
            "ghost_US_JTF_ocp_Aegis_B_D_LSV_01_unarmed_F",
            "ghost_US_JTF_ocp_Aegis_B_D_RadioOperator_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Recon_CQ_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Recon_GL_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Recon_MG_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Recon_Sharpshooter",
            "ghost_US_JTF_ocp_Aegis_B_D_Sharpshooter_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Soldier_CQ_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Soldier_MG_F",
            "ghost_US_JTF_ocp_Aegis_B_D_Static_Designator_01_F",
            "ghost_US_JTF_ocp_Aegis_B_D_TwinMortar_RF",
            "ghost_US_JTF_ocp_Aegis_B_D_UAV_01_F",
            "ghost_US_JTF_ocp_Aegis_B_D_UAV_02_lxWS",
            "ghost_US_JTF_ocp_Aegis_B_D_UAV_05_F",
            "ghost_US_JTF_ocp_Aegis_B_D_UGV_02_Demining_F",
            "ghost_US_JTF_ocp_Aegis_B_D_soldier_UGV_02_Demining_F",
            "ghost_US_JTF_ocp_Aegis_B_D_support_CMort_RF",
            "ghost_US_JTF_ocp_Aegis_B_MJTF_D_APC_Wheeled_01_medical_F",
            "ghost_US_JTF_ocp_Atlas_B_D_JSOC_F",
            "ghost_US_JTF_ocp_Atlas_B_D_JSOC_JTAC_F",
            "ghost_US_JTF_ocp_Atlas_B_D_JSOC_LAT_F",
            "ghost_US_JTF_ocp_Atlas_B_D_JSOC_UAV_F",
            "ghost_US_JTF_ocp_Atlas_B_D_JSOC_UAV_lxWS",
            "ghost_US_JTF_ocp_B_AAA_System_01_F",
            "ghost_US_JTF_ocp_B_D_APC_Wheeled_01_atgm_lxWS_v2",
            "ghost_US_JTF_ocp_B_D_APC_Wheeled_01_cannon_lxWS_v2",
            "ghost_US_JTF_ocp_B_D_APC_Wheeled_01_command_lxWS",
            "ghost_US_JTF_ocp_B_D_APC_Wheeled_01_mortar_lxWS",
            "ghost_US_JTF_ocp_B_D_Fighter_Pilot_F",
            "ghost_US_JTF_ocp_B_D_HeliPilot_lxWS",
            "ghost_US_JTF_ocp_B_D_MBT_01_arty_lxWS",
            "ghost_US_JTF_ocp_B_D_MBT_01_mlrs_lxWS",
            "ghost_US_JTF_ocp_B_D_MRAP_01_gmg_lxWS",
            "ghost_US_JTF_ocp_B_D_MRAP_01_hmg_lxWS",
            "ghost_US_JTF_ocp_B_D_MRAP_01_lxWS",
            "ghost_US_JTF_ocp_B_D_Mortar_01_lxWS",
            "ghost_US_JTF_ocp_B_D_Pilot_lxWS",
            "ghost_US_JTF_ocp_B_D_Quadbike_01_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_A_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_GL_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_SL_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_TL_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_lite_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_lxWS",
            "ghost_US_JTF_ocp_B_D_Soldier_unarmed_lxWS",
            "ghost_US_JTF_ocp_B_D_Survivor_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_Repair_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_ammo_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_box_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_cargo_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_covered_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_flatbed_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_fuel_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_medical_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_mover_lxWS",
            "ghost_US_JTF_ocp_B_D_Truck_01_transport_lxWS",
            "ghost_US_JTF_ocp_B_D_VTOL_03_unarmed_QAV",
            "ghost_US_JTF_ocp_B_D_crew_lxWS",
            "ghost_US_JTF_ocp_B_D_engineer_lxWS",
            "ghost_US_JTF_ocp_B_D_medic_lxWS",
            "ghost_US_JTF_ocp_B_D_officer_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_AR_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_JTAC_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_LAT_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_M_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_TL_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_exp_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_lxWS",
            "ghost_US_JTF_ocp_B_D_recon_medic_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_AAA_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_AAR_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_AAT_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_AA_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_AR_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_AT_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_LAT2_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_LAT_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_M_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_PG_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_UAV01_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_UAV02_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_exp_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_mine_lxWS",
            "ghost_US_JTF_ocp_B_D_soldier_repair_lxWS",
            "ghost_US_JTF_ocp_B_D_static_AA_lxWS",
            "ghost_US_JTF_ocp_B_D_static_AT_lxWS",
            "ghost_US_JTF_ocp_B_D_support_AMort_lxWS",
            "ghost_US_JTF_ocp_B_Heli_Light_01_F",
            "ghost_US_JTF_ocp_B_Heli_Light_01_dynamicLoadout_F",
            "ghost_US_JTF_ocp_B_Heli_Light_01_stripped_F",
            "ghost_US_JTF_ocp_B_Heli_Transport_01_F",
            "ghost_US_JTF_ocp_B_Heli_Transport_01_pylons_F",
            "ghost_US_JTF_ocp_B_Heli_Transport_01_unarmed_F",
            "ghost_US_JTF_ocp_B_Heli_Transport_03_F",
            "ghost_US_JTF_ocp_B_Heli_Transport_03_unarmed_F",
            "ghost_US_JTF_ocp_B_Plane_CAS_01_Cluster_F",
            "ghost_US_JTF_ocp_B_Plane_CAS_01_dynamicLoadout_F",
            "ghost_US_JTF_ocp_B_Plane_Fighter_01_Cluster_F",
            "ghost_US_JTF_ocp_B_Plane_Fighter_01_F",
            "ghost_US_JTF_ocp_B_Plane_Fighter_01_Stealth_F",
            "ghost_US_JTF_ocp_B_Radar_System_01_F",
            "ghost_US_JTF_ocp_B_SAM_System_03_F",
            "ghost_US_JTF_ocp_B_SDV_01_F",
            "ghost_US_JTF_ocp_B_T_APC_Wheeled_01_atgm_lxWS",
            "ghost_US_JTF_ocp_B_T_APC_Wheeled_01_cannon_F",
            "ghost_US_JTF_ocp_B_T_Boat_Armed_01_minigun_F",
            "ghost_US_JTF_ocp_B_T_Boat_Transport_01_F",
            "ghost_US_JTF_ocp_B_T_Diver_Exp_F",
            "ghost_US_JTF_ocp_B_T_Diver_F",
            "ghost_US_JTF_ocp_B_T_Diver_TL_F",
            "ghost_US_JTF_ocp_B_T_Sniper_F",
            "ghost_US_JTF_ocp_B_T_Spotter_F",
            "ghost_US_JTF_ocp_B_T_Support_AMG_F",
            "ghost_US_JTF_ocp_B_T_Support_GMG_F",
            "ghost_US_JTF_ocp_B_T_Support_MG_F",
            "ghost_US_JTF_ocp_B_T_Support_Mort_F",
            "ghost_US_JTF_ocp_B_T_VTOL_01_armed_F",
            "ghost_US_JTF_ocp_B_T_VTOL_01_infantry_F",
            "ghost_US_JTF_ocp_B_T_VTOL_01_vehicle_F",
            "ghost_US_JTF_ocp_B_qav_abramsx",
            "ghost_US_JTF_ocp_B_qav_abramsx_templar",
            "ghost_US_JTF_ocp_B_qav_abramsx_tusk",
            "ghost_US_JTF_ocp_E22_B_JC_D_AAA_System_01_F",
            "ghost_US_JTF_ocp_E22_B_JC_D_Radar_system_01_F",
            "ghost_US_JTF_ocp_E22_B_JC_D_SAM_system_01_F",
            "ghost_US_JTF_ocp_EF_B_CombatBoat_AT_NATO_Des",
            "ghost_US_JTF_ocp_EF_B_CombatBoat_HMG_NATO_Des",
            "ghost_US_JTF_ocp_EF_B_CombatBoat_Unarmed_NATO_Des",
            "ghost_US_JTF_ocp_EF_B_MRAP_01_AT_NATO_Des",
            "ghost_US_JTF_ocp_EF_B_MRAP_01_FSV_NATO_Des",
            "ghost_US_JTF_ocp_EF_B_MRAP_01_LAAD_NATO_Des",
            "ghost_US_JTF_ocp_GX_B_HONEYBADGER_UGV_AT_BLACK",
            "ghost_US_JTF_ocp_GX_B_HONEYBADGER_UGV_AT_DESERT",
            "ghost_US_JTF_ocp_GX_B_HONEYBADGER_UGV_AT_GREEN",
            "ghost_US_JTF_ocp_GX_B_HONEYBADGER_UGV_AT_HEX",
            "ghost_US_JTF_ocp_GX_B_HUNTER_SP_LAUNCHER",
            "ghost_US_JTF_ocp_GX_B_HUNTER_SP_UAV",
            "ghost_US_JTF_ocp_GX_B_MAGURA_V5_USV",
            "ghost_US_JTF_ocp_GX_B_MQ8B_UAV_ARMED",
            "ghost_US_JTF_ocp_GX_B_MQ8B_UAV_RECON",
            "ghost_US_JTF_ocp_GX_B_MQ8B_UAV_RECON_SEATED",
            "ghost_US_JTF_ocp_GX_B_RWS_DEFNDER_MEDIUM",
            "ghost_US_JTF_ocp_GX_B_THEMIS_UGV_CARGO",
            "ghost_US_JTF_ocp_GX_B_THEMIS_UGV_DEFNDER_MEDIUM",
            "ghost_US_JTF_ocp_GX_B_THEMIS_UGV_HUNTER_LAUNCHER",
            "ghost_US_JTF_ocp_JK_B_CDF_76n6_ClamShell_F",
            "ghost_US_JTF_ocp_JK_B_CDF_76n6_ClamShell_Lower_F",
            "ghost_US_JTF_ocp_qav_b_ripsaw_Mk44",
            "ghost_US_JTF_ocp_qav_ripsaw_c",
            "ghost_US_JTF_ocp_C_IDAP_UAV_06_antimine_backpack_F",
            "ghost_US_JTF_ocp_C_IDAP_UAV_06_antimine_F",
            "ghost_US_JTF_ocp_B_Heli_Transport_01_medevac_F",
            "ghost_US_JTF_ocp_Drone_Operator"
        };
        weapons[] = {"ghost_US_JTF_ocp_LMG_Mk200_plain_RCO_LP_F_snds","ghost_US_JTF_ocp_MMG_02_sand_RCO_LP_F_snds","ghost_US_JTF_ocp_SMG_01_Holo_F_snds","ghost_US_JTF_ocp_SMG_01_black_Holo_F_snds","ghost_US_JTF_ocp_arifle_MXC_ACO_pointer_F_snds","ghost_US_JTF_ocp_arifle_MXC_F_snds","ghost_US_JTF_ocp_arifle_MXC_Holo_F_snds","ghost_US_JTF_ocp_arifle_MXC_Holo_pointer_F_snds","ghost_US_JTF_ocp_arifle_MXC_khk_ACO_Pointer_F_snds","ghost_US_JTF_ocp_arifle_MXM_MOS_LP_BI_F_snds","ghost_US_JTF_ocp_arifle_MX_ACO_pointer_F_snds","ghost_US_JTF_ocp_arifle_MX_GL_ACO_pointer_F_snds","ghost_US_JTF_ocp_arifle_MX_GL_Hamr_pointer_F_snds","ghost_US_JTF_ocp_arifle_MX_Hamr_pointer_F_snds","ghost_US_JTF_ocp_arifle_MX_Holo_pointer_F_snds","ghost_US_JTF_ocp_arifle_MX_SW_Hamr_pointer_F_snds","ghost_US_JTF_ocp_srifle_DMR_03_tan_AMS_LP_F_snds","ghost_US_JTF_ocp_srifle_LRR_tna_LRPS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
