
class CfgAmmo {
    class BulletBase;
    class GVAR(65x51_Fury_Ammo) : BulletBase {
        ACE_ammoTempMuzzleVelocityShifts[]={-27.2, -26.44, -23.76, -21, -17.54, -13.1, -7.95, -1.62, 6.24, 15.48, 27.75};
        ACE_ballisticCoefficients[]={0.488};
        ACE_Caliber=7.06;
        ACE_bulletLength=27.007;
        ACE_bulletMass=8.7;
        ACE_muzzleVelocityVariationSD=0.15;
        ACE_velocityBoundaries[]={};
        ACE_standardAtmosphere="ASM";
        ACE_dragModel=1;
        ACE_muzzleVelocities[]={915};
        ACE_barrelLengths[]={330};
        hit=15;
        indirectHit=0;
        indirectHitRange=0;
        aiAmmoUsageFlags=64;
        dangerRadiusBulletClose=8;
        dangerRadiusHit=12;
        suppressionRadiusBulletClose=6;
        suppressionRadiusHit=8;
        cost=1.2;
        airLock=1;
        typicalSpeed=915;
        caliber=1;
        model="\A3\Weapons_f\Data\bullettracer\tracer_white";
        cartridge="FxCartridge_65";
        airFriction=-0.0009;
        class CamShakeExplode {
            power=2.44949;
            duration=0.4;
            frequency=20;
            distance=7.34847;
        };
        class CamShakeHit {
            power=6;
            duration=0.4;
            frequency=20;
            distance=1;
        };
    };
    class GVAR(65x51_Fury_Ammo_RT): BulletBase {
        ACE_ammoTempMuzzleVelocityShifts[]={-27.2, -26.44, -23.76, -21, -17.54, -13.1, -7.95, -1.62, 6.24, 15.48, 27.75};
        ACE_ballisticCoefficients[]={0.488};
        ACE_Caliber=7.06;
        ACE_bulletLength=27.007;
        ACE_bulletMass=8.7;
        ACE_muzzleVelocityVariationSD=0.15;
        ACE_velocityBoundaries[]={};
        ACE_standardAtmosphere="ASM";
        ACE_dragModel=1;
        ACE_muzzleVelocities[]={915};
        ACE_barrelLengths[]={330};
        hit=15;
        indirectHit=0;
        indirectHitRange=0;
        aiAmmoUsageFlags=64;
        dangerRadiusBulletClose=8;
        dangerRadiusHit=12;
        suppressionRadiusBulletClose=6;
        suppressionRadiusHit=8;
        cost=1.2;
        airLock=1;
        typicalSpeed=915;
        caliber=1;
        model="\A3\Weapons_f\Data\bullettracer\tracer_red";
        cartridge="FxCartridge_65";
        airFriction=-0.0009;
        tracerStartTime=0.073;
        tracerEndTime=1.57123;
        class CamShakeExplode {
            power=2.44949;
            duration=0.4;
            frequency=20;
            distance=7.34847;
        };
        class CamShakeHit {
            power=6;
            duration=0.4;
            frequency=20;
            distance=1;
        };
    };
    class GVAR(65x51_Fury_Ammo_IR) : BulletBase {
        ACE_ammoTempMuzzleVelocityShifts[]={-27.2, -26.44, -23.76, -21, -17.54, -13.1, -7.95, -1.62, 6.24, 15.48, 27.75};
        ACE_ballisticCoefficients[]={0.488};
        ACE_Caliber=7.06;
        ACE_bulletLength=27.007;
        ACE_bulletMass=8.7;
        ACE_muzzleVelocityVariationSD=0.15;
        ACE_velocityBoundaries[]={};
        ACE_standardAtmosphere="ASM";
        ACE_dragModel=1;
        ACE_muzzleVelocities[]={915};
        ACE_barrelLengths[]={330};
        hit=15;
        indirectHit=0;
        indirectHitRange=0;
        aiAmmoUsageFlags=64;
        dangerRadiusBulletClose=8;
        dangerRadiusHit=12;
        suppressionRadiusBulletClose=6;
        suppressionRadiusHit=8;
        cost=1.2;
        airLock=1;
        typicalSpeed=915;
        caliber=1;
        model="\A3\Weapons_f\Data\bullettracer\tracer_red";
        cartridge="FxCartridge_65";
        airFriction=-0.0009;
        tracerStartTime=0.073;
        tracerEndTime=1.57123;
        nvgOnly = 1;
        class CamShakeExplode {
            power=2.44949;
            duration=0.4;
            frequency=20;
            distance=7.34847;
        };
        class CamShakeHit {
            power=6;
            duration=0.4;
            frequency=20;
            distance=1;
        };
    };
};

