// Generated by tools/gen_us_factions.py - re-run rather than hand-edit.
//
// FORWARD DECLARATIONS, NOT DEPENDENCIES. Every parent below
// belongs to somebody else's mod. Declaring it means a load order
// without that mod gets an inert class rather than a config that
// refuses to build - see requiredAddons in config.cpp.

class CfgVehicles {
    class B_Captain_Dwarden_F;
    class B_GEN_APC_Wheeled_02_hmg_lxWS;
    class B_G_Boat_Transport_02_F;
    class B_GEN_Commander_F;
    class B_GEN_Heli_EC_01_RF;
    class B_GEN_Helipilot_RF;
    class B_GEN_Offroad_01_comms_F;
    class B_GEN_Offroad_01_covered_F;
    class B_GEN_Offroad_01_gen_F;
    class B_GEN_Pickup_covered_rf;
    class B_Quadbike_01_F;
    class B_GEN_Soldier_F;
    class B_GEN_Soldier_RF;
    class B_GEN_Van_02_transport_F;
    class B_GEN_Van_02_vehicle_F;
    class B_GEN_crew_lxWS;
    class EF_B_CombatBoat_Unarmed_GEN;
    class EF_B_Gyra_GEN;
    class EF_B_Gyra_HMG_GEN;

    class GVAR(B_Captain_Dwarden_F): B_Captain_Dwarden_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Dwarden";
        side = 1;
        faction = QUOTE(ADDON);
        uniformClass = "U_B_GEN_Soldier_F";
        weapons[] = {QEGVAR(weapons,arifle_famasF1_RIS_F),QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_RIS_F),QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas),"17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas),"17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        linkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        items[] = {"FirstAidKit"};
        respawnItems[] = {"FirstAidKit"};
        backpack = "";
    };
    class GVAR(B_GEN_APC_Wheeled_02_hmg_lxWS): B_GEN_APC_Wheeled_02_hmg_lxWS {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Otokar ARMA (HMG)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_crew_lxWS);
    };
    class GVAR(B_GEN_Boat_Transport_02_F): B_G_Boat_Transport_02_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "RHIB";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Soldier_F);
    };
    class GVAR(B_GEN_Commander_F): B_GEN_Commander_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gendarmerie Commander";
        side = 1;
        faction = QUOTE(ADDON);
        uniformClass = "U_B_GEN_Soldier_F";
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_F),QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_F),QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        magazines[] = {"30Rnd_556x45_Stanag","17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        linkedItems[] = {"V_PlateCarrier1_blk","H_Beret_gen_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"V_PlateCarrier1_blk","H_Beret_gen_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        items[] = {"FirstAidKit"};
        respawnItems[] = {"FirstAidKit"};
        backpack = "";
    };
    class GVAR(B_GEN_Heli_EC_01_RF): B_GEN_Heli_EC_01_RF {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "H225 Super Puma (Transport)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Helipilot_RF);
    };
    class GVAR(B_GEN_Helipilot_RF): B_GEN_Helipilot_RF {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Helicopter Pilot";
        side = 1;
        faction = QUOTE(ADDON);
        magazines[] = {"30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","17Rnd_9x19_Mag_RF","17Rnd_9x19_Mag_RF","17Rnd_9x19_Mag_RF","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","17Rnd_9x19_Mag_RF","17Rnd_9x19_Mag_RF","17Rnd_9x19_Mag_RF","HandGrenade","SmokeShell"};
    };
    class GVAR(B_GEN_Offroad_01_comms_F): B_GEN_Offroad_01_comms_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Offroad (Comms)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
    class GVAR(B_GEN_Offroad_01_covered_F): B_GEN_Offroad_01_covered_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Offroad (Covered)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
    class GVAR(B_GEN_Offroad_01_gen_F): B_GEN_Offroad_01_gen_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Offroad";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
    class GVAR(B_GEN_Pickup_covered_rf): B_GEN_Pickup_covered_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Covered)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
    class GVAR(B_GEN_Quadbike_01_F): B_Quadbike_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Quad Bike";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Soldier_F);
    };
    class GVAR(B_GEN_Soldier_F): B_GEN_Soldier_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gendarme (SMG)";
        // user, 2026-10-02: the shotgun man a shotgun, the rifleman a marksman rifle, the SMG man an SMG
        side = 1;
        faction = QUOTE(ADDON);
        uniformClass = "U_B_GEN_Soldier_F";
        weapons[] = {"SMG_05_F",QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        respawnWeapons[] = {"SMG_05_F",QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        magazines[] = {"30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        linkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        items[] = {"FirstAidKit"};
        respawnItems[] = {"FirstAidKit"};
        backpack = "";
    };
    class GVAR(B_GEN_Soldier_RF): B_GEN_Soldier_RF {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gendarme (Light)";
        side = 1;
        faction = QUOTE(ADDON);
        uniformClass = "U_B_GEN_Soldier_F";
        weapons[] = {QEGVAR(weapons,arifle_famasF1_Grip_F),QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_Grip_F),QEGVAR(weapons,hgun_G17_black_F),"Throw","Put"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas),"17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas),"17Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        linkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        items[] = {"FirstAidKit"};
        respawnItems[] = {"FirstAidKit"};
        backpack = "";
    };
    class GVAR(B_GEN_Soldier_Rifle_F): B_GEN_Soldier_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gendarme (Rifle)";
        side = 1;
        faction = QUOTE(ADDON);
        uniformClass = "U_B_GEN_Soldier_F";
        linkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        weapons[] = {QEGVAR(weapons,srifle_DMR_06_black_khs_bipod_F),"hgun_P07_F","Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,srifle_DMR_06_black_khs_bipod_F),"hgun_P07_F","Throw","Put"};
        magazines[] = {"20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","HandGrenade","HandGrenade","SmokeShell","SmokeShell"};
        respawnMagazines[] = {"20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","HandGrenade","HandGrenade","SmokeShell","SmokeShell"};
    };
    class GVAR(B_GEN_Soldier_SG_F): B_GEN_Soldier_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gendarme (Shotgun)";
        side = 1;
        faction = QUOTE(ADDON);
        uniformClass = "U_B_GEN_Soldier_F";
        linkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"V_PlateCarrier1_blk","STC_H_MK7_blk_Visor_up_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        weapons[] = {QEGVAR(weapons,sgun_M4_ACO_F),"hgun_P07_F","Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,sgun_M4_ACO_F),"hgun_P07_F","Throw","Put"};
        magazines[] = {"8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Slug","8Rnd_12Gauge_Slug","8Rnd_12Gauge_Slug","8Rnd_12Gauge_Slug","16Rnd_9x21_Mag","16Rnd_9x21_Mag","HandGrenade","HandGrenade","SmokeShell","SmokeShell"};
        respawnMagazines[] = {"8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Pellets","8Rnd_12Gauge_Slug","8Rnd_12Gauge_Slug","8Rnd_12Gauge_Slug","8Rnd_12Gauge_Slug","16Rnd_9x21_Mag","16Rnd_9x21_Mag","HandGrenade","HandGrenade","SmokeShell","SmokeShell"};
    };
    class GVAR(B_GEN_Van_02_transport_F): B_GEN_Van_02_transport_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Van Transport";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Soldier_F);
    };
    class GVAR(B_GEN_Van_02_vehicle_F): B_GEN_Van_02_vehicle_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Van (Cargo)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Soldier_F);
    };
    class GVAR(B_GEN_crew_lxWS): B_GEN_crew_lxWS {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Crewman";
        side = 1;
        faction = QUOTE(ADDON);
        magazines[] = {"30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","HandGrenade","SmokeShell"};
    };
    class GVAR(EF_B_CombatBoat_Unarmed_GEN): EF_B_CombatBoat_Unarmed_GEN {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Combat Boat (Unarmed)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
    class GVAR(EF_B_Gyra_GEN): EF_B_Gyra_GEN {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gyra";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
    class GVAR(EF_B_Gyra_HMG_GEN): EF_B_Gyra_HMG_GEN {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gyra HMG";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(B_GEN_Commander_F);
    };
};
