#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_Russia_ard_AddGis_O_R_ard_Heli_EC_01A_military_F",
            "ghost_Russia_ard_AddGis_O_R_ard_Heli_EC_02_F",
            "ghost_Russia_ard_Aegis_O_R_APC_Tracked_02_30mm_ard_lxWS",
            "ghost_Russia_ard_Aegis_O_R_APC_Tracked_02_30mm_lxWS",
            "ghost_Russia_ard_Aegis_O_R_Conscript_Repair_ard_F",
            "ghost_Russia_ard_Aegis_O_R_Heli_Attack_04_ard_F",
            "ghost_Russia_ard_Aegis_O_R_MBT_02_Railgun_ard_F",
            "ghost_Russia_ard_Aegis_O_R_Sharpshooter_ard_F",
            "ghost_Russia_ard_Aegis_O_R_Truck_02_aa_ard_F",
            "ghost_Russia_ard_Aegis_O_R_UAV_02_ard_lxWS",
            "ghost_Russia_ard_O_R_APC_Tracked_02_AA_ard_F",
            "ghost_Russia_ard_O_R_APC_Tracked_02_medical_ard_F",
            "ghost_Russia_ard_O_R_APC_Wheeled_04_cannon_ard_F",
            "ghost_Russia_ard_O_R_APC_Wheeled_04_cannon_v2_ard_F",
            "ghost_Russia_ard_O_R_Boat_Armed_01_hmg_ard_F",
            "ghost_Russia_ard_O_R_Boat_Transport_01_ard_F",
            "ghost_Russia_ard_O_R_Fighter_Pilot_ard_F",
            "ghost_Russia_ard_O_R_GMG_01_A_ard_F",
            "ghost_Russia_ard_O_R_GMG_01_ard_F",
            "ghost_Russia_ard_O_R_GMG_01_high_ard_F",
            "ghost_Russia_ard_O_R_HMG_01_A_ard_F",
            "ghost_Russia_ard_O_R_HMG_01_ard_F",
            "ghost_Russia_ard_O_R_HMG_01_high_ard_F",
            "ghost_Russia_ard_O_R_Heli_Attack_02_dynamicLoadout_ard_F",
            "ghost_Russia_ard_O_R_Heli_Light_02_dynamicLoadout_ard_F",
            "ghost_Russia_ard_O_R_Heli_Light_02_unarmed_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_ammo_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_bench_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_box_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_covered_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_fuel_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_medevac_ard_F",
            "ghost_Russia_ard_O_R_Heli_Transport_04_repair_ard_F",
            "ghost_Russia_ard_O_R_LSV_02_AT_ard_F",
            "ghost_Russia_ard_O_R_LSV_02_armed_ard_F",
            "ghost_Russia_ard_O_R_LSV_02_unarmed_ard_F",
            "ghost_Russia_ard_O_R_Lifeboat_ard_F",
            "ghost_Russia_ard_O_R_MBT_02_arty_ard_F",
            "ghost_Russia_ard_O_R_MBT_02_cannon_ard_F",
            "ghost_Russia_ard_O_R_MBT_04_cannon_ard_F",
            "ghost_Russia_ard_O_R_MBT_04_command_ard_F",
            "ghost_Russia_ard_O_R_MRAP_02_ard_F",
            "ghost_Russia_ard_O_R_MRAP_02_gmg_ard_F",
            "ghost_Russia_ard_O_R_MRAP_02_hmg_ard_F",
            "ghost_Russia_ard_O_R_Mortar_01_ard_F",
            "ghost_Russia_ard_O_R_Plane_CAS_02_dynamicLoadout_ard_F",
            "ghost_Russia_ard_O_R_Plane_Fighter_02_Stealth_ard_F",
            "ghost_Russia_ard_O_R_Plane_Fighter_02_ard_F",
            "ghost_Russia_ard_O_R_Quadbike_01_ard_F",
            "ghost_Russia_ard_O_R_Radar_System_02_ard_F",
            "ghost_Russia_ard_O_R_RadioOperator_ard_F",
            "ghost_Russia_ard_O_R_SAM_System_04_ard_F",
            "ghost_Russia_ard_O_R_SDV_01_ard_F",
            "ghost_Russia_ard_O_R_Soldier_AAA_ard_F",
            "ghost_Russia_ard_O_R_Soldier_AAR_ard_F",
            "ghost_Russia_ard_O_R_Soldier_AAT_ard_F",
            "ghost_Russia_ard_O_R_Soldier_AHAT_ard_F",
            "ghost_Russia_ard_O_R_Soldier_A_ard_F",
            "ghost_Russia_ard_O_R_Soldier_CBRN_ard_F",
            "ghost_Russia_ard_O_R_Soldier_CQ_ard_F",
            "ghost_Russia_ard_O_R_Soldier_GL_ard_F",
            "ghost_Russia_ard_O_R_Soldier_HAT_ard_F",
            "ghost_Russia_ard_O_R_Soldier_LAT_ard_F",
            "ghost_Russia_ard_O_R_Soldier_PG_ard_F",
            "ghost_Russia_ard_O_R_Soldier_SL_ard_F",
            "ghost_Russia_ard_O_R_Soldier_TL_ard_F",
            "ghost_Russia_ard_O_R_Soldier_ard_F",
            "ghost_Russia_ard_O_R_Soldier_lite_ard_F",
            "ghost_Russia_ard_O_R_Soldier_unarmed_ard_F",
            "ghost_Russia_ard_O_R_Static_AA_ard_F",
            "ghost_Russia_ard_O_R_Static_AT_ard_F",
            "ghost_Russia_ard_O_R_Static_Designator_02_ard_F",
            "ghost_Russia_ard_O_R_Survivor_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_Ammo_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_MRL_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_box_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_cargo_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_flatbed_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_fuel_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_medical_ard_F",
            "ghost_Russia_ard_O_R_Truck_02_transport_ard_F",
            "ghost_Russia_ard_O_R_Truck_03_ammo_ard_F",
            "ghost_Russia_ard_O_R_Truck_03_covered_ard_F",
            "ghost_Russia_ard_O_R_Truck_03_fuel_ard_F",
            "ghost_Russia_ard_O_R_Truck_03_medical_ard_F",
            "ghost_Russia_ard_O_R_Truck_03_repair_ard_F",
            "ghost_Russia_ard_O_R_Truck_03_transport_ard_F",
            "ghost_Russia_ard_O_R_UAV_01_ard_F",
            "ghost_Russia_ard_O_R_UAV_02_dynamicLoadout_ard_F",
            "ghost_Russia_ard_O_R_UAV_06_ard_F",
            "ghost_Russia_ard_O_R_UAV_06_medical_ard_F",
            "ghost_Russia_ard_O_R_UGV_01_ard_F",
            "ghost_Russia_ard_O_R_UGV_01_medical_ard_F",
            "ghost_Russia_ard_O_R_UGV_01_rcws_ard_F",
            "ghost_Russia_ard_O_R_UGV_02_Demining_ard_F",
            "ghost_Russia_ard_O_R_crew_ard_F",
            "ghost_Russia_ard_O_R_diver_TL_ard_F",
            "ghost_Russia_ard_O_R_diver_ard_F",
            "ghost_Russia_ard_O_R_diver_exp_ard_F",
            "ghost_Russia_ard_O_R_engineer_ard_F",
            "ghost_Russia_ard_O_R_ghillie_ard_F",
            "ghost_Russia_ard_O_R_ghillie_lsh_F",
            "ghost_Russia_ard_O_R_ghillie_sard_F",
            "ghost_Russia_ard_O_R_ghillie_spotter_ard_F",
            "ghost_Russia_ard_O_R_ghillie_spotter_lsh_F",
            "ghost_Russia_ard_O_R_ghillie_spotter_sard_F",
            "ghost_Russia_ard_O_R_helicrew_ard_F",
            "ghost_Russia_ard_O_R_helipilot_ard_F",
            "ghost_Russia_ard_O_R_medic_ard_F",
            "ghost_Russia_ard_O_R_officer_ard_F",
            "ghost_Russia_ard_O_R_recon_AR_ard_F",
            "ghost_Russia_ard_O_R_recon_CQ_ard_F",
            "ghost_Russia_ard_O_R_recon_GL_ard_F",
            "ghost_Russia_ard_O_R_recon_JTAC_ard_F",
            "ghost_Russia_ard_O_R_recon_LAT_ard_F",
            "ghost_Russia_ard_O_R_recon_M_ard_F",
            "ghost_Russia_ard_O_R_recon_TL_ard_F",
            "ghost_Russia_ard_O_R_recon_ard_F",
            "ghost_Russia_ard_O_R_recon_exp_ard_F",
            "ghost_Russia_ard_O_R_recon_medic_ard_F",
            "ghost_Russia_ard_O_R_sniper_ard_F",
            "ghost_Russia_ard_O_R_soldier_AA_ard_F",
            "ghost_Russia_ard_O_R_soldier_AR_ard_F",
            "ghost_Russia_ard_O_R_soldier_AT_ard_F",
            "ghost_Russia_ard_O_R_soldier_M_ard_F",
            "ghost_Russia_ard_O_R_soldier_UAV_02_ard_lxWS_F",
            "ghost_Russia_ard_O_R_soldier_UAV_06_ard_F",
            "ghost_Russia_ard_O_R_soldier_UAV_06_medical_ard_F",
            "ghost_Russia_ard_O_R_soldier_UAV_ard_F",
            "ghost_Russia_ard_O_R_soldier_UGV_02_Demining_ard_F",
            "ghost_Russia_ard_O_R_soldier_exp_ard_F",
            "ghost_Russia_ard_O_R_soldier_mine_ard_F",
            "ghost_Russia_ard_O_R_soldier_repair_ard_F",
            "ghost_Russia_ard_O_R_spotter_ard_F",
            "ghost_Russia_ard_O_R_support_AMG_ard_F",
            "ghost_Russia_ard_O_R_support_AMort_ard_F",
            "ghost_Russia_ard_O_R_support_GMG_ard_F",
            "ghost_Russia_ard_O_R_support_MG_ard_F",
            "ghost_Russia_ard_O_R_support_Mort_ard_F",
            "ghost_Russia_ard_ghost_antiship_launcher",
            "ghost_Russia_ard_ghost_antiship_radar",
            "ghost_Russia_ard_O_UAV_03_dynamicLoadout_F",
            "ghost_Russia_ard_O_SwitchBlade_300",
            "ghost_Russia_ard_O_SwitchBlade_600",
            "ghost_Russia_ard_O_SwitchBlade_300_LaunchTube",
            "ghost_Russia_ard_O_SwitchBlade_600_LaunchTube",
            "ghost_Russia_ard_SwitchBlade_Operator",
            "ghost_Russia_ard_rksla3_aeroshark_opfor",
            "ghost_Russia_ard_rksla3_uav_gdt_sa_o",
            "ghost_Russia_ard_rksla3_uav_wkshelter_sa_o",
            "ghost_Russia_ard_O_Rapier_FSC_Launcher",
            "ghost_Russia_ard_O_Rapier_FSC_Blindfire",
            "ghost_Russia_ard_O_Rapier_FSC_Dagger",
            "ghost_Russia_ard_Drone_Operator"
        };
        weapons[] = {"ghost_Russia_ard_Aegis_SMG_Gepard_blk_ACO_F_snds","ghost_Russia_ard_Aegis_arifle_RPK12_545_arco_pointer_F_snds","ghost_Russia_ard_arifle_AK12U_545_F_snds","ghost_Russia_ard_arifle_AK12U_545_aco_F_snds","ghost_Russia_ard_arifle_AK12U_545_aco_flash_F_snds","ghost_Russia_ard_arifle_AK12U_545_aco_pointer_F_snds","ghost_Russia_ard_arifle_AK12U_545_holo_pointer_F_snds","ghost_Russia_ard_arifle_AK12_545_aco_pointer_F_snds","ghost_Russia_ard_arifle_AK12_545_arco_pointer_F_snds","ghost_Russia_ard_arifle_AK12_545_holo_pointer_F_snds","ghost_Russia_ard_arifle_AK12_GL_545_aco_pointer_F_snds","ghost_Russia_ard_arifle_AK12_GL_545_arco_pointer_F_snds","ghost_Russia_ard_sgun_Mp153_black_F_snds","ghost_Russia_ard_srifle_DMR_01_black_DMS_LP_BI_F_snds","ghost_Russia_ard_srifle_DMR_05_DMS_LP_BI_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
