// Generated by tools/gen_aceax.py -- do not edit by hand.
class mxa_arsenal_stubby_sound_suppressor_6_5_mm
{
    label = "Stubby Sound Suppressor (6.5 mm)";
    author = "2040 mission arsenal";
    options[] = {"camo"};
    class camo
    {
        values[] = {"STD", "KHK", "SND", "ARID", "LUSH", "SNAKE"};
    };
};
