// Generated by tools/gen_aceax.py -- do not edit by hand.
class mxa_arsenal_vortex_spitfire_prism
{
    label = "Vortex Spitfire Prism";
    author = "2040 mission arsenal";
    options[] = {"camo"};
    class camo
    {
        values[] = {"STD", "KHK", "TAN"};
    };
};
