// Generated by tools/gen_aceax.py -- do not edit by hand.
class mxa_arsenal_sound_suppressor_5_56_mm
{
    label = "Sound Suppressor (5.56 mm)";
    author = "2040 mission arsenal";
    options[] = {"camo"};
    class camo
    {
        values[] = {"STD", "KHK", "SND", "STRIPES"};
    };
};
