// Generated by tools/gen_aceax.py -- do not edit by hand.
class mxa_arsenal_ghost_mbs_remote_xm157
{
    label = "[Ghost] MBS Remote XM157";
    author = "2040 mission arsenal";
    options[] = {"camo"};
    class camo
    {
        values[] = {"STD", "KHK", "SND", "CBR"};
    };
};
