// Generated by tools/gen_aceax.py -- do not edit by hand.
class mxa_arsenal_m115a3_bipod
{
    label = "M115A3 Bipod";
    author = "2040 mission arsenal";
    options[] = {"mount"};
    class mount : mxa_mount
    {
        values[] = {"FORWARD", "REARWARD"};
    };
};
