// Generated by tools/gen_aceax.py -- do not edit by hand.
class mxa_arsenal_eotech_xps3_smg
{
    label = "EOTech XPS3 SMG";
    author = "2040 mission arsenal";
    options[] = {"camo"};
    class camo
    {
        values[] = {"BLK", "KHK", "TAN", "SNAKE"};
    };
};
