#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_US_tna_ACE_B_T_SpottingScope",
            "ghost_US_tna_Aegis_B_T_AH99J_EF",
            "ghost_US_tna_Aegis_B_T_CommandoMortar_RF",
            "ghost_US_tna_Aegis_B_T_Heli_Attack_03_F",
            "ghost_US_tna_Aegis_B_T_Heli_EC_03_RF",
            "ghost_US_tna_Aegis_B_T_Heli_EC_04_military_RF",
            "ghost_US_tna_Aegis_B_T_UAV_02_lxWS",
            "ghost_US_tna_Aegis_B_T_support_CMort_RF",
            "ghost_US_tna_Atlas_B_T_JSOC_AR_F",
            "ghost_US_tna_Atlas_B_T_JSOC_Exp_F",
            "ghost_US_tna_Atlas_B_T_JSOC_F",
            "ghost_US_tna_Atlas_B_T_JSOC_GL_F",
            "ghost_US_tna_Atlas_B_T_JSOC_JTAC_F",
            "ghost_US_tna_Atlas_B_T_JSOC_LAT_F",
            "ghost_US_tna_Atlas_B_T_JSOC_M_F",
            "ghost_US_tna_Atlas_B_T_JSOC_Medic_F",
            "ghost_US_tna_Atlas_B_T_JSOC_SL_F",
            "ghost_US_tna_Atlas_B_T_JSOC_Sharpshooter_F",
            "ghost_US_tna_Atlas_B_T_JSOC_TL_F",
            "ghost_US_tna_Atlas_B_T_JSOC_UAV_F",
            "ghost_US_tna_Atlas_B_T_JSOC_UAV_lxWS",
            "ghost_US_tna_B_SDV_01_F",
            "ghost_US_tna_B_T_AFV_Wheeled_01_cannon_F",
            "ghost_US_tna_B_T_AFV_Wheeled_01_up_cannon_F",
            "ghost_US_tna_B_T_APC_Tracked_01_AA_F",
            "ghost_US_tna_B_T_APC_Tracked_01_CRV_F",
            "ghost_US_tna_B_T_APC_Tracked_01_rcws_F",
            "ghost_US_tna_B_T_APC_Wheeled_01_apc_QAV",
            "ghost_US_tna_B_T_APC_Wheeled_01_atgm_lxWS_v2",
            "ghost_US_tna_B_T_APC_Wheeled_01_cannon_v2_F",
            "ghost_US_tna_B_T_APC_Wheeled_01_command_lxWS",
            "ghost_US_tna_B_T_APC_Wheeled_01_medical_F",
            "ghost_US_tna_B_T_APC_Wheeled_01_mgs_QAV",
            "ghost_US_tna_B_T_APC_Wheeled_01_mgs_up_QAV",
            "ghost_US_tna_B_T_APC_Wheeled_01_mortar_lxWS",
            "ghost_US_tna_B_T_APC_Wheeled_01_shorad_QAV",
            "ghost_US_tna_B_T_Boat_Armed_01_minigun_F",
            "ghost_US_tna_B_T_Boat_Transport_01_F",
            "ghost_US_tna_B_T_Crew_F",
            "ghost_US_tna_B_T_Diver_Exp_F",
            "ghost_US_tna_B_T_Diver_F",
            "ghost_US_tna_B_T_Diver_TL_F",
            "ghost_US_tna_B_T_Engineer_F",
            "ghost_US_tna_B_T_Fighter_Pilot_F",
            "ghost_US_tna_B_T_GMG_01_A_F",
            "ghost_US_tna_B_T_GMG_01_F",
            "ghost_US_tna_B_T_GMG_01_high_F",
            "ghost_US_tna_B_T_HMG_01_A_F",
            "ghost_US_tna_B_T_HMG_01_F",
            "ghost_US_tna_B_T_HMG_01_high_F",
            "ghost_US_tna_B_T_HMG_02_F",
            "ghost_US_tna_B_T_HMG_02_high_F",
            "ghost_US_tna_B_T_HeavyGunner_F",
            "ghost_US_tna_B_T_Heli_Attack_01_dynamicLoadout_F",
            "ghost_US_tna_B_T_Heli_Light_01_dynamicLoadout_F",
            "ghost_US_tna_B_T_Heli_Transport_01_F",
            "ghost_US_tna_B_T_Heli_Transport_01_medevac_F",
            "ghost_US_tna_B_T_Heli_Transport_03_F",
            "ghost_US_tna_B_T_Heli_Transport_03_unarmed_F",
            "ghost_US_tna_B_T_Heli_light_01_F",
            "ghost_US_tna_B_T_Helicrew_F",
            "ghost_US_tna_B_T_Helipilot_F",
            "ghost_US_tna_B_T_LSV_01_AT_F",
            "ghost_US_tna_B_T_LSV_01_armed_F",
            "ghost_US_tna_B_T_LSV_01_light_F",
            "ghost_US_tna_B_T_LSV_01_unarmed_F",
            "ghost_US_tna_B_T_Lifeboat",
            "ghost_US_tna_B_T_MBT_01_TUSK_F",
            "ghost_US_tna_B_T_MBT_01_arty_F",
            "ghost_US_tna_B_T_MBT_01_cannon_F",
            "ghost_US_tna_B_T_MBT_01_mlrs_F",
            "ghost_US_tna_B_T_MRAP_01_F",
            "ghost_US_tna_B_T_MRAP_01_gmg_F",
            "ghost_US_tna_B_T_MRAP_01_hmg_F",
            "ghost_US_tna_B_T_Medic_F",
            "ghost_US_tna_B_T_Mortar_01_F",
            "ghost_US_tna_B_T_Officer_F",
            "ghost_US_tna_B_T_Pilot_F",
            "ghost_US_tna_B_T_Plane_CAS_01_dynamicLoadout_F",
            "ghost_US_tna_B_T_Plane_Fighter_01_F",
            "ghost_US_tna_B_T_Plane_Fighter_01_Stealth_F",
            "ghost_US_tna_B_T_Plane_Fighter_05_F",
            "ghost_US_tna_B_T_Plane_Fighter_05_Stealth_F",
            "ghost_US_tna_B_T_Quadbike_01_F",
            "ghost_US_tna_B_T_Radar_System_01_F",
            "ghost_US_tna_B_T_RadioOperator_F",
            "ghost_US_tna_B_T_Recon_AR_F",
            "ghost_US_tna_B_T_Recon_CQ_F",
            "ghost_US_tna_B_T_Recon_Exp_F",
            "ghost_US_tna_B_T_Recon_F",
            "ghost_US_tna_B_T_Recon_GL_F",
            "ghost_US_tna_B_T_Recon_JTAC_F",
            "ghost_US_tna_B_T_Recon_LAT_F",
            "ghost_US_tna_B_T_Recon_MG_F",
            "ghost_US_tna_B_T_Recon_M_F",
            "ghost_US_tna_B_T_Recon_Medic_F",
            "ghost_US_tna_B_T_Recon_Sharpshooter_F",
            "ghost_US_tna_B_T_Recon_TL_F",
            "ghost_US_tna_B_T_SAM_System_03_F",
            "ghost_US_tna_B_T_SDV_01_F",
            "ghost_US_tna_B_T_Sharpshooter_F",
            "ghost_US_tna_B_T_Sniper_F",
            "ghost_US_tna_B_T_Soldier_AAA_F",
            "ghost_US_tna_B_T_Soldier_AAR_F",
            "ghost_US_tna_B_T_Soldier_AAT_F",
            "ghost_US_tna_B_T_Soldier_AA_F",
            "ghost_US_tna_B_T_Soldier_AR_F",
            "ghost_US_tna_B_T_Soldier_AT_F",
            "ghost_US_tna_B_T_Soldier_A_F",
            "ghost_US_tna_B_T_Soldier_CBRN_F",
            "ghost_US_tna_B_T_Soldier_CQ_F",
            "ghost_US_tna_B_T_Soldier_Exp_F",
            "ghost_US_tna_B_T_Soldier_F",
            "ghost_US_tna_B_T_Soldier_GL_F",
            "ghost_US_tna_B_T_Soldier_LAT2_F",
            "ghost_US_tna_B_T_Soldier_LAT_F",
            "ghost_US_tna_B_T_Soldier_Lite_F",
            "ghost_US_tna_B_T_Soldier_MG_F",
            "ghost_US_tna_B_T_Soldier_PG_F",
            "ghost_US_tna_B_T_Soldier_Repair_F",
            "ghost_US_tna_B_T_Soldier_SL_F",
            "ghost_US_tna_B_T_Soldier_TL_F",
            "ghost_US_tna_B_T_Soldier_UAV_F",
            "ghost_US_tna_B_T_Soldier_unarmed_F",
            "ghost_US_tna_B_T_Spotter_F",
            "ghost_US_tna_B_T_Static_AA_F",
            "ghost_US_tna_B_T_Static_AT_F",
            "ghost_US_tna_B_T_Static_Designator_01_F",
            "ghost_US_tna_B_T_Support_AMG_F",
            "ghost_US_tna_B_T_Support_AMort_F",
            "ghost_US_tna_B_T_Support_GMG_F",
            "ghost_US_tna_B_T_Support_MG_F",
            "ghost_US_tna_B_T_Support_Mort_F",
            "ghost_US_tna_B_T_Survivor_F",
            "ghost_US_tna_B_T_Truck_01_FFT_rf",
            "ghost_US_tna_B_T_Truck_01_Repair_F",
            "ghost_US_tna_B_T_Truck_01_ammo_F",
            "ghost_US_tna_B_T_Truck_01_box_F",
            "ghost_US_tna_B_T_Truck_01_cargo_F",
            "ghost_US_tna_B_T_Truck_01_covered_F",
            "ghost_US_tna_B_T_Truck_01_flatbed_F",
            "ghost_US_tna_B_T_Truck_01_fuel_F",
            "ghost_US_tna_B_T_Truck_01_medical_F",
            "ghost_US_tna_B_T_Truck_01_mover_F",
            "ghost_US_tna_B_T_Truck_01_transport_F",
            "ghost_US_tna_B_T_TwinMortar_RF",
            "ghost_US_tna_B_T_UAV_01_F",
            "ghost_US_tna_B_T_UAV_02_dynamicLoadout_F",
            "ghost_US_tna_B_T_UAV_03_dynamicLoadout_F",
            "ghost_US_tna_B_T_UAV_05_F",
            "ghost_US_tna_B_T_UAV_06_F",
            "ghost_US_tna_B_T_UAV_06_medical_F",
            "ghost_US_tna_B_T_UGV_01_medical_olive_F",
            "ghost_US_tna_B_T_UGV_01_olive_F",
            "ghost_US_tna_B_T_UGV_01_rcws_olive_F",
            "ghost_US_tna_B_T_UGV_02_Demining_F",
            "ghost_US_tna_B_T_VTOL_01_armed_F",
            "ghost_US_tna_B_T_VTOL_01_infantry_F",
            "ghost_US_tna_B_T_VTOL_01_vehicle_F",
            "ghost_US_tna_B_T_ghillie_spotter_tna_F",
            "ghost_US_tna_B_T_ghillie_tna_F",
            "ghost_US_tna_B_T_qav_abramsx",
            "ghost_US_tna_B_T_soldier_M_F",
            "ghost_US_tna_B_T_soldier_UAV_02_LxWS_F",
            "ghost_US_tna_B_T_soldier_UAV_06_F",
            "ghost_US_tna_B_T_soldier_UAV_06_medical_F",
            "ghost_US_tna_B_T_soldier_UGV_02_Demining_F",
            "ghost_US_tna_B_T_soldier_mine_F",
            "ghost_US_tna_EF_B_CombatBoat_AT_NATO_T",
            "ghost_US_tna_EF_B_CombatBoat_HMG_NATO_T",
            "ghost_US_tna_EF_B_CombatBoat_Unarmed_NATO_T",
            "ghost_US_tna_EF_B_MRAP_01_AT_NATO_T",
            "ghost_US_tna_EF_B_MRAP_01_FSV_NATO_T",
            "ghost_US_tna_EF_B_MRAP_01_LAAD_NATO_T"
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
