/*
Function: ghost_fnc_FullArsenal

Description:
    Fills Arsenal with predefined equipment dependent on _Type. Each Arsenal can be a different type
    and have a different duration.

    Arguments:
    _object - Object the Arsenal is applied to.  <OBJECT>
    _type - Type of Arsenal, can be 0 = "ghost", 1 = "WINTER", 3 = "INCOGNITO" <STRING>
    _Duration - How long in minutes until the Arsenal is removed. 0 makes it permanent. <SCALAR>

1000+ weapons
1000+ atachments
1500+ face bling

ca
500 vests
2000 uniforms
3000+ headgear (ok 1200ish are ball caps but still)
200 + backpacks

Examples:
    (begin example)
    [this] call ghost_fnc_FullArsenal;
    [this, "2", 50] call ghost_fnc_FullArsenal;
    [this, "1"] call ghost_fnc_FullArsenal;
    [MyAmmoCrate, "INCOGNITO", 0] call ghost_fnc_FullArsenal;
    (end)

Author:
    MitchJC
*/

if (!isServer) exitwith {};

params [
    "_object",
    ["_Type", "1"],
    ["_Duration", 0]
];

call {
    if (_Type isEqualto 0) exitwith {_Type = "Ghost"};
    if (_Type isEqualto 1) exitwith {_Type = "Incogneato"};
    
};

if (isClass (configFile >> "CfgPatches" >> "ace_main")) then {
    [_object, false] call ace_arsenal_fnc_initBox;
} else {
    ["AmmoboxInit", [_object, false]] call BIS_fnc_arsenal;
};

private [
    "_AvailableItems", "_AvailableHeadgear", "_AvailableGoggles", 
    "_AvailableUniforms", "_AvailableVests", "_AvailableBackpacks", 
    "_AvailableWeapons", "_AvailableMagazines","_AvailableAttachments"
];

_ArsenalType = call {
    if (_Type isEqualTo "Ghost") exitwith {
        _AvailableHeadgear = [
            "ghost_H_Booniehat_Solid_Black",
            "ghost_H_Booniehat_Solid_Black_hs",
            "ghost_H_Cap_Solid_Black",
            "ghost_H_Cap_Solid_Black_hs",
            "ghost_H_Booniehat_Solid_CoyoteBrown",
            "ghost_H_Booniehat_Solid_CoyoteBrown_hs",
            "ghost_H_Cap_Solid_CoyoteBrown_hs",
            "ghost_H_Booniehat_US_DCU",
            "ghost_H_Booniehat_US_DCU_hs",
            "ghost_H_Cap_US_DCU",
            "ghost_H_Booniehat_US_M81",
            "ghost_H_Booniehat_US_M81_hs",
            "ghost_H_Cap_US_M81",
            "ghost_H_Cap_US_M81_hs",
            "ghost_H_Booniehat_Multicam_Snow",
            "ghost_H_Booniehat_Multicam_Snow_hs",
            "ghost_H_Cap_Multicam_Snow",
            "ghost_H_Cap_Multicam_Snow_hs",
            "ghost_H_Booniehat_Multicam_Woodland",
            "ghost_H_Booniehat_Multicam_Woodland_hs",
            "ghost_H_Cap_Multicam_Woodland",
            "ghost_H_Cap_Multicam_Woodland_hs",
            "ghost_Multicam_H_Booniehat_Multicam",
            "ghost_H_Cap_Multicam",
            "ghost_H_Cap_Multicam_hs",
            "ghost_H_Booniehat_Solid_Olive",
            "ghost_H_Booniehat_Solid_Olive_hs",
            "ghost_H_Cap_Solid_Olive_hs",
            "ghost_H_Booniehat_Solid_Ranger_Green",
            "ghost_H_Booniehat_Solid_Ranger_Green_hs",
            "ghost_H_Cap_Solid_Ranger_Green",
            "ghost_H_Booniehat_Solid_Tan",
            "ghost_H_Booniehat_Solid_Tan_hs",
            "ghost_H_Cap_Solid_Tan",
            "ghost_H_Cap_Solid_Tan_hs",
            "ghost_H_Booniehat_US_Tigerstripe",
            "ghost_H_Booniehat_US_Tigerstripe_hs",
            "ghost_H_Cap_US_Tigerstripe",
            "ghost_H_Cap_US_Tigerstripe_hs",
            "ghost_H_Booniehat_Solid_White",
            "ghost_H_Booniehat_Solid_White_hs",
            "ghost_H_Cap_Solid_White",
            "ghost_H_Cap_Solid_White_hs",
            "ghost_H_Cap_Solid_Ranger_Green_hs",
            "ghost_H_Cap_Solid_Olive",
            "ghost_H_Booniehat_Multicam_hs",
            "ghost_H_Cap_US_DCU_hs",
            "ghost_H_Cap_Solid_CoyoteBrown",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_Aus",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_can",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_can",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_fr",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_fr",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_ger",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_ger",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_jap",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_jap",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_ned",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_ned",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_nor",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_nor",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_pl",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_pl",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_sk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_sk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_tw",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_tw",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_uk",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_uk",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5_us",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5_us",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_1",
            "FPGP_2_OpscoreMar_Snakeskin_blk_Ct_1",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_2",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_2",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_3",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_3",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_4",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_4",
            "FPGP_2_OpscoreMar_Snakeskin_blk_amp_5",
            "FPGP_2_OpscoreMar_Snakeskin_blk_ct_5",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_amp_1",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Ct_1",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_2",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_2",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_3",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_3",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_4",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_4",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_Amp_5",
            "FPGP_2_OpscoreMar_Snakeskin_Tan_ct_5"
        ];
        _AvailableGoggles = [
            "FPGP2_Headgear_Face_Shemagh_rgr_gatorz_1",
            "FPGP2_Headgear_Face_Shemagh_cbr_gatorz_1",
            "FPGP2_Headgear_Face_Shemagh_BLK_gatorz_1",
            "FPGP2_Headgear_Face_gatorz_1",
            "FPGP2_Headgear_Face_Shemagh_rgr_ess_1",
            "FPGP2_Headgear_Face_ESS_1",
            "FPGP2_Headgear_Face_Shemagh_BLK_ess_1",
            "FPGP2_Headgear_Face_Shemagh_cbr_ess_1",
            "FPGP2_Headgear_Face_Shemagh_BLK_1",
            "FPGP2_Headgear_Face_Shemagh_cbr_1",
            "FPGP2_Headgear_Face_Shemagh_rgr_1",
            "G_Tactical_Black",
            "G_Tactical_Clear",
            "G_B_Diving"
        ];
        _AvailableUniforms = [
            "FPGP2_Uni_Crye_ts_1_U",
            "FPGP2_Uni_Crye_dts_1_U",
            "FPGP2_Uni_Crye_rgr_1_U",
            "FPGP2_Uni_Crye_1_U",
            "FPGP2_Uni_Crye_mct_1_U",
            "FPGP2_Uni_Crye_mcb_1_U",
            "FPGP2_Uni_Crye_mcar_1_U",
            "FPGP2_Uni_Crye_m81_1_U",
            "FPGP2_Uni_Crye_khk_1_U",
            "ghost_equipment_Wetsuit"
        ];
        _AvailableVests = [
            "FPGP_PC_Tan_1",
            "FPGP_PC_Tan_3",
            "FPGP_PC_Tan_4",
            "FPGP_PC_Tan_5",
            "FPGP_PC_Tan_6",
            "FPGP_PC_Tan_7",
            "FPGP_PC_Tan_2",
            "ghost_equipment_rebreather"
        ];
        _AvailableBackpacks = [
            "ace_gunbag",
            "ace_gunbag_Tan",
            "FPGP_Hydration1_Tan_1_Backpanel",
            "FPGP_Hydration2_Tan_1_Backpanel",
            "B_UAV_06_backpack_F",
            "B_UGV_02_Demining_backpack_F",
            "B_UGV_02_Science_backpack_F",
            "B_UAV_01_backpack_F",
            "B_Static_Designator_01_weapon_F",
            "B_W_Static_Designator_01_weapon_F"
        ];
        _AvailableWeapons = [
            "SPS_AI_AXMC308_26_PB_F",
            "SPS_AI_AXMC308_26_G_F",
            "SPS_AI_AXMC308_26_ES_F",
            "SPS_AI_AXMC308_26_B_F",
            "SPS_AI_AXMC308_26_DE_F",
            "SPS_AI_AXMC300_26_PB_PRCFB_F",
            "SPS_AI_AXMC300_26_ES_PRCFB_F",
            "SPS_AI_AXMC300_26_B_PRCFB_F",
            "SPS_AI_AXMC300_26_PB_F",
            "SPS_AI_AXMC300_26_G_F",
            "SPS_AI_AXMC300_26_ES_F",
            "SPS_AI_AXMC300_26_B_F",
            "SPS_AI_AXMC300_26_DE_F",
            "SPS_AI_AXMC300_26_DE_PRCFB_F",
            "SPS_AI_AXMC300_26_G_PRCFB_F",
            "SPS_AI_AXMC308_26_DE_PRCFB_F",
            "SPS_AI_AXMC308_26_B_PRCFB_F",
            "SPS_AI_AXMC308_26_ES_PRCFB_F",
            "SPS_AI_AXMC308_26_G_PRCFB_F",
            "SPS_AI_AXMC308_26_PB_PRCFB_F",
            "SPS_AI_AXMC338_27_DE_F",
            "SPS_AI_AXMC338_27_B_F",
            "SPS_AI_AXMC338_27_ES_F",
            "SPS_AI_AXMC338_27_G_F",
            "SPS_AI_AXMC338_27_PB_F",
            "SPS_AI_AXMC338_27_DE_PRCFB_F",
            "SPS_AI_AXMC338_27_B_PRCFB_F",
            "SPS_AI_AXMC338_27_ES_PRCFB_F",
            "SPS_AI_AXMC338_27_G_PRCFB_F",
            "SPS_AI_AXMC338_27_PB_PRCFB_F",
            "SPS_hk417_13_afg_black_f",
            "SPS_hk417_13_afg_fde_f",
            "SPS_hk417_13_afg_ral8000_f",
            "SPS_hk417_13_vfg_black_f",
            "SPS_hk417_13_vfg_fde_f",
            "SPS_hk417_13_vfg_ral8000_f",
            "SPS_hk417_13_glm_black_f",
            "SPS_hk417_13_glm_fde_f",
            "SPS_hk417_13_glm_ral8000_f",
            "SPS_hk417_16_afg_black_f",
            "SPS_hk417_16_afg_fde_f",
            "SPS_hk417_16_afg_ral8000_f",
            "SPS_hk417_16_vfg_black_f",
            "SPS_hk417_16_vfg_fde_f",
            "SPS_hk417_16_vfg_ral8000_f",
            "SPS_hk417_16_glm_black_f",
            "SPS_hk417_16_glm_ral8000_f",
            "SPS_hk417_20_afg_fde_f",
            "SPS_hk417_20_afg_ral8000_f",
            "SPS_hk417_20_vfg_black_f",
            "SPS_hk417_20_vfg_fde_f",
            "SPS_hk417_20_vfg_ral8000_f",
            "SPS_hk417_20_afg_black_f",
            "SPS_hk417_16_glm_fde_f",
            "SPS_KAC_LWAMG_Tan_F",
            "SPS_KAC_LWAMG_Black_F",
            "SPS_KAC_LAMG_Tan_F",
            "SPS_KAC_LAMG_black_F",
            "SPS_KAC_LAMG_NHG_tan_F",
            "SPS_KAC_LAMG_NHG_black_F",
            "launch_B_Titan_short_tna_F",
            "launch_B_Titan_tna_F",
            "launch_B_Titan_F",
            "launch_B_Titan_short_F",
            "launch_MRAWS_sand_F",
            "launch_MRAWS_olive_F",
            "launch_MRAWS_green_F",
            "launch_MRAWS_sand_rail_F",
            "launch_MRAWS_olive_rail_F",
            "launch_MRAWS_green_rail_F",
            "launch_NLAW_F",
            "ace_csw_staticHMGCarry",
            "ace_csw_staticGMGCarry",
            "ace_csw_staticMortarCarry",
            "ace_csw_carryMortarBaseplate",
            "sps_hk_vp9_tac_ral8000",
            "sps_hk_vp9_tac_ral8000_black",
            "sps_hk_vp9_tac_grey_bb",
            "sps_hk_vp9_tac_grey",
            "sps_hk_vp9_tac_green",
            "sps_hk_vp9_tac_fde_bb",
            "sps_hk_vp9_tac_ral8000_bb",
            "sps_hk_vp9_tac_fde_black",
            "sps_hk_vp9_tac_black_bb",
            "sps_hk_vp9_tac_black",
            "sps_hk_vp9_stnd_ral8000",
            "sps_hk_vp9_stnd_ral8000_bb",
            "sps_hk_vp9_stnd_ral8000_black",
            "sps_hk_vp9_stnd_grey",
            "sps_hk_vp9_stnd_green",
            "sps_hk_vp9_stnd_fde_bb",
            "sps_hk_vp9_stnd_fde_black",
            "sps_hk_vp9_stnd_black",
            "sps_hk_vp9_stnd_black_bb",
            "sps_hk_vp9_stnd_grey_bb",
            "sps_fk_brno_psd_3_b",
            "sps_fk_brno_psd_d_b",
            "ACE_VMH3",
            "ACE_VMM3",
            "SPS_hk337_t_vfg_ral8000_f",
            "SPS_hk337_t_vfg_fde_f",
            "SPS_hk337_t_vfg_black_f",
            "SPS_hk337_t_ctr_vfg_ral8000_f",
            "SPS_hk337_t_ctr_vfg_fde_f",
            "SPS_hk337_t_ctr_vfg_black_f",
            "SPS_hk337_hk_ctr_vfg_ral8000_f",
            "SPS_hk337_hk_ctr_vfg_fde_f",
            "SPS_hk337_hk_ctr_vfg_black_f",
            "SPS_hk337_vfg_ral8000_f",
            "SPS_hk337_vfg_fde_f",
            "SPS_hk337_vfg_black_f",
            "SPS_hk337_t_ral8000_f",
            "SPS_hk337_t_fde_f",
            "SPS_hk337_t_black_f",
            "SPS_hk337_ral8000_f",
            "SPS_hk337_fde_f",
            "SPS_hk337_black_f",
            "SPS_hk337_t_ctr_ral8000_f",
            "SPS_hk337_t_ctr_fde_f",
            "SPS_hk337_t_ctr_black_f",
            "SPS_hk337_hk_ctr_fde_f",
            "SPS_hk337_hk_ctr_black_f",
            "SPS_hk337_t_afg_ral8000_f",
            "SPS_hk337_t_afg_fde_f",
            "SPS_hk337_t_ctr_afg_ral8000_f",
            "SPS_hk337_t_ctr_afg_fde_f",
            "SPS_hk337_t_ctr_afg_black_f",
            "SPS_hk337_hk_ctr_afg_ral8000_f",
            "SPS_hk337_hk_ctr_afg_fde_f",
            "SPS_hk337_hk_ctr_afg_black_f",
            "SPS_hk337_afg_ral8000_f",
            "SPS_hk337_afg_fde_f",
            "SPS_hk337_afg_black_f",
            "SPS_hk337_t_afg_black_f",
            "SPS_hk337_hk_ctr_ral8000_f",
            "vtf_MK13",
            "vtf_MK13_black"
        ];
        _AvailableMagazines = [
            "SPS_AI_AXMC_762x51mm_M80A1_EPR_Mag",
            "SPS_AI_AXMC_762x51mm_M80A1_EPR_Tracer_Mag",
            "SPS_AI_AXMC_762x51mm_M80A1_EPR_IR_Mag",
            "SPS_AI_AXMC_762x51mm_M80_Mag",
            "SPS_AI_AXMC_762x51_M993_AP_Mag",
            "SPS_AI_AXMC_762x51_Mk319_Mod_0_Mag",
            "SPS_AI_AXMC_762x51_Mk316_Mod_0_Mag",
            "SPS_AI_AXMC_762x51_M118LR_Mag",
            "SPS_AI_AXMC_762x51_Berger_JOTM_Mag",
            "SPS_AI_AXMC_762x51_Berger_JOTM_Mag_Tracer",
            "SPS_AI_AXMC_762x51_Berger_JOTM_Mag_IR",
            "SPS_AI_AXMC_762x67_Mk248_Mod_0_Mag",
            "SPS_AI_AXMC_762x67_Mk248_Mod_1_Mag",
            "SPS_AI_AXMC_762x67_Berger_Hybrid_OTM_Mag",
            "SPS_AI_AXMC_762x67_Berger_Hybrid_OTM_Tracer_Mag",
            "SPS_AI_AXMC_762x67_Berger_Hybrid_OTM_IR_Mag",
            "SPS_AI_AXMC_338_300gr_Scenar_Mag",
            "SPS_AI_AXMC_338_300gr_Scenar_Tracer_Mag",
            "SPS_AI_AXMC_338_300gr_Scenar_IR_Mag",
            "SPS_AI_AXMC_338_250gr_Naturalis_Mag",
            "SPS_AI_AXMC_338_250gr_Naturalis_Tracer_Mag",
            "SPS_AI_AXMC_338_250gr_Naturalis_IR_Mag",
            "SPS_AI_AXMC_338_300gr_HPBT_Mag",
            "SPS_AI_AXMC_338_API526_Mag",
            "SPS_AI_AXMC_338_Mag",
            "SPS_AI_AXMC_338_300gr_Berger_Mag",
            "SPS_AI_AXMC_338_300gr_Berger_Mag_Tracer",
            "SPS_AI_AXMC_338_300gr_Berger_Mag_IR",
            "SPS_20Rnd_762x51mm_M80A1_EPR",
            "SPS_20Rnd_762x51mm_M80A1_EPR_Tracer",
            "SPS_20Rnd_762x51mm_M80A1_EPR_IR",
            "1Rnd_HE_Grenade_shell",
            "UGL_FlareWhite_F",
            "UGL_FlareGreen_F",
            "UGL_FlareRed_F",
            "UGL_FlareYellow_F",
            "UGL_FlareCIR_F",
            "1Rnd_Smoke_Grenade_shell",
            "1Rnd_SmokeRed_Grenade_shell",
            "1Rnd_SmokeGreen_Grenade_shell",
            "1Rnd_SmokeYellow_Grenade_shell",
            "1Rnd_SmokePurple_Grenade_shell",
            "1Rnd_SmokeBlue_Grenade_shell",
            "1Rnd_SmokeOrange_Grenade_shell",
            "ACE_HuntIR_M203",
            "ACE_40mm_Flare_white",
            "ACE_40mm_Flare_red",
            "ACE_40mm_Flare_green",
            "ACE_40mm_Flare_ir",
            "SPS_KAC_LWAMG_100rnd_Box",
            "SPS_KAC_LWAMG_100rnd_Box_T",
            "SPS_KAC_LWAMG_100rnd_Box_M",
            "SPS_KAC_LWAMG_100rnd_Box_M80A1",
            "SPS_KAC_LWAMG_100rnd_Box_M62A1",
            "SPS_KAC_LWAMG_100rnd_Box_M80A1M62A1",
            "SPS_KAC_LWAMG_100rnd_Box_IRDIM",
            "SPS_KAC_LAMG_150rnd_Box_Tan",
            "SPS_KAC_LAMG_150rnd_Box",
            "SPS_KAC_LAMG_150rnd_M_Box",
            "SPS_KAC_LAMG_150rnd_T_Box",
            "SPS_KAC_LAMG_150rnd_IR_Box",
            "SPS_KAC_LAMG_M855A1_150rnd_Box",
            "SPS_KAC_LAMG_M855A1_150rnd_M_Box",
            "SPS_KAC_LAMG_M856A1_150rnd_T_Box",
            "SPS_KAC_LAMG_M856A1_150rnd_IR_Box",
            "SPS_KAC_LAMG_150rnd_M_Box_Tan",
            "SPS_KAC_LAMG_150rnd_T_Box_Tan",
            "SPS_KAC_LAMG_150rnd_IR_Box_Tan",
            "SPS_KAC_LAMG_M855A1_150rnd_Box_Tan",
            "SPS_KAC_LAMG_M855A1_150rnd_M_Box_Tan",
            "SPS_KAC_LAMG_M856A1_150rnd_T_Box_Tan",
            "SPS_KAC_LAMG_M856A1_150rnd_IR_Box_Tan",
            "Titan_AT",
            "Titan_AP",
            "Titan_AA",
            "MRAWS_HEAT_F",
            "MRAWS_HE_F",
            "MRAWS_HEAT55_F",
            "sps_16Rnd_75x27_FK_95gr_jhp",
            "tsp_frameCharge_mag",
            "tsp_popperCharge_mag",
            "tsp_popperCharge_auto_mag",
            "DemoCharge_Remote_Mag",
            "ClaymoreDirectionalMine_Remote_Mag",
            "SLAMDirectionalMine_Wire_Mag",
            "ATMine_Range_Mag",
            "tsp_stickCharge_mag",
            "tsp_stickCharge_auto_mag",
            "ACE_FlareTripMine_Mag",
            "ACE_M14",
            "ACE_Chemlight_Orange",
            "ACE_Chemlight_HiYellow",
            "ACE_Chemlight_HiWhite",
            "ACE_Chemlight_HiRed",
            "ACE_Chemlight_HiGreen",
            "ACE_Chemlight_HiBlue",
            "Chemlight_green",
            "Chemlight_blue",
            "ACE_Chemlight_IR",
            "Chemlight_red",
            "ACE_Chemlight_UltraHiOrange",
            "ACE_Chemlight_White",
            "Chemlight_yellow",
            "ACE_CTS9",
            "B_IR_Grenade",
            "ACE_HandFlare_Yellow",
            "ACE_HandFlare_Red",
            "ACE_HandFlare_Green",
            "ACE_HandFlare_White",
            "SmokeShellBlue",
            "SmokeShellGreen",
            "SmokeShellOrange",
            "SmokeShellPurple",
            "SmokeShellRed",
            "SmokeShellYellow",
            "HandGrenade",
            "SmokeShell",
            "ACE_M84",
            "MS_Strobe_Mag_1",
            "MS_Strobe_Mag_2",
            "MiniGrenade",
            "SPS_HKG3PMAG_30Rnd_300BLK_230_T",
            "SPS_HKG3PMAG_30Rnd_300BLK_230_S",
            "SPS_HKG3PMAG_30Rnd_300BLK_230_B",
            "SPS_HKG3PMAG_30Rnd_300BLK_147_T",
            "SPS_HKG3PMAG_30Rnd_300BLK_147_S",
            "SPS_HKG3PMAG_30Rnd_300BLK_147_B",
            "SPS_HKG3PMAG_30Rnd_300BLK_124_T",
            "SPS_HKG3PMAG_30Rnd_300BLK_124_S",
            "SPS_HKG3PMAG_30Rnd_300BLK_124_B",
            "ACE_SpareBarrel",
            "kat_Painkiller",
            "ACE_LWAMG_SpareBarrel",
            "ACE_LAMG_SpareBarrel",
            "kat_Carbonate",
            "Laserbatteries",
            "FlareYellow_F",
            "FlareWhite_F",
            "FlareRed_F",
            "FlareGreen_F",
            "ACE_1Rnd_82mm_Mo_Smoke",
            "ACE_1Rnd_82mm_Mo_Illum",
            "ACE_1Rnd_82mm_Mo_HE",
            "ACE_1Rnd_82mm_Mo_HE_Guided",
            "ace_csw_20Rnd_20mm_G_belt",
            "ace_csw_100Rnd_127x99_mag_yellow",
            "ace_csw_100Rnd_127x99_mag_red",
            "ace_csw_100Rnd_127x99_mag_green",
            "ace_csw_100Rnd_127x99_mag",
            "ace_csw_50Rnd_127x108_mag",
            "ACE_1Rnd_82mm_Mo_HE_LaserGuided"
        ];
        _AvailableAttachments = [
            "optic_Nightstalker",
            "optic_tws",
            "optic_tws_mg",
            "optic_NVS",
            "optic_SOS",
            "optic_SOS_khk_F",
            "optic_MRCO",
            "optic_Arco",
            "optic_Arco_ghex_F",
            "optic_Arco_blk_F",
            "optic_Arco_AK_arid_F",
            "optic_Arco_AK_blk_F",
            "optic_Arco_AK_lush_F",
            "optic_Arco_arid_F",
            "optic_Arco_lush_F",
            "optic_Aco",
            "optic_ACO_grn",
            "optic_Aco_smg",
            "optic_ACO_grn_smg",
            "optic_Hamr",
            "optic_Hamr_khk_F",
            "optic_Holosight",
            "optic_Holosight_blk_F",
            "optic_Holosight_khk_F",
            "optic_Holosight_arid_F",
            "optic_Holosight_lush_F",
            "optic_Holosight_smg",
            "optic_Holosight_smg_blk_F",
            "optic_Holosight_smg_khk_F",
            "optic_DMS",
            "optic_DMS_ghex_F",
            "optic_DMS_weathered_F",
            "optic_DMS_weathered_Kir_F",
            "optic_LRPS",
            "optic_LRPS_ghex_F",
            "optic_LRPS_tna_F",
            "optic_AMS",
            "optic_AMS_khk",
            "optic_AMS_snd",
            "optic_KHS_blk",
            "optic_KHS_hex",
            "optic_KHS_old",
            "optic_KHS_tan",
            "optic_ERCO_blk_F",
            "optic_ERCO_khk_F",
            "optic_ERCO_snd_F",
            "optic_Yorris",
            "ACE_optic_Hamr_2D",
            "ACE_optic_Hamr_PIP",
            "ACE_optic_Arco_2D",
            "ACE_optic_Arco_PIP",
            "ACE_optic_MRCO_2D",
            "ACE_optic_SOS_2D",
            "ACE_optic_SOS_PIP",
            "ACE_optic_LRPS_2D",
            "ACE_optic_LRPS_PIP",
            "ghost_equipment_optic_Nightstalker",
            "ghost_equipment_optic_AMS",
            "ghost_equipment_optic_AMS_khk",
            "ghost_equipment_optic_AMS_snd",
            "ghost_equipment_optic_AMSTI",
            "ghost_equipment_optic_AMSTI_khk",
            "ghost_equipment_optic_AMSTI_snd",
            "ghost_equipment_xm157_prototype",
            "ghost_equipment_optic_DMS",
            "optic_MRD",
            "optic_MRD_black",
            "acc_flashlight",
            "acc_pointer_IR",
            "ACE_acc_pointer_green",
            "sps_M300C_MAWL_IR",
            "sps_M300C_RAID_IR",
            "sps_M300C",
            "sps_M300C_MAWL_IR_tan",
            "sps_M300C_RAID_IR_tan",
            "sps_M300C_tan",
            "sps_M300C_MAWL_smr_IR",
            "sps_M300C_RAID_smr_IR",
            "sps_M300C_MAWL_smr_IR_tan",
            "sps_M300C_RAID_smr_IR_tan",
            "sps_M300C_MAWL_ext_IR",
            "sps_M300C_RAID_ext_IR",
            "sps_M300C_MAWL_ext_IR_tan",
            "sps_M300C_RAID_ext_IR_tan",
            "sps_M300C_MAWL_high_IR",
            "sps_M300C_RAID_high_IR",
            "sps_M300C_MAWL_high_IR_tan",
            "sps_M300C_RAID_high_IR_tan",
            "sps_M300C_MAWL_high_ext_IR",
            "sps_M300C_RAID_high_ext_IR",
            "sps_M300C_MAWL_high_ext_IR_tan",
            "sps_M300C_RAID_high_ext_IR_tan",
            "sps_M300C_MAWL_LAMG_IR",
            "sps_M300C_RAID_LAMG_IR",
            "sps_M300C_MAWL_LAMG_IR_tan",
            "sps_M300C_RAID_LAMG_IR_tan",
            "DBAL_A4_IR_Pointer",
            "DBAL_A4_IR_Pointer_Tan",
            "DBAL_A4_Top_Fwd_IR_Pointer",
            "DBAL_A4_Top_Fwd_IR_Pointer_Tan",
            "DBAL_A4_Top_Mid_IR_Pointer",
            "DBAL_A4_Top_Mid_IR_Pointer_Tan",
            "DBAL_A4_Top_Rwd_IR_Pointer",
            "DBAL_A4_Top_Rwd_IR_Pointer_Tan",
            "DBAL_A4_Top_Rwd_High_IR_Pointer",
            "DBAL_A4_Top_Rwd_High_IR_Pointer_Tan",
            "DBAL_A4_Top_Fwd_High_IR_Pointer",
            "DBAL_A4_Top_Fwd_High_IR_Pointer_Tan",
            "DBAL_A4_Top_Mid_High_IR_Pointer",
            "DBAL_A4_Top_Mid_High_IR_Pointer_Tan",
            "DBAL_A4_Top_Mid_LAMG_IR_Pointer",
            "DBAL_A4_Top_Mid_LAMG_IR_Pointer_Tan",
            "DBAL_A4_Top_Rwd_LAMG_IR_Pointer",
            "DBAL_A4_Top_Rwd_LAMG_IR_Pointer_Tan",
            "DBAL_A4_Top_Fwd_LAMG_IR_Pointer",
            "DBAL_A4_Top_Fwd_LAMG_IR_Pointer_Tan",
            "acc_flashlight_pistol",
            "muzzle_snds_338_black",
            "muzzle_snds_338_green",
            "muzzle_snds_338_sand",
            "ACE_muzzle_mzls_338",
            "muzzle_snds_SPS_AI_PB_H",
            "muzzle_snds_SPS_AI_B_H",
            "muzzle_snds_SPS_AI_G_H",
            "muzzle_snds_SPS_AI_ES_H",
            "muzzle_snds_SPS_AI_DE_H",
            "muzzle_snds_B",
            "muzzle_snds_B_khk_F",
            "muzzle_snds_B_snd_F",
            "muzzle_snds_B_arid_F",
            "muzzle_snds_B_lush_F",
            "ACE_muzzle_mzls_B",
            "muzzle_snds_M",
            "muzzle_snds_m_khk_F",
            "muzzle_snds_m_snd_F",
            "ACE_muzzle_mzls_L",
            "muzzle_snds_L",
            "ACE_muzzle_mzls_smg_02",
            "bipod_01_F_snd",
            "bipod_01_F_blk",
            "bipod_01_F_mtp",
            "bipod_02_F_blk",
            "bipod_02_F_tan",
            "bipod_02_F_hex",
            "bipod_03_F_blk",
            "bipod_03_F_oli",
            "bipod_01_F_khk",
            "bipod_02_F_arid",
            "bipod_02_F_lush"
        ];
    };
    if (_Type isEqualTo "Incogneato") exitwith {
        _AvailableHeadgear = [];
        _AvailableGoggles = [];
        _AvailableUniforms = [];
        _AvailableVests = [];
        _AvailableBackpacks = [];
        _AvailableWeapons = [];
        _AvailableMagazines = [];
        _AvailableAttachments = [];
    };
};

_AvailableItems = [
    "kat_IV_16",
    "ACE_RangeTable_82mm",
    "ACE_adenosine",
    "kat_AED",
    "kat_X_AED",
    "ACE_artilleryTable",
    "ACE_ATragMX",
    "ACE_fieldDressing",
    "ACE_elasticBandage",
    "ACE_packingBandage",
    "ACE_quikclot",
    "ACE_bloodIV",
    "ACE_bloodIV_250",
    "ACE_bloodIV_500",
    "ACE_bodyBag",
    "kat_plate",
    "ghost_medbags_FirstAid",
    "ACE_CableTie",
    "ACE_Canteen",
    "ACE_Chemlight_Shield",
    "kat_clamp",
    "ALIVE_Tablet",
    "ACE_DAGR",
    "ACE_DeadManSwitch",
    "ACE_DefusalKit",
    "kat_vacuum",
    "ghost_medbags_DrugKit",
    "kat_EACA",
    "ACE_EarPlugs",
    "ACE_EntrenchingTool",
    "ACE_epinephrine",
    "kat_etomidate",
    "kat_IO_FAST",
    "FirstAidKit",
    "ghost_medbags_Fluid",
    "kat_flumazenil",
    "ACE_Fortify",
    "ACE_Flashlight_MX991",
    "ACE_Humanitarian_Ration",
    "ACE_HuntIR_monitor",
    "ACE_IR_Strobe_Item",
    "ACE_Kestrel4500",
    "ACE_Flashlight_KSF1",
    "kat_lidocaine",
    "tsp_lockpick",
    "kat_lorazepam",
    "ACE_M26_Clacker",
    "ACE_Clacker",
    "ACE_Flashlight_XL50",
    "ACE_MapTools",
    "ace_marker_flags_black",
    "ace_marker_flags_blue",
    "ace_marker_flags_green",
    "ace_marker_flags_orange",
    "ace_marker_flags_purple",
    "ace_marker_flags_red",
    "ace_marker_flags_white",
    "ace_marker_flags_yellow",
    "ghost_medbags_MedicKit",
    "Medikit",
    "ACE_microDAGR",
    "MineDetector",
    "ACE_morphine",
    "kat_naloxone",
    "kat_nitroglycerin",
    "kat_norepinephrine",
    "tsp_paperclip",
    "ACE_personalAidKit",
    "kat_phenylephrine",
    "kat_phenylephrine_inject",
    "ACE_plasmaIV",
    "ACE_plasmaIV_250",
    "ACE_plasmaIV_500",
    "ACE_RangeCard",
    "kat_retractor",
    "ACE_salineIV",
    "ACE_salineIV_250",
    "ACE_salineIV_500",
    "ACE_Sandbag_empty",
    "kat_scalpel",
    "ACE_SpareBarrel_Item",
    "ACE_splint",
    "ACE_SpottingScope",
    "ACE_SpraypaintBlack",
    "ACE_SpraypaintBlue",
    "ACE_SpraypaintGreen",
    "ACE_SpraypaintRed",
    "ACE_Tripod",
    "ACE_surgicalKit",
    "ToolKit",
    "ACE_tourniquet",
    "ghost_medbags_Trauma",
    "kat_TXA",
    "ACE_UAVBattery",
    "ghost_vs17_vs17",
    "ACE_wirecutter",
    "B_UavTerminal",
    "ACE_Altimeter",
    "ItemWatch",
    "TFAR_anprc152",
    "ItemCompass",
    "ItemMap",
    "ghost_equipment_Vector_Designator_NVG",
    "ghost_equipment_Vector_Designator",
    "Binocular",
    "Laserdesignator",
    "Laserdesignator_03",
    "ACE_MX2A",
    "Rangefinder",
    "ace_dragon_sight",
    "ghost_nvg_anvg_blk",
    "ghost_nvg_anvg_grn",
    "ghost_nvg_anvg_gry",
    "ghost_nvg_anvgTI_blk",
    "ghost_nvg_anvgTI_grn",
    "ghost_nvg_anvgTI_gry",
    "ghost_nvg_nvg5_blk",
    "ghost_nvg_nvg5_brn",
    "ghost_nvg_nvg5_grn",
    "ghost_nvg_nvg5TI_blk",
    "ghost_nvg_nvg5TI_brn",
    "ghost_nvg_nvg5TI_grn",
    "ALiVE_Humrat",
    "ALiVE_Waterbottle"
];

if (isClass (configFile >> "CfgPatches" >> "ace_main")) then {
    [_object, _AvailableHeadgear, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableGoggles, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableUniforms, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableGear, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableVests, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableBackpacks, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableWeapons, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableMagazines, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableAttachments, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, _AvailableItems, true] call ace_arsenal_fnc_addVirtualItems;
    [_object, false] call ace_dragging_fnc_setCarryable;
    [_object, false] call ace_dragging_fnc_setDraggable;

} else {
    [_object, _AvailableHeadgear, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableGoggles, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableUniforms, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableGear, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableVests, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableBackpacks, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableWeapons, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableMagazines, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableAttachments, true] call BIS_fnc_addVirtualItemCargo;
    [_object, _AvailableItems, true] call BIS_fnc_addVirtualItemCargo;
};
    {
    _x addCuratorEditableObjects [[_object], false];
} forEach allCurators;

_handle = [
    {
        (_this select 0) params ["_object", "_duration"];

        if (_duration == 0) exitwith {
            [_handle] call CBA_fnc_removePerFrameHandler;
            };

        if (time > (_duration * 60)) exitwith {
            deletevehicle _object;
            [_handle] call CBA_fnc_removePerFrameHandler;
            };
    }, 60, [_object, _duration]
] call CBA_fnc_addPerFrameHandler;