// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
//
// EVERY CLASS BUILDS ON A LOADED MOD'S OWN (or a kept ghost class). The mods are required in
// config.cpp, so without them the faction is skipped rather than loading empty classes.

class CfgVehicles {
    class b_ptni_apc_01_F;
    class b_ptni_apc_01_gun_F;
    class B_PTNI_MRAP_01_F;
    class B_PTNI_MRAP_01_GUN_F;
    class EGVAR(vehicle,I_EAF_Heli_Attack_04_F);
    class I_Boat_Armed_01_minigun_F;
    class I_Boat_Transport_01_F;
    class I_G_Offroad_01_armed_F;
    class I_G_Offroad_01_AT_F;
    class I_G_Offroad_01_F;
    class I_GMG_01_high_F;
    class I_Heli_light_03_dynamicLoadout_F;
    class I_Heli_light_03_unarmed_F;
    class I_Heli_Transport_02_F;
    class I_helipilot_F;
    class I_HMG_01_high_F;
    class I_LT_01_AA_F;
    class I_Mortar_01_F;
    class I_Pilot_F;
    class I_Plane_Fighter_03_dynamicLoadout_F;
    class I_Plane_Fighter_04_F;
    class I_static_AA_F;
    class I_static_AT_F;
    class I_Truck_02_medical_F;
    class I_Truck_02_MRL_F;
    class I_UAV_02_dynamicLoadout_F;
    class I_UGV_01_rcws_F;
    class ptni_badak_F;
    class PTNI_Crewman_Malvinas;
    class PTNI_Grenadier_Malvinas;
    class PTNI_Leopard;
    class ptni_maung_F;
    class PTNI_Medic_Malvinas;
    class PTNI_MG_Malvinas;
    class PTNI_mp;
    class PTNI_Officer_Malvinas;
    class PTNI_Pandur;
    class PTNI_Rifleman_AT_Malvinas;
    class PTNI_Rifleman_Malvinas;
    class PTNI_Rifleman_Malvinas_Short_NoGloves;
    class PTNI_Rifleman_Malvinas_Short_NoGloves_SP1;
    class PTNI_Rifleman_Marksman_Malvinas;
    class PTNI_Rifleman_SL_Malvinas;
    class PTNI_Rifleman_TL_Malvinas;
    class PTNI_Rifleman_Unarmed_Malvinas;
    class PTNI_Sniper;
    class PTNI_Spotter;
    class PTNI_Tank_Base_F;
    class PTNI_Truck;
    class PTNI_Truck_Ammo;
    class PTNI_Truck_Fuel;
    class PTNI_Truck_Repair;

    class GVAR(PTNI_Rifleman_Malvinas): PTNI_Rifleman_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v2_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v2_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_MG_Malvinas): PTNI_MG_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        magazines[] = {"FA_b_200Rnd_556x45_Box_F_t3", "FA_b_200Rnd_556x45_Box_F_t3", "FA_b_200Rnd_556x45_Box_F_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_200Rnd_556x45_Box_F_t3", "FA_b_200Rnd_556x45_Box_F_t3", "FA_b_200Rnd_556x45_Box_F_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Medic_Malvinas): PTNI_Medic_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v2_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v2_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Crewman_Malvinas): PTNI_Crewman_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v5_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v5_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Grenadier_Malvinas): PTNI_Grenadier_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v2_GL_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v2_GL_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "MiniGrenade", "MiniGrenade", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeOrange_Grenade_shell", "1Rnd_SmokePurple_Grenade_shell"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "MiniGrenade", "MiniGrenade", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeOrange_Grenade_shell", "1Rnd_SmokePurple_Grenade_shell"};
    };

    class GVAR(PTNI_Rifleman_AT_Malvinas): PTNI_Rifleman_AT_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v2_snds), "launch_NLAW_F", "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v2_snds), "launch_NLAW_F", "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "NLAW_F", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "NLAW_F", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Rifleman_Unarmed_Malvinas): PTNI_Rifleman_Unarmed_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Rifleman_Marksman_Malvinas): PTNI_Rifleman_Marksman_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_spm1_optic_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_spm1_optic_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Rifleman_TL_Malvinas): PTNI_Rifleman_TL_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v2_GL_snds), "PTNI_Pistol_01_F", "Binocular", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v2_GL_snds), "PTNI_Pistol_01_F", "Binocular", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "MiniGrenade", "MiniGrenade", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "SmokeShell", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeOrange_Grenade_shell", "1Rnd_SmokePurple_Grenade_shell"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "MiniGrenade", "MiniGrenade", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "SmokeShell", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeOrange_Grenade_shell", "1Rnd_SmokePurple_Grenade_shell"};
    };

    class GVAR(PTNI_Rifleman_SL_Malvinas): PTNI_Rifleman_SL_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_ss2_v2_snds), "PTNI_Pistol_01_F", "Binocular", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_ss2_v2_snds), "PTNI_Pistol_01_F", "Binocular", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "I_IR_Grenade", "I_IR_Grenade", "SmokeShell", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "I_IR_Grenade", "I_IR_Grenade", "SmokeShell", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Officer_Malvinas): PTNI_Officer_Malvinas {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_mp): PTNI_mp {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "9Rnd_45ACP_Mag", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Sniper): PTNI_Sniper {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(PTNI_DMR_Optic_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(PTNI_DMR_Optic_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "I_IR_Grenade", "I_IR_Grenade", "SmokeShell", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_tni_10Rnd_762x51_Mag_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "I_IR_Grenade", "I_IR_Grenade", "SmokeShell", "SmokeShellGreen", "SmokeShellOrange", "SmokeShellPurple", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Spotter): PTNI_Spotter {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_spm1_optic_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_spm1_optic_snds), "PTNI_Pistol_01_F", "Throw", "Put"};
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Rifleman_Malvinas_Short_NoGloves): PTNI_Rifleman_Malvinas_Short_NoGloves {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        magazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_30Rnd_556_Mk327_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(PTNI_Rifleman_Malvinas_Short_NoGloves_SP1): PTNI_Rifleman_Malvinas_Short_NoGloves_SP1 {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
        weapons[] = {QGVAR(ptni_sp1_snds), "PTNI_Pistol_02_F", "Throw", "Put"};
        respawnWeapons[] = {QGVAR(ptni_sp1_snds), "PTNI_Pistol_02_F", "Throw", "Put"};
        magazines[] = {"FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
        respawnMagazines[] = {"FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_20Rnd_762_M80A2_HV_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "FA_b_16Rnd_9x21_Mk424_AP_t3", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellGreen", "Chemlight_green", "Chemlight_green"};
    };

    class GVAR(I_helipilot_F): I_helipilot_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
    };

    class GVAR(I_Pilot_F): I_Pilot_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        editorSubcategory = "EdSubcat_Personnel";
        vehicleClass = "Men";
    };

    class GVAR(ptni_badak_F): ptni_badak_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(ptni_maung_F): ptni_maung_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(B_PTNI_MRAP_01_F): B_PTNI_MRAP_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(B_PTNI_MRAP_01_GUN_F): B_PTNI_MRAP_01_GUN_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(PTNI_Tank_Base_F): PTNI_Tank_Base_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(PTNI_Leopard): PTNI_Leopard {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(PTNI_Pandur): PTNI_Pandur {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(PTNI_Truck): PTNI_Truck {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(PTNI_Truck_Fuel): PTNI_Truck_Fuel {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(PTNI_Truck_Ammo): PTNI_Truck_Ammo {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(PTNI_Truck_Repair): PTNI_Truck_Repair {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(b_ptni_apc_01_F): b_ptni_apc_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(b_ptni_apc_01_gun_F): b_ptni_apc_01_gun_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(I_EAF_Heli_Attack_04_F): EGVAR(vehicle,I_EAF_Heli_Attack_04_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(I_helipilot_F);
    };

    class GVAR(I_Heli_light_03_dynamicLoadout_F): I_Heli_light_03_dynamicLoadout_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(I_helipilot_F);
    };

    class GVAR(I_Heli_Transport_02_F): I_Heli_Transport_02_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(I_helipilot_F);
    };

    class GVAR(I_Heli_light_03_unarmed_F): I_Heli_light_03_unarmed_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(I_helipilot_F);
    };

    class GVAR(I_Plane_Fighter_03_dynamicLoadout_F): I_Plane_Fighter_03_dynamicLoadout_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(I_Pilot_F);
    };

    class GVAR(I_Plane_Fighter_04_F): I_Plane_Fighter_04_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(I_Pilot_F);
    };

    class GVAR(I_LT_01_AA_F): I_LT_01_AA_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(I_Truck_02_MRL_F): I_Truck_02_MRL_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Crewman_Malvinas);
    };

    class GVAR(I_Boat_Armed_01_minigun_F): I_Boat_Armed_01_minigun_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_Boat_Transport_01_F): I_Boat_Transport_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_UAV_02_dynamicLoadout_F): I_UAV_02_dynamicLoadout_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = "I_UAV_AI";
    };

    class GVAR(I_UGV_01_rcws_F): I_UGV_01_rcws_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = "I_UAV_AI";
    };

    class GVAR(I_HMG_01_high_F): I_HMG_01_high_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_GMG_01_high_F): I_GMG_01_high_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_static_AT_F): I_static_AT_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_static_AA_F): I_static_AA_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_Mortar_01_F): I_Mortar_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_Truck_02_medical_F): I_Truck_02_medical_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_G_Offroad_01_F): I_G_Offroad_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_G_Offroad_01_armed_F): I_G_Offroad_01_armed_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

    class GVAR(I_G_Offroad_01_AT_F): I_G_Offroad_01_AT_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 2;
        faction = QUOTE(ADDON);
        crew = QGVAR(PTNI_Rifleman_Malvinas);
    };

};
