// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
// SUPPRESSED PRESETS (tools/gen_mod_factions.py): the weapon the mod issues with a base-game
// suppressor its MuzzleSlot takes linked on; scope 1 and baseWeapon keep the arsenal showing
// the plain weapon. The man's weapons[] names the preset.
class CfgWeapons {
    class LMG_min_rf_6p69;
    class LMG_min_rf_6p69_desert;
    class SMG_min_rf_pp_2000;
    class srifle_min_rf_orsis_t5000_desert;
    class LMG_min_rf_6p69_1p_87: LMG_min_rf_6p69 {
        class LinkedItems;
    };
    class LMG_min_rf_6p69_desert_eotech_553: LMG_min_rf_6p69_desert {
        class LinkedItems;
    };
    class SMG_min_rf_pp_2000_ekp_8_18: SMG_min_rf_pp_2000 {
        class LinkedItems;
    };
    class srifle_min_rf_orsis_t5000_desert_LRPS: srifle_min_rf_orsis_t5000_desert {
        class LinkedItems;
    };

    class GVAR(LMG_min_rf_6p69_1p_87_snds): LMG_min_rf_6p69_1p_87 {
        scope = 1;
        author = QAUTHOR;
        baseWeapon = "LMG_min_rf_6p69";
        class LinkedItems: LinkedItems {
            class LinkedItemsMuzzle {
                slot = "MuzzleSlot";
                item = "muzzle_snds_H_MG";
            };
        };
    };
    class GVAR(LMG_min_rf_6p69_desert_eotech_553_snds): LMG_min_rf_6p69_desert_eotech_553 {
        scope = 1;
        author = QAUTHOR;
        baseWeapon = "LMG_min_rf_6p69_desert";
        class LinkedItems: LinkedItems {
            class LinkedItemsMuzzle {
                slot = "MuzzleSlot";
                item = "muzzle_snds_H_MG";
            };
        };
    };
    class GVAR(SMG_min_rf_pp_2000_ekp_8_18_snds): SMG_min_rf_pp_2000_ekp_8_18 {
        scope = 1;
        author = QAUTHOR;
        baseWeapon = "SMG_min_rf_pp_2000";
        class LinkedItems: LinkedItems {
            class LinkedItemsMuzzle {
                slot = "MuzzleSlot";
                item = "muzzle_snds_L";
            };
        };
    };
    class GVAR(srifle_min_rf_orsis_t5000_desert_LRPS_snds): srifle_min_rf_orsis_t5000_desert_LRPS {
        scope = 1;
        author = QAUTHOR;
        baseWeapon = "srifle_min_rf_orsis_t5000_desert";
        class LinkedItems: LinkedItems {
            class LinkedItemsMuzzle {
                slot = "MuzzleSlot";
                item = "muzzle_snds_338_sand";
            };
        };
    };
};
