// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
class CfgFactionClasses {
    class ADDON {
        displayName = "2040 NATO (Arid)";
        side = 1;
        priority = 3;
        icon = "\A3\Data_F\cfgFactionClasses_BLU_ca.paa";
        flag = "\A3\Data_F\Flags\Flag_NATO_CO.paa";
    };
};
