#include "script_component.hpp"

// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(B_Fighter_Pilot_F), QGVAR(Hawks_GTK_Boxer_HMG_Sand), QGVAR(Hawks_GTK_Boxer_GMG_Sand), QGVAR(Hawks_GTK_Boxer_IFV_Sand), QGVAR(Hawks_GTK_Boxer_RCH155_Sand), QGVAR(qav_B_challenger2), QGVAR(qav_B_challenger2_e), QGVAR(B_Plane_Fighter_05_F), QGVAR(B_Plane_Fighter_05_Stealth_F), QGVAR(B_T_VTOL_01_infantry_F), QGVAR(B_T_VTOL_01_vehicle_F), QGVAR(B_T_VTOL_01_armed_F), QGVAR(B_Heli_Attack_01_dynamicLoadout_F), QGVAR(B_Heli_Attack_01_pylons_dynamicLoadout_F), QGVAR(B_Heli_Attack_03_F), QGVAR(B_M_Heli_Attack_03_F), QGVAR(B_A_UAV_07_F), QGVAR(B_Heli_Transport_01_unarmed_F), QGVAR(B_Heli_Transport_01_pylons_F), QGVAR(B_APC_Wheeled_01_cannon_F), QGVAR(B_Boat_Armed_01_minigun_F), QGVAR(B_Boat_Transport_01_F), QGVAR(B_Lifeboat), QGVAR(B_SDV_01_F), QGVAR(B_UAV_01_F), QGVAR(B_UAV_02_dynamicLoadout_F), QGVAR(B_HMG_01_F), QGVAR(B_HMG_01_high_F), QGVAR(B_HMG_01_A_F), QGVAR(B_GMG_01_F), QGVAR(B_GMG_01_high_F), QGVAR(B_GMG_01_A_F), QGVAR(B_UGV_02_Science_F), QGVAR(B_UGV_02_Demining_F), QGVAR(B_LSV_01_armed_F), QGVAR(B_LSV_01_AT_F), QGVAR(B_LSV_01_unarmed_F), QGVAR(B_Heli_Transport_03_F), QGVAR(B_Heli_Transport_03_unarmed_F), QGVAR(B_Plane_Fighter_01_F), QGVAR(B_Plane_Fighter_01_Stealth_F), QGVAR(B_UAV_05_F), QGVAR(B_AAA_System_01_F), QGVAR(B_SAM_System_01_F), QGVAR(B_SAM_System_02_F), QGVAR(B_Radar_System_01_F), QGVAR(B_SAM_System_03_F), QGVAR(B_Static_Designator_01_F), QGVAR(B_UAV_06_F), QGVAR(B_UAV_06_medical_F), QGVAR(B_AFV_Wheeled_01_cannon_F), QGVAR(B_AFV_Wheeled_01_up_cannon_F)
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        // The mods these classes build on - skipped whole without them (see the header of
        // tools/gen_mod_factions.py). Tier magazines are named as strings, so FA is not required.
        requiredAddons[] = {"ghost_main", "ghost_vehicle", "QAV_Challenger", "hawks_gtk_boxer"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
