// Generated by tools/aegis_port - do not hand-edit; change the generator and re-run.
// Imported from the public Aegis, Atlas and OpF sources (APL-SA).

    class V_HarnessO_gry;
    class V_HarnessOSpec_brn;
    class V_PlateCarrierIA1_dgtl;
    class V_PlateCarrierIA2_dgtl;
    class V_Rangemaster_belt;
    class V_RebreatherB;
    class Vest_NoCamo_Base;
    class V_HarnessOGL_brn: Vest_NoCamo_Base {
        class ItemInfo;
    };
