// Generated by tools/aegis_port - do not hand-edit; change the generator and re-run.
// Imported from the public Aegis, Atlas and OpF sources (APL-SA).

    class GVAR(V_HarnessO_oicamo): V_HarnessO_gry {
        author = "Avery Kaiserin";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_HarnessO_oicamo_ca.paa";
        displayName = "LBV Harness (Brown)";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\clothing_oicamo_CO.paa", "\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_oicamo_CO.paa"};
    };
    class GVAR(V_Rangemaster_belt_cbr): V_Rangemaster_belt {
        author = "Avery Kaiserin";
        displayName = "Battle Belt (Coyote)";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_Rangemaster_belt_cbr_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\vests\models\characters\Vests\Data\vests_cbr_CO.paa"};
    };
    class GVAR(V_HarnessOSpec_oicamo): V_HarnessOSpec_brn {
        author = "Avery Kaiserin";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_HarnessOSpec_oicamo_ca.paa";
        displayName = "ELBV Harness (Brown)";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\clothing_oicamo_CO.paa", "\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_oicamo_CO.paa"};
    };
    class GVAR(V_HarnessOGL_oicamo): V_HarnessOGL_brn {
        author = "Avery Kaiserin";
        displayName = "LBV Grenadier Harness (Brown)";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_HarnessOGL_oicamo_ca.paa";
        hiddenSelections[] = {"camo1", "camo2"};
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\clothing_oicamo_CO.paa", "\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_oicamo_CO.paa"};
        class ItemInfo: ItemInfo {
            hiddenSelections[] = {"camo1", "camo2"};
        };
    };
    class GVAR(V_PlateCarrierIA2_oli): V_PlateCarrierIA2_dgtl {
        author = "Avery Kaiserin";
        displayName = "GA Carrier Rig (Olive)";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_PlateCarrierIA2_oli_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\vests\models\characters\Vests\Data\equip_IA_Vest01_oli_CO.paa"};
    };
    class GVAR(V_PlateCarrierIA1_oli): V_PlateCarrierIA1_dgtl {
        author = "Avery Kaiserin";
        displayName = "GA Carrier Lite (Olive)";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_PlateCarrierIA1_oli_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\vests\models\characters\Vests\Data\equip_IA_Vest01_oli_CO.paa"};
    };
    class GVAR(V_PlateCarrier2_oli): V_PlateCarrier2_rgr {
        author = "Avery Kaiserin";
        displayName = "Carrier Rig (Olive)";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_PlateCarrier2_oli_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\vests\models\characters\Vests\Data\vests_oli_CO.paa"};
    };
    class GVAR(V_RebreatherRU): V_RebreatherB {
        author = "Avery Kaiserin";
        displayName = "Rebreather [RU]";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_RebreatherRU_CA.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\diver_equip_CO.paa"};
        hiddenUnderwaterSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\diver_equip_CO.paa", "\z\ghost\addons\uniform\models\characters\Uniforms\Data\diver_equip_CO.paa", "\A3\Characters_F\Data\visors_CA.paa"};
    };
    class GVAR(V_HarnessOSpec_ghex_F): V_HarnessOSpec_brn {
        author = "Avery Kaiserin";
        picture = "\z\ghost\addons\vests\models\characters\Vests\Data\UI\icon_V_HarnessOSpec_ghex_F_ca.paa";
        displayName = "ELBV Harness (Green Hex)";
        hiddenSelectionsTextures[] = {"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa", "\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_tna_CO.paa"};
    };
