// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
// The mod's weapons take this addon's wells. A weapon with no well of its own (the MPT-76, the
// PKP) knew its magazines only by name; += keeps whatever wells it had.
class CfgWeapons {
    class DMR_01_base_F;
    class LMG_Zafir_F;
    class LMG_min_rf_6p69_desert;
    class Pistol_Base_F;
    class arifle_AK12_base_F;
    class arifle_ARX_blk_F;
    class arifle_min_rf_ak_12_gp;
    class arifle_min_rf_ak_12_grip;
    class pdw2000_base_F;
    class srifle_min_rf_orsis_t5000_camo;
    class srifle_min_rf_orsis_t5000_desert;
    class srifle_min_rf_orsis_t5000_winter;

    class hgun_Rook40_F: Pistol_Base_F {
        magazineWell[] += {"ghost_fa_minrf_9x19"};
    };
    class arifle_min_rf_aek_a545: arifle_AK12_base_F {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12: arifle_AK12_base_F {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class LMG_min_rf_6p69: LMG_Zafir_F {
        magazineWell[] += {"ghost_fa_minrf_762x54"};
    };
    class SMG_min_rf_pp_2000: pdw2000_base_F {
        magazineWell[] += {"ghost_fa_minrf_9x19"};
    };
    class srifle_min_rf_orsis_t5000: DMR_01_base_F {
        magazineWell[] += {"ghost_fa_minrf_338"};
    };
    class arifle_min_rf_aek_a545_1p_87: arifle_min_rf_aek_a545 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_camo: arifle_min_rf_aek_a545 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_desert: arifle_min_rf_aek_a545 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_eotech_553_ir: arifle_min_rf_aek_a545 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_winter: arifle_min_rf_aek_a545 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_1p_87: arifle_min_rf_ak_12 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_pkm_a: arifle_min_rf_ak_12 {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ash_12: arifle_ARX_blk_F {
        magazineWell[] += {"ghost_fa_minrf_127x55"};
    };
    class LMG_min_rf_6p69_1p_87: LMG_min_rf_6p69 {
        magazineWell[] += {"ghost_fa_minrf_762x54"};
    };
    class LMG_min_rf_6p69_eotech_553: LMG_min_rf_6p69 {
        magazineWell[] += {"ghost_fa_minrf_762x54"};
    };
    class SMG_min_rf_pp_2000_ekp_8_18: SMG_min_rf_pp_2000 {
        magazineWell[] += {"ghost_fa_minrf_9x19"};
    };
    class srifle_min_rf_orsis_t5000_LRPS: srifle_min_rf_orsis_t5000 {
        magazineWell[] += {"ghost_fa_minrf_338"};
    };
    class arifle_min_rf_aek_a545_camo_1p_87_sd: arifle_min_rf_aek_a545_camo {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_desert_1p_87_sd: arifle_min_rf_aek_a545_desert {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_desert_eotech_553_ir: arifle_min_rf_aek_a545_desert {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_aek_a545_winter_1p_87_sd: arifle_min_rf_aek_a545_winter {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_1p_87: arifle_min_rf_ak_12_gp {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_camo: arifle_min_rf_ak_12_gp {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_desert: arifle_min_rf_ak_12_gp {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_eotech_553_ir: arifle_min_rf_ak_12_gp {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_winter: arifle_min_rf_ak_12_gp {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_grip_1p_87: arifle_min_rf_ak_12_grip {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_grip_desert: arifle_min_rf_ak_12_grip {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_grip_eotech_553_ir: arifle_min_rf_ak_12_grip {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ash_12_ekp_8_18: arifle_min_rf_ash_12 {
        magazineWell[] += {"ghost_fa_minrf_127x55"};
    };
    class LMG_min_rf_6p69_desert_eotech_553: LMG_min_rf_6p69_desert {
        magazineWell[] += {"ghost_fa_minrf_762x54"};
    };
    class srifle_min_rf_orsis_t5000_camo_LRPS: srifle_min_rf_orsis_t5000_camo {
        magazineWell[] += {"ghost_fa_minrf_338"};
    };
    class srifle_min_rf_orsis_t5000_desert_LRPS: srifle_min_rf_orsis_t5000_desert {
        magazineWell[] += {"ghost_fa_minrf_338"};
    };
    class srifle_min_rf_orsis_t5000_winter_LRPS: srifle_min_rf_orsis_t5000_winter {
        magazineWell[] += {"ghost_fa_minrf_338"};
    };
    class arifle_min_rf_ak_12_gp_camo_1p_87_sd: arifle_min_rf_ak_12_gp_camo {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_desert_1p_87_sd: arifle_min_rf_ak_12_gp_desert {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_desert_eotech_553_ir: arifle_min_rf_ak_12_gp_desert {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_gp_winter_1p_87_sd: arifle_min_rf_ak_12_gp_winter {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
    class arifle_min_rf_ak_12_grip_desert_eotech_553_ir: arifle_min_rf_ak_12_grip_desert {
        magazineWell[] += {"ghost_fa_minrf_545"};
    };
};
