// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
class CfgFactionClasses {
    class ADDON {
        displayName = "2040 Turkey (Arid)";
        side = 0;
        priority = 13;
        icon = "\TMT\TMT_Core\Data\cfgFactionClasses_TR_ca.paa";
        flag = "\TMT\TMT_Core\Data\flag_Turkish_co.paa";
    };
};
