#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(KAR_FDF35_AA),
            QGVAR(KAR_FDF35_ARTY),
            QGVAR(KAR_FDF35_AT),
            QGVAR(KAR_FDF35_CREW),
            QGVAR(KAR_FDF35_ENG),
            QGVAR(KAR_FDF35_EOD),
            QGVAR(KAR_FDF35_F35),
            QGVAR(KAR_FDF35_F35_S),
            QGVAR(KAR_FDF35_GRE),
            QGVAR(KAR_FDF35_HELIKIPOTER),
            QGVAR(KAR_FDF35_HELI_L),
            QGVAR(KAR_FDF35_IPTSV),
            QGVAR(KAR_FDF35_ITOHJ),
            QGVAR(KAR_FDF35_ITOMIM),
            QGVAR(KAR_FDF35_KRH),
            QGVAR(KAR_FDF35_KRH_W),
            QGVAR(KAR_FDF35_LEO2SG),
            QGVAR(KAR_FDF35_MED),
            QGVAR(KAR_FDF35_MG),
            QGVAR(KAR_FDF35_MK),
            QGVAR(KAR_FDF35_MOSTKA),
            QGVAR(KAR_FDF35_MQ4A),
            QGVAR(KAR_FDF35_MRAP),
            QGVAR(KAR_FDF35_MRAP_HMG),
            QGVAR(KAR_FDF35_PATRIA360),
            QGVAR(KAR_FDF35_PATRIA360_AMOS),
            QGVAR(KAR_FDF35_PATRIA360_ATGM),
            QGVAR(KAR_FDF35_PATRIA360_CV),
            QGVAR(KAR_FDF35_PATRIA660),
            QGVAR(KAR_FDF35_PSTOHJ),
            QGVAR(KAR_FDF35_RADISTI),
            QGVAR(KAR_FDF35_RIF),
            QGVAR(KAR_FDF35_RPSV),
            QGVAR(KAR_FDF35_RSRAKH),
            QGVAR(KAR_FDF35_SERGEI),
            QGVAR(KAR_FDF35_SIS),
            QGVAR(KAR_FDF35_SISU),
            QGVAR(KAR_FDF35_SISU_AMMO),
            QGVAR(KAR_FDF35_SISU_COV),
            QGVAR(KAR_FDF35_SISU_FUEL),
            QGVAR(KAR_FDF35_SISU_MEDICAL),
            QGVAR(KAR_FDF35_SISU_REPAIR),
            QGVAR(KAR_FDF35_SIS_AT),
            QGVAR(KAR_FDF35_SIS_MED),
            QGVAR(KAR_FDF35_SIS_MK),
            QGVAR(KAR_FDF35_SIS_RADISTI),
            QGVAR(KAR_FDF35_SIS_SL),
            QGVAR(KAR_FDF35_SL),
            QGVAR(KAR_FDF35_SNI),
            QGVAR(KAR_FDF35_SOF_AA),
            QGVAR(KAR_FDF35_SOF_AT),
            QGVAR(KAR_FDF35_SOF_ENG),
            QGVAR(KAR_FDF35_SOF_MED),
            QGVAR(KAR_FDF35_SOF_MG),
            QGVAR(KAR_FDF35_SOF_MK),
            QGVAR(KAR_FDF35_SOF_RADISTI),
            QGVAR(KAR_FDF35_SOF_RIF),
            QGVAR(KAR_FDF35_SOF_SL),
            QGVAR(KAR_FDF35_SOF_SNI),
            QGVAR(KAR_FDF35_SOF_SNI_G),
            QGVAR(KAR_FDF35_UAV),
            QGVAR(KAR_FDF35_UAV_OP),
            QGVAR(EF_B_MRAP_01_FSV_MJTF_Wdl),
            QGVAR(EF_B_MRAP_01_AT_MJTF_Wdl),
            QGVAR(EF_B_MRAP_01_LAAD_MJTF_Wdl),
            QGVAR(B_UAV_RC40_HE_RF),
            QGVAR(B_UAV_RC40_SENSOR_RF),
            QGVAR(B_T_UAV_03_dynamicLoadout_F),
            QGVAR(B_T_UGV_01_olive_F),
            QGVAR(B_T_UGV_01_rcws_olive_F),
            QGVAR(GX_B_HONEYBADGER_UGV_AT_GREEN),
            QGVAR(GX_B_HUNTER_SP_UAV),
            QGVAR(GX_B_MAGURA_V5_USV),
            QGVAR(GX_B_MQ8B_UAV_ARMED),
            QGVAR(GX_B_MQ8B_UAV_RECON),
            QGVAR(GX_B_MQ8B_UAV_RECON_SEATED),
            QGVAR(GX_B_THEMIS_UGV_CARGO),
            QGVAR(GX_B_THEMIS_UGV_DEFNDER_MEDIUM),
            QGVAR(GX_B_THEMIS_UGV_HUNTER_LAUNCHER),
            QGVAR(qav_ripsaw_Mk44),
            QGVAR(qav_ripsaw_c),
            QGVAR(rksla3_aeroshark_blufor)
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "ghost_main",
            "KAR_FDF35_Faction",
            "KAR_FDF35_V",
            "KAR_FDF35_U",
            "A3_Weapons_F",
            "A3_Weapons_F_Exp",
            "A3_Weapons_F_Exp_Rifles_AK12",
            "A3_Weapons_F_Mark",
            "A3_Aegis_Weapons_F_Aegis_Rifles_SCAR",
            "A3_Weapons_F_Exp_Rifles_SPAR_01",
            "A3_Weapons_F_Exp_Rifles_SPAR_03",
            "KAR_FDF35_Faction_W",
            "A3_Aegis_Armor_F_Aegis",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Exp_APC_Wheeled_01",
            "A3_Armor_F_Exp_APC_Wheeled_02",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Soft_F_Exp",
            "A3_Soft_F_MRAP_01",
            "A3_Armor_F_Exp_MBT_01",
            "A3_Air_F_Exp_UAV_03",
            "A3_Characters_F_BLUFOR",
            "ghostfa_ammo",
            "ghostfa_vehicles",
            "ghostfa_maincaliber",
            "ghostfa_mediumcaliber",
            "ghostfa_grenade_40mm",
            "ghostfa_missiles",
            "A3_Armor_F_Gamma",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02"
        };
        skipWhenMissingDependencies = 1;
        authorUrl = "https://www.ghostsofbattle.com/";
        author = QAUTHOR;
        authors[] = {"Ghost"};
        VERSION_CONFIG;
    };
};

#include "CfgEditorCategories.hpp"
#include "CfgFactionClasses.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
