#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_EUDF_ACE_B_SpottingScope",
            "ghost_EUDF_Aegis_B_A_Heli_Transport_02_wdl_F",
            "ghost_EUDF_Aegis_B_Heli_Attack_03_F",
            "ghost_EUDF_Aegis_B_Pickup_AT_RF",
            "ghost_EUDF_Atlas_B_A_Plane_Fighter_05_ard_F",
            "ghost_EUDF_Atlas_B_G_LT_01_AA_F",
            "ghost_EUDF_Atlas_B_G_LT_01_AT_F",
            "ghost_EUDF_Atlas_B_G_LT_01_cannon_F",
            "ghost_EUDF_Atlas_B_G_LT_01_scout_F",
            "ghost_EUDF_Atlas_B_G_MBT_03_cannon_F",
            "ghost_EUDF_Atlas_B_JSOC_F",
            "ghost_EUDF_Atlas_B_JSOC_JTAC_F",
            "ghost_EUDF_Atlas_B_JSOC_LAT_F",
            "ghost_EUDF_Atlas_B_JSOC_UAV_F",
            "ghost_EUDF_Atlas_B_JSOC_UAV_lxWS",
            "ghost_EUDF_Atlas_B_T_JSOC_F",
            "ghost_EUDF_Atlas_B_T_JSOC_JTAC_F",
            "ghost_EUDF_Atlas_B_T_JSOC_LAT_F",
            "ghost_EUDF_B_AAA_System_01_F",
            "ghost_EUDF_B_AFV_Wheeled_01_cannon_F",
            "ghost_EUDF_B_AFV_Wheeled_01_up_cannon_F",
            "ghost_EUDF_B_APC_Tracked_01_AA_F",
            "ghost_EUDF_B_APC_Tracked_01_CRV_F",
            "ghost_EUDF_B_APC_Tracked_01_rcws_F",
            "ghost_EUDF_B_A_Plane_Transport_01_infantry_tna_F",
            "ghost_EUDF_B_A_Plane_Transport_01_vehicle_tna_F",
            "ghost_EUDF_B_Boat_Armed_01_minigun_F",
            "ghost_EUDF_B_Boat_Transport_01_F",
            "ghost_EUDF_B_Captain_Pettka_F",
            "ghost_EUDF_B_CommandoMortar_RF",
            "ghost_EUDF_B_Competitor_F",
            "ghost_EUDF_B_Deck_Crew_F",
            "ghost_EUDF_B_Fighter_Pilot_F",
            "ghost_EUDF_B_GMG_01_A_F",
            "ghost_EUDF_B_GMG_01_F",
            "ghost_EUDF_B_GMG_01_high_F",
            "ghost_EUDF_B_HMG_01_A_F",
            "ghost_EUDF_B_HMG_01_F",
            "ghost_EUDF_B_HMG_01_high_F",
            "ghost_EUDF_B_HMG_02_F",
            "ghost_EUDF_B_HMG_02_high_F",
            "ghost_EUDF_B_HeavyGunner_F",
            "ghost_EUDF_B_Heli_Attack_01_dynamicLoadout_F",
            "ghost_EUDF_B_Heli_Attack_01_pylons_dynamicLoadout_F",
            "ghost_EUDF_B_Heli_EC_03_RF",
            "ghost_EUDF_B_Heli_EC_04_military_RF",
            "ghost_EUDF_B_Heli_Light_01_F",
            "ghost_EUDF_B_Heli_Light_01_dynamicLoadout_F",
            "ghost_EUDF_B_Heli_Transport_01_F",
            "ghost_EUDF_B_Heli_Transport_01_pylons_F",
            "ghost_EUDF_B_Heli_Transport_01_unarmed_F",
            "ghost_EUDF_B_Heli_Transport_03_F",
            "ghost_EUDF_B_Heli_Transport_03_unarmed_F",
            "ghost_EUDF_B_Helipilot_F",
            "ghost_EUDF_B_LSV_01_AT_F",
            "ghost_EUDF_B_LSV_01_armed_F",
            "ghost_EUDF_B_LSV_01_light_F",
            "ghost_EUDF_B_LSV_01_unarmed_F",
            "ghost_EUDF_B_Lifeboat",
            "ghost_EUDF_B_MBT_01_TUSK_F",
            "ghost_EUDF_B_MBT_01_arty_F",
            "ghost_EUDF_B_MBT_01_cannon_F",
            "ghost_EUDF_B_MBT_01_mlrs_F",
            "ghost_EUDF_B_MRAP_01_F",
            "ghost_EUDF_B_MRAP_01_gmg_F",
            "ghost_EUDF_B_MRAP_01_hmg_F",
            "ghost_EUDF_B_Mortar_01_F",
            "ghost_EUDF_B_Officer_Parade_F",
            "ghost_EUDF_B_Officer_Parade_Veteran_F",
            "ghost_EUDF_B_Pickup_Comms_rf",
            "ghost_EUDF_B_Pickup_aat_rf",
            "ghost_EUDF_B_Pickup_mmg_rf",
            "ghost_EUDF_B_Pickup_rf",
            "ghost_EUDF_B_Pilot_F",
            "ghost_EUDF_B_Plane_CAS_01_dynamicLoadout_F",
            "ghost_EUDF_B_Plane_Fighter_01_F",
            "ghost_EUDF_B_Plane_Fighter_01_Stealth_F",
            "ghost_EUDF_B_QRF_soldier_LAT_RF",
            "ghost_EUDF_B_QRF_soldier_UAV_RF",
            "ghost_EUDF_B_Quadbike_01_F",
            "ghost_EUDF_B_RadioOperator_F",
            "ghost_EUDF_B_RangeMaster_F",
            "ghost_EUDF_B_Recon_Sharpshooter_F",
            "ghost_EUDF_B_SDV_01_F",
            "ghost_EUDF_B_Sharpshooter_F",
            "ghost_EUDF_B_Ship_Gun_01_F",
            "ghost_EUDF_B_Ship_MRLS_01_F",
            "ghost_EUDF_B_Slingload_01_Ammo_F",
            "ghost_EUDF_B_Slingload_01_Cargo_F",
            "ghost_EUDF_B_Slingload_01_Fuel_F",
            "ghost_EUDF_B_Slingload_01_Medevac_F",
            "ghost_EUDF_B_Slingload_01_Repair_F",
            "ghost_EUDF_B_Soldier_A_F",
            "ghost_EUDF_B_Soldier_CBRN_F",
            "ghost_EUDF_B_Soldier_CQ_F",
            "ghost_EUDF_B_Soldier_GL_F",
            "ghost_EUDF_B_Soldier_MG_F",
            "ghost_EUDF_B_Soldier_SL_F",
            "ghost_EUDF_B_Soldier_TL_F",
            "ghost_EUDF_B_Soldier_lite_F",
            "ghost_EUDF_B_Soldier_unarmed_F",
            "ghost_EUDF_B_Static_Designator_01_F",
            "ghost_EUDF_B_Story_Protagonist_F",
            "ghost_EUDF_B_Survivor_F",
            "ghost_EUDF_B_Truck_01_FFT_rf",
            "ghost_EUDF_B_Truck_01_Repair_F",
            "ghost_EUDF_B_Truck_01_ammo_F",
            "ghost_EUDF_B_Truck_01_box_F",
            "ghost_EUDF_B_Truck_01_cargo_F",
            "ghost_EUDF_B_Truck_01_covered_F",
            "ghost_EUDF_B_Truck_01_flatbed_F",
            "ghost_EUDF_B_Truck_01_fuel_F",
            "ghost_EUDF_B_Truck_01_medical_F",
            "ghost_EUDF_B_Truck_01_mover_F",
            "ghost_EUDF_B_Truck_01_transport_F",
            "ghost_EUDF_B_TwinMortar_RF",
            "ghost_EUDF_B_UAV_01_F",
            "ghost_EUDF_B_UAV_02_lxWS",
            "ghost_EUDF_B_UAV_05_F",
            "ghost_EUDF_B_UAV_RC40_HE_RF",
            "ghost_EUDF_B_UAV_RC40_SENSOR_RF",
            "ghost_EUDF_B_UAV_RC40_SmokeBlue_RF",
            "ghost_EUDF_B_UAV_RC40_SmokeGreen_RF",
            "ghost_EUDF_B_UAV_RC40_SmokeOrange_RF",
            "ghost_EUDF_B_UAV_RC40_SmokeRed_RF",
            "ghost_EUDF_B_UAV_RC40_SmokeWhite_RF",
            "ghost_EUDF_B_UGV_02_Demining_F",
            "ghost_EUDF_B_VTOL_01_armed_F",
            "ghost_EUDF_B_VTOL_01_infantry_F",
            "ghost_EUDF_B_VTOL_01_vehicle_F",
            "ghost_EUDF_B_crew_F",
            "ghost_EUDF_B_diver_F",
            "ghost_EUDF_B_diver_TL_F",
            "ghost_EUDF_B_diver_exp_F",
            "ghost_EUDF_B_engineer_F",
            "ghost_EUDF_B_ghillie_ard_F",
            "ghost_EUDF_B_ghillie_lsh_F",
            "ghost_EUDF_B_ghillie_sard_F",
            "ghost_EUDF_B_ghillie_spotter_ard_F",
            "ghost_EUDF_B_ghillie_spotter_lsh_F",
            "ghost_EUDF_B_ghillie_spotter_sard_F",
            "ghost_EUDF_B_helicrew_F",
            "ghost_EUDF_B_medic_F",
            "ghost_EUDF_B_officer_F",
            "ghost_EUDF_B_qav_abramsx",
            "ghost_EUDF_B_qav_abramsx_templar",
            "ghost_EUDF_B_qav_abramsx_tusk",
            "ghost_EUDF_B_qav_abramsx_zeus",
            "ghost_EUDF_B_recon_AR_F",
            "ghost_EUDF_B_recon_CQ_F",
            "ghost_EUDF_B_recon_F",
            "ghost_EUDF_B_recon_GL_F",
            "ghost_EUDF_B_recon_JTAC_F",
            "ghost_EUDF_B_recon_LAT_F",
            "ghost_EUDF_B_recon_MG_F",
            "ghost_EUDF_B_recon_M_F",
            "ghost_EUDF_B_recon_TL_F",
            "ghost_EUDF_B_recon_exp_F",
            "ghost_EUDF_B_recon_medic_F",
            "ghost_EUDF_B_sniper_F",
            "ghost_EUDF_B_soldier_AAA_F",
            "ghost_EUDF_B_soldier_AAR_F",
            "ghost_EUDF_B_soldier_AAT_F",
            "ghost_EUDF_B_soldier_AA_F",
            "ghost_EUDF_B_soldier_AR_F",
            "ghost_EUDF_B_soldier_AT_F",
            "ghost_EUDF_B_soldier_F",
            "ghost_EUDF_B_soldier_LAT2_F",
            "ghost_EUDF_B_soldier_LAT_F",
            "ghost_EUDF_B_soldier_M_F",
            "ghost_EUDF_B_soldier_PG_F",
            "ghost_EUDF_B_soldier_UAV_F",
            "ghost_EUDF_B_soldier_UAV_lxWS",
            "ghost_EUDF_B_soldier_UGV_02_Demining_F",
            "ghost_EUDF_B_soldier_exp_F",
            "ghost_EUDF_B_soldier_mine_F",
            "ghost_EUDF_B_soldier_repair_F",
            "ghost_EUDF_B_spotter_F",
            "ghost_EUDF_B_static_AA_F",
            "ghost_EUDF_B_static_AT_F",
            "ghost_EUDF_B_support_AMG_F",
            "ghost_EUDF_B_support_AMort_F",
            "ghost_EUDF_B_support_CMort_RF",
            "ghost_EUDF_B_support_GMG_F",
            "ghost_EUDF_B_support_MG_F",
            "ghost_EUDF_B_support_Mort_F",
            "ghost_EUDF_EF_B_AH99J_NATO",
            "ghost_EUDF_EF_B_CombatBoat_AT_NATO",
            "ghost_EUDF_EF_B_CombatBoat_HMG_NATO",
            "ghost_EUDF_EF_B_CombatBoat_Unarmed_NATO",
            "ghost_EUDF_EF_B_MRAP_01_AT_NATO",
            "ghost_EUDF_EF_B_MRAP_01_FSV_NATO",
            "ghost_EUDF_EF_B_MRAP_01_LAAD_NATO",
            "ghost_EUDF_GX_B_HONEYBADGER_UGV_AT_BLACK",
            "ghost_EUDF_GX_B_HONEYBADGER_UGV_AT_DESERT",
            "ghost_EUDF_GX_B_HONEYBADGER_UGV_AT_GREEN",
            "ghost_EUDF_GX_B_HONEYBADGER_UGV_AT_HEX",
            "ghost_EUDF_GX_B_HUNTER_SP_LAUNCHER",
            "ghost_EUDF_GX_B_HUNTER_SP_UAV",
            "ghost_EUDF_GX_B_MAGURA_V5_USV",
            "ghost_EUDF_GX_B_MQ8B_UAV_ARMED",
            "ghost_EUDF_GX_B_MQ8B_UAV_RECON",
            "ghost_EUDF_GX_B_MQ8B_UAV_RECON_SEATED",
            "ghost_EUDF_GX_B_RWS_DEFNDER_MEDIUM",
            "ghost_EUDF_GX_B_THEMIS_UGV_CARGO",
            "ghost_EUDF_GX_B_THEMIS_UGV_DEFNDER_MEDIUM",
            "ghost_EUDF_GX_B_THEMIS_UGV_HUNTER_LAUNCHER",
            "ghost_EUDF_Slingload_MortarContainerLid_AAF_RF",
            "ghost_EUDF_Slingload_MortarContainerLid_Olive_RF",
            "ghost_EUDF_Slingload_MortarContainerLid_Tan_RF",
            "ghost_EUDF_Slingload_MortarContainerLid_nato_RF",
            "ghost_EUDF_Slingload_MortarContainer_AAF_RF",
            "ghost_EUDF_Slingload_MortarContainer_Olive_RF",
            "ghost_EUDF_Slingload_MortarContainer_Tan_RF",
            "ghost_EUDF_Slingload_MortarContainer_nato_RF",
            "ghost_EUDF_ace_csw_HMG_02_bare",
            "ghost_EUDF_ace_csw_HMG_02_bare_high",
            "ghost_EUDF_ace_csw_HMG_02_shield",
            "ghost_EUDF_ace_csw_HMG_02_shield_high",
            "ghost_EUDF_ace_csw_HMG_02_shield_sight",
            "ghost_EUDF_ace_csw_HMG_02_shield_sight_high",
            "ghost_EUDF_ace_csw_HMG_02_sight",
            "ghost_EUDF_ace_csw_HMG_02_sight_high",
            "ghost_EUDF_ace_dragon_staticAssembled",
            "ghost_EUDF_ghost_naval_vlsAA",
            "ghost_EUDF_qav_b_ripsaw_Mk44",
            "ghost_EUDF_rev_B_Plane_Fighter_04_F",
            "ghost_EUDF_B_UAV_01_backpack_F",
            "ghost_EUDF_C_IDAP_UAV_06_antimine_backpack_F",
            "ghost_EUDF_C_IDAP_UAV_06_antimine_F",
            "ghost_EUDF_B_Heli_Transport_01_medevac_F",
            "ghost_EUDF_Drone_Operator"
        };
        weapons[] = {"ghost_EUDF_LMG_Mk200_plain_RCO_LP_F_snds","ghost_EUDF_MMG_02_sand_RCO_LP_F_snds","ghost_EUDF_SMG_01_Holo_F_snds","ghost_EUDF_SMG_01_black_Holo_F_snds","ghost_EUDF_arifle_MXC_ACO_pointer_F_snds","ghost_EUDF_arifle_MXC_F_snds","ghost_EUDF_arifle_MXC_Holo_F_snds","ghost_EUDF_arifle_MXC_Holo_flash_F_snds","ghost_EUDF_arifle_MXC_Holo_pointer_F_snds","ghost_EUDF_arifle_MXM_MOS_LP_BI_F_snds","ghost_EUDF_arifle_MX_ACO_pointer_F_snds","ghost_EUDF_arifle_MX_GL_ACO_pointer_F_snds","ghost_EUDF_arifle_MX_GL_Hamr_pointer_F_snds","ghost_EUDF_arifle_MX_Hamr_pointer_F_snds","ghost_EUDF_arifle_MX_Holo_pointer_F_snds","ghost_EUDF_arifle_MX_SW_Hamr_pointer_F_snds","ghost_EUDF_srifle_DMR_03_tan_AMS_LP_F_snds","ghost_EUDF_srifle_LRR_camo_LRPS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
