#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(E22_B_JC_W_SAM_system_01_F),
            QGVAR(E22_B_JC_W_AAA_System_01_F),
            QGVAR(E22_B_JC_W_Radar_system_01_F),
            QGVAR(ACE_B_SpottingScope),
            QGVAR(Aegis_B_A_Heli_Transport_02_wdl_F),
            QGVAR(Aegis_B_Heli_Attack_03_F),
            QGVAR(Aegis_B_Pickup_AT_RF),
            QGVAR(Atlas_B_A_Plane_Fighter_05_ard_F),
            QGVAR(Atlas_B_G_LT_01_AA_F),
            QGVAR(Atlas_B_G_LT_01_AT_F),
            QGVAR(Atlas_B_G_LT_01_cannon_F),
            QGVAR(Atlas_B_G_LT_01_scout_F),
            QGVAR(Atlas_B_G_MBT_03_cannon_F),
            QGVAR(Atlas_B_JSOC_F),
            QGVAR(Atlas_B_JSOC_JTAC_F),
            QGVAR(Atlas_B_JSOC_LAT_F),
            QGVAR(Atlas_B_JSOC_UAV_F),
            QGVAR(Atlas_B_JSOC_UAV_lxWS),
            QGVAR(Atlas_B_T_JSOC_F),
            QGVAR(Atlas_B_T_JSOC_JTAC_F),
            QGVAR(Atlas_B_T_JSOC_LAT_F),
            QGVAR(B_AAA_System_01_F),
            QGVAR(B_AFV_Wheeled_01_cannon_F),
            QGVAR(B_AFV_Wheeled_01_up_cannon_F),
            QGVAR(B_APC_Tracked_01_AA_F),
            QGVAR(B_APC_Tracked_01_CRV_F),
            QGVAR(B_APC_Tracked_01_rcws_F),
            QGVAR(B_A_Plane_Transport_01_infantry_tna_F),
            QGVAR(B_A_Plane_Transport_01_vehicle_tna_F),
            QGVAR(B_Boat_Armed_01_minigun_F),
            QGVAR(B_Boat_Transport_01_F),
            QGVAR(B_Captain_Pettka_F),
            QGVAR(B_CommandoMortar_RF),
            QGVAR(B_Competitor_F),
            QGVAR(B_Deck_Crew_F),
            QGVAR(B_Fighter_Pilot_F),
            QGVAR(B_GMG_01_A_F),
            QGVAR(B_GMG_01_F),
            QGVAR(B_GMG_01_high_F),
            QGVAR(B_HMG_01_A_F),
            QGVAR(B_HMG_01_F),
            QGVAR(B_HMG_01_high_F),
            QGVAR(B_HMG_02_F),
            QGVAR(B_HMG_02_high_F),
            QGVAR(B_HeavyGunner_F),
            QGVAR(B_Heli_Attack_01_dynamicLoadout_F),
            QGVAR(B_Heli_Attack_01_pylons_dynamicLoadout_F),
            QGVAR(B_Heli_EC_03_RF),
            QGVAR(B_Heli_EC_04_military_RF),
            QGVAR(B_Heli_Light_01_F),
            QGVAR(B_Heli_Light_01_dynamicLoadout_F),
            QGVAR(B_Heli_Transport_01_F),
            QGVAR(B_Heli_Transport_01_pylons_F),
            QGVAR(B_Heli_Transport_01_unarmed_F),
            QGVAR(B_Heli_Transport_03_F),
            QGVAR(B_Heli_Transport_03_unarmed_F),
            QGVAR(B_Helipilot_F),
            QGVAR(B_LSV_01_AT_F),
            QGVAR(B_LSV_01_armed_F),
            QGVAR(B_LSV_01_light_F),
            QGVAR(B_LSV_01_unarmed_F),
            QGVAR(B_Lifeboat),
            QGVAR(B_MBT_01_TUSK_F),
            QGVAR(B_MBT_01_arty_F),
            QGVAR(B_MBT_01_cannon_F),
            QGVAR(B_MBT_01_mlrs_F),
            QGVAR(B_MRAP_01_F),
            QGVAR(B_MRAP_01_gmg_F),
            QGVAR(B_MRAP_01_hmg_F),
            QGVAR(B_Mortar_01_F),
            QGVAR(B_Officer_Parade_F),
            QGVAR(B_Officer_Parade_Veteran_F),
            QGVAR(B_Pickup_Comms_rf),
            QGVAR(B_Pickup_aat_rf),
            QGVAR(B_Pickup_mmg_rf),
            QGVAR(B_Pickup_rf),
            QGVAR(B_Pilot_F),
            QGVAR(B_Plane_CAS_01_dynamicLoadout_F),
            QGVAR(B_Plane_Fighter_01_F),
            QGVAR(B_Plane_Fighter_01_Stealth_F),
            QGVAR(B_QRF_soldier_LAT_RF),
            QGVAR(B_QRF_soldier_UAV_RF),
            QGVAR(B_Quadbike_01_F),
            QGVAR(B_RadioOperator_F),
            QGVAR(B_RangeMaster_F),
            QGVAR(B_Recon_Sharpshooter_F),
            QGVAR(B_SDV_01_F),
            QGVAR(B_Sharpshooter_F),
            QGVAR(B_Ship_Gun_01_F),
            QGVAR(B_Ship_MRLS_01_F),
            QGVAR(B_Slingload_01_Ammo_F),
            QGVAR(B_Slingload_01_Cargo_F),
            QGVAR(B_Slingload_01_Fuel_F),
            QGVAR(B_Slingload_01_Medevac_F),
            QGVAR(B_Slingload_01_Repair_F),
            QGVAR(B_Soldier_A_F),
            QGVAR(B_Soldier_CBRN_F),
            QGVAR(B_Soldier_CQ_F),
            QGVAR(B_Soldier_GL_F),
            QGVAR(B_Soldier_MG_F),
            QGVAR(B_Soldier_SL_F),
            QGVAR(B_Soldier_TL_F),
            QGVAR(B_Soldier_lite_F),
            QGVAR(B_Soldier_unarmed_F),
            QGVAR(B_Static_Designator_01_F),
            QGVAR(B_Story_Protagonist_F),
            QGVAR(B_Survivor_F),
            QGVAR(B_Truck_01_FFT_rf),
            QGVAR(B_Truck_01_Repair_F),
            QGVAR(B_Truck_01_ammo_F),
            QGVAR(B_Truck_01_box_F),
            QGVAR(B_Truck_01_cargo_F),
            QGVAR(B_Truck_01_covered_F),
            QGVAR(B_Truck_01_flatbed_F),
            QGVAR(B_Truck_01_fuel_F),
            QGVAR(B_Truck_01_medical_F),
            QGVAR(B_Truck_01_mover_F),
            QGVAR(B_Truck_01_transport_F),
            QGVAR(B_TwinMortar_RF),
            QGVAR(B_UAV_01_F),
            QGVAR(B_UAV_02_lxWS),
            QGVAR(B_UAV_05_F),
            QGVAR(B_UAV_RC40_HE_RF),
            QGVAR(B_UAV_RC40_SENSOR_RF),
            QGVAR(B_UAV_RC40_SmokeBlue_RF),
            QGVAR(B_UAV_RC40_SmokeGreen_RF),
            QGVAR(B_UAV_RC40_SmokeOrange_RF),
            QGVAR(B_UAV_RC40_SmokeRed_RF),
            QGVAR(B_UAV_RC40_SmokeWhite_RF),
            QGVAR(B_UGV_02_Demining_F),
            QGVAR(B_VTOL_01_armed_F),
            QGVAR(B_VTOL_01_infantry_F),
            QGVAR(B_VTOL_01_vehicle_F),
            QGVAR(B_crew_F),
            QGVAR(B_diver_F),
            QGVAR(B_diver_TL_F),
            QGVAR(B_diver_exp_F),
            QGVAR(B_engineer_F),
            QGVAR(B_ghillie_ard_F),
            QGVAR(B_ghillie_lsh_F),
            QGVAR(B_ghillie_sard_F),
            QGVAR(B_ghillie_spotter_ard_F),
            QGVAR(B_ghillie_spotter_lsh_F),
            QGVAR(B_ghillie_spotter_sard_F),
            QGVAR(B_helicrew_F),
            QGVAR(B_medic_F),
            QGVAR(B_officer_F),
            QGVAR(B_qav_abramsx),
            QGVAR(B_qav_abramsx_templar),
            QGVAR(B_qav_abramsx_tusk),
            QGVAR(B_qav_abramsx_zeus),
            QGVAR(B_recon_AR_F),
            QGVAR(B_recon_CQ_F),
            QGVAR(B_recon_F),
            QGVAR(B_recon_GL_F),
            QGVAR(B_recon_JTAC_F),
            QGVAR(B_recon_LAT_F),
            QGVAR(B_recon_MG_F),
            QGVAR(B_recon_M_F),
            QGVAR(B_recon_TL_F),
            QGVAR(B_recon_exp_F),
            QGVAR(B_recon_medic_F),
            QGVAR(B_sniper_F),
            QGVAR(B_soldier_AAA_F),
            QGVAR(B_soldier_AAR_F),
            QGVAR(B_soldier_AAT_F),
            QGVAR(B_soldier_AA_F),
            QGVAR(B_soldier_AR_F),
            QGVAR(B_soldier_AT_F),
            QGVAR(B_soldier_F),
            QGVAR(B_soldier_LAT2_F),
            QGVAR(B_soldier_LAT_F),
            QGVAR(B_soldier_M_F),
            QGVAR(B_soldier_PG_F),
            QGVAR(B_soldier_UAV_F),
            QGVAR(B_soldier_UAV_lxWS),
            QGVAR(B_soldier_UGV_02_Demining_F),
            QGVAR(B_soldier_exp_F),
            QGVAR(B_soldier_mine_F),
            QGVAR(B_soldier_repair_F),
            QGVAR(B_spotter_F),
            QGVAR(B_static_AA_F),
            QGVAR(B_static_AT_F),
            QGVAR(B_support_AMG_F),
            QGVAR(B_support_AMort_F),
            QGVAR(B_support_CMort_RF),
            QGVAR(B_support_GMG_F),
            QGVAR(B_support_MG_F),
            QGVAR(B_support_Mort_F),
            QGVAR(EF_B_AH99J_NATO),
            QGVAR(EF_B_CombatBoat_AT_NATO),
            QGVAR(EF_B_CombatBoat_HMG_NATO),
            QGVAR(EF_B_CombatBoat_Unarmed_NATO),
            QGVAR(GX_B_HONEYBADGER_UGV_AT_BLACK),
            QGVAR(GX_B_HONEYBADGER_UGV_AT_DESERT),
            QGVAR(GX_B_HONEYBADGER_UGV_AT_GREEN),
            QGVAR(GX_B_HONEYBADGER_UGV_AT_HEX),
            QGVAR(GX_B_HUNTER_SP_LAUNCHER),
            QGVAR(GX_B_HUNTER_SP_UAV),
            QGVAR(GX_B_MAGURA_V5_USV),
            QGVAR(GX_B_MQ8B_UAV_ARMED),
            QGVAR(GX_B_MQ8B_UAV_RECON),
            QGVAR(GX_B_MQ8B_UAV_RECON_SEATED),
            QGVAR(GX_B_RWS_DEFNDER_MEDIUM),
            QGVAR(GX_B_THEMIS_UGV_CARGO),
            QGVAR(GX_B_THEMIS_UGV_DEFNDER_MEDIUM),
            QGVAR(GX_B_THEMIS_UGV_HUNTER_LAUNCHER),
            QGVAR(qav_challenger2),
            QGVAR(qav_challenger2_e),
            QGVAR(Slingload_MortarContainerLid_AAF_RF),
            QGVAR(Slingload_MortarContainerLid_Olive_RF),
            QGVAR(Slingload_MortarContainerLid_Tan_RF),
            QGVAR(Slingload_MortarContainerLid_nato_RF),
            QGVAR(Slingload_MortarContainer_AAF_RF),
            QGVAR(Slingload_MortarContainer_Olive_RF),
            QGVAR(Slingload_MortarContainer_Tan_RF),
            QGVAR(Slingload_MortarContainer_nato_RF),
            QGVAR(ace_csw_HMG_02_bare),
            QGVAR(ace_csw_HMG_02_bare_high),
            QGVAR(ace_csw_HMG_02_shield),
            QGVAR(ace_csw_HMG_02_shield_high),
            QGVAR(ace_csw_HMG_02_shield_sight),
            QGVAR(ace_csw_HMG_02_shield_sight_high),
            QGVAR(ace_csw_HMG_02_sight),
            QGVAR(ace_csw_HMG_02_sight_high),
            QGVAR(ace_dragon_staticAssembled),
            QGVAR(ghost_naval_vlsAA),
            QGVAR(qav_b_ripsaw_Mk44),
            QGVAR(rev_B_Plane_Fighter_04_F),
            QGVAR(B_UAV_01_backpack_F),
            QGVAR(C_IDAP_UAV_06_antimine_backpack_F),
            QGVAR(C_IDAP_UAV_06_antimine_F),
            QGVAR(B_Heli_Transport_01_medevac_F),
            QGVAR(Drone_Operator)
        };
        weapons[] = {QGVAR(LMG_Mk200_plain_RCO_LP_F_snds),QGVAR(MMG_02_sand_RCO_LP_F_snds),QGVAR(SMG_01_Holo_F_snds),QGVAR(SMG_01_black_Holo_F_snds),QGVAR(arifle_MXC_ACO_pointer_F_snds),QGVAR(arifle_MXC_F_snds),QGVAR(arifle_MXC_Holo_F_snds),QGVAR(arifle_MXC_Holo_flash_F_snds),QGVAR(arifle_MXC_Holo_pointer_F_snds),QGVAR(arifle_MXM_MOS_LP_BI_F_snds),QGVAR(arifle_MX_ACO_pointer_F_snds),QGVAR(arifle_MX_GL_ACO_pointer_F_snds),QGVAR(arifle_MX_GL_Hamr_pointer_F_snds),QGVAR(arifle_MX_Hamr_pointer_F_snds),QGVAR(arifle_MX_Holo_pointer_F_snds),QGVAR(arifle_MX_SW_Hamr_pointer_F_snds),QGVAR(srifle_DMR_03_tan_AMS_LP_F_snds),QGVAR(srifle_LRR_camo_LRPS_F_snds)};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main", "ghost_uniform", "ghost_vehicle"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
