#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {
            QGVAR(EF_V_AAV_Black),
            QGVAR(EF_V_AAV_Diver_Black),
            QGVAR(EF_V_AAV_Diver_Alt_Black),
            QGVAR(EF_V_AAV_Diver_NoReb_Black),
            QGVAR(EF_V_AAV_Diver_NoReb_Alt_Black),
            QGVAR(EF_V_AAV_Rifleman_Black),
            QGVAR(EF_V_AAV_Rifleman_Alt_Black),
            QGVAR(EF_V_AAV_Sailor_Black),
            QGVAR(EF_V_AAV_Sailor_Alt_Black),
            QGVAR(EF_V_AAV_Scout_Black),
            QGVAR(EF_V_AAV_Scout_Alt_Black),
            QGVAR(EF_V_AAV_Support_Black),
            QGVAR(EF_V_AAV_TL_Black),
            QGVAR(EF_V_AAV_TL_Alt_Black),
            QGVAR(EF_V_AAV_Coy),
            QGVAR(EF_V_AAV_Diver_Coy),
            QGVAR(EF_V_AAV_Diver_NoReb_Coy),
            QGVAR(EF_V_AAV_Diver_NoReb_Alt_Coy),
            QGVAR(EF_V_AAV_Rifleman_Coy),
            QGVAR(EF_V_AAV_Rifleman_Alt_Coy),
            QGVAR(EF_V_AAV_Sailor_Coy),
            QGVAR(EF_V_AAV_Sailor_Alt_Coy),
            QGVAR(EF_V_AAV_Scout_Coy),
            QGVAR(EF_V_AAV_Scout_Alt_Coy),
            QGVAR(EF_V_AAV_Support_Coy),
            QGVAR(EF_V_AAV_TL_Coy),
            QGVAR(EF_V_AAV_TL_Alt_Coy),
            QGVAR(EFA_V_AAV_des),
            QGVAR(EFA_V_AAV_Diver_des),
            QGVAR(EFA_V_AAV_Diver_Alt_des),
            QGVAR(EFA_V_AAV_Diver_NoReb_des),
            QGVAR(EFA_V_AAV_Diver_NoReb_Alt_des),
            QGVAR(EFA_V_AAV_Rifleman_des),
            QGVAR(EFA_V_AAV_Rifleman_Alt_des),
            QGVAR(EFA_V_AAV_Sailor_des),
            QGVAR(EFA_V_AAV_Sailor_Alt_des),
            QGVAR(EFA_V_AAV_Scout_DES),
            QGVAR(EFA_V_AAV_Scout_Alt_DES),
            QGVAR(EFA_V_AAV_Support_des),
            QGVAR(EFA_V_AAV_TL_des),
            QGVAR(EFA_V_AAV_TL_Alt_des),
            QGVAR(EFA_V_AAV_tna),
            QGVAR(EFA_V_AAV_Diver_tna),
            QGVAR(EFA_V_AAV_Diver_Alt_tna),
            QGVAR(EFA_V_AAV_Diver_NoReb_Alt_tna),
            QGVAR(EFA_V_AAV_Rifleman_tna),
            QGVAR(EFA_V_AAV_Rifleman_Alt_tna),
            QGVAR(EFA_V_AAV_Sailor_tna),
            QGVAR(EFA_V_AAV_Sailor_Alt_tna),
            QGVAR(EFA_V_AAV_Scout_tna),
            QGVAR(EFA_V_AAV_Scout_Alt_tna),
            QGVAR(EFA_V_AAV_Support_tna),
            QGVAR(EFA_V_AAV_TL_tna),
            QGVAR(EFA_V_AAV_TL_Alt_tna),
            QGVAR(EFA_V_AAV_wdl),
            QGVAR(EFA_V_AAV_Diver_wdl),
            QGVAR(EFA_V_AAV_Diver_Alt_wdl),
            QGVAR(EFA_V_AAV_Diver_NoReb_wdl),
            QGVAR(EFA_V_AAV_Diver_NoReb_Alt_wdl),
            QGVAR(EFA_V_AAV_Rifleman_wdl),
            QGVAR(EFA_V_AAV_Rifleman_Alt_wdl),
            QGVAR(EFA_V_AAV_Sailor_wdl),
            QGVAR(EFA_V_AAV_Sailor_Alt_wdl),
            QGVAR(EFA_V_AAV_Scout_wdl),
            QGVAR(EFA_V_AAV_Scout_Alt_wdl),
            QGVAR(EFA_V_AAV_Support_wdl),
            QGVAR(EFA_V_AAV_TL_wdl),
            QGVAR(EFA_V_AAV_Diver_Alt_MTP),
            QGVAR(EFA_V_AAV_Diver_NoReb_MTP),
            QGVAR(EFA_V_AAV_Diver_NoReb_Alt_MTP),
            QGVAR(EFA_V_AAV_Rifleman_Alt_MTP),
            QGVAR(EFA_V_AAV_Sailor_Alt_MTP),
            QGVAR(EFA_V_AAV_Scout_Alt_MTP),
            QGVAR(EFA_V_AAV_TL_Alt_MTP),
            QGVAR(EFA_V_AAV_MTP),
            QGVAR(EFA_V_AAV_Diver_MTP),
            QGVAR(EFA_V_AAV_Rifleman_MTP),
            QGVAR(EFA_V_AAV_Sailor_MTP),
            QGVAR(EFA_V_AAV_Scout_MTP),
            QGVAR(EFA_V_AAV_Support_MTP),
            QGVAR(EFA_V_AAV_TL_MTP),
            QGVAR(EF_V_AAV_Olive),
            QGVAR(EF_V_AAV_Diver_Olive),
            QGVAR(EF_V_AAV_Diver_Alt_Olive),
            QGVAR(EF_V_AAV_Diver_NoReb_Olive),
            QGVAR(EF_V_AAV_Diver_NoReb_Alt_Olive),
            QGVAR(EF_V_AAV_Rifleman_Olive),
            QGVAR(EF_V_AAV_Rifleman_Alt_Olive),
            QGVAR(EF_V_AAV_Sailor_Olive),
            QGVAR(EF_V_AAV_Sailor_Alt_Olive),
            QGVAR(EF_V_AAV_Scout_Alt_Olive),
            QGVAR(EF_V_AAV_Support_Olive),
            QGVAR(EF_V_AAV_TL_Olive),
            QGVAR(EF_V_AAV_TL_Alt_Olive),
            QGVAR(EF_V_CCR_Rifleman_Black),
            QGVAR(EF_V_CCR_Rifleman_Alt_Black),
            QGVAR(EF_V_CCR_Scout_Black),
            QGVAR(EF_V_CCR_Scout_Alt_Black),
            QGVAR(EF_V_CCR_Support_Black),
            QGVAR(EF_V_CCR_TL_Black),
            QGVAR(EF_V_CCR_TL_Alt_Black),
            QGVAR(EF_V_CCR_Rifleman_Coy),
            QGVAR(EF_V_CCR_Rifleman_Alt_Coy),
            QGVAR(EF_V_CCR_Scout_Coy),
            QGVAR(EF_V_CCR_Scout_Alt_Coy),
            QGVAR(EF_V_CCR_Support_Coy),
            QGVAR(EF_V_CCR_TL_Coy),
            QGVAR(EF_V_CCR_TL_Alt_Coy),
            QGVAR(EFA_V_CCR_Rifleman_des),
            QGVAR(EFA_V_CCR_Rifleman_Alt_des),
            QGVAR(EFA_V_CCR_Scout_des),
            QGVAR(EFA_V_CCR_Scout_Alt_des),
            QGVAR(EFA_V_CCR_Support_des),
            QGVAR(EFA_V_CCR_TL_Alt_des),
            QGVAR(EFA_V_CCR_Rifleman_tna),
            QGVAR(EFA_V_CCR_Rifleman_Alt_tna),
            QGVAR(EFA_V_CCR_Scout_tna),
            QGVAR(EFA_V_CCR_Scout_Alt_tna),
            QGVAR(EFA_V_CCR_Support_tna),
            QGVAR(EFA_V_CCR_TL_tna),
            QGVAR(EFA_V_CCR_TL_Alt_tna),
            QGVAR(EFA_V_CCR_Rifleman_wdl),
            QGVAR(EFA_V_CCR_Rifleman_Alt_wdl),
            QGVAR(EFA_V_CCR_Scout_wdl),
            QGVAR(EFA_V_CCR_Scout_Alt_wdl),
            QGVAR(EFA_V_CCR_Support_wdl),
            QGVAR(EFA_V_CCR_TL_wdl),
            QGVAR(EFA_V_CCR_TL_Alt_wdl),
            QGVAR(EFA_V_CCR_Rifleman_Alt_MTP),
            QGVAR(EFA_V_CCR_Scout_Alt_MTP),
            QGVAR(EFA_V_CCR_TL_Alt_MTP),
            QGVAR(EFA_V_CCR_Rifleman_MTP),
            QGVAR(EFA_V_CCR_Scout_MTP),
            QGVAR(EFA_V_CCR_Support_MTP),
            QGVAR(EFA_V_CCR_TL_MTP),
            QGVAR(EF_V_CCR_Rifleman_Olive),
            QGVAR(EF_V_CCR_Scout_Olive),
            QGVAR(EF_V_CCR_Scout_Alt_Olive),
            QGVAR(EF_V_CCR_Support_Olive),
            QGVAR(EF_V_CCR_TL_Olive),
            QGVAR(EF_V_CCR_TL_Alt_Olive),
            QGVAR(EF_V_CCR_Rifleman_Alt_Olive),
            QGVAR(EFA_V_CCR_TL_des),
            QGVAR(EF_V_AAV_Scout_Olive),
            QGVAR(EFA_V_AAV_TL_Alt_wdl),
            QGVAR(EFA_V_AAV_Diver_NoReb_tna),
            QGVAR(EF_V_AAV_Diver_Alt_Coy)
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "ghost_main",
            "A3_EFA_characters_f_Aegis"
        };
        skipWhenMissingDependencies = 1;
        authorUrl = "https://www.ghostsofbattle.com/";
        author = QAUTHOR;
        authors[] = {""};
        VERSION_CONFIG;
    };
};

#include "CfgEventHandlers.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
