#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "ghost_main",
            "A3_Atlas_Soft_F_Atlas_Truck_02",
            "A3_Aegis_Soft_F_Aegis_Truck_02",
            "A3_Soft_F_Gamma_Truck_02",
            "ace_cookoff",
            "A3_Sounds_F",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Enoch_Truck_02",
            "Vehicles_F_lxWS_Truck_02",
            "ace_refuel",
            "ace_vehicles",
            "ace_cargo",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "ace_repair",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F",
            "A3_Data_F_ParticleEffects",
            "CUP_Core",
            "chongo_c",
            "A3_Map_seangola",
            "ace_interaction",
            "ace_tagging",
            "acre_sys_attenuate",
            "A3_Armor_F_Beta",
            "A3_Data_F_Curator",
            "ace_thermals",
            "zen_attributes",
            "cba_xeh",
            "acre_sys_rack",
            "A3_Characters_F",
            "A3_Aegis_Characters_F_Aegis",
            "ace_nouniformrestrictions",
            "A3_Iransf_Characters_F_Iransf",
            "aceax_ingame",
            "A3_Sounds_F_Exp",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "acre_sys_components",
            "A3_Air_F_Heli",
            "ace_explosives",
            "A3_Characters_F_Mark",
            "A3_Atlas_Soft_F_Atlas_LSV_02",
            "A3_Soft_F_Exp_LSV_02",
            "ace_realisticnames",
            "ghost_acre",
            "A3_Aegis_Soft_F_Aegis_LSV_02",
            "A3_Atlas_Soft_F_Atlas_Quadbike_01",
            "A3_Soft_F_Quadbike_01",
            "ace_rearm",
            "cba_xeh_ws",
            "A3_Opf_Soft_F_Opf_Truck_02",
            "A3_Atlas_Static_F_Atlas_AA_01",
            "A3_Static_F_AA_01",
            "A3_Aegis_Static_F_Aegis_AA_01",
            "ace_csw",
            "A3_Static_F",
            "A3_Static_F_AT_01",
            "CUP_WarfareBuildings",
            "ace_dragging",
            "A3_Atlas_Static_F_Atlas_AT_01",
            "A3_Aegis_Static_F_Aegis_AT_01",
            "ace_javelin",
            "A3_Atlas_Static_F_Atlas_GMG_01",
            "A3_Aegis_Static_F_Aegis_GMG_01",
            "A3_Atlas_Static_F_Atlas_HMG_01",
            "A3_Atlas_Static_F_Atlas_HMG_02",
            "A3_Static_F_HMG_02",
            "A3_Atlas_Static_F_Atlas_Mortar_01",
            "A3_Static_F_Mortar_01",
            "A3_Aegis_Static_F_Aegis_Mortar_01",
            "ace_mk6mortar",
            "ace_artillerytables",
            "A3_Atlas_Air_F_Atlas_Heli_Attack_02",
            "A3_Air_F_Beta_Heli_Attack_02",
            "ace_aircraft",
            "ace_fastroping",
            "acre_sys_intercom",
            "A3_Air_F",
            "ace_logistics_uavbattery",
            "A3_Atlas_Air_F_Atlas_Heli_Attack_04",
            "A3_Aegis_Air_F_Aegis_Heli_Attack_04",
            "A3_Aegis_Sounds_F_Aegis",
            "A3_Atlas_Air_F_Atlas_Heli_Light_02",
            "A3_Air_F_Heli_Light_02",
            "A3_Aegis_Air_F_Aegis_Heli_Light_02",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Beta_Heli_Transport_01",
            "Air_F_lxWS_Heli_Light_02",
            "A3_Aegis_Air_F_Aegis_Heli_Attack_03",
            "A3_Atlas_Air_F_Atlas_Plane_Fighter_03",
            "A3_Aegis_Air_F_Aegis_Plane_Fighter_03",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_Beta",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "A3_Aegis_Air_F_Aegis",
            "A3_Aegis_Air_F_Aegis_Plane_Fighter_05",
            "A3_Aegis_Air_F_Aegis_Plane_Transport_01",
            "A3_Atlas_Air_F_Atlas_Plane_Transport_01",
            "A3_Atlas_Armor_F_Atlas_APC_Tracked_02",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Aegis_Armor_F_Aegis_APC_Tracked_02",
            "ace_vehicle_damage",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "A3_Atlas_Armor_F_Atlas_APC_Wheeled_02",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Aegis_Armor_F_Aegis_APC_Wheeled_02",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "Vehicles_F_lxWS_APC_Wheeled_01",
            "A3_Aegis_Armor_F_Aegis_APC_Wheeled_04",
            "vehicles_1_F_lxWS_APC_Wheeled_02",
            "PJC_OCE",
            "A3_Atlas_Armor_F_Atlas_MBT_02",
            "A3_Aegis_Armor_F_Aegis_MBT_02",
            "ace_hunterkiller",
            "A3_Atlas_Characters_F_Atlas"
        };
        authorUrl = "https://www.ghostsofbattle.com/";
        author = QAUTHOR;
        authors[] = {""};
        VERSION_CONFIG;
    };
};

#include "CfgEventHandlers.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
#include "CfgFactionClasses.hpp"
#include "CfgGroups.hpp"

