#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(Athena_B_A_Heli_Transport_02_wdl_F),
            QGVAR(Athena_B_G_Heli_Attack_03_F),
            QGVAR(Athena_B_G_Plane_Fighter_05_F),
            QGVAR(Athena_B_G_Plane_Fighter_05_Stealth_F),
            QGVAR(Athena_B_Heli_Transport_03_F),
            QGVAR(Athena_B_Heli_Transport_03_unarmed_F),
            QGVAR(Athena_O_Spotter_F),
            QGVAR(Athena_O_T_Boat_Armed_01_hmg_F),
            QGVAR(Athena_O_T_Boat_Transport_01_F),
            QGVAR(Athena_O_T_CombatBoat_AT_EF),
            QGVAR(Athena_O_T_CombatBoat_HMG_EF),
            QGVAR(Athena_O_T_CombatBoat_Unarmed_EF),
            QGVAR(Athena_O_T_Crew_F),
            QGVAR(Athena_O_T_Diver_F),
            QGVAR(Athena_O_T_Diver_TL_F),
            QGVAR(Athena_O_T_Diver_exp_F),
            QGVAR(Athena_O_T_Engineer_F),
            QGVAR(Athena_O_T_Fighter_Pilot_F),
            QGVAR(Athena_O_T_GMG_01_A_F),
            QGVAR(Athena_O_T_GMG_01_F),
            QGVAR(Athena_O_T_GMG_01_high_F),
            QGVAR(Athena_O_T_HMG_01_A_F),
            QGVAR(Athena_O_T_HMG_01_F),
            QGVAR(Athena_O_T_HMG_01_high_F),
            QGVAR(Athena_O_T_Heli_Transport_01_F),
            QGVAR(Athena_O_T_Helicrew_F),
            QGVAR(Athena_O_T_Helipilot_F),
            QGVAR(Athena_O_T_MBT_03_cannon_F),
            QGVAR(Athena_O_T_MRAP_03_F),
            QGVAR(Athena_O_T_MRAP_03_gmg_F),
            QGVAR(Athena_O_T_MRAP_03_hmg_F),
            QGVAR(Athena_O_T_Medic_F),
            QGVAR(Athena_O_T_Mortar_01_F),
            QGVAR(Athena_O_T_Officer_F),
            QGVAR(Athena_O_T_RadioOperator_F),
            QGVAR(Athena_O_T_Recon_AR_F),
            QGVAR(Athena_O_T_Recon_F),
            QGVAR(Athena_O_T_Recon_LAT_F),
            QGVAR(Athena_O_T_Recon_M_F),
            QGVAR(Athena_O_T_Recon_TL_F),
            QGVAR(Athena_O_T_Recon_exp_F),
            QGVAR(Athena_O_T_Recon_medic_F),
            QGVAR(Athena_O_T_Sniper_F),
            QGVAR(Athena_O_T_Soldier_AAA_F),
            QGVAR(Athena_O_T_Soldier_AAR_F),
            QGVAR(Athena_O_T_Soldier_AAT_F),
            QGVAR(Athena_O_T_Soldier_AA_F),
            QGVAR(Athena_O_T_Soldier_AR_F),
            QGVAR(Athena_O_T_Soldier_AT_F),
            QGVAR(Athena_O_T_Soldier_A_F),
            QGVAR(Athena_O_T_Soldier_Exp_F),
            QGVAR(Athena_O_T_Soldier_F),
            QGVAR(Athena_O_T_Soldier_GL_F),
            QGVAR(Athena_O_T_Soldier_LAT_F),
            QGVAR(Athena_O_T_Soldier_SL_F),
            QGVAR(Athena_O_T_Soldier_TL_F),
            QGVAR(Athena_O_T_Soldier_unarmed_F),
            QGVAR(Athena_O_T_Static_AA_F),
            QGVAR(Athena_O_T_Static_AT_F),
            QGVAR(Athena_O_T_UAV_02_dynamicLoadout_F),
            QGVAR(Athena_O_T_UGV_01_F),
            QGVAR(Athena_O_T_UGV_01_medical_F),
            QGVAR(Athena_O_T_UGV_01_rcws_F),
            QGVAR(Athena_O_T_recon_GL_F),
            QGVAR(Athena_O_T_recon_JTAC_F),
            QGVAR(Athena_O_T_soldier_M_F),
            QGVAR(B_APC_Wheeled_02_unarmed_lxWS),
            QGVAR(B_GEN_APC_Wheeled_02_hmg_lxWS),
            QGVAR(B_MRAP_01_F),
            QGVAR(B_MRAP_01_gmg_F),
            QGVAR(B_MRAP_01_hmg_F),
            QGVAR(B_Truck_01_Repair_F),
            QGVAR(B_Truck_01_ammo_F),
            QGVAR(B_Truck_01_box_F),
            QGVAR(B_Truck_01_cargo_F),
            QGVAR(B_Truck_01_covered_F),
            QGVAR(B_Truck_01_flatbed_F),
            QGVAR(B_Truck_01_fuel_F),
            QGVAR(B_Truck_01_medical_F),
            QGVAR(B_Truck_01_mover_F),
            QGVAR(B_Truck_01_transport_F),
            QGVAR(EF_O_Gyra_Antiair_OPF),
            QGVAR(EF_O_Gyra_Armed_OPF),
            QGVAR(EF_O_Gyra_HMG_OPF),
            QGVAR(EF_O_Gyra_OPF),
            QGVAR(O_Quadbike_ALIVE),
            QGVAR(O_SDV_01_F),
            QGVAR(O_T_APC_Wheeled_02_rcws_ghex_F),
            QGVAR(O_T_APC_Wheeled_02_rcws_v2_ghex_F),
            QGVAR(O_T_Boat_Armed_01_hmg_F),
            QGVAR(O_T_Boat_Transport_01_F),
            QGVAR(O_T_Diver_Exp_F),
            QGVAR(O_T_Diver_F),
            QGVAR(O_T_Diver_TL_F),
            QGVAR(O_T_Engineer_F),
            QGVAR(O_T_Medic_F),
            QGVAR(O_T_Officer_F),
            QGVAR(O_T_Pathfinder_F),
            QGVAR(O_T_RadioOperator_F),
            QGVAR(O_T_Recon_Exp_F),
            QGVAR(O_T_Recon_F),
            QGVAR(O_T_Recon_JTAC_F),
            QGVAR(O_T_Recon_LAT_F),
            QGVAR(O_T_Recon_M_F),
            QGVAR(O_T_Recon_Medic_F),
            QGVAR(O_T_Recon_TL_F),
            QGVAR(O_T_Sniper_F),
            QGVAR(O_T_Soldier_AAA_F),
            QGVAR(O_T_Soldier_AAR_F),
            QGVAR(O_T_Soldier_AAT_F),
            QGVAR(O_T_Soldier_AA_F),
            QGVAR(O_T_Soldier_AHAT_F),
            QGVAR(O_T_Soldier_AR_F),
            QGVAR(O_T_Soldier_AT_F),
            QGVAR(O_T_Soldier_A_F),
            QGVAR(O_T_Soldier_Exp_F),
            QGVAR(O_T_Soldier_F),
            QGVAR(O_T_Soldier_GL_F),
            QGVAR(O_T_Soldier_HAT_F),
            QGVAR(O_T_Soldier_LAT_F),
            QGVAR(O_T_Soldier_M_F),
            QGVAR(O_T_Soldier_Repair_F),
            QGVAR(O_T_Soldier_SL_F),
            QGVAR(O_T_Soldier_TL_F),
            QGVAR(O_T_Spotter_F),
            QGVAR(O_T_Support_AMG_F),
            QGVAR(O_T_Support_AMort_F),
            QGVAR(O_T_Support_GMG_F),
            QGVAR(O_T_Support_MG_F),
            QGVAR(O_T_Support_Mort_F),
            QGVAR(O_T_VTOL_02_infantry_ghex_F),
            QGVAR(ghost_antiship_launcher),
            QGVAR(ghost_antiship_radar),
            QGVAR(Drone_Operator)
        };
        weapons[] = {QGVAR(LMG_03_Arco_Pointer_F_snds),QGVAR(SMG_02_F_snds),QGVAR(arifle_SCAR_L_F_snds),QGVAR(arifle_SCAR_L_GL_F_snds),QGVAR(arifle_SCAR_L_grip_F_snds),QGVAR(arifle_SCAR_L_short_F_snds),QGVAR(hgun_P07_blk_F_snds),QGVAR(hgun_Rook40_F_snds),QGVAR(srifle_DMR_07_blk_DMS_F_snds)};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main", "ghost_vehicle", "ghost_weapons"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
