#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_China_ard_ACE_O_T_SpottingScope",
            "ghost_China_ard_Aegis_O_C_D_Crew_F",
            "ghost_China_ard_Aegis_O_C_D_Engineer_F",
            "ghost_China_ard_Aegis_O_C_D_Fighter_Pilot_F",
            "ghost_China_ard_Aegis_O_C_D_HeavyGunner_F",
            "ghost_China_ard_Aegis_O_C_D_Helicrew_F",
            "ghost_China_ard_Aegis_O_C_D_Helipilot_F",
            "ghost_China_ard_Aegis_O_C_D_Medic_F",
            "ghost_China_ard_Aegis_O_C_D_Officer_F",
            "ghost_China_ard_Aegis_O_C_D_Pathfinder_F",
            "ghost_China_ard_Aegis_O_C_D_Pilot_F",
            "ghost_China_ard_Aegis_O_C_D_RadioOperator_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_AR_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_CQ_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_Exp_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_GL_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_JTAC_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_LAT_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_M_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_Medic_F",
            "ghost_China_ard_Aegis_O_C_D_Recon_TL_F",
            "ghost_China_ard_Aegis_O_C_D_Sharpshooter_F",
            "ghost_China_ard_Aegis_O_C_D_Sniper_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AAA_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AAR_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AAT_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AA_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AHAT_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AR_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_AT_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_A_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_CBRN_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_CQ_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_Exp_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_GL_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_HAT_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_LAT_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_Lite_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_M_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_PG_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_Repair_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_SL_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_TL_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_UAV_06_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_UAV_06_medical_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_UAV_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_UGV_02_Demining_F",
            "ghost_China_ard_Aegis_O_C_D_Soldier_unarmed_F",
            "ghost_China_ard_Aegis_O_C_D_Spotter_F",
            "ghost_China_ard_Aegis_O_C_D_Support_AMG_F",
            "ghost_China_ard_Aegis_O_C_D_Support_AMort_F",
            "ghost_China_ard_Aegis_O_C_D_Support_GMG_F",
            "ghost_China_ard_Aegis_O_C_D_Support_MG_F",
            "ghost_China_ard_Aegis_O_C_D_Support_Mort_F",
            "ghost_China_ard_Aegis_O_T_BoatCrew_EF",
            "ghost_China_ard_Aegis_O_T_UAV_02_lxWS",
            "ghost_China_ard_EF_O_CombatBoat_AT_OPF_T",
            "ghost_China_ard_EF_O_CombatBoat_HMG_OPF_T",
            "ghost_China_ard_EF_O_CombatBoat_Unarmed_OPF_T",
            "ghost_China_ard_EF_O_Gyra_Antiair_OPF_T",
            "ghost_China_ard_EF_O_Gyra_Armed_OPF_T",
            "ghost_China_ard_EF_O_Gyra_HMG_OPF_T",
            "ghost_China_ard_EF_O_Gyra_Mortar_OPF_T",
            "ghost_China_ard_EF_O_Gyra_OPF_T",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_ammo_F",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_bench_F",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_box_F",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_covered_F",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_fuel_F",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_medevac_F",
            "ghost_China_ard_Land_Pod_Heli_Transport_04_repair_F",
            "ghost_China_ard_O_APC_Tracked_02_30mm_lxWS",
            "ghost_China_ard_O_APC_Tracked_02_AA_F",
            "ghost_China_ard_O_APC_Tracked_02_cannon_F",
            "ghost_China_ard_O_APC_Wheeled_02_hmg_lxWS",
            "ghost_China_ard_O_APC_Wheeled_02_rcws_F",
            "ghost_China_ard_O_APC_Wheeled_02_rcws_v2_F",
            "ghost_China_ard_O_APC_Wheeled_02_unarmed_lxWS",
            "ghost_China_ard_O_Boat_Armed_01_hmg_F",
            "ghost_China_ard_O_Boat_Transport_01_F",
            "ghost_China_ard_O_GMG_01_A_F",
            "ghost_China_ard_O_GMG_01_F",
            "ghost_China_ard_O_GMG_01_high_F",
            "ghost_China_ard_O_HMG_01_A_F",
            "ghost_China_ard_O_HMG_01_F",
            "ghost_China_ard_O_HMG_01_high_F",
            "ghost_China_ard_O_Heli_Attack_02_F",
            "ghost_China_ard_O_Heli_Attack_02_dynamicLoadout_F",
            "ghost_China_ard_O_Heli_Light_02_dynamicLoadout_F",
            "ghost_China_ard_O_Heli_Light_02_unarmed_F",
            "ghost_China_ard_O_Heli_Transport_04_F",
            "ghost_China_ard_O_Heli_Transport_04_ammo_F",
            "ghost_China_ard_O_Heli_Transport_04_bench_F",
            "ghost_China_ard_O_Heli_Transport_04_box_F",
            "ghost_China_ard_O_Heli_Transport_04_covered_F",
            "ghost_China_ard_O_Heli_Transport_04_fuel_F",
            "ghost_China_ard_O_Heli_Transport_04_medevac_F",
            "ghost_China_ard_O_Heli_Transport_04_repair_F",
            "ghost_China_ard_O_LSV_02_AT_F",
            "ghost_China_ard_O_LSV_02_armed_F",
            "ghost_China_ard_O_LSV_02_unarmed_F",
            "ghost_China_ard_O_Lifeboat",
            "ghost_China_ard_O_MBT_02_arty_F",
            "ghost_China_ard_O_MBT_02_cannon_F",
            "ghost_China_ard_O_MBT_02_railgun_F",
            "ghost_China_ard_O_MBT_04_cannon_F",
            "ghost_China_ard_O_MBT_04_command_F",
            "ghost_China_ard_O_MRAP_02_F",
            "ghost_China_ard_O_MRAP_02_gmg_F",
            "ghost_China_ard_O_MRAP_02_hmg_F",
            "ghost_China_ard_O_Mortar_01_F",
            "ghost_China_ard_O_Pickup_Comms_rf",
            "ghost_China_ard_O_Pickup_rcws_rf",
            "ghost_China_ard_O_Pickup_rf",
            "ghost_China_ard_O_Plane_CAS_02_dynamicLoadout_F",
            "ghost_China_ard_O_Plane_Fighter_02_F",
            "ghost_China_ard_O_Plane_Fighter_02_Stealth_F",
            "ghost_China_ard_O_Quadbike_01_F",
            "ghost_China_ard_O_Quadbike_ALIVE",
            "ghost_China_ard_O_Radar_System_02_F",
            "ghost_China_ard_O_SAM_System_04_F",
            "ghost_China_ard_O_SDV_01_F",
            "ghost_China_ard_O_Static_Designator_02_F",
            "ghost_China_ard_O_T_Diver_Exp_F",
            "ghost_China_ard_O_T_Diver_F",
            "ghost_China_ard_O_T_Diver_TL_F",
            "ghost_China_ard_O_T_Soldier_UAV_02_lxWS_F",
            "ghost_China_ard_O_T_Survivor_F",
            "ghost_China_ard_O_T_Truck_02_F",
            "ghost_China_ard_O_T_UAV_04_CAS_F",
            "ghost_China_ard_O_T_VTOL_02_infantry_ghex_F",
            "ghost_China_ard_O_T_ghillie_spotter_tna_F",
            "ghost_China_ard_O_T_ghillie_tna_F",
            "ghost_China_ard_O_T_soldier_mine_F",
            "ghost_China_ard_O_Truck_02_Ammo_F",
            "ghost_China_ard_O_Truck_02_MRL_F",
            "ghost_China_ard_O_Truck_02_box_F",
            "ghost_China_ard_O_Truck_02_cargo_lxWS",
            "ghost_China_ard_O_Truck_02_flatbed_lxWS",
            "ghost_China_ard_O_Truck_02_fuel_F",
            "ghost_China_ard_O_Truck_02_medical_F",
            "ghost_China_ard_O_Truck_02_transport_F",
            "ghost_China_ard_O_Truck_03_ammo_F",
            "ghost_China_ard_O_Truck_03_cargo_RF",
            "ghost_China_ard_O_Truck_03_covered_F",
            "ghost_China_ard_O_Truck_03_device_F",
            "ghost_China_ard_O_Truck_03_fuel_F",
            "ghost_China_ard_O_Truck_03_medical_F",
            "ghost_China_ard_O_Truck_03_repair_F",
            "ghost_China_ard_O_Truck_03_transport_F",
            "ghost_China_ard_O_UAV_01_F",
            "ghost_China_ard_O_UAV_06_F",
            "ghost_China_ard_O_UAV_06_medical_F",
            "ghost_China_ard_O_UGV_01_F",
            "ghost_China_ard_O_UGV_01_rcws_F",
            "ghost_China_ard_O_UGV_02_Demining_F",
            "ghost_China_ard_O_VTOL_02_infantry_dynamicLoadout_F",
            "ghost_China_ard_O_VTOL_02_vehicle_dynamicLoadout_F",
            "ghost_China_ard_O_static_AA_F",
            "ghost_China_ard_O_static_AT_F",
            "ghost_China_ard_ghost_antiship_launcher",
            "ghost_China_ard_ghost_antiship_radar",
            "ghost_China_ard_qav_o_t_625e",
            "ghost_China_ard_qav_o_t_ztl11",
            "ghost_China_ard_rksla3_aeroshark_opfor",
            "ghost_China_ard_rksla3_uav_h450_2",
            "ghost_China_ard_O_UAV_01_backpack_F",
            "ghost_China_ard_O_UAV_06_backpack_F",
            "ghost_China_ard_O_UAV_03_dynamicLoadout_F",
            "ghost_China_ard_O_SwitchBlade_300",
            "ghost_China_ard_O_SwitchBlade_600",
            "ghost_China_ard_O_SwitchBlade_300_LaunchTube",
            "ghost_China_ard_O_SwitchBlade_600_LaunchTube",
            "ghost_China_ard_SwitchBlade_Operator",
            "ghost_China_ard_rksla3_uav_gdt_sa_o",
            "ghost_China_ard_rksla3_uav_wkshelter_sa_o",
            "ghost_China_ard_O_Rapier_FSC_Launcher",
            "ghost_China_ard_O_Rapier_FSC_Blindfire",
            "ghost_China_ard_O_Rapier_FSC_Dagger",
            "ghost_China_ard_Drone_Operator"
        };
        weapons[] = {"ghost_China_ard_Aegis_arifle_CTARS_tan_ARCO_Pointer_F_snds","ghost_China_ard_Aegis_arifle_CTAR_GL_tan_ARCO_Pointer_F_snds","ghost_China_ard_Aegis_arifle_CTAR_tan_ARCO_Pointer_F_snds","ghost_China_ard_Aegis_sgun_AA40_tan_ACO_LP_LxWS_snds","ghost_China_ard_LMG_03_Arco_Pointer_F_snds","ghost_China_ard_SMG_02_ACO_F_snds","ghost_China_ard_hgun_Rook40_F_snds","ghost_China_ard_srifle_DMR_05_KHS_LP_F_snds","ghost_China_ard_srifle_DMR_07_blk_DMS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
