// Generated by tools/gen_aceax.py -- do not edit by hand.
class ef_snds_diplomat
{
    model = "mxa_arsenal_diplomat_sound_suppressor_9_mm";
    camo = "STD";
};
class ef_snds_diplomat_coy
{
    model = "mxa_arsenal_diplomat_sound_suppressor_9_mm";
    camo = "CBR";
};
