// Generated by tools/gen_aceax.py -- do not edit by hand.
class optic_r1_high_arid_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "ARID";
};
class optic_r1_high_black_sand_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "BLKSND";
};
class optic_r1_high_khaki_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "KHK";
};
class optic_r1_high_lush_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "LUSH";
};
class optic_r1_high_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "BLK";
};
class optic_r1_high_sand_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "SND";
};
class optic_r1_high_snake_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "HIGH";
    camo = "SNAKE";
};
class optic_r1_low_arid_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "LOW";
    camo = "ARID";
};
class optic_r1_low_khaki_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "LOW";
    camo = "KHK";
};
class optic_r1_low_lush_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "LOW";
    camo = "LUSH";
};
class optic_r1_low_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "LOW";
    camo = "BLK";
};
class optic_r1_low_sand_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "LOW";
    camo = "SND";
};
class optic_r1_low_snake_lxWS
{
    model = "mxa_arsenal_aimpoint_micro_r_1";
    mount = "LOW";
    camo = "SNAKE";
};
