// Generated by tools/gen_aceax.py -- do not edit by hand.
class JCA_optic_ICO_black
{
    model = "mxa_arsenal_ico";
    camo = "BLK";
};
class JCA_optic_ICO_olive
{
    model = "mxa_arsenal_ico";
    camo = "OLI";
};
class JCA_optic_ICO_sand
{
    model = "mxa_arsenal_ico";
    camo = "SND";
};
