// Generated by tools/gen_aceax.py -- do not edit by hand.
class JCA_optic_ARS_black
{
    model = "mxa_arsenal_ars";
    camo = "BLK";
};
class JCA_optic_ARS_olive
{
    model = "mxa_arsenal_ars";
    camo = "OLI";
};
class JCA_optic_ARS_sand
{
    model = "mxa_arsenal_ars";
    camo = "SND";
};
