// Generated by tools/gen_aceax.py -- do not edit by hand.
class acc_pointer_IR_arid_lxWS
{
    model = "mxa_arsenal_ir_laser_pointer";
    camo = "ARID";
};
class acc_pointer_IR_lush_lxWS
{
    model = "mxa_arsenal_ir_laser_pointer";
    camo = "LUSH";
};
class acc_pointer_IR_sand_lxWS
{
    model = "mxa_arsenal_ir_laser_pointer";
    camo = "SND";
};
class acc_pointer_IR_snake_lxWS
{
    model = "mxa_arsenal_ir_laser_pointer";
    camo = "SNAKE";
};
class EF_acc_pointer_IR_coy
{
    model = "mxa_arsenal_ir_laser_pointer";
    camo = "CBR";
};
