// Generated by tools/gen_aceax.py -- do not edit by hand.
class bipod_01_F_blk
{
    model = "mxa_arsenal_bipod_nato";
    camo = "BLK";
};
class bipod_01_F_khk
{
    model = "mxa_arsenal_bipod_nato";
    camo = "KHK";
};
class bipod_01_F_mtp
{
    model = "mxa_arsenal_bipod_nato";
    camo = "MTP";
};
class bipod_01_F_snd
{
    model = "mxa_arsenal_bipod_nato";
    camo = "SND";
};
