#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_Iran_ACE_O_SpottingScope",
            "ghost_Iran_Aegis_O_BoatCrew_EF",
            "ghost_Iran_EF_O_CombatBoat_AT_OPF",
            "ghost_Iran_EF_O_CombatBoat_HMG_OPF",
            "ghost_Iran_EF_O_CombatBoat_Unarmed_OPF",
            "ghost_Iran_EF_O_Gyra_Antiair_OPF",
            "ghost_Iran_EF_O_Gyra_Armed_OPF",
            "ghost_Iran_EF_O_Gyra_HMG_OPF",
            "ghost_Iran_EF_O_Gyra_Mortar_OPF",
            "ghost_Iran_EF_O_Gyra_OPF",
            "ghost_Iran_JK_O_76n6_ClamShell_F",
            "ghost_Iran_JK_O_76n6_ClamShell_Lower_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_ammo_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_bench_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_box_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_covered_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_fuel_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_medevac_F",
            "ghost_Iran_Land_Pod_Heli_Transport_04_repair_F",
            "ghost_Iran_O_AAA_System_01_F",
            "ghost_Iran_O_APC_Tracked_02_30mm_lxWS",
            "ghost_Iran_O_APC_Tracked_02_AA_F",
            "ghost_Iran_O_APC_Tracked_02_cannon_F",
            "ghost_Iran_O_APC_Wheeled_02_hmg_lxWS",
            "ghost_Iran_O_APC_Wheeled_02_rcws_F",
            "ghost_Iran_O_APC_Wheeled_02_rcws_v2_F",
            "ghost_Iran_O_APC_Wheeled_02_unarmed_lxWS",
            "ghost_Iran_O_Boat_Armed_01_hmg_F",
            "ghost_Iran_O_Boat_Transport_01_F",
            "ghost_Iran_O_CommandoMortar_RF",
            "ghost_Iran_O_Fighter_Pilot_F",
            "ghost_Iran_O_GMG_01_A_F",
            "ghost_Iran_O_GMG_01_F",
            "ghost_Iran_O_GMG_01_high_F",
            "ghost_Iran_O_HMG_01_A_F",
            "ghost_Iran_O_HMG_01_F",
            "ghost_Iran_O_HMG_01_high_F",
            "ghost_Iran_O_HMG_02_F",
            "ghost_Iran_O_HMG_02_high_F",
            "ghost_Iran_O_HeavyGunner_F",
            "ghost_Iran_O_Heli_Attack_02_F",
            "ghost_Iran_O_Heli_Attack_02_dynamicLoadout_F",
            "ghost_Iran_O_Heli_Light_02_dynamicLoadout_F",
            "ghost_Iran_O_Heli_Light_02_unarmed_F",
            "ghost_Iran_O_Heli_Transport_04_F",
            "ghost_Iran_O_Heli_Transport_04_ammo_F",
            "ghost_Iran_O_Heli_Transport_04_bench_F",
            "ghost_Iran_O_Heli_Transport_04_box_F",
            "ghost_Iran_O_Heli_Transport_04_covered_F",
            "ghost_Iran_O_Heli_Transport_04_fuel_F",
            "ghost_Iran_O_Heli_Transport_04_medevac_F",
            "ghost_Iran_O_Heli_Transport_04_repair_F",
            "ghost_Iran_O_LSV_02_AT_F",
            "ghost_Iran_O_LSV_02_armed_F",
            "ghost_Iran_O_LSV_02_unarmed_F",
            "ghost_Iran_O_Lifeboat",
            "ghost_Iran_O_MBT_02_arty_F",
            "ghost_Iran_O_MBT_02_cannon_F",
            "ghost_Iran_O_MBT_02_railgun_F",
            "ghost_Iran_O_MBT_04_cannon_F",
            "ghost_Iran_O_MBT_04_command_F",
            "ghost_Iran_O_MRAP_02_F",
            "ghost_Iran_O_MRAP_02_gmg_F",
            "ghost_Iran_O_MRAP_02_hmg_F",
            "ghost_Iran_O_Mortar_01_F",
            "ghost_Iran_O_Officer_Parade_F",
            "ghost_Iran_O_Officer_Parade_Veteran_F",
            "ghost_Iran_O_Pathfinder_F",
            "ghost_Iran_O_Pickup_Comms_rf",
            "ghost_Iran_O_Pickup_rcws_rf",
            "ghost_Iran_O_Pickup_rf",
            "ghost_Iran_O_Pilot_F",
            "ghost_Iran_O_Plane_CAS_02_dynamicLoadout_F",
            "ghost_Iran_O_Plane_Fighter_02_F",
            "ghost_Iran_O_Plane_Fighter_02_Stealth_F",
            "ghost_Iran_O_QRF_Soldier_UAV_RF",
            "ghost_Iran_O_Quadbike_01_F",
            "ghost_Iran_O_Quadbike_ALIVE",
            "ghost_Iran_O_Radar_System_02_F",
            "ghost_Iran_O_RadioOperator_F",
            "ghost_Iran_O_SAM_System_01_F",
            "ghost_Iran_O_SAM_System_02_F",
            "ghost_Iran_O_SAM_System_04_F",
            "ghost_Iran_O_SDV_01_F",
            "ghost_Iran_O_Sharpshooter_F",
            "ghost_Iran_O_Soldier_AAA_F",
            "ghost_Iran_O_Soldier_AAR_F",
            "ghost_Iran_O_Soldier_AAT_F",
            "ghost_Iran_O_Soldier_AA_F",
            "ghost_Iran_O_Soldier_AHAT_F",
            "ghost_Iran_O_Soldier_AR_F",
            "ghost_Iran_O_Soldier_AT_F",
            "ghost_Iran_O_Soldier_A_F",
            "ghost_Iran_O_Soldier_CBRN_F",
            "ghost_Iran_O_Soldier_CQ_F",
            "ghost_Iran_O_Soldier_GL_F",
            "ghost_Iran_O_Soldier_HAT_F",
            "ghost_Iran_O_Soldier_LAT_F",
            "ghost_Iran_O_Soldier_SL_F",
            "ghost_Iran_O_Soldier_TL_F",
            "ghost_Iran_O_Soldier_lite_F",
            "ghost_Iran_O_Soldier_unarmed_F",
            "ghost_Iran_O_Static_Designator_02_F",
            "ghost_Iran_O_Survivor_F",
            "ghost_Iran_O_Truck_02_Ammo_F",
            "ghost_Iran_O_Truck_02_MRL_F",
            "ghost_Iran_O_Truck_02_box_F",
            "ghost_Iran_O_Truck_02_cargo_lxWS",
            "ghost_Iran_O_Truck_02_covered_F",
            "ghost_Iran_O_Truck_02_flatbed_lxWS",
            "ghost_Iran_O_Truck_02_fuel_F",
            "ghost_Iran_O_Truck_02_medical_F",
            "ghost_Iran_O_Truck_02_transport_F",
            "ghost_Iran_O_Truck_03_ammo_F",
            "ghost_Iran_O_Truck_03_cargo_RF",
            "ghost_Iran_O_Truck_03_covered_F",
            "ghost_Iran_O_Truck_03_device_F",
            "ghost_Iran_O_Truck_03_fuel_F",
            "ghost_Iran_O_Truck_03_medical_F",
            "ghost_Iran_O_Truck_03_repair_F",
            "ghost_Iran_O_Truck_03_transport_F",
            "ghost_Iran_O_UAV_01_F",
            "ghost_Iran_O_UAV_02_dynamicLoadout_F",
            "ghost_Iran_O_UAV_02_lxWS",
            "ghost_Iran_O_UAV_06_F",
            "ghost_Iran_O_UAV_06_medical_F",
            "ghost_Iran_O_UAV_RC40_HE_RF",
            "ghost_Iran_O_UAV_RC40_SENSOR_RF",
            "ghost_Iran_O_UAV_RC40_SmokeBlue_RF",
            "ghost_Iran_O_UAV_RC40_SmokeGreen_RF",
            "ghost_Iran_O_UAV_RC40_SmokeOrange_RF",
            "ghost_Iran_O_UAV_RC40_SmokeRed_RF",
            "ghost_Iran_O_UAV_RC40_SmokeWhite_RF",
            "ghost_Iran_O_UGV_01_F",
            "ghost_Iran_O_UGV_01_rcws_F",
            "ghost_Iran_O_UGV_02_Demining_F",
            "ghost_Iran_O_UGV_02_Science_F",
            "ghost_Iran_O_VTOL_02_infantry_dynamicLoadout_F",
            "ghost_Iran_O_VTOL_02_vehicle_dynamicLoadout_F",
            "ghost_Iran_O_crew_F",
            "ghost_Iran_O_diver_F",
            "ghost_Iran_O_diver_TL_F",
            "ghost_Iran_O_diver_exp_F",
            "ghost_Iran_O_engineer_F",
            "ghost_Iran_O_ghillie_ard_F",
            "ghost_Iran_O_ghillie_lsh_F",
            "ghost_Iran_O_ghillie_sard_F",
            "ghost_Iran_O_ghillie_spotter_ard_F",
            "ghost_Iran_O_ghillie_spotter_lsh_F",
            "ghost_Iran_O_ghillie_spotter_sard_F",
            "ghost_Iran_O_helicrew_F",
            "ghost_Iran_O_helipilot_F",
            "ghost_Iran_O_medic_F",
            "ghost_Iran_O_officer_F",
            "ghost_Iran_O_recon_AR_F",
            "ghost_Iran_O_recon_CQ_F",
            "ghost_Iran_O_recon_F",
            "ghost_Iran_O_recon_GL_F",
            "ghost_Iran_O_recon_JTAC_F",
            "ghost_Iran_O_recon_LAT_F",
            "ghost_Iran_O_recon_M_F",
            "ghost_Iran_O_recon_TL_F",
            "ghost_Iran_O_recon_exp_F",
            "ghost_Iran_O_recon_medic_F",
            "ghost_Iran_O_sniper_F",
            "ghost_Iran_O_soldier_F",
            "ghost_Iran_O_soldier_M_F",
            "ghost_Iran_O_soldier_PG_F",
            "ghost_Iran_O_soldier_UAV_06_F",
            "ghost_Iran_O_soldier_UAV_06_medical_F",
            "ghost_Iran_O_soldier_UAV_F",
            "ghost_Iran_O_soldier_UAV_lxWS",
            "ghost_Iran_O_soldier_UGV_02_Demining_F",
            "ghost_Iran_O_soldier_exp_F",
            "ghost_Iran_O_soldier_mine_F",
            "ghost_Iran_O_soldier_repair_F",
            "ghost_Iran_O_spotter_F",
            "ghost_Iran_O_static_AA_F",
            "ghost_Iran_O_static_AT_F",
            "ghost_Iran_O_support_AMG_F",
            "ghost_Iran_O_support_AMort_F",
            "ghost_Iran_O_support_CMort_RF",
            "ghost_Iran_O_support_GMG_F",
            "ghost_Iran_O_support_MG_F",
            "ghost_Iran_O_support_Mort_F",
            "ghost_Iran_ghost_antiship_launcher",
            "ghost_Iran_ghost_antiship_radar",
            "ghost_Iran_rksla3_uav_h450_2",
            "ghost_Iran_O_UAV_01_backpack_F",
            "ghost_Iran_O_UAV_06_backpack_F",
            "ghost_Iran_O_UAV_03_dynamicLoadout_F",
            "ghost_Iran_O_SwitchBlade_300",
            "ghost_Iran_O_SwitchBlade_600",
            "ghost_Iran_O_SwitchBlade_300_LaunchTube",
            "ghost_Iran_O_SwitchBlade_600_LaunchTube",
            "ghost_Iran_SwitchBlade_Operator",
            "ghost_Iran_rksla3_aeroshark_opfor",
            "ghost_Iran_rksla3_uav_gdt_sa_o",
            "ghost_Iran_rksla3_uav_wkshelter_sa_o",
            "ghost_Iran_O_Rapier_FSC_Launcher",
            "ghost_Iran_O_Rapier_FSC_Blindfire",
            "ghost_Iran_O_Rapier_FSC_Dagger",
            "ghost_Iran_Drone_Operator"
        };
        weapons[] = {"ghost_Iran_Aegis_sgun_AA40_ACO_LP_LxWS_snds","ghost_Iran_Aegis_srifle_SVD_f_snds","ghost_Iran_Rev_arifle_AK103_GL_ARCO_AK_FL_F_snds","ghost_Iran_SMG_02_ACO_F_snds","ghost_Iran_arifle_RPK12_arco_pointer_F_snds","ghost_Iran_arifle_AK103_arco"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
