// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
//
// EVERY UNIT IS THIS FACTION'S OWN: each vehicle below is the GVAR class in CfgVehicles.hpp.

class CfgGroups {
    class East {

        class ADDON {
            name = "2040 China";

            class Infantry {
                name = "Infantry";

                class GVAR(O_T_InfHQ) {
                    name = "Infantry HQ";
                    side = 0;
                    faction = QUOTE(ADDON);
                    rarityGroup = 0.1;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_SL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,5,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {3,0,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Medic_F);
                        rank = "CORPORAL";
                        position[] = {5,0,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_Repair_F);
                        rank = "PRIVATE";
                        position[] = {7,0,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {9,0,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };
                };

                class GVAR(O_T_InfSentry) {
                    name = "Sentry";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_GL_F);
                        rank = "CORPORAL";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };
                };

                class GVAR(O_T_InfSniper) {
                    name = "Sniper Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    rarityGroup = 0.05;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Sniper_F);
                        rank = "LIEUTENANT";
                        position[] = {0,5,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Spotter_F);
                        rank = "SERGEANT";
                        position[] = {3,0,0};
                    };
                };

                class GVAR(O_T_InfSquad) {
                    name = "Rifle Squad";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_RadioOperator_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_LAT_F);
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "CORPORAL";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_A_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 0;
                        vehicle = QGVAR(O_T_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {25,-25,0};
                    };
                };

                class GVAR(O_T_InfSquad_Weapons) {
                    name = "Weapons Squad";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_GL_F);
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_M_F);
                        rank = "SERGEANT";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AT_F);
                        rank = "CORPORAL";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AAT_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_A_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 0;
                        vehicle = QGVAR(O_T_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {25,-25,0};
                    };
                };

                class GVAR(O_T_InfSupTeam) {
                    name = "Support Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    rarityGroup = 0.3;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,5,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_LAT_F);
                        rank = "CORPORAL";
                        position[] = {3,0,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Medic_F);
                        rank = "PRIVATE";
                        position[] = {5,0,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {7,0,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(O_T_InfTeam) {
                    name = "Fire Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_LAT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(O_T_InfTeam_AA) {
                    name = "Air-defense Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AA_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AA_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AAA_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(O_T_InfTeam_AT) {
                    name = "Anti-armor Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.1;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AT_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AAT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(O_T_InfTeam_AT_Heavy) {
                    name = "Anti-Armor Team (Heavy)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_HAT_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_HAT_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AHAT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(O_T_InfWepTeam) {
                    name = "Weapons Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    rarityGroup = 0.3;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,5,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "CORPORAL";
                        position[] = {3,0,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_LAT_F);
                        rank = "PRIVATE";
                        position[] = {5,0,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {7,0,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };


                class GVAR(Atlas_O_T_InfSentry_M) {
                    name = "Marine Sentry";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_GL_F);
                        rank = "CORPORAL";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };
                };

                class GVAR(Atlas_O_T_InfSquad_M) {
                    name = "Marine Rifle Squad";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_RadioOperator_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_LAT_F);
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "CORPORAL";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_A_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 0;
                        vehicle = QGVAR(O_T_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {25,-25,0};
                    };
                };

                class GVAR(Atlas_O_T_InfSquad_Weapons_M) {
                    name = "Marine Weapons Squad";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_GL_F);
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_A_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 0;
                        vehicle = QGVAR(O_T_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {25,-25,0};
                    };
                };

                class GVAR(Atlas_O_T_InfTeam_AA_M) {
                    name = "Marine Air-defense Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AA_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AA_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(Atlas_O_T_InfTeam_AT_M) {
                    name = "Marine Anti-armor Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AT_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

                class GVAR(Atlas_O_T_InfTeam_M) {
                    name = "Marine Fire Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_AR_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Soldier_LAT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Drone_Operator);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(SwitchBlade_Operator);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class GVAR(O_T_ReconSquad) {
                    name = "Recon Squad";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_M_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_LAT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_JTAC_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_Exp_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 0;
                        vehicle = QGVAR(O_T_Pathfinder_F);
                        rank = "CORPORAL";
                        position[] = {20,-20,0};
                    };
                };

                class GVAR(O_T_SniperTeam) {
                    name = "Sniper Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Spotter_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Sniper_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };
                };

                class GVAR(O_T_diverTeam) {
                    name = "Diver Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Diver_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Diver_Exp_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Diver_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Diver_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class GVAR(O_T_reconPatrol) {
                    name = "Recon Patrol";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_M_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class GVAR(O_T_reconSentry) {
                    name = "Recon Sentry";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_M_F);
                        rank = "CORPORAL";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_F);
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };
                };

                class GVAR(O_T_reconTeam) {
                    name = "Recon Team";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_M_F);
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_LAT_F);
                        rank = "CORPORAL";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_JTAC_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_Exp_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized";

                class GVAR(Mot_CSK181) {
                    name = "Motorized Team (CSK182)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_motor_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(CSK181);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(MotSquad_SX2316) {
                    name = "Motorized Squad (SX2316)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_motor_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(SX2316);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(MotSquad_SX2220) {
                    name = "Motorized Squad (SX2220)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_motor_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(SX2220);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

            };

            class Mechanized {
                name = "Mechanized";

                class GVAR(Mech_O_ZBD04A) {
                    name = "Mechanized Squad (ZBD04A)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_mech_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZBD04A);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mech_O_ZBD05) {
                    name = "Mechanized Squad (ZBD05)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_mech_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZBD05);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mech_O_ZBL09) {
                    name = "Mechanized Squad (ZBL09)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_mech_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZBL09);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mech_O_ZTL11) {
                    name = "Mechanized Squad (ZTL11)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_mech_inf.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTL11);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_T_Recon_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 0;
                        vehicle = QGVAR(Aegis_O_T_BoatCrew_EF);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

            };

            class Armored {
                name = "Armored";

                class GVAR(TankPlatoon_O_ZTD05) {
                    name = "Tank Platoon (ZTD05)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTD05);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTD05);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTD05);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTD05);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTD05) {
                    name = "Tank Section (ZTD05)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTD05);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTD05);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(TankPlatoon_O_ZTQ15) {
                    name = "Tank Platoon (ZTQ15)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTQ15) {
                    name = "Tank Section (ZTQ15)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(TankPlatoon_O_ZTQ15B) {
                    name = "Tank Platoon (ZTQ15 HEAVY)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15B);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15B);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15B);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15B);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTQ15B) {
                    name = "Tank Section (ZTQ15 HEAVY)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15B);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTQ15B);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(TankPlatoon_O_ZTZ99) {
                    name = "Tank Platoon (ZTZ99)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTZ99) {
                    name = "Tank Section (ZTZ99)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(TankPlatoon_O_ZTZ99A) {
                    name = "Tank Platoon (ZTZ99A)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99A);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99A);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99A);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99A);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTZ99A) {
                    name = "Tank Section (ZTZ99A)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99A);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ99A);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(TankPlatoon_O_ZTZ96A) {
                    name = "Tank Platoon (ZTZ96A)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96A);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96A);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96A);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96A);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTZ96A) {
                    name = "Tank Section (ZTZ96A)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96A);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96A);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(TankPlatoon_O_ZTZ96B) {
                    name = "Tank Platoon (ZTZ96B)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96B);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96B);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96B);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96B);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_O_ZTZ96B) {
                    name = "Tank Section (ZTZ96B)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96B);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_ZTZ96B);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(AASection_HQ6A) {
                    name = "Air Defence Section (HQ6A(LD2000))";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(HQ6A);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(HQ6A);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(AASection_O_PGZ09_AA) {
                    name = "Air Defence Section (PGZ09)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_PGZ09_AA);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_PGZ09_AA);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(AASection_O_PGZ09_TY90) {
                    name = "Air Defence Section (PGZ09-TY90)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_armor.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_PGZ09_TY90);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_PGZ09_TY90);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Battery_O_PLL09) {
                    name = "Artillery Battery (PLL09)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_art.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_PLL09);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_PLL09);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_PLL09);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                };

                class GVAR(Battery_O_PLZ05) {
                    name = "Artillery Battery (PLZ05)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_art.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(O_PLZ05);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(O_PLZ05);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 0;
                        vehicle = QGVAR(O_PLZ05);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                };

            };

            class Air {
                name = "Air";

                class GVAR(AttackPair_Z10) {
                    name = "Attack Helicopter Pair (Z10)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_air.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(Z10);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(Z10);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(AttackPair_Z19) {
                    name = "Attack Helicopter Pair (Z19)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_air.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(Z19);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(Z19);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Transport_Z11WA) {
                    name = "Transport Helicopter (Z11WA)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_air.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(Z11WA);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Transport_Z11WA_2) {
                    name = "Transport Helicopter (Z11WA(FFV))";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_air.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(Z11WA_2);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Transport_Z20) {
                    name = "Transport Helicopter (Z20)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_air.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(Z20);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Transport_Z8L) {
                    name = "Transport Helicopter (Z8L)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_air.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(Z8L);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Flight_PLAAF_Fighter_J10) {
                    name = "Flight (PLAAF Fighter J10)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_plane.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J10);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J10);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Flight_PLAAF_Fighter_J11) {
                    name = "Flight (PLAAF Fighter J11)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_plane.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J11);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J11);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Flight_PLAAF_Fighter_J15) {
                    name = "Flight (PLAAF Fighter J15)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_plane.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J15);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J15);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Flight_PLAAF_Fighter_J16) {
                    name = "Flight (PLAAF Fighter J16)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_plane.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J16);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J16);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Flight_PLAAF_Fighter_J20) {
                    name = "Flight (PLAAF Fighter J20)";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_plane.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J20);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 0;
                        vehicle = QGVAR(PLAAF_Fighter_J20);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

            };

            class Support {
                name = "Support";

                class GVAR(Support_SX2316_Flat) {
                    name = "SX2316 Flat";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_support.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(SX2316_Flat);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Support_SX2220_Flat) {
                    name = "SX2220 Flat";
                    side = 0;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\o_support.paa";

                    class Unit0 {
                        side = 0;
                        vehicle = QGVAR(SX2220_Flat);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

            };

        };
    };
};
