#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_China_ACE_O_T_SpottingScope",
            "ghost_China_Aegis_O_T_BoatCrew_EF",
            "ghost_China_Aegis_O_T_UAV_02_lxWS",
            "ghost_China_EF_O_CombatBoat_AT_OPF_T",
            "ghost_China_EF_O_CombatBoat_HMG_OPF_T",
            "ghost_China_EF_O_CombatBoat_Unarmed_OPF_T",
            "ghost_China_EF_O_Gyra_Antiair_OPF_T",
            "ghost_China_EF_O_Gyra_Armed_OPF_T",
            "ghost_China_EF_O_Gyra_HMG_OPF_T",
            "ghost_China_EF_O_Gyra_Mortar_OPF_T",
            "ghost_China_EF_O_Gyra_OPF_T",
            "ghost_China_Land_Pod_Heli_Transport_04_ammo_ghex_F",
            "ghost_China_Land_Pod_Heli_Transport_04_bench_ghex_F",
            "ghost_China_Land_Pod_Heli_Transport_04_box_ghex_F",
            "ghost_China_Land_Pod_Heli_Transport_04_covered_ghex_F",
            "ghost_China_Land_Pod_Heli_Transport_04_fuel_ghex_F",
            "ghost_China_Land_Pod_Heli_Transport_04_medevac_ghex_F",
            "ghost_China_Land_Pod_Heli_Transport_04_repair_ghex_F",
            "ghost_China_O_Heli_Attack_02_F",
            "ghost_China_O_Quadbike_ALIVE",
            "ghost_China_O_T_APC_Tracked_02_30mm_lxWS",
            "ghost_China_O_T_APC_Tracked_02_AA_ghex_F",
            "ghost_China_O_T_APC_Tracked_02_cannon_ghex_F",
            "ghost_China_O_T_APC_Wheeled_02_hmg_lxWS",
            "ghost_China_O_T_APC_Wheeled_02_rcws_ghex_F",
            "ghost_China_O_T_APC_Wheeled_02_rcws_v2_ghex_F",
            "ghost_China_O_T_APC_Wheeled_02_unarmed_lxWS",
            "ghost_China_O_T_Boat_Armed_01_hmg_F",
            "ghost_China_O_T_Boat_Transport_01_F",
            "ghost_China_O_T_Crew_F",
            "ghost_China_O_T_Diver_Exp_F",
            "ghost_China_O_T_Diver_F",
            "ghost_China_O_T_Diver_TL_F",
            "ghost_China_O_T_Engineer_F",
            "ghost_China_O_T_Fighter_Pilot_F",
            "ghost_China_O_T_GMG_01_A_F",
            "ghost_China_O_T_GMG_01_F",
            "ghost_China_O_T_GMG_01_high_F",
            "ghost_China_O_T_HMG_01_A_F",
            "ghost_China_O_T_HMG_01_F",
            "ghost_China_O_T_HMG_01_high_F",
            "ghost_China_O_T_HeavyGunner_F",
            "ghost_China_O_T_Heli_Attack_02_dynamicLoadout_F",
            "ghost_China_O_T_Heli_Light_02_dynamicLoadout_ghex_F",
            "ghost_China_O_T_Heli_Light_02_unarmed_F",
            "ghost_China_O_T_Heli_Transport_04_F",
            "ghost_China_O_T_Heli_Transport_04_ammo_F",
            "ghost_China_O_T_Heli_Transport_04_bench_F",
            "ghost_China_O_T_Heli_Transport_04_box_F",
            "ghost_China_O_T_Heli_Transport_04_covered_F",
            "ghost_China_O_T_Heli_Transport_04_fuel_F",
            "ghost_China_O_T_Heli_Transport_04_medevac_F",
            "ghost_China_O_T_Heli_Transport_04_repair_F",
            "ghost_China_O_T_Helicrew_F",
            "ghost_China_O_T_Helipilot_F",
            "ghost_China_O_T_LSV_02_AT_F",
            "ghost_China_O_T_LSV_02_armed_F",
            "ghost_China_O_T_LSV_02_unarmed_F",
            "ghost_China_O_T_Lifeboat",
            "ghost_China_O_T_MBT_02_arty_ghex_F",
            "ghost_China_O_T_MBT_02_cannon_ghex_F",
            "ghost_China_O_T_MBT_02_railgun_ghex_F",
            "ghost_China_O_T_MBT_04_cannon_F",
            "ghost_China_O_T_MBT_04_command_F",
            "ghost_China_O_T_MRAP_02_ghex_F",
            "ghost_China_O_T_MRAP_02_gmg_ghex_F",
            "ghost_China_O_T_MRAP_02_hmg_ghex_F",
            "ghost_China_O_T_Medic_F",
            "ghost_China_O_T_Mortar_01_F",
            "ghost_China_O_T_Officer_F",
            "ghost_China_O_T_Pathfinder_F",
            "ghost_China_O_T_Pickup_Comms_rf",
            "ghost_China_O_T_Pickup_rcws_rf",
            "ghost_China_O_T_Pickup_rf",
            "ghost_China_O_T_Pilot_F",
            "ghost_China_O_T_Plane_CAS_02_dynamicLoadout_ghex_F",
            "ghost_China_O_T_Plane_Fighter_02_Stealth_ghex_F",
            "ghost_China_O_T_Plane_Fighter_02_ghex_F",
            "ghost_China_O_T_Quadbike_01_ghex_F",
            "ghost_China_O_T_Radar_System_02_F",
            "ghost_China_O_T_RadioOperator_F",
            "ghost_China_O_T_Recon_AR_F",
            "ghost_China_O_T_Recon_CQ_F",
            "ghost_China_O_T_Recon_Exp_F",
            "ghost_China_O_T_Recon_F",
            "ghost_China_O_T_Recon_GL_F",
            "ghost_China_O_T_Recon_JTAC_F",
            "ghost_China_O_T_Recon_LAT_F",
            "ghost_China_O_T_Recon_M_F",
            "ghost_China_O_T_Recon_Medic_F",
            "ghost_China_O_T_Recon_TL_F",
            "ghost_China_O_T_SAM_System_04_F",
            "ghost_China_O_T_SDV_01_F",
            "ghost_China_O_T_Sharpshooter_F",
            "ghost_China_O_T_Sniper_F",
            "ghost_China_O_T_Soldier_AAA_F",
            "ghost_China_O_T_Soldier_AAR_F",
            "ghost_China_O_T_Soldier_AAT_F",
            "ghost_China_O_T_Soldier_AA_F",
            "ghost_China_O_T_Soldier_AHAT_F",
            "ghost_China_O_T_Soldier_AR_F",
            "ghost_China_O_T_Soldier_AT_F",
            "ghost_China_O_T_Soldier_A_F",
            "ghost_China_O_T_Soldier_CBRN_F",
            "ghost_China_O_T_Soldier_CQ_F",
            "ghost_China_O_T_Soldier_Exp_F",
            "ghost_China_O_T_Soldier_F",
            "ghost_China_O_T_Soldier_GL_F",
            "ghost_China_O_T_Soldier_HAT_F",
            "ghost_China_O_T_Soldier_LAT_F",
            "ghost_China_O_T_Soldier_Lite_F",
            "ghost_China_O_T_Soldier_M_F",
            "ghost_China_O_T_Soldier_PG_F",
            "ghost_China_O_T_Soldier_Repair_F",
            "ghost_China_O_T_Soldier_SL_F",
            "ghost_China_O_T_Soldier_TL_F",
            "ghost_China_O_T_Soldier_UAV_02_lxWS_F",
            "ghost_China_O_T_Soldier_UAV_F",
            "ghost_China_O_T_Soldier_unarmed_F",
            "ghost_China_O_T_Spotter_F",
            "ghost_China_O_T_Static_AA_F",
            "ghost_China_O_T_Static_AT_F",
            "ghost_China_O_T_Static_Designator_02_F",
            "ghost_China_O_T_Support_AMG_F",
            "ghost_China_O_T_Support_AMort_F",
            "ghost_China_O_T_Support_GMG_F",
            "ghost_China_O_T_Support_MG_F",
            "ghost_China_O_T_Support_Mort_F",
            "ghost_China_O_T_Survivor_F",
            "ghost_China_O_T_Truck_02_Ammo_F",
            "ghost_China_O_T_Truck_02_Box_F",
            "ghost_China_O_T_Truck_02_F",
            "ghost_China_O_T_Truck_02_MRL_F",
            "ghost_China_O_T_Truck_02_Medical_F",
            "ghost_China_O_T_Truck_02_cargo_lxWS",
            "ghost_China_O_T_Truck_02_flatbed_lxWS",
            "ghost_China_O_T_Truck_02_fuel_F",
            "ghost_China_O_T_Truck_02_transport_F",
            "ghost_China_O_T_Truck_03_ammo_ghex_F",
            "ghost_China_O_T_Truck_03_cargo_RF",
            "ghost_China_O_T_Truck_03_covered_ghex_F",
            "ghost_China_O_T_Truck_03_device_ghex_F",
            "ghost_China_O_T_Truck_03_fuel_ghex_F",
            "ghost_China_O_T_Truck_03_medical_ghex_F",
            "ghost_China_O_T_Truck_03_repair_ghex_F",
            "ghost_China_O_T_Truck_03_transport_ghex_F",
            "ghost_China_O_T_UAV_01_F",
            "ghost_China_O_T_UAV_04_CAS_F",
            "ghost_China_O_T_UAV_06_F",
            "ghost_China_O_T_UAV_06_medical_F",
            "ghost_China_O_T_UGV_01_ghex_F",
            "ghost_China_O_T_UGV_01_rcws_ghex_F",
            "ghost_China_O_T_UGV_02_Demining_F",
            "ghost_China_O_T_VTOL_02_infantry_dynamicLoadout_F",
            "ghost_China_O_T_VTOL_02_infantry_ghex_F",
            "ghost_China_O_T_VTOL_02_vehicle_dynamicLoadout_F",
            "ghost_China_O_T_ghillie_spotter_tna_F",
            "ghost_China_O_T_ghillie_tna_F",
            "ghost_China_O_T_soldier_UAV_06_F",
            "ghost_China_O_T_soldier_UAV_06_medical_F",
            "ghost_China_O_T_soldier_UGV_02_Demining_F",
            "ghost_China_O_T_soldier_mine_F",
            "ghost_China_ghost_antiship_launcher",
            "ghost_China_ghost_antiship_radar",
            "ghost_China_qav_o_t_625e",
            "ghost_China_qav_o_t_ztl11",
            "ghost_China_rksla3_aeroshark_opfor",
            "ghost_China_rksla3_uav_h450_2",
            "ghost_China_O_UAV_03_dynamicLoadout_F",
            "ghost_China_O_SwitchBlade_300",
            "ghost_China_O_SwitchBlade_600",
            "ghost_China_O_SwitchBlade_300_LaunchTube",
            "ghost_China_O_SwitchBlade_600_LaunchTube",
            "ghost_China_SwitchBlade_Operator",
            "ghost_China_rksla3_uav_gdt_sa_o",
            "ghost_China_rksla3_uav_wkshelter_sa_o",
            "ghost_China_O_Rapier_FSC_Launcher",
            "ghost_China_O_Rapier_FSC_Blindfire",
            "ghost_China_O_Rapier_FSC_Dagger",
            "ghost_China_Drone_Operator"
        };
        weapons[] = {"ghost_China_Aegis_sgun_AA40_ACO_LP_LxWS_snds","ghost_China_LMG_03_Arco_Pointer_F_snds","ghost_China_SMG_02_ACO_F_snds","ghost_China_arifle_CTARS_blk_ARCO_Pointer_F_snds","ghost_China_arifle_CTAR_GL_blk_ARCO_Pointer_F_snds","ghost_China_arifle_CTAR_blk_ARCO_Pointer_F_snds","ghost_China_hgun_Rook40_F_snds","ghost_China_srifle_DMR_05_KHS_LP_F_snds","ghost_China_srifle_DMR_07_blk_DMS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
