#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_US_JTF_tna_ACE_B_T_SpottingScope",
            "ghost_US_JTF_tna_Aegis_B_T_CommandoMortar_RF",
            "ghost_US_JTF_tna_Aegis_B_T_UAV_02_lxWS",
            "ghost_US_JTF_tna_Aegis_B_T_support_CMort_RF",
            "ghost_US_JTF_tna_Atlas_B_T_JSOC_F",
            "ghost_US_JTF_tna_Atlas_B_T_JSOC_JTAC_F",
            "ghost_US_JTF_tna_Atlas_B_T_JSOC_LAT_F",
            "ghost_US_JTF_tna_Atlas_B_T_JSOC_UAV_F",
            "ghost_US_JTF_tna_Atlas_B_T_JSOC_UAV_lxWS",
            "ghost_US_JTF_tna_B_AAA_System_01_F",
            "ghost_US_JTF_tna_B_Heli_Light_01_F",
            "ghost_US_JTF_tna_B_Heli_Light_01_dynamicLoadout_F",
            "ghost_US_JTF_tna_B_Heli_Light_01_stripped_F",
            "ghost_US_JTF_tna_B_Heli_Transport_01_F",
            "ghost_US_JTF_tna_B_Heli_Transport_01_pylons_F",
            "ghost_US_JTF_tna_B_Heli_Transport_01_unarmed_F",
            "ghost_US_JTF_tna_B_Heli_Transport_03_F",
            "ghost_US_JTF_tna_B_Heli_Transport_03_unarmed_F",
            "ghost_US_JTF_tna_B_Plane_CAS_01_Cluster_F",
            "ghost_US_JTF_tna_B_Plane_CAS_01_dynamicLoadout_F",
            "ghost_US_JTF_tna_B_Plane_Fighter_01_Cluster_F",
            "ghost_US_JTF_tna_B_Plane_Fighter_01_F",
            "ghost_US_JTF_tna_B_Plane_Fighter_01_Stealth_F",
            "ghost_US_JTF_tna_B_Radar_System_01_F",
            "ghost_US_JTF_tna_B_SAM_System_03_F",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_apc_QAV",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_atgm_lxWS",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_atgm_lxWS_v2",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_cannon_F",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_command_lxWS",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_medical_F",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_mgs_QAV",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_mgs_up_QAV",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_mortar_lxWS",
            "ghost_US_JTF_tna_B_T_APC_Wheeled_01_shorad_QAV",
            "ghost_US_JTF_tna_B_T_Boat_Armed_01_minigun_F",
            "ghost_US_JTF_tna_B_T_Boat_Transport_01_F",
            "ghost_US_JTF_tna_B_T_Crew_F",
            "ghost_US_JTF_tna_B_T_Diver_Exp_F",
            "ghost_US_JTF_tna_B_T_Diver_F",
            "ghost_US_JTF_tna_B_T_Diver_TL_F",
            "ghost_US_JTF_tna_B_T_Engineer_F",
            "ghost_US_JTF_tna_B_T_Fighter_Pilot_F",
            "ghost_US_JTF_tna_B_T_GMG_01_A_F",
            "ghost_US_JTF_tna_B_T_GMG_01_F",
            "ghost_US_JTF_tna_B_T_GMG_01_high_F",
            "ghost_US_JTF_tna_B_T_HMG_01_A_F",
            "ghost_US_JTF_tna_B_T_HMG_01_F",
            "ghost_US_JTF_tna_B_T_HMG_01_high_F",
            "ghost_US_JTF_tna_B_T_HMG_02_F",
            "ghost_US_JTF_tna_B_T_HMG_02_high_F",
            "ghost_US_JTF_tna_B_T_HeavyGunner_F",
            "ghost_US_JTF_tna_B_T_Helicrew_F",
            "ghost_US_JTF_tna_B_T_Helipilot_F",
            "ghost_US_JTF_tna_B_T_LSV_01_AT_F",
            "ghost_US_JTF_tna_B_T_LSV_01_armed_F",
            "ghost_US_JTF_tna_B_T_LSV_01_light_F",
            "ghost_US_JTF_tna_B_T_LSV_01_unarmed_F",
            "ghost_US_JTF_tna_B_T_Lifeboat",
            "ghost_US_JTF_tna_B_T_MBT_01_arty_F",
            "ghost_US_JTF_tna_B_T_MBT_01_mlrs_F",
            "ghost_US_JTF_tna_B_T_MRAP_01_F",
            "ghost_US_JTF_tna_B_T_MRAP_01_gmg_F",
            "ghost_US_JTF_tna_B_T_MRAP_01_hmg_F",
            "ghost_US_JTF_tna_B_T_Medic_F",
            "ghost_US_JTF_tna_B_T_Mortar_01_F",
            "ghost_US_JTF_tna_B_T_Officer_F",
            "ghost_US_JTF_tna_B_T_Pilot_F",
            "ghost_US_JTF_tna_B_T_Quadbike_01_F",
            "ghost_US_JTF_tna_B_T_RadioOperator_F",
            "ghost_US_JTF_tna_B_T_Recon_AR_F",
            "ghost_US_JTF_tna_B_T_Recon_CQ_F",
            "ghost_US_JTF_tna_B_T_Recon_Exp_F",
            "ghost_US_JTF_tna_B_T_Recon_F",
            "ghost_US_JTF_tna_B_T_Recon_GL_F",
            "ghost_US_JTF_tna_B_T_Recon_JTAC_F",
            "ghost_US_JTF_tna_B_T_Recon_LAT_F",
            "ghost_US_JTF_tna_B_T_Recon_MG_F",
            "ghost_US_JTF_tna_B_T_Recon_M_F",
            "ghost_US_JTF_tna_B_T_Recon_Medic_F",
            "ghost_US_JTF_tna_B_T_Recon_Sharpshooter_F",
            "ghost_US_JTF_tna_B_T_Recon_TL_F",
            "ghost_US_JTF_tna_B_T_SDV_01_F",
            "ghost_US_JTF_tna_B_T_Sharpshooter_F",
            "ghost_US_JTF_tna_B_T_Sniper_F",
            "ghost_US_JTF_tna_B_T_Soldier_AAA_F",
            "ghost_US_JTF_tna_B_T_Soldier_AAR_F",
            "ghost_US_JTF_tna_B_T_Soldier_AAT_F",
            "ghost_US_JTF_tna_B_T_Soldier_AA_F",
            "ghost_US_JTF_tna_B_T_Soldier_AR_F",
            "ghost_US_JTF_tna_B_T_Soldier_AT_F",
            "ghost_US_JTF_tna_B_T_Soldier_A_F",
            "ghost_US_JTF_tna_B_T_Soldier_CBRN_F",
            "ghost_US_JTF_tna_B_T_Soldier_CQ_F",
            "ghost_US_JTF_tna_B_T_Soldier_Exp_F",
            "ghost_US_JTF_tna_B_T_Soldier_F",
            "ghost_US_JTF_tna_B_T_Soldier_GL_F",
            "ghost_US_JTF_tna_B_T_Soldier_LAT2_F",
            "ghost_US_JTF_tna_B_T_Soldier_LAT_F",
            "ghost_US_JTF_tna_B_T_Soldier_Lite_F",
            "ghost_US_JTF_tna_B_T_Soldier_MG_F",
            "ghost_US_JTF_tna_B_T_Soldier_PG_F",
            "ghost_US_JTF_tna_B_T_Soldier_Repair_F",
            "ghost_US_JTF_tna_B_T_Soldier_SL_F",
            "ghost_US_JTF_tna_B_T_Soldier_TL_F",
            "ghost_US_JTF_tna_B_T_Soldier_UAV_F",
            "ghost_US_JTF_tna_B_T_Soldier_unarmed_F",
            "ghost_US_JTF_tna_B_T_Spotter_F",
            "ghost_US_JTF_tna_B_T_Static_AA_F",
            "ghost_US_JTF_tna_B_T_Static_AT_F",
            "ghost_US_JTF_tna_B_T_Static_Designator_01_F",
            "ghost_US_JTF_tna_B_T_Support_AMG_F",
            "ghost_US_JTF_tna_B_T_Support_AMort_F",
            "ghost_US_JTF_tna_B_T_Support_GMG_F",
            "ghost_US_JTF_tna_B_T_Support_MG_F",
            "ghost_US_JTF_tna_B_T_Support_Mort_F",
            "ghost_US_JTF_tna_B_T_Survivor_F",
            "ghost_US_JTF_tna_B_T_Truck_01_FFT_rf",
            "ghost_US_JTF_tna_B_T_Truck_01_Repair_F",
            "ghost_US_JTF_tna_B_T_Truck_01_ammo_F",
            "ghost_US_JTF_tna_B_T_Truck_01_box_F",
            "ghost_US_JTF_tna_B_T_Truck_01_cargo_F",
            "ghost_US_JTF_tna_B_T_Truck_01_covered_F",
            "ghost_US_JTF_tna_B_T_Truck_01_flatbed_F",
            "ghost_US_JTF_tna_B_T_Truck_01_fuel_F",
            "ghost_US_JTF_tna_B_T_Truck_01_medical_F",
            "ghost_US_JTF_tna_B_T_Truck_01_mover_F",
            "ghost_US_JTF_tna_B_T_Truck_01_transport_F",
            "ghost_US_JTF_tna_B_T_TwinMortar_RF",
            "ghost_US_JTF_tna_B_T_UAV_01_F",
            "ghost_US_JTF_tna_B_T_UAV_05_F",
            "ghost_US_JTF_tna_B_T_UGV_02_Demining_F",
            "ghost_US_JTF_tna_B_T_VTOL_01_armed_F",
            "ghost_US_JTF_tna_B_T_VTOL_01_infantry_F",
            "ghost_US_JTF_tna_B_T_VTOL_01_vehicle_F",
            "ghost_US_JTF_tna_B_T_VTOL_03_unarmed_QAV",
            "ghost_US_JTF_tna_B_T_ghillie_spotter_tna_F",
            "ghost_US_JTF_tna_B_T_ghillie_tna_F",
            "ghost_US_JTF_tna_B_T_qav_abramsx",
            "ghost_US_JTF_tna_B_T_soldier_M_F",
            "ghost_US_JTF_tna_B_T_soldier_UAV_02_LxWS_F",
            "ghost_US_JTF_tna_B_T_soldier_UGV_02_Demining_F",
            "ghost_US_JTF_tna_B_T_soldier_mine_F",
            "ghost_US_JTF_tna_B_qav_abramsx_templar",
            "ghost_US_JTF_tna_B_qav_abramsx_tusk",
            "ghost_US_JTF_tna_E22_B_JC_W_AAA_System_01_F",
            "ghost_US_JTF_tna_E22_B_JC_W_Radar_system_01_F",
            "ghost_US_JTF_tna_E22_B_JC_W_SAM_system_01_F",
            "ghost_US_JTF_tna_EF_B_CombatBoat_AT_NATO_T",
            "ghost_US_JTF_tna_EF_B_CombatBoat_HMG_NATO_T",
            "ghost_US_JTF_tna_EF_B_CombatBoat_Unarmed_NATO_T",
            "ghost_US_JTF_tna_EF_B_MRAP_01_AT_NATO_T",
            "ghost_US_JTF_tna_EF_B_MRAP_01_FSV_NATO_T",
            "ghost_US_JTF_tna_EF_B_MRAP_01_LAAD_NATO_T",
            "ghost_US_JTF_tna_GX_B_HONEYBADGER_UGV_AT_GREEN",
            "ghost_US_JTF_tna_GX_B_HUNTER_SP_LAUNCHER",
            "ghost_US_JTF_tna_GX_B_HUNTER_SP_UAV",
            "ghost_US_JTF_tna_GX_B_MAGURA_V5_USV",
            "ghost_US_JTF_tna_GX_B_MQ8B_UAV_ARMED",
            "ghost_US_JTF_tna_GX_B_MQ8B_UAV_RECON",
            "ghost_US_JTF_tna_GX_B_MQ8B_UAV_RECON_SEATED",
            "ghost_US_JTF_tna_GX_B_RWS_DEFNDER_MEDIUM",
            "ghost_US_JTF_tna_GX_B_THEMIS_UGV_CARGO",
            "ghost_US_JTF_tna_GX_B_THEMIS_UGV_DEFNDER_MEDIUM",
            "ghost_US_JTF_tna_GX_B_THEMIS_UGV_HUNTER_LAUNCHER",
            "ghost_US_JTF_tna_JK_B_CDF_76n6_ClamShell_F",
            "ghost_US_JTF_tna_JK_B_CDF_76n6_ClamShell_Lower_F",
            "ghost_US_JTF_tna_qav_b_ripsaw_Mk44",
            "ghost_US_JTF_tna_qav_ripsaw_c",
            "ghost_US_JTF_tna_C_IDAP_UAV_06_antimine_backpack_F",
            "ghost_US_JTF_tna_C_IDAP_UAV_06_antimine_F",
            "ghost_US_JTF_tna_B_Heli_Transport_01_medevac_F",
            "ghost_US_JTF_tna_Drone_Operator"
        };
        weapons[] = {"ghost_US_JTF_tna_LMG_Mk200_khk_Hamr_Pointer_Bipod_F_snds","ghost_US_JTF_tna_MMG_02_khaki_RCO_LP_F_snds","ghost_US_JTF_tna_SMG_01_khk_Holo_F_snds","ghost_US_JTF_tna_arifle_MXC_khk_ACO_Pointer_F_snds","ghost_US_JTF_tna_arifle_MXC_khk_F_snds","ghost_US_JTF_tna_arifle_MXC_khk_Holo_F_snds","ghost_US_JTF_tna_arifle_MXC_khk_Holo_Flash_F_snds","ghost_US_JTF_tna_arifle_MXC_khk_Holo_Pointer_F_snds","ghost_US_JTF_tna_arifle_MXM_khk_MOS_Pointer_Bipod_F_snds","ghost_US_JTF_tna_arifle_MX_GL_khk_ACO_Pointer_F_snds","ghost_US_JTF_tna_arifle_MX_GL_khk_Hamr_Pointer_F_snds","ghost_US_JTF_tna_arifle_MX_SW_khk_Hamr_Pointer_F_snds","ghost_US_JTF_tna_arifle_MX_khk_ACO_Pointer_F_snds","ghost_US_JTF_tna_arifle_MX_khk_Hamr_Pointer_F_snds","ghost_US_JTF_tna_arifle_MX_khk_Holo_Pointer_F_snds","ghost_US_JTF_tna_srifle_DMR_03_khaki_AMS_LP_BI_F_snds","ghost_US_JTF_tna_srifle_LRR_tna_LRPS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
