// TIER VARIANTS OF THE FUTUREAMMO ROUNDS.
//
//   _t4   +6%    peer+, the edge nobody else has
//   _t3   as built - the FA round IS tier 3, so this is an empty inherit
//   _t2   -12%
//   t1/t0 base game ammo, so nothing is generated for them
//
// ONLY SMALL ARMS. A tier is a supply difference in what a rifleman is
// issued, not a reason to weaken a Titan warhead or a 120mm APFSDS.
//
// Generated by tools/gen_fa_tiers.py - re-run rather than hand-edit.

class CfgAmmo {
    // ---- EXTERNAL. Defined by the fa_* addons named in requiredAddons,
    // ---- declared here so the tier variants below have a parent.

};
