// Generated by tools/gen_fa_tiers.py - re-run rather than hand-edit.
//
// A TIER MAGAZINE IS A NEW CLASS, AND A WEAPON KNOWS ITS MAGAZINES BY
// NAME. Inheriting from FA_o_150Rnd_762x54_Box makes _t4 look like the
// belt and hit like the belt; it does not make the Zafir load it -
// magazines[] and CfgMagazineWells are matched on the class name, and
// neither had heard of a _t4. Every tier variant goes back into the
// wells its base magazine sits in, so a tier 4 rifleman is not carrying
// eight magazines he cannot chamber.
class CfgMagazineWells {
    class CBA_127x55_ASh12 {
        ADDON[] += {};
    };
    class STANAG_556x45 {
        ADDON[] += {};
    };
    class ghost_fa_Glock19_RF {
        ADDON[] += {};
    };
};
