// Generated by tools/cdlc_split.py - re-run it rather than hand-edit.
// Expeditionary Forces: everything ghost builds on it, out of the base addons. Without the DLC this addon skips itself
// (skipWhenMissingDependencies) and the base addons load with their stand-ins.

class CfgGroups {
    class West {
        class DOUBLES(PREFIX,faction_eudf_arc) {
            class Motorized_MTP {
                class EGVAR(faction_eudf_arc,Mot_EF_B_MRAP_01_FSV_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_MRAP_01_FSV_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                };
                class EGVAR(faction_eudf_arc,Mot_EF_B_MRAP_01_AT_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_MRAP_01_AT_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                };
            };
            class Armored {
                class EGVAR(faction_eudf_arc,AASection_EF_B_MRAP_01_LAAD_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_MRAP_01_LAAD_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                    class Unit1 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_MRAP_01_LAAD_NATO);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };
                };
            };
            class Air {
                class EGVAR(faction_eudf_arc,AttackPair_EF_B_AH99J_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_AH99J_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                    class Unit1 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_AH99J_NATO);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };
                };
            };
            class Naval {
                class EGVAR(faction_eudf_arc,Boat_EF_B_CombatBoat_Unarmed_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_CombatBoat_Unarmed_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                };
                class EGVAR(faction_eudf_arc,Boat_EF_B_CombatBoat_HMG_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_CombatBoat_HMG_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                };
                class EGVAR(faction_eudf_arc,Boat_EF_B_CombatBoat_AT_NATO) {
                    class Unit0 {
                        side = 1;
                        vehicle = QEGVAR(faction_eudf_arc,EF_B_CombatBoat_AT_NATO);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };
                };
            };
        };
    };
};

class CfgVehicles {
    class EF_B_AH99J_NATO;
    class EF_B_CombatBoat_AT_NATO;
    class EF_B_CombatBoat_HMG_NATO;
    class EF_B_CombatBoat_Unarmed_NATO;
    class EF_B_MRAP_01_AT_NATO;
    class EF_B_MRAP_01_FSV_NATO;
    class EF_B_MRAP_01_LAAD_NATO;

    class EGVAR(faction_eudf_arc,EF_B_AH99J_NATO): EF_B_AH99J_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_Helipilot_F);
    };
    class EGVAR(faction_eudf_arc,EF_B_CombatBoat_Unarmed_NATO): EF_B_CombatBoat_Unarmed_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_Soldier_F);
    };
    class EGVAR(faction_eudf_arc,EF_B_CombatBoat_HMG_NATO): EF_B_CombatBoat_HMG_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_Soldier_F);
    };
    class EGVAR(faction_eudf_arc,EF_B_CombatBoat_AT_NATO): EF_B_CombatBoat_AT_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_Soldier_F);
    };
    class EGVAR(faction_eudf_arc,EF_B_MRAP_01_FSV_NATO): EF_B_MRAP_01_FSV_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_crew_F);
    };
    class EGVAR(faction_eudf_arc,EF_B_MRAP_01_LAAD_NATO): EF_B_MRAP_01_LAAD_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_crew_F);
    };
    class EGVAR(faction_eudf_arc,EF_B_MRAP_01_AT_NATO): EF_B_MRAP_01_AT_NATO {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        side = 1;
        faction = "ghost_faction_eudf_arc";
        crew = QEGVAR(faction_eudf_arc,B_crew_F);
    };
};
