name = "Ghost"
mainprefix = "z"
prefix = "ghost"
author = "YonV"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "3rdparty",
    "AUTHORS.txt",
    "gobp2_256_g.paa",
    "gobp2_256.paa",
    "2035_modern_equipment_replacment_helmet.png",
    "2023-11-18_12-57-37.png"
]

exclude = ["*.psd", "*.tga"]

[version]
path = "addons/main/script_version.hpp"

[asc]
exclude = [
    ".inc.sqf",
    "cba_settings.sqf",
]