// Generated by tools/gen_jca_rails.py - re-run rather than hand-edit.
// JCA'S ATTACHMENTS ON THE BASE GAME'S RAILS. A rifle's slots are root classes -
// CBA Joint Rails' asdg_* for the SPARs, the base game's own PointerSlot_Rail
// for the MX's side rail, which cba_jr leaves alone - and an item fits a slot
// when it is listed in that class's compatibleItems. JCA lists its optics,
// lasers and torches there but keeps the dual mount for its own M4A4, its
// bipods on its own slot and its cans by 5.56 / 7.62. This addon adds the
// missing entries to the same root classes; no weapon class is touched and JCA
// itself is untouched. See the tool's docstring for what goes where.
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"ghost_main", "cba_jr", "Weapons_F_JCA_IA"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

class PointerSlot;
class asdg_SlotInfo;
class asdg_MuzzleSlot;

class PointerSlot_Rail: PointerSlot {
    class compatibleItems {
        JCA_acc_DualMount_black_Pointer = 1;
        JCA_acc_DualMount_black_Laser_Red = 1;
        JCA_acc_DualMount_black_Laser_Green = 1;
        JCA_acc_DualMount_black_Light = 1;
        JCA_acc_DualMount_black_Light_LP = 1;
        JCA_acc_DualMount_sand_Pointer = 1;
        JCA_acc_DualMount_sand_Laser_Red = 1;
        JCA_acc_DualMount_sand_Laser_Green = 1;
        JCA_acc_DualMount_sand_Light = 1;
        JCA_acc_DualMount_sand_Light_LP = 1;
        JCA_acc_DualMount_olive_Pointer = 1;
        JCA_acc_DualMount_olive_Laser_Red = 1;
        JCA_acc_DualMount_olive_Laser_Green = 1;
        JCA_acc_DualMount_olive_Light = 1;
        JCA_acc_DualMount_olive_Light_LP = 1;
    };
};

class asdg_FrontSideRail: asdg_SlotInfo {
    class compatibleItems {
        JCA_acc_DualMount_black_Pointer = 1;
        JCA_acc_DualMount_black_Laser_Red = 1;
        JCA_acc_DualMount_black_Laser_Green = 1;
        JCA_acc_DualMount_black_Light = 1;
        JCA_acc_DualMount_black_Light_LP = 1;
        JCA_acc_DualMount_sand_Pointer = 1;
        JCA_acc_DualMount_sand_Laser_Red = 1;
        JCA_acc_DualMount_sand_Laser_Green = 1;
        JCA_acc_DualMount_sand_Light = 1;
        JCA_acc_DualMount_sand_Light_LP = 1;
        JCA_acc_DualMount_olive_Pointer = 1;
        JCA_acc_DualMount_olive_Laser_Red = 1;
        JCA_acc_DualMount_olive_Laser_Green = 1;
        JCA_acc_DualMount_olive_Light = 1;
        JCA_acc_DualMount_olive_Light_LP = 1;
    };
};

class asdg_UnderSlot: asdg_SlotInfo {
    class compatibleItems {
        JCA_bipod_AWM_01_black = 1;
        JCA_bipod_AWM_02_black = 1;
        JCA_bipod_M107_black = 1;
        JCA_bipod_M107_sand = 1;
        JCA_bipod_M107_olive = 1;
    };
};

class asdg_MuzzleSlot_762: asdg_MuzzleSlot {
    class compatibleItems {
        JCA_muzzle_snds_SR25_black = 1;
        JCA_muzzle_snds_SR25_sand = 1;
        JCA_muzzle_snds_SR25_olive = 1;
    };
};

class asdg_MuzzleSlot_65: asdg_MuzzleSlot_762 {
    class compatibleItems: compatibleItems {
        JCA_muzzle_snds_556_advanced_black = 1;
        JCA_muzzle_snds_556_advanced_sand = 1;
        JCA_muzzle_snds_556_advanced_olive = 1;
        JCA_muzzle_snds_556_enhanced_black = 1;
        JCA_muzzle_snds_556_enhanced_sand = 1;
        JCA_muzzle_snds_556_enhanced_olive = 1;
    };
};

class asdg_MuzzleSlot_338: asdg_MuzzleSlot {
    class compatibleItems {
        JCA_muzzle_snds_AWM_black = 1;
        JCA_muzzle_snds_AWM_sand = 1;
        JCA_muzzle_snds_AWM_olive = 1;
    };
};
