#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_b_fdf_Boat_Armed_01_minigun_F",
            "ghost_b_fdf_APC_Wheeled_01_cannon_ATGM_F",
            "ghost_b_fdf_APC_Wheeled_01_command_F",
            "ghost_b_fdf_APC_Wheeled_01_mortar_F",
            "ghost_b_fdf_MRAP_01_AT_F",
            "ghost_b_fdf_MRAP_01_FSV_F",
            "ghost_b_fdf_Heli_EC_04_military_RF",
            "ghost_b_fdf_Heli_EC_03_RF",
            "ghost_b_fdf_MRAP_01_LAAD_F",
            "ghost_b_fdf_W_SAM_system_01_F",
            "ghost_b_fdf_W_AAA_System_01_F",
            "ghost_b_fdf_W_Radar_system_01_F",
            "ghost_b_fdf_B_UAV_RC40_HE_RF",
            "ghost_b_fdf_B_UAV_RC40_SENSOR_RF",
            "ghost_b_fdf_GX_B_HONEYBADGER_UGV_AT_GREEN",
            "ghost_b_fdf_GX_B_HUNTER_SP_UAV",
            "ghost_b_fdf_qav_ripsaw_c",
            "ghost_b_fdf_qav_ripsaw_Mk44",
            "ghost_b_fdf_GX_B_THEMIS_UGV_HUNTER_LAUNCHER",
            "ghost_b_fdf_GX_B_THEMIS_UGV_DEFNDER_MEDIUM",
            "ghost_b_fdf_GX_B_THEMIS_UGV_CARGO",
            "ghost_b_fdf_GX_B_MAGURA_V5_USV",
            "ghost_b_fdf_GX_B_MQ8B_UAV_RECON_SEATED",
            "ghost_b_fdf_GX_B_MQ8B_UAV_RECON",
            "ghost_b_fdf_GX_B_MQ8B_UAV_ARMED",
            "ghost_b_fdf_rksla3_aeroshark_blufor",
            "ghost_b_fdf_B_T_UAV_03_dynamicLoadout_F",
            "ghost_b_fdf_Soldier_01_F",
            "ghost_b_fdf_Soldier_02_F",
            "ghost_b_fdf_Soldier_03_F",
            "ghost_b_fdf_Soldier_04_F",
            "ghost_b_fdf_Soldier_F",
            "ghost_b_fdf_Soldier_Light_F",
            "ghost_b_fdf_Soldier_Unarmed_F",
            "ghost_b_fdf_Soldier_GL_F",
            "ghost_b_fdf_Soldier_SL_F",
            "ghost_b_fdf_Soldier_TL_F",
            "ghost_b_fdf_Soldier_M_F",
            "ghost_b_fdf_Soldier_LAT_F",
            "ghost_b_fdf_Soldier_CLS_F",
            "ghost_b_fdf_Soldier_REP_F",
            "ghost_b_fdf_Soldier_EXP_F",
            "ghost_b_fdf_Helipilot_F",
            "ghost_b_fdf_Helicrew_F",
            "ghost_b_fdf_Soldier_AB_F",
            "ghost_b_fdf_Soldier_ENG_F",
            "ghost_b_fdf_Crewman_F",
            "ghost_b_fdf_Officer_F",
            "ghost_b_fdf_Officer_Field_F",
            "ghost_b_fdf_Soldier_Survivor_F",
            "ghost_b_fdf_Soldier_Mine_F",
            "ghost_b_fdf_RadioOperator_F",
            "ghost_b_fdf_Support_Mortar_F",
            "ghost_b_fdf_Support_Mortar_A_F",
            "ghost_b_fdf_Soldier_UAV_F",
            "ghost_b_fdf_Soldier_UAV_01_F",
            "ghost_b_fdf_Soldier_UAV_06_F",
            "ghost_b_fdf_Soldier_UAV_06_medical_F",
            "ghost_b_fdf_Soldier_UAV_06_demining_F",
            "ghost_b_fdf_Soldier_UGV_02_science_F",
            "ghost_b_fdf_Soldier_UGV_02_demining_F",
            "ghost_b_fdf_Recon_base",
            "ghost_b_fdf_Recon_F",
            "ghost_b_fdf_Recon_LAT_F",
            "ghost_b_fdf_Recon_EXP_F",
            "ghost_b_fdf_Recon_CLS_F",
            "ghost_b_fdf_Recon_TL_F",
            "ghost_b_fdf_Recon_M_F",
            "ghost_b_fdf_Recon_JTAC_F",
            "ghost_b_fdf_Plane_Fighter_04_F",
            "ghost_b_fdf_UAV_01_F",
            "ghost_b_fdf_UAV_01_backpack_F",
            "ghost_b_fdf_UAV_06_F",
            "ghost_b_fdf_UAV_06_antimine_F",
            "ghost_b_fdf_UAV_06_medical_F",
            "ghost_b_fdf_UAV_06_backpack_F",
            "ghost_b_fdf_UAV_06_antimine_backpack_F",
            "ghost_b_fdf_UAV_06_medical_backpack_F",
            "ghost_b_fdf_APC_Tracked_03_F",
            "ghost_b_fdf_APC_Tracked_01_AA_F",
            "ghost_b_fdf_APC_Wheeled_01_cannon_F",
            "ghost_b_fdf_APC_Wheeled_01_unarmed_F",
            "ghost_b_fdf_MBT_03_cannon_F",
            "ghost_b_fdf_Boat_Combat_01_unarmed_F",
            "ghost_b_fdf_Boat_Combat_01_HMG_F",
            "ghost_b_fdf_Boat_Combat_01_AT_F",
            "ghost_b_fdf_Boat_Transport_01_F",
            "ghost_b_fdf_Boat_Transport_02_F",
            "ghost_b_fdf_LSV_01_unarmed_F",
            "ghost_b_fdf_LSV_01_light_F",
            "ghost_b_fdf_LSV_01_AT_F",
            "ghost_b_fdf_MRAP_01_F",
            "ghost_b_fdf_MRAP_01_hmg_F",
            "ghost_b_fdf_MRAP_01_gmg_F",
            "ghost_b_fdf_Pickup_01_F",
            "ghost_b_fdf_Pickup_01_comms_F",
            "ghost_b_fdf_Pickup_01_fuel_F",
            "ghost_b_fdf_Pickup_01_MMG_F",
            "ghost_b_fdf_Pickup_01_MRL_F",
            "ghost_b_fdf_Pickup_01_AAT_F",
            "ghost_b_fdf_Pickup_01_RCWS_F",
            "ghost_b_fdf_Quadbike_01_F",
            "ghost_b_fdf_Truck_01_transport_F",
            "ghost_b_fdf_Truck_01_covered_F",
            "ghost_b_fdf_Truck_01_mover_F",
            "ghost_b_fdf_Truck_01_Box_F",
            "ghost_b_fdf_Truck_01_Repair_F",
            "ghost_b_fdf_Truck_01_ammo_F",
            "ghost_b_fdf_Truck_01_fuel_F",
            "ghost_b_fdf_Truck_01_medical_F",
            "ghost_b_fdf_Truck_01_flatbed_F",
            "ghost_b_fdf_Truck_01_cargo_F",
            "ghost_b_fdf_UGV_02_Science_F",
            "ghost_b_fdf_UGV_02_Demining_F",
            "ghost_b_fdf_UGV_02_Science_backpack_F",
            "ghost_b_fdf_UGV_02_Demining_backpack_F",
            "ghost_b_fdf_UGV_01_F",
            "ghost_b_fdf_UGV_01_rcws_F",
            "ghost_b_fdf_HMG_02_F",
            "ghost_b_fdf_HMG_02_high_F",
            "ghost_b_fdf_HMG_02_support_F",
            "ghost_b_fdf_HMG_02_support_high_F",
            "ghost_b_fdf_HMG_02_weapon_F",
            "ghost_b_fdf_HMG_02_high_weapon_F",
            "ghost_b_fdf_Mortar_01_F",
            "ghost_b_fdf_Mortar_01_support_F",
            "ghost_b_fdf_Mortar_01_weapon_F"
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "ghost_main",
            "A3_Armor_F_Exp_APC_Tracked_01",
            "A3_Soft_F_Exp_UGV_01",
            "A3_Boat_F_Exp_Boat_Armed_01",
            "A3_Air_F_Exp_UAV_03",
            "Characters_F_FDF",
            "Vests_F_FDF",
            "Headwear_F_FDF",
            "Air_F_FDF_Plane_Fighter_04",
            "Air_F_FDF_UAV_01",
            "Air_F_FDF_UAV_06",
            "Armour_F_FDF_APC_Tracked_03",
            "Armour_F_FDF_APC_Wheeled_01",
            "Armour_F_FDF_MBT_03",
            "Boats_F_Levi_Boat_Combat_01",
            "Boats_F_FDF_Boat_Transport_01",
            "Boats_F_FDF_Boat_Transport_02",
            "Soft_F_FDF_LSV_01",
            "Soft_F_FDF_MRAP_01",
            "Soft_F_FDF_Pickup_01",
            "Soft_F_FDF_Quadbike_01",
            "Soft_F_FDF_Truck_01",
            "Soft_F_FDF_UGV_02",
            "Static_F_FDF_HMG_02",
            "Static_F_FDF_Mortar_01",
            "ghostfa_ammo",
            "A3_Armor_F_Gamma",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02"
        };
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        authors[] = {"Ghost"};
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
