#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_Turkey_ind_Athena_B_G_Heli_Attack_03_F",
            "ghost_Turkey_ind_Athena_B_G_Plane_Fighter_05_F",
            "ghost_Turkey_ind_Athena_B_G_Plane_Fighter_05_Stealth_F",
            "ghost_Turkey_ind_Athena_O_Spotter_F",
            "ghost_Turkey_ind_Athena_O_T_APC_Wheeled_02_rcws_v2_F",
            "ghost_Turkey_ind_Athena_O_T_Boat_Armed_01_hmg_F",
            "ghost_Turkey_ind_Athena_O_T_Boat_Transport_01_F",
            "ghost_Turkey_ind_Athena_O_T_CombatBoat_AT_EF",
            "ghost_Turkey_ind_Athena_O_T_CombatBoat_HMG_EF",
            "ghost_Turkey_ind_Athena_O_T_CombatBoat_Unarmed_EF",
            "ghost_Turkey_ind_Athena_O_T_Crew_F",
            "ghost_Turkey_ind_Athena_O_T_Diver_F",
            "ghost_Turkey_ind_Athena_O_T_Diver_TL_F",
            "ghost_Turkey_ind_Athena_O_T_Diver_exp_F",
            "ghost_Turkey_ind_Athena_O_T_Engineer_F",
            "ghost_Turkey_ind_Athena_O_T_Fighter_Pilot_F",
            "ghost_Turkey_ind_Athena_O_T_GMG_01_A_F",
            "ghost_Turkey_ind_Athena_O_T_GMG_01_F",
            "ghost_Turkey_ind_Athena_O_T_GMG_01_high_F",
            "ghost_Turkey_ind_Athena_O_T_HMG_01_A_F",
            "ghost_Turkey_ind_Athena_O_T_HMG_01_F",
            "ghost_Turkey_ind_Athena_O_T_HMG_01_high_F",
            "ghost_Turkey_ind_Athena_O_T_Heli_Attack_02_dynamicLoadout_F",
            "ghost_Turkey_ind_Athena_O_T_Heli_Transport_01_F",
            "ghost_Turkey_ind_Athena_O_T_Helicrew_F",
            "ghost_Turkey_ind_Athena_O_T_Helipilot_F",
            "ghost_Turkey_ind_Athena_O_T_MBT_03_cannon_F",
            "ghost_Turkey_ind_Athena_O_T_MRAP_03_F",
            "ghost_Turkey_ind_Athena_O_T_MRAP_03_gmg_F",
            "ghost_Turkey_ind_Athena_O_T_MRAP_03_hmg_F",
            "ghost_Turkey_ind_Athena_O_T_Medic_F",
            "ghost_Turkey_ind_Athena_O_T_Mortar_01_F",
            "ghost_Turkey_ind_Athena_O_T_Officer_F",
            "ghost_Turkey_ind_Athena_O_T_Plane_Fighter_02_Stealth_Turkey_F",
            "ghost_Turkey_ind_Athena_O_T_Plane_Fighter_02_Turkey_F",
            "ghost_Turkey_ind_Athena_O_T_RadioOperator_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_AR_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_LAT_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_M_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_TL_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_exp_F",
            "ghost_Turkey_ind_Athena_O_T_Recon_medic_F",
            "ghost_Turkey_ind_Athena_O_T_Sniper_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_AAA_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_AAR_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_AAT_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_AA_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_AR_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_AT_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_A_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_Exp_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_GL_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_LAT_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_SL_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_TL_F",
            "ghost_Turkey_ind_Athena_O_T_Soldier_unarmed_F",
            "ghost_Turkey_ind_Athena_O_T_Static_AA_F",
            "ghost_Turkey_ind_Athena_O_T_Static_AT_F",
            "ghost_Turkey_ind_Athena_O_T_Truck_03_ammo_F",
            "ghost_Turkey_ind_Athena_O_T_Truck_03_covered_F",
            "ghost_Turkey_ind_Athena_O_T_Truck_03_fuel_F",
            "ghost_Turkey_ind_Athena_O_T_Truck_03_medical_F",
            "ghost_Turkey_ind_Athena_O_T_Truck_03_repair_F",
            "ghost_Turkey_ind_Athena_O_T_Truck_03_transport_F",
            "ghost_Turkey_ind_Athena_O_T_UAV_02_dynamicLoadout_F",
            "ghost_Turkey_ind_Athena_O_T_UGV_01_F",
            "ghost_Turkey_ind_Athena_O_T_UGV_01_medical_F",
            "ghost_Turkey_ind_Athena_O_T_UGV_01_rcws_F",
            "ghost_Turkey_ind_Athena_O_T_recon_GL_F",
            "ghost_Turkey_ind_Athena_O_T_recon_JTAC_F",
            "ghost_Turkey_ind_Athena_O_T_soldier_M_F",
            "ghost_Turkey_ind_B_MRAP_01_F",
            "ghost_Turkey_ind_B_MRAP_01_gmg_F",
            "ghost_Turkey_ind_B_MRAP_01_hmg_F",
            "ghost_Turkey_ind_B_Truck_01_Repair_F",
            "ghost_Turkey_ind_B_Truck_01_ammo_F",
            "ghost_Turkey_ind_B_Truck_01_box_F",
            "ghost_Turkey_ind_B_Truck_01_cargo_F",
            "ghost_Turkey_ind_B_Truck_01_covered_F",
            "ghost_Turkey_ind_B_Truck_01_flatbed_F",
            "ghost_Turkey_ind_B_Truck_01_fuel_F",
            "ghost_Turkey_ind_B_Truck_01_medical_F",
            "ghost_Turkey_ind_B_Truck_01_mover_F",
            "ghost_Turkey_ind_B_Truck_01_transport_F",
            "ghost_Turkey_ind_EF_O_Gyra_Antiair_OPF",
            "ghost_Turkey_ind_EF_O_Gyra_Armed_OPF",
            "ghost_Turkey_ind_EF_O_Gyra_HMG_OPF",
            "ghost_Turkey_ind_EF_O_Gyra_OPF",
            "ghost_Turkey_ind_O_G_APC_Wheeled_03_cannon_F",
            "ghost_Turkey_ind_O_Heli_Attack_02_F",
            "ghost_Turkey_ind_O_Quadbike_ALIVE",
            "ghost_Turkey_ind_O_SDV_01_F",
            "ghost_Turkey_ind_O_T_APC_Tracked_02_AA_ghex_F",
            "ghost_Turkey_ind_O_T_APC_Tracked_02_cannon_ghex_F",
            "ghost_Turkey_ind_O_T_APC_Wheeled_02_rcws_ghex_F",
            "ghost_Turkey_ind_O_T_APC_Wheeled_02_rcws_v2_ghex_F",
            "ghost_Turkey_ind_O_T_Boat_Armed_01_hmg_F",
            "ghost_Turkey_ind_O_T_Boat_Transport_01_F",
            "ghost_Turkey_ind_O_T_Diver_Exp_F",
            "ghost_Turkey_ind_O_T_Diver_F",
            "ghost_Turkey_ind_O_T_Diver_TL_F",
            "ghost_Turkey_ind_O_T_Engineer_F",
            "ghost_Turkey_ind_O_T_MBT_02_arty_ghex_F",
            "ghost_Turkey_ind_O_T_MBT_02_cannon_ghex_F",
            "ghost_Turkey_ind_O_T_MBT_04_cannon_F",
            "ghost_Turkey_ind_O_T_MBT_04_command_F",
            "ghost_Turkey_ind_O_T_MRAP_02_ghex_F",
            "ghost_Turkey_ind_O_T_MRAP_02_gmg_ghex_F",
            "ghost_Turkey_ind_O_T_MRAP_02_hmg_ghex_F",
            "ghost_Turkey_ind_O_T_Medic_F",
            "ghost_Turkey_ind_O_T_Officer_F",
            "ghost_Turkey_ind_O_T_Pathfinder_F",
            "ghost_Turkey_ind_O_T_RadioOperator_F",
            "ghost_Turkey_ind_O_T_Recon_Exp_F",
            "ghost_Turkey_ind_O_T_Recon_F",
            "ghost_Turkey_ind_O_T_Recon_JTAC_F",
            "ghost_Turkey_ind_O_T_Recon_LAT_F",
            "ghost_Turkey_ind_O_T_Recon_M_F",
            "ghost_Turkey_ind_O_T_Recon_Medic_F",
            "ghost_Turkey_ind_O_T_Recon_TL_F",
            "ghost_Turkey_ind_O_T_Sniper_F",
            "ghost_Turkey_ind_O_T_Soldier_AAA_F",
            "ghost_Turkey_ind_O_T_Soldier_AAR_F",
            "ghost_Turkey_ind_O_T_Soldier_AAT_F",
            "ghost_Turkey_ind_O_T_Soldier_AA_F",
            "ghost_Turkey_ind_O_T_Soldier_AHAT_F",
            "ghost_Turkey_ind_O_T_Soldier_AR_F",
            "ghost_Turkey_ind_O_T_Soldier_AT_F",
            "ghost_Turkey_ind_O_T_Soldier_A_F",
            "ghost_Turkey_ind_O_T_Soldier_Exp_F",
            "ghost_Turkey_ind_O_T_Soldier_F",
            "ghost_Turkey_ind_O_T_Soldier_GL_F",
            "ghost_Turkey_ind_O_T_Soldier_HAT_F",
            "ghost_Turkey_ind_O_T_Soldier_LAT_F",
            "ghost_Turkey_ind_O_T_Soldier_M_F",
            "ghost_Turkey_ind_O_T_Soldier_Repair_F",
            "ghost_Turkey_ind_O_T_Soldier_SL_F",
            "ghost_Turkey_ind_O_T_Soldier_TL_F",
            "ghost_Turkey_ind_O_T_Spotter_F",
            "ghost_Turkey_ind_O_T_Support_AMG_F",
            "ghost_Turkey_ind_O_T_Support_AMort_F",
            "ghost_Turkey_ind_O_T_Support_GMG_F",
            "ghost_Turkey_ind_O_T_Support_MG_F",
            "ghost_Turkey_ind_O_T_Support_Mort_F",
            "ghost_Turkey_ind_O_T_Truck_03_covered_ghex_F",
            "ghost_Turkey_ind_O_T_Truck_03_transport_ghex_F",
            "ghost_Turkey_ind_O_T_VTOL_02_infantry_ghex_F",
            "ghost_Turkey_ind_ghost_antiship_launcher",
            "ghost_Turkey_ind_ghost_antiship_radar",
            "ghost_Turkey_ind_Drone_Operator"
        };
        weapons[] = {"ghost_Turkey_ind_LMG_03_Arco_Pointer_F_snds","ghost_Turkey_ind_SMG_02_F_snds","ghost_Turkey_ind_arifle_SCAR_L_F_snds","ghost_Turkey_ind_arifle_SCAR_L_GL_F_snds","ghost_Turkey_ind_arifle_SCAR_L_grip_F_snds","ghost_Turkey_ind_arifle_SCAR_L_short_F_snds","ghost_Turkey_ind_hgun_P07_blk_F_snds","ghost_Turkey_ind_hgun_Rook40_F_snds","ghost_Turkey_ind_srifle_DMR_07_blk_DMS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
