// The magazine for each tier variant, pointing at the tiered round.
// Generated by tools/gen_fa_tiers.py - re-run rather than hand-edit.

class CfgMagazines {
    // ---- EXTERNAL, as above.
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB;
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue;
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green;
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange;
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red;
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White;
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White;
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow;

    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_t2";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Red Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Red_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Red Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Red_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Red Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Red_t2";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Yellow Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Yellow_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Yellow Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Yellow_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Yellow Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Yellow_t2";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Green Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Green_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Green Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Green_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Green Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Green_t2";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - White Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_White_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - White Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_White_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - White Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_White_t2";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Blue Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Blue_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Blue Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Blue_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Blue Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Blue_t2";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange_t4: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Orange Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Orange_t4";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange_t3: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Orange Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Orange_t3";
    };
    class FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange_t2: FA_EF_30Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange {
        displayName = "[Ghost] 30Rnd 6.5mm Mk367 PAB [EF] - Orange Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Orange_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Red Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Red_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Red Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Red_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Red {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Red Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Red_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Yellow Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Yellow_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Yellow Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Yellow_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Yellow {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Yellow Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Yellow_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Green Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Green_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Green Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Green_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Green {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Green Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Green_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - White Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_White_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - White Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_White_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_White {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - White Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_White_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Blue Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Blue_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Blue Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Blue_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Blue {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Blue Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Blue_t2";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange_t4: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Orange Tracer, Coyote, T4";
        ammo = "FA_b_65_Mk367_PAB_T_Orange_t4";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange_t3: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Orange Tracer, Coyote, T3";
        ammo = "FA_b_65_Mk367_PAB_T_Orange_t3";
    };
    class FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange_t2: FA_EF_100Rnd_65x39_caseless_coy_mag_Mk367_PAB_T_Orange {
        displayName = "[Ghost] 100Rnd 6.5mm Mk367 PAB [EF] - Orange Tracer, Coyote, T2";
        ammo = "FA_b_65_Mk367_PAB_T_Orange_t2";
    };
};
