// Generated by tools/cdlc_split.py - re-run it rather than hand-edit.
// Expeditionary Forces: everything ghost builds on it, out of the base addons. Without the DLC this addon skips itself
// (skipWhenMissingDependencies) and the base addons load with their stand-ins.

class XtdGearInfos {
    class CfgWeapons {
class ef_snds_diplomat
{
    model = "mxa_arsenal_diplomat_sound_suppressor_9_mm";
    camo = "STD";
};
class ef_snds_diplomat_coy
{
    model = "mxa_arsenal_diplomat_sound_suppressor_9_mm";
    camo = "CBR";
};
class EF_acc_pointer_IR_coy
{
    model = "mxa_arsenal_ir_laser_pointer";
    camo = "CBR";
};
class ef_optic_mbs
{
    model = "mxa_arsenal_mbs";
    variant = "STD";
    camo = "STD";
};
class ef_optic_mbs_coy
{
    model = "mxa_arsenal_mbs";
    variant = "STD";
    camo = "CBR";
};
class ef_optic_mbs_khk
{
    model = "mxa_arsenal_mbs";
    variant = "STD";
    camo = "KHK";
};
class ef_optic_mbs_remote
{
    model = "mxa_arsenal_mbs";
    variant = "REMOTE";
    camo = "STD";
};
class ef_optic_mbs_remote_coy
{
    model = "mxa_arsenal_mbs";
    variant = "REMOTE";
    camo = "CBR";
};
class ef_optic_mbs_remote_khk
{
    model = "mxa_arsenal_mbs";
    variant = "REMOTE";
    camo = "KHK";
};
class ef_optic_mbs_remote_sand
{
    model = "mxa_arsenal_mbs";
    variant = "REMOTE";
    camo = "SND";
};
class ef_optic_mbs_sand
{
    model = "mxa_arsenal_mbs";
    variant = "STD";
    camo = "SND";
};
class ef_optic_microsight
{
    model = "mxa_arsenal_microsight";
    mount = "STD";
    camo = "STD";
};
class ef_optic_microsight_coy
{
    model = "mxa_arsenal_microsight";
    mount = "STD";
    camo = "CBR";
};
class ef_optic_microsight_khk
{
    model = "mxa_arsenal_microsight";
    mount = "STD";
    camo = "KHK";
};
class ef_optic_microsight_pistol
{
    model = "mxa_arsenal_microsight";
    mount = "PISTOL";
    camo = "STD";
};
class ef_optic_microsight_pistol_coy
{
    model = "mxa_arsenal_microsight";
    mount = "PISTOL";
    camo = "CBR";
};
class ef_optic_microsight_pistol_khk
{
    model = "mxa_arsenal_microsight";
    mount = "PISTOL";
    camo = "KHK";
};
class ef_optic_microsight_pistol_sand
{
    model = "mxa_arsenal_microsight";
    mount = "PISTOL";
    camo = "SND";
};
class ef_optic_microsight_sand
{
    model = "mxa_arsenal_microsight";
    mount = "STD";
    camo = "SND";
};
class ef_snds_mxar
{
    model = "mxa_arsenal_mxar_sound_suppressor_6_5_mm";
    camo = "STD";
};
class ef_snds_mxar_coy
{
    model = "mxa_arsenal_mxar_sound_suppressor_6_5_mm";
    camo = "CBR";
};
class ef_snds_mxar_khk
{
    model = "mxa_arsenal_mxar_sound_suppressor_6_5_mm";
    camo = "KHK";
};
class ef_snds_mxar_sand
{
    model = "mxa_arsenal_mxar_sound_suppressor_6_5_mm";
    camo = "SND";
};
    };
};
