#include "script_component.hpp"

// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(Aegis_O_C_D_Crew_F),
            QGVAR(Aegis_O_C_D_Engineer_F),
            QGVAR(Aegis_O_C_D_Fighter_Pilot_F),
            QGVAR(Aegis_O_C_D_HeavyGunner_F),
            QGVAR(Aegis_O_C_D_Helicrew_F),
            QGVAR(Aegis_O_C_D_Helipilot_F),
            QGVAR(Aegis_O_C_D_Medic_F),
            QGVAR(Aegis_O_C_D_Officer_F),
            QGVAR(Aegis_O_C_D_Pathfinder_F),
            QGVAR(Aegis_O_C_D_Pilot_F),
            QGVAR(Aegis_O_C_D_RadioOperator_F),
            QGVAR(Aegis_O_C_D_Recon_AR_F),
            QGVAR(Aegis_O_C_D_Recon_CQ_F),
            QGVAR(Aegis_O_C_D_Recon_Exp_F),
            QGVAR(Aegis_O_C_D_Recon_F),
            QGVAR(Aegis_O_C_D_Recon_GL_F),
            QGVAR(Aegis_O_C_D_Recon_JTAC_F),
            QGVAR(Aegis_O_C_D_Recon_LAT_F),
            QGVAR(Aegis_O_C_D_Recon_M_F),
            QGVAR(Aegis_O_C_D_Recon_Medic_F),
            QGVAR(Aegis_O_C_D_Recon_TL_F),
            QGVAR(Aegis_O_C_D_Sharpshooter_F),
            QGVAR(Aegis_O_C_D_Sniper_F),
            QGVAR(Aegis_O_C_D_Soldier_AAA_F),
            QGVAR(Aegis_O_C_D_Soldier_AAR_F),
            QGVAR(Aegis_O_C_D_Soldier_AAT_F),
            QGVAR(Aegis_O_C_D_Soldier_AA_F),
            QGVAR(Aegis_O_C_D_Soldier_AHAT_F),
            QGVAR(Aegis_O_C_D_Soldier_AR_F),
            QGVAR(Aegis_O_C_D_Soldier_AT_F),
            QGVAR(Aegis_O_C_D_Soldier_A_F),
            QGVAR(Aegis_O_C_D_Soldier_CBRN_F),
            QGVAR(Aegis_O_C_D_Soldier_CQ_F),
            QGVAR(Aegis_O_C_D_Soldier_Exp_F),
            QGVAR(Aegis_O_C_D_Soldier_F),
            QGVAR(Aegis_O_C_D_Soldier_GL_F),
            QGVAR(Aegis_O_C_D_Soldier_HAT_F),
            QGVAR(Aegis_O_C_D_Soldier_LAT_F),
            QGVAR(Aegis_O_C_D_Soldier_Lite_F),
            QGVAR(Aegis_O_C_D_Soldier_M_F),
            QGVAR(Aegis_O_C_D_Soldier_PG_F),
            QGVAR(Aegis_O_C_D_Soldier_Repair_F),
            QGVAR(Aegis_O_C_D_Soldier_SL_F),
            QGVAR(Aegis_O_C_D_Soldier_TL_F),
            QGVAR(Aegis_O_C_D_Soldier_UAV_06_F),
            QGVAR(Aegis_O_C_D_Soldier_UAV_06_medical_F),
            QGVAR(Aegis_O_C_D_Soldier_UAV_F),
            QGVAR(Aegis_O_C_D_Soldier_UGV_02_Demining_F),
            QGVAR(Aegis_O_C_D_Soldier_unarmed_F),
            QGVAR(Aegis_O_C_D_Spotter_F),
            QGVAR(Aegis_O_C_D_Support_AMG_F),
            QGVAR(Aegis_O_C_D_Support_AMort_F),
            QGVAR(Aegis_O_C_D_Support_GMG_F),
            QGVAR(Aegis_O_C_D_Support_MG_F),
            QGVAR(Aegis_O_C_D_Support_Mort_F),
            QGVAR(Aegis_O_T_BoatCrew_EF),
            QGVAR(O_T_Diver_Exp_F),
            QGVAR(O_T_Diver_F),
            QGVAR(O_T_Diver_TL_F),
            QGVAR(O_T_Soldier_UAV_02_lxWS_F),
            QGVAR(O_T_Survivor_F),
            QGVAR(O_T_ghillie_spotter_tna_F),
            QGVAR(O_T_ghillie_tna_F),
            QGVAR(O_T_soldier_mine_F),
            QGVAR(SwitchBlade_Operator),
            QGVAR(Drone_Operator),
            QGVAR(CSK181),
            QGVAR(SX2316),
            QGVAR(SX2316_Flat),
            QGVAR(SX2220),
            QGVAR(SX2220_Flat),
            QGVAR(HQ6A),
            QGVAR(PLAAF_Fighter_J10),
            QGVAR(PLAAF_Fighter_J11),
            QGVAR(PLAAF_Fighter_J15),
            QGVAR(PLAAF_Fighter_J16),
            QGVAR(PLAAF_Fighter_J20),
            QGVAR(O_PGZ09_AA),
            QGVAR(O_PGZ09_TY90),
            QGVAR(O_PLL09),
            QGVAR(Z10),
            QGVAR(Z11WA),
            QGVAR(Z11WA_2),
            QGVAR(Z19),
            QGVAR(Z20),
            QGVAR(Z8L),
            QGVAR(O_ZBD04A),
            QGVAR(O_ZBD05),
            QGVAR(O_ZBL09),
            QGVAR(O_ZTD05),
            QGVAR(O_ZTL11),
            QGVAR(O_ZTQ15),
            QGVAR(O_ZTQ15B),
            QGVAR(O_ZTZ99),
            QGVAR(O_ZTZ99A),
            QGVAR(O_PLZ05),
            QGVAR(O_ZTZ96A),
            QGVAR(O_ZTZ96B)
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        // The mods these classes build on - skipped whole without them (see the header of
        // tools/gen_mod_factions.py). Tier magazines are named as strings, so FA is not required.
        requiredAddons[] = {"ghost_main", "ghost_uniform", "ghost_vehicle", "ghost_vests", "ghost_weapons", "csk181_c", "hmv3_c", "hq6a_c", "lk_jets_c", "pgz09_lk", "pll09_lk", "plz05_lk", "z10_lk", "z11wa_lk", "z19_lk", "z20_lk", "z8l_lk", "zbd04_lk", "zbd05_lk", "zbl09_lk", "ztd05_lk", "ztl11_lk", "ztq15_lk", "ztz96_c_lk", "ztz99_lk", "ztz99a_lk"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
