#!/usr/bin/env python3
"""Give every US and Marine faction the same drone roster.

    python tools/gen_us_drones.py

Reads work/factions.json and writes drones.hpp into each US faction addon,
adding whatever that faction is missing from the COMBINED set of drones the six
of them field between them.

WHY: the six factions are one army in four theatres plus the Marines, and they
had wildly different drone rosters - base US fields sixty-odd, the Marines
seven. A section's drone options should not depend on which camo its faction
happens to wear, so the union is issued to all of them.

DEDUPED BY DISPLAY NAME, NOT BY CLASSNAME. Every faction has its own textured
AR-2 Darter under its own classname; they are the same drone. A faction that
already fields a Darter keeps ITS Darter and is not given five more.

STATIC WEAPON SYSTEMS ARE NOT DRONES. Patriot launchers, ship turrets, radars
and the AMOS container all sit in the Autonomous editor category because they
are remotely operated - they are not something a UAV operator carries to a
ridge. The exclusion list below is short and reviewable on purpose.
"""
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "work", "factions.json")
ADDONS = os.path.join(ROOT, "addons")

# faction class -> addon directory
US = [
    ("BLU_F", "faction_blu_f"),
    ("BLU_T_F", "faction_blu_t_f"),
    ("BLU_W_F", "faction_blu_w_f"),
    ("BLU_NATO_lxWS", "faction_blu_nato_lxws"),
    ("EF_B_MJTF_Des", "faction_ef_b_mjtf_des"),
    ("EF_B_MJTF_Wdl", "faction_ef_b_mjtf_wdl"),
]

# Remotely operated, but not a drone anybody deploys - static launchers, ship
# turrets, radars. Matched against the display name.
NOT_A_DRONE = [
    "MIM-104 Patriot", "Mk-29 ESSM", "Mk41 VLS", "Mk45 Hammer", "Mk49 Spartan",
    "Praetorian", "Radar", "AMOS Container", "Destroyer VLS", "Mk66",
]

# One editor subcategory across all six, so the drone list reads the same
# wherever it is opened from.
SUBCAT = "EdSubcat_UAV"


def is_drone(u):
    name = u["name"]
    return not any(bad.lower() in name.lower() for bad in NOT_A_DRONE)


def crlf(path, lines):
    io.open(path, "w", encoding="utf-8", newline="\r\n").write("\n".join(lines) + "\n")


def main():
    if not os.path.isfile(DATA):
        print("no %s" % DATA)
        return 1
    facs = json.load(io.open(DATA, encoding="utf-8"))

    have = {}     # faction -> {display name: class}
    source = {}   # display name -> class to inherit from
    for cls, comp in US:
        if cls not in facs:
            print("  %s not in the dump - skipped" % cls)
            continue
        drones = [u for u in facs[cls]["units"]
                  if u["vclass"] == "Autonomous" and is_drone(u)]
        have[cls] = dict((u["name"], u["cls"]) for u in drones)
        for u in drones:
            # First one seen wins, and BLU_F is first in the list - the base US
            # roster is the richest and the least theatre-specific.
            source.setdefault(u["name"], u["cls"])

    print("%d distinct drone(s) across the six" % len(source))

    for cls, comp in US:
        d = os.path.join(ADDONS, comp)
        if not os.path.isdir(d):
            print("  %-24s MISSING addon - skipped" % comp)
            continue

        mine = have.get(cls, {})
        missing = sorted([n for n in source if n not in mine], key=str.lower)

        lines = [
            "// THE COMBINED DRONE ROSTER.",
            "//",
            "// The six US and Marine factions are one army in four theatres plus the",
            "// Marines, and they shipped wildly different drone lists - base US fields",
            "// sixty-odd, the Marines seven. What a section can put in the air should",
            "// not depend on which camo its faction wears, so every one of them gets",
            "// the union of all six.",
            "//",
            "// THIS FACTION ALREADY HAD %d OF THEM; %d are added below." % (len(mine), len(missing)),
            "//",
            "// DEDUPED BY DISPLAY NAME. Every faction has its own textured AR-2 Darter",
            "// under its own classname - they are the same drone, so a faction that has",
            "// one keeps its own rather than being handed five more.",
            "//",
            "// ONE SUBCATEGORY, %s, on all of them - the list reads the" % SUBCAT,
            "// same wherever it is opened from.",
            "//",
            "// Generated by tools/gen_us_drones.py - re-run it rather than hand-editing.",
            "// The class bodies are bare: config.cpp wraps every piece in ONE",
            "// class CfgVehicles, because four of them is three the engine drops.",
            "",
        ]

        # Forward-declare every base class once. These belong to other mods; a
        # declaration means a load order without one gets an inert class rather
        # than a config that refuses to build.
        bases = sorted(set(source[n] for n in missing), key=str.lower)
        for b in bases:
            lines.append("    class %s;" % b)
        if bases:
            lines.append("")

        for n in missing:
            base = source[n]
            new = "ghost_%s_%s" % (comp.replace("faction_", ""), base)
            new = re.sub(r"[^A-Za-z0-9_]", "_", new)
            lines += [
                "    class %s: %s {" % (new, base),
                "        scope = 2;",
                "        scopeCurator = 2;",
                "        author = QAUTHOR;",
                '        faction = "%s";' % cls,
                '        vehicleClass = "Autonomous";',
                '        editorSubcategory = "%s";' % SUBCAT,
                "    };   // %s" % n,
            ]
        crlf(os.path.join(d, "drones.hpp"), lines)

        cfg = os.path.join(d, "config.cpp")
        s = io.open(cfg, encoding="utf-8", newline="").read()
        # config.cpp wraps every piece in ONE class CfgVehicles - a second
        # one is a class the engine drops, taking its contents with it. A
        # piece not listed yet goes INSIDE that block, never ahead of it.
        if '#include "drones.hpp"' not in s:
            s = s.replace("class CfgVehicles {",
                          'class CfgVehicles {\r\n    #include "drones.hpp"', 1)
        io.open(cfg, "w", encoding="utf-8", newline="").write(s)

        print("  %-24s had %3d, added %3d" % (comp, len(mine), len(missing)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
