#!/usr/bin/env python3
"""Take dropped mods' classes out of the generated faction addons, in place.

    python tools/strip_faction_mods.py [--dry-run]

WHY THIS EXISTS WHEN gen_us_factions.py COULD JUST BE RE-RUN. The generator
reads an in-game ORBAT dump out of the RPT, and that RPT is gone - Arma keeps
ten and the 2026-08-22 dump has rolled off. Re-running means another trip
through the game with every mod loaded, which is the very load order this is
taking apart. So the rule the generator now applies at build time
(gen_us_factions.DROP_MODS) is applied here to what is already on disk. Both
read the same rule; either gives the same answer.

WHAT IT DOES, per addons/faction_* whose files carry the generator's header:

  CfgVehicles.hpp     drops the forward declaration and the ghost_ class of
                      every unit whose parent is a dropped mod's, and every
                      class that inherits from one of those. A kept vehicle
                      crewed by a dropped class is re-crewed with the
                      faction's own crewman. A paint job whose textures live
                      in a dropped mod's PBO is removed - the vehicle keeps
                      its source paint rather than spawning untextured. A kit
                      item from a dropped mod is swapped through ITEM_SWAP.
  CfgGroups.hpp       drops every slot naming a dropped class, then every
                      group left with no slots, then every category left
                      with no groups. Slots are renumbered.
  config.cpp          units[] is rewritten to what is still defined.
  CfgFactionClasses   an icon or flag from a dropped mod's PBO becomes the
                      base game's side art.
  README.md           the unit count in the seeded prose is corrected.

WHAT IT WILL NOT DO: empty a faction. An addon whose every unit came from a
dropped mod is reported and left alone. The answer there is to delete the
addon and re-point whatever named it, and that is a decision, not a side
effect of a script.

NOTHING GOES IN SILENCE. Every dropped class, every re-crew, every removed
paint job and every remaining foreign name is printed - see the header of
gen_us_factions.DROP_MODS for why a class name alone cannot say which mod it
came from, and therefore why the report is the check.

work/vanilla_vehicles.json MUST EXIST. Run tools/gen_vanilla_vehicles.py first.
"""
import argparse
import io
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_us_factions as G

ROOT = G.ROOT
ADDONS = G.ADDONS
GEN_HDR = "Generated by tools/gen_us_factions.py"

# A kept man wearing a dropped mod's kit. The generator's KIT_SWAP was
# rewritten to the same values; this is for what is already on disk.
ITEM_SWAP = {
    "Atlas_U_O_CombatFatigues_mhex_F": "U_O_T_Soldier_F",
}

# Addons with nothing left once their mod went - every man came from it.
# Stripping one would leave a faction of drones with nobody to fly them, so
# these are not touched and are reported every run until they are dealt
# with. faction_himf was one (Atlas_BLU_H_F) and is now rebuilt on the base
# game by tools/gen_himf.py, whose header this tool does not recognise - so
# it is left alone as hand-written, which is right.
REMOVED = {}

RE_DECL = re.compile(r"^(\s*)class ([A-Za-z0-9_]+);\s*$")
RE_OPEN = re.compile(r"^(\s*)class ([A-Za-z0-9_]+)(?:: ([A-Za-z0-9_]+))? \{\s*$")
RE_STR = re.compile(r'"([^"]*)"')


def foreign(text):
    """Every quoted name in the text that a dropped mod owns - by prefix or by
    DROP_TESTS - whether it is a class, a crew, a backpack or a kit item."""
    return sorted(set(s for s in RE_STR.findall(text)
                      if G.class_origin(s, None) == "dropped"))


def read(p):
    return io.open(p, encoding="utf-8", errors="replace").read()


def write(p, text, dry):
    if dry:
        return
    io.open(p, "w", encoding="utf-8", newline="\r\n").write(text)


def split_lines(text):
    return text.replace("\r\n", "\n").split("\n")


# ---------------------------------------------------------------------------
# a class-block parser that survives multi-line arrays
# ---------------------------------------------------------------------------
# A block opens on `class X: Y {` and closes on the `};` at the SAME indent.
# Arrays inside a class also open with `{` and close with `};`, but always one
# indent deeper, so indent - not brace depth - is what tells them apart.

def parse(lines):
    """-> list of nodes. A node is ('line', text) or ('block', open, indent, name, parent, children)."""
    out, stack = [], []
    for ln in lines:
        m = RE_OPEN.match(ln)
        if m:
            node = ["block", ln, len(m.group(1)), m.group(2), m.group(3), []]
            (stack[-1][5] if stack else out).append(node)
            stack.append(node)
            continue
        if stack:
            top = stack[-1]
            if re.match(r"^\s*\};", ln) and (len(ln) - len(ln.lstrip(" "))) == top[2]:
                top.append(ln)          # the close line, index 6
                stack.pop()
                continue
            top[5].append(["line", ln])
            continue
        out.append(["line", ln])
    if stack:
        raise SystemExit("unbalanced class blocks")
    return out


def emit(nodes, L):
    for n in nodes:
        if n[0] == "line":
            L.append(n[1])
        else:
            L.append(n[1])
            emit(n[5], L)
            L.append(n[6])
    return L


def blocks(nodes):
    return [n for n in nodes if n[0] == "block"]


# ---------------------------------------------------------------------------
# CfgVehicles.hpp
# ---------------------------------------------------------------------------

def faction_of(text):
    """The ghost_ faction class a CfgFactionClasses.hpp declares."""
    m = re.search(r"^\s*class (ghost_[A-Za-z0-9_]+): NO_CATEGORY", text, re.M)
    return m.group(1) if m else None


def strip_vehicles(text, vanilla, rep, faction=None):
    dropped_by = lambda c: G.is_dropped(c, vanilla, faction)
    lines = split_lines(text)
    tree = parse(lines)
    root = [n for n in blocks(tree) if n[3] == "CfgVehicles"]
    if len(root) != 1:
        raise SystemExit("expected one CfgVehicles root")
    root = root[0]

    dropped_ghost = set()      # our classes that go, by name
    kept = []                 # our classes that stay, in order

    # First pass: decide. Parents are declared before children in the
    # generated file, so one ordered pass resolves the whole chain.
    for n in root[5]:
        if n[0] == "line":
            m = RE_DECL.match(n[1])
            if m and dropped_by(m.group(2)):
                n[0] = "drop"
                rep["decl"].append(m.group(2))
            continue
        name, parent = n[3], n[4]
        gone = parent in dropped_ghost or (parent and dropped_by(parent))
        # A man whose backpack is a dropped mod's system - the KVN operator -
        # goes with it: he was that system's carrier and nothing else.
        why = parent
        for it in n[5]:
            m = re.match(r'^\s*backpack = "([A-Za-z0-9_]+)";', it[1]) if it[0] == "line" else None
            if m and dropped_by(m.group(1)):
                gone = True
                why = "%s (carries %s)" % (name, m.group(1))
        if gone:
            n[0] = "drop"
            dropped_ghost.add(name)
            rep["cls"].append((name, why))
            # The generator writes crew = for everything that is not a man,
            # and for nothing that is. That is how a group below can tell
            # whether what it lost was a rifleman or its APC.
            if any(it[0] == "line" and it[1].strip().startswith("crew = ") for it in n[5]):
                rep["vehicles"].add(name)
        else:
            kept.append(name)

    # Second pass: fix what the kept classes say.
    for n in root[5]:
        if n[0] != "block":
            continue
        body = n[5]
        out = []
        i = 0
        while i < len(body):
            item = body[i]
            if item[0] != "line":
                out.append(item)
                i += 1
                continue
            ln = item[1]
            s = ln.strip()

            # crew
            m = re.match(r'^crew = "([A-Za-z0-9_]+)";$', s)
            if m:
                cr = m.group(1)
                if cr in dropped_ghost or dropped_by(cr):
                    # matched to the seat - a pilot for a pilot - see pick_crew
                    sub = G.pick_crew(cr, kept)
                    if sub:
                        out.append(["line", '        crew = "%s";' % sub])
                    rep["crew"].append((n[3], cr, sub))
                    i += 1
                    continue

            # a paint job into a dropped mod's PBO: the whole block goes, and
            # the hiddenSelections[] line written with it goes too
            if s.startswith("hiddenSelectionsTextures[] = {"):
                j = i
                while j < len(body) and body[j][1].strip() != "};":
                    j += 1
                blk = [body[k][1] for k in range(i, j + 1)]
                if any(G.DROP_PATH.search(x) for x in blk):
                    if out and out[-1][0] == "line" and out[-1][1].strip().startswith("hiddenSelections[] = {"):
                        out.pop()
                    rep["paint"].append(n[3])
                    i = j + 1
                    continue
                out.extend(body[i:j + 1])
                i = j + 1
                continue

            # kit
            if s.startswith(("uniformClass = ", "linkedItems[] = ", "respawnLinkedItems[] = ")):
                new = ln
                for a, b in ITEM_SWAP.items():
                    if '"%s"' % a in new:
                        new = new.replace('"%s"' % a, '"%s"' % b)
                        rep["kit"].append((n[3], a, b))
                out.append(["line", new])
                i += 1
                continue

            out.append(item)
            i += 1
        n[5] = out

    # If every "fielded by this faction" extra went, the banner above them is
    # a comment about nothing.
    kids = root[5]
    for idx, n in enumerate(kids):
        if n[0] == "line" and "fielded by this faction, not by its source" in n[1]:
            if not any(k[0] == "block" for k in kids[idx:]):
                for k in kids[idx:]:
                    if k[0] == "line":
                        k[0] = "drop"
            break

    # Emit, minus the dropped nodes, collapsing the blank runs they leave.
    root[5] = [n for n in root[5] if n[0] != "drop"]
    L = emit(tree, [])
    L = collapse_blanks(L)
    text = "\n".join(L)
    rep["left"].extend(foreign(text))
    return text, kept


def collapse_blanks(L):
    out = []
    for ln in L:
        if ln.strip() == "" and out and out[-1].strip() == "":
            continue
        out.append(ln)
    return out


# ---------------------------------------------------------------------------
# CfgGroups.hpp
# ---------------------------------------------------------------------------

def strip_groups(text, kept, rep):
    keptset = set(kept)
    tree = parse(split_lines(text))
    root = [n for n in blocks(tree) if n[3] == "CfgGroups"][0]
    for side in blocks(root[5]):
        for fac in blocks(side[5]):
            for cat in blocks(fac[5]):
                for grp in blocks(cat[5]):
                    slots = blocks(grp[5])
                    live, lost = [], []
                    for u in slots:
                        veh = None
                        for it in u[5]:
                            m = re.match(r'^\s*vehicle = "([A-Za-z0-9_]+)";$', it[1]) if it[0] == "line" else None
                            if m:
                                veh = m.group(1)
                        if veh in keptset:
                            live.append(u)
                        else:
                            lost.append(veh)
                            rep["slot"].append((grp[3], veh))
                    if not live:
                        grp[0] = "drop"
                        rep["group"].append(grp[3])
                        continue
                    lost_veh = [v for v in lost if v in rep["vehicles"]]
                    if lost_veh or len(lost) * 2 > len(slots):
                        # A MECHANISED SQUAD THAT LOST ITS APC IS A RIFLE SQUAD
                        # UNDER THE WRONG NAME - and in the wrong category, which
                        # is what ALiVE picks by. It goes, and so does a group
                        # that lost most of its men (a mortar team down to its
                        # leader). A squad that lost a man stays, one short,
                        # and is reported.
                        grp[0] = "drop"
                        rep["group_veh"].append((grp[3], lost_veh or lost))
                        continue
                    if lost:
                        rep["partial"].append((grp[3], len(lost), len(slots), lost))
                    # renumber, keeping the props ahead of the first slot
                    head = []
                    for it in grp[5]:
                        if it[0] == "block":
                            break
                        head.append(it)
                    while head and head[-1][0] == "line" and head[-1][1].strip() == "":
                        head.pop()
                    body = list(head)
                    for i, u in enumerate(live):
                        u[1] = re.sub(r"class Unit\d+", "class Unit%d" % i, u[1])
                        body.append(["line", ""])
                        body.append(u)
                    grp[5] = body
                cat[5] = [n for n in cat[5] if n[0] != "drop"]
                if not blocks(cat[5]):
                    cat[0] = "drop"
                    rep["cat"].append(cat[3])
            fac[5] = [n for n in fac[5] if n[0] != "drop"]
    L = collapse_blanks(emit(tree, []))
    return "\n".join(L)


# ---------------------------------------------------------------------------
# config.cpp / CfgFactionClasses.hpp / README.md
# ---------------------------------------------------------------------------

def strip_patches(text, kept):
    keptset = set(kept)
    lines = split_lines(text)
    out, i = [], 0
    while i < len(lines):
        if lines[i].strip() == "units[] = {":
            out.append(lines[i])
            j = i + 1
            names = []
            while lines[j].strip() != "};":
                m = RE_STR.search(lines[j])
                if m:
                    names.append(m.group(1))
                j += 1
            names = [n for n in names if n in keptset]
            for k, n in enumerate(names):
                out.append('            "%s"%s' % (n, "," if k < len(names) - 1 else ""))
            out.append(lines[j])
            i = j + 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def strip_faction(text, rep):
    m = re.search(r"^\s*side = (\d);", text, re.M)
    side = int(m.group(1)) if m else 1

    def sub(mm):
        kind, val = mm.group(1), mm.group(2)
        if G.DROP_PATH.search(val):
            rep["art"].append((kind, val))
            return '%s = "%s";' % (kind, G.VANILLA_ART[kind][side])
        return mm.group(0)
    return re.sub(r'(icon|flag) = "([^"]+)";', sub, text)


def fix_readme(text, count):
    return re.sub(r"A content pack: \d+ unit class(?:es)?\.",
                  "A content pack: %d unit class%s." % (count, "es" if count != 1 else ""), text)


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    vanilla = G.load_vanilla()
    if vanilla is None:
        print("work/vanilla_vehicles.json is missing - run tools/gen_vanilla_vehicles.py first.")
        print("Without it a plain-named class cannot be told from the base game's, and")
        print("that is most of what Aegis adds.")
        return 2

    empties = []
    for addon in sorted(os.listdir(ADDONS)):
        d = os.path.join(ADDONS, addon)
        vp = os.path.join(d, "CfgVehicles.hpp")
        if not addon.startswith("faction_") or not os.path.exists(vp):
            continue
        if addon in REMOVED:
            print("%-20s DELETE THIS ADDON - %s" % (addon, REMOVED[addon]))
            empties.append(addon)
            continue
        if GEN_HDR not in read(vp):
            print("%-20s hand-written - not touched" % addon)
            continue

        rep = dict(decl=[], cls=[], crew=[], paint=[], kit=[], left=[],
                   slot=[], group=[], group_veh=[], partial=[], cat=[], art=[],
                   vehicles=set())
        fp = os.path.join(d, "CfgFactionClasses.hpp")
        vtext, kept = strip_vehicles(read(vp), vanilla, rep, faction_of(read(fp)))
        if not kept:
            empties.append(addon)
            print("%-20s EVERY unit came from a dropped mod - left alone; delete the addon" % addon)
            continue

        gp = os.path.join(d, "CfgGroups.hpp")
        gtext = strip_groups(read(gp), kept, rep)
        cp = os.path.join(d, "config.cpp")
        ctext = strip_patches(read(cp), kept)
        ftext = strip_faction(read(fp), rep)
        rp = os.path.join(d, "README.md")
        rtext = fix_readme(read(rp), len(kept)) if os.path.exists(rp) else None

        write(vp, vtext, args.dry_run)
        write(gp, gtext, args.dry_run)
        write(cp, ctext, args.dry_run)
        write(fp, ftext, args.dry_run)
        if rtext is not None:
            write(rp, rtext, args.dry_run)

        print("%-20s %4d kept, %4d dropped  (%d slot(s), %d group(s), %d categor%s gone)%s"
              % (addon, len(kept), len(rep["cls"]), len(rep["slot"]), len(rep["group"]),
                 len(rep["cat"]), "y" if len(rep["cat"]) == 1 else "ies",
                 "  [dry run]" if args.dry_run else ""))
        for name, parent in rep["cls"]:
            print("      - %s" % parent)
        for veh, cr, new in rep["crew"]:
            print("      crew  %s: %s -> %s" % (veh, cr, new or "(parent's crew stands)"))
        for veh in rep["paint"]:
            print("      paint %s: dropped-mod textures removed, source paint stands" % veh)
        for veh, a, b in rep["kit"]:
            print("      kit   %s: %s -> %s" % (veh, a, b))
        for kind, val in rep["art"]:
            print("      art   %s was %s" % (kind, val))
        for g in rep["group"]:
            print("      group %s: no slots left" % g)
        for g, vehs in rep["group_veh"]:
            print("      group %s: lost its %s - dropped" % (g, ", ".join(vehs)))
        for g, lost, total, vehs in rep["partial"]:
            print("      group %s: %d of %d men lost, kept short - %s" % (g, lost, total, ", ".join(vehs)))
        if rep["left"]:
            print("      !! still named: %s" % ", ".join(rep["left"]))

    if empties:
        print()
        print("NOT WRITTEN, TO BE DELETED: %s" % ", ".join(empties))
        print("Delete the addon directory and re-point whatever names its faction.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
