#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "ace_ballistics",
            "ghost_fa_main",
            "cba_main",
            "ghost_fa_mediumcaliber"
        };
        author = QAUTHOR;
        VERSION_CONFIG;
        ammo[] = {
            "FA_Sh_105mm_APFSDS",
            "FA_Sh_105mm_APFSDS_T_Red",
            "FA_Sh_105mm_APFSDS_T_Yellow",
            "FA_Sh_105mm_APFSDS_T_Green",
            "FA_Sh_105mm_APFSDS_T_White",
            "FA_Sh_105mm_APFSDS_T_Blue",
            "FA_Sh_105mm_APFSDS_T_Orange",
            "FA_Sh_105mm_APFSDS_T_IR",
            "FA_Sh_105mm_HEATMP",
            "FA_Sh_105mm_HEATMP_T_Red",
            "FA_Sh_105mm_HEATMP_T_Yellow",
            "FA_Sh_105mm_HEATMP_T_Green",
            "FA_Sh_105mm_HEATMP_T_White",
            "FA_Sh_105mm_HEATMP_T_Blue",
            "FA_Sh_105mm_HEATMP_T_Orange",
            "FA_Sh_105mm_HEATMP_T_IR",
            "FA_Sh_105mm_HEOB",
            "FA_Sh_105mm_HEOB_T_Red",
            "FA_Sh_105mm_HEOB_T_Yellow",
            "FA_Sh_105mm_HEOB_T_Green",
            "FA_Sh_105mm_HEOB_T_White",
            "FA_Sh_105mm_HEOB_T_Blue",
            "FA_Sh_105mm_HEOB_T_Orange",
            "FA_Sh_105mm_HEOB_T_IR",
            "FA_Sh_120mm_APFSDS",
            "FA_Sh_120mm_APFSDS_Red",
            "FA_Sh_120mm_APFSDS_T_Red",
            "FA_Sh_120mm_APFSDS_T_Yellow",
            "FA_Sh_120mm_APFSDS_T_Green",
            "FA_Sh_120mm_APFSDS_T_White",
            "FA_Sh_120mm_APFSDS_T_Blue",
            "FA_Sh_120mm_APFSDS_T_Orange",
            "FA_Sh_120mm_APFSDS_T_IR",
            "FA_Sh_120mm_AMP",
            "FA_Sh_120mm_AMP_T_Red",
            "FA_Sh_120mm_AMP_T_Yellow",
            "FA_Sh_120mm_AMP_T_Green",
            "FA_Sh_120mm_AMP_T_White",
            "FA_Sh_120mm_AMP_T_Blue",
            "FA_Sh_120mm_AMP_T_Orange",
            "FA_Sh_120mm_AMP_T_IR",
            "FA_Sh_120mm_HEATMP",
            "FA_Sh_120mm_HEATMP_T_Red",
            "FA_Sh_120mm_HEATMP_T_Yellow",
            "FA_Sh_120mm_HEATMP_T_Green",
            "FA_Sh_120mm_HEATMP_T_White",
            "FA_Sh_120mm_HEATMP_T_Blue",
            "FA_Sh_120mm_HEATMP_T_Orange",
            "FA_Sh_120mm_HEATMP_T_IR",
            "FA_Sh_120mm_HEAB",
            "FA_Sh_120mm_HEAB_T_Red",
            "FA_Sh_120mm_HEAB_T_Yellow",
            "FA_Sh_120mm_HEAB_T_Green",
            "FA_Sh_120mm_HEAB_T_White",
            "FA_Sh_120mm_HEAB_T_Blue",
            "FA_Sh_120mm_HEAB_T_Orange",
            "FA_Sh_120mm_HEAB_T_IR",
            "FA_Sh_125mm_APFSDS",
            "FA_Sh_125mm_APFSDS_T_Red",
            "FA_Sh_125mm_APFSDS_T_Yellow",
            "FA_Sh_125mm_APFSDS_T_Green",
            "FA_Sh_125mm_APFSDS_T_White",
            "FA_Sh_125mm_APFSDS_T_Blue",
            "FA_Sh_125mm_APFSDS_T_Orange",
            "FA_Sh_125mm_APFSDS_T_IR",
            "FA_Sh_125mm_AMP",
            "FA_Sh_125mm_3BM70", "FA_Sh_125mm_3BK31", "FA_Sh_125mm_3OF82", "FA_M_125mm_Refleks",
            "FA_Sh_125mm_AMP_T_Red",
            "FA_Sh_125mm_AMP_T_Yellow",
            "FA_Sh_125mm_AMP_T_Green",
            "FA_Sh_125mm_AMP_T_White",
            "FA_Sh_125mm_AMP_T_Blue",
            "FA_Sh_125mm_AMP_T_Orange",
            "FA_Sh_125mm_AMP_T_IR"
        };
        magazines[] = {
            "FA_20Rnd_105mm_APFSDS",
            "FA_20Rnd_105mm_APFSDS_T_Red",
            "FA_20Rnd_105mm_APFSDS_T_Yellow",
            "FA_20Rnd_105mm_APFSDS_T_Green",
            "FA_20Rnd_105mm_APFSDS_T_White",
            "FA_20Rnd_105mm_APFSDS_T_Blue",
            "FA_20Rnd_105mm_APFSDS_T_Orange",
            "FA_20Rnd_105mm_APFSDS_T_IR",
            "FA_20Rnd_105mm_HEATMP",
            "FA_20Rnd_105mm_HEATMP_T_Red",
            "FA_20Rnd_105mm_HEATMP_T_Yellow",
            "FA_20Rnd_105mm_HEATMP_T_Green",
            "FA_20Rnd_105mm_HEATMP_T_White",
            "FA_20Rnd_105mm_HEATMP_T_Blue",
            "FA_20Rnd_105mm_HEATMP_T_Orange",
            "FA_20Rnd_105mm_HEATMP_T_IR",
            "FA_20Rnd_105mm_HEOB",
            "FA_20Rnd_105mm_HEOB_T_Red",
            "FA_20Rnd_105mm_HEOB_T_Yellow",
            "FA_20Rnd_105mm_HEOB_T_Green",
            "FA_20Rnd_105mm_HEOB_T_White",
            "FA_20Rnd_105mm_HEOB_T_Blue",
            "FA_20Rnd_105mm_HEOB_T_Orange",
            "FA_20Rnd_105mm_HEOB_T_IR",
            "FA_30Rnd_120mm_APFSDS",
            "FA_30Rnd_120mm_APFSDS_Red",
            "FA_30Rnd_120mm_APFSDS_T_Red",
            "FA_30Rnd_120mm_APFSDS_T_Yellow",
            "FA_30Rnd_120mm_APFSDS_T_Green",
            "FA_30Rnd_120mm_APFSDS_T_White",
            "FA_30Rnd_120mm_APFSDS_T_Blue",
            "FA_30Rnd_120mm_APFSDS_T_Orange",
            "FA_30Rnd_120mm_APFSDS_T_IR",
            "FA_30Rnd_120mm_AMP",
            "FA_30Rnd_120mm_AMP_T_Red",
            "FA_30Rnd_120mm_AMP_T_Yellow",
            "FA_30Rnd_120mm_AMP_T_Green",
            "FA_30Rnd_120mm_AMP_T_White",
            "FA_30Rnd_120mm_AMP_T_Blue",
            "FA_30Rnd_120mm_AMP_T_Orange",
            "FA_30Rnd_120mm_AMP_T_IR",
            "FA_30Rnd_120mm_HEATMP",
            "FA_30Rnd_120mm_HEATMP_T_Red",
            "FA_30Rnd_120mm_HEATMP_T_Yellow",
            "FA_30Rnd_120mm_HEATMP_T_Green",
            "FA_30Rnd_120mm_HEATMP_T_White",
            "FA_30Rnd_120mm_HEATMP_T_Blue",
            "FA_30Rnd_120mm_HEATMP_T_Orange",
            "FA_30Rnd_120mm_HEATMP_T_IR",
            "FA_30Rnd_120mm_HEAB",
            "FA_30Rnd_120mm_HEAB_T_Red",
            "FA_30Rnd_120mm_HEAB_T_Yellow",
            "FA_30Rnd_120mm_HEAB_T_Green",
            "FA_30Rnd_120mm_HEAB_T_White",
            "FA_30Rnd_120mm_HEAB_T_Blue",
            "FA_30Rnd_120mm_HEAB_T_Orange",
            "FA_30Rnd_120mm_HEAB_T_IR",
            "FA_24Rnd_125mm_APFSDS",
            "FA_24Rnd_125mm_APFSDS_T_Red",
            "FA_24Rnd_125mm_APFSDS_T_Yellow",
            "FA_24Rnd_125mm_APFSDS_T_Green",
            "FA_24Rnd_125mm_APFSDS_T_White",
            "FA_24Rnd_125mm_APFSDS_T_Blue",
            "FA_24Rnd_125mm_APFSDS_T_Orange",
            "FA_24Rnd_125mm_APFSDS_T_IR",
            "FA_12Rnd_125mm_AMP",
            "FA_24Rnd_125mm_3BM70", "FA_12Rnd_125mm_3BK31", "FA_12Rnd_125mm_3OF82", "FA_4Rnd_125mm_Refleks",
            "FA_12Rnd_125mm_AMP_T_Red",
            "FA_12Rnd_125mm_AMP_T_Yellow",
            "FA_12Rnd_125mm_AMP_T_Green",
            "FA_12Rnd_125mm_AMP_T_White",
            "FA_12Rnd_125mm_AMP_T_Blue",
            "FA_12Rnd_125mm_AMP_T_Orange",
            "FA_12Rnd_125mm_AMP_T_IR"
        };
    };
};

#include "CfgEventHandlers.hpp"
#include "CfgAmmo.hpp"
#include "CfgMagazines.hpp"
#include "CfgWeapons.hpp"
