"""Turn a dump_hidden_selections.sqf dump into a config the camo pipeline can read.

Creator DLC ships encrypted .ebo, so neither its configs nor its textures can be read off disk and the
pipeline skips every vehicle built on one. Two things change that:

  * the dump (work/ef_selections.txt), taken in the debug console with the mod loaded, carries each class's
    hiddenSelections IN ORDER, the textures it sets, and its appearance-menu entries. The game pairs
    hiddenSelectionsTextures[i] with hiddenSelections[i] by index, so that order is the whole ballgame -
    guessing it is what once put a hull texture on the PGL-625E's wheels.
  * a sample pack (D:\\Git\\EF_Samples) carries the textures themselves, unencrypted, including the plain
    OLIVE paint a camo wants to be recoloured from.

This writes work/ef_dump.hpp - a CfgVehicles the pipeline parses like any mod config. Each dumped class is
given a base-game parent of the right kind so VB.family resolves it; nothing else about it is invented.

    python tools/camo/ef_dump.py [--dump work/ef_selections.txt] [--out work/ef_dump.hpp]
"""
import argparse, collections, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
GHOST = os.path.normpath(os.path.join(HERE, "..", ".."))
SAMPLES = os.environ.get("EF_SAMPLES", r"D:\Git\EF_Samples")

# The kind decides only which base class the synthetic entry inherits, so that family() resolves and the
# vehicle is not mistaken for a plane or a boat. Ordered: first match wins.
KIND = [("plane", "Plane_Base_F"), ("heli", "Helicopter_Base_F"), ("boat", "Boat_F"),
        ("combatboat", "Boat_F"), ("uav", "UAV_01_base_F"), ("apc", "Tank_F"), ("gyra", "Tank_F"),
        ("mbt", "Tank_F"), ("truck", "Car_F"), ("mrap", "Car_F"), ("hunter", "Car_F"),
        ("quad", "Car_F"), ("van", "Car_F"), ("car", "Car_F")]


def parent_for(model, cls):
    hay = (model + " " + cls).lower()
    for k, base in KIND:
        if k in hay:
            return base
    return "Car_F"


def sample_index():
    """basename -> path, for every texture in the sample pack. The dump's paths are the mod's own
    (ef\\ef_gyra_t\\data\\...); the pack lays the same files out flat under one folder per vehicle."""
    idx = {}
    for root, _d, files in os.walk(SAMPLES):
        for f in files:
            if f.lower().endswith(".paa"):
                idx.setdefault(f.lower(), os.path.join(root, f))
    return idx


def split(line):
    return [x.strip() for x in line.split(";")]


def unquote(s):
    return [x.strip().strip('"') for x in s.split("|") if x.strip().strip('"')]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", default=os.path.join(GHOST, "work", "ef_selections.txt"))
    ap.add_argument("--out", default=os.path.join(GHOST, "work", "ef_dump.hpp"))
    args = ap.parse_args()

    idx = sample_index()
    print("sample pack: %d textures under %s" % (len(idx), SAMPLES))

    sel, srcs = {}, collections.defaultdict(list)
    for raw in open(args.dump, encoding="utf-8", errors="replace"):
        raw = raw.strip()
        if raw.startswith("HSEL;"):
            p = split(raw)
            if len(p) >= 5:
                sel[p[1]] = (p[2], unquote(p[3]), unquote(p[4]))
        elif raw.startswith("HSRC;"):
            p = split(raw)
            if len(p) >= 5:
                srcs[p[1]].append((p[2], p[3], unquote(p[4])))

    # A Western Sahara camo net or slat cage has a base-game twin: the lxWS desert armour (Cheetah, Panther, Slammer)
    # wears base-game hull sheets and only its net was unreadable, which skipped the whole vehicle (user, 2026-09-19:
    # "ghost_EUDF_des_B_D_APC_Tracked_01_aa_lxWS has no camo").
    NET = {"camonet_nato_flat_desert_co.paa": "a3" + chr(92) + "Armor_F" + chr(92) + "Data" + chr(92) + "camonet_NATO_Desert_CO.paa",
           "camonet_nato_flat_green_co.paa": "a3" + chr(92) + "Armor_F" + chr(92) + "Data" + chr(92) + "camonet_NATO_CO.paa",
           "cage_sand_co.paa": "a3" + chr(92) + "Armor_F" + chr(92) + "Data" + chr(92) + "cage_sand_CO.paa"}

    def twin(t):
        b = os.path.basename(t.replace("/", chr(92))).lower()
        return NET.get(b, t)

    def readable(tex):
        """Every texture either lies in the sample pack or is a base-game path the game already has."""
        ok = 0
        for t in map(twin, tex):
            b = os.path.basename(t.replace("/", chr(92))).lower()
            if b in idx or t.lower().lstrip(chr(92)).startswith("a3" + chr(92)):
                ok += 1
        return ok == len(tex) and ok > 0

    out, kept, skipped = [], 0, 0
    out.append("// Generated by tools/camo/ef_dump.py from a dump_hidden_selections.sqf dump.")
    out.append("// Creator DLC configs cannot be read off disk; these carry the selection ORDER that the")
    out.append("// camo pipeline needs, so it can paint these vehicles instead of skipping them.")
    out.append("class CfgVehicles {")
    for cls, (model, hs, tex) in sorted(sel.items()):
        if not hs or not tex or not readable(tex):
            skipped += 1
            continue
        kept += 1
        out.append("    class %s: %s {" % (cls, parent_for(model, cls)))
        out.append('        model = "%s";' % model)
        out.append("        hiddenSelections[] = {%s};" % ", ".join('"%s"' % x for x in hs))
        out.append("        hiddenSelectionsTextures[] = {%s};" % ", ".join('"%s"' % twin(x) for x in tex))
        entries = [e for e in srcs.get(cls, []) if readable(e[2])]
        if entries:
            out.append("        class TextureSources {")
            for name, disp, tx in entries:
                out.append("            class %s {" % re.sub(r"\W", "_", name))
                out.append('                displayName = "%s";' % (disp or name).replace('"', ""))
                out.append("                textures[] = {%s};" % ", ".join('"%s"' % x for x in tx))
                out.append("            };")
            out.append("        };")
        out.append("    };")
    out.append("};")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    open(args.out, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("dumped classes: %d readable, %d skipped (textures not in the sample pack)" % (kept, skipped))
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
