#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(Item_H_Helmet_FASTMT_Headset_Multicam_F),
            QGVAR(Item_H_Helmet_FASTMT_Headset_Multicam_Snow_F),
            QGVAR(Item_H_Helmet_FASTMT_Headset_A3_Multicam_Woodland_F),
            QGVAR(Item_H_Helmet_FASTMT_Headset_US_OCP_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_mtp_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_tna_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_wdl_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_desert_F),
            QGVAR(Item_H_Helmet_FASTMT_Multicam_F),
            QGVAR(Item_H_Helmet_FASTMT_Multicam_Snow_F),
            QGVAR(Item_H_Helmet_FASTMT_A3_Multicam_Woodland_F),
            QGVAR(Item_H_Helmet_FASTMT_US_OCP_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_Multicam_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_Multicam_Snow_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_A3_Multicam_Woodland_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_US_OCP_F),
            QGVAR(Item_H_Helmet_FASTMT_Cover_ghost_US_OCP_F),
            QGVAR(Item_H_Booniehat_Multicam_F),
            QGVAR(Item_H_Booniehat_Multicam_hs_F),
            QGVAR(Item_H_Booniehat_Multicam_Snow_F),
            QGVAR(Item_H_Booniehat_Multicam_Snow_hs_F),
            QGVAR(Item_H_Booniehat_Multicam_Woodland_F),
            QGVAR(Item_H_Booniehat_Multicam_Woodland_hs_F),
            QGVAR(Item_H_Booniehat_Solid_CoyoteBrown_F),
            QGVAR(Item_H_Booniehat_Solid_CoyoteBrown_hs_F),
            QGVAR(Item_H_Booniehat_Solid_Ranger_Green_F),
            QGVAR(Item_H_Booniehat_Solid_Ranger_Green_hs_F),
            QGVAR(Item_H_Booniehat_Solid_Olive_F),
            QGVAR(Item_H_Booniehat_Solid_Olive_hs_F),
            QGVAR(Item_H_Booniehat_Solid_Tan_F),
            QGVAR(Item_H_Booniehat_Solid_Tan_hs_F),
            QGVAR(Item_H_Booniehat_Solid_White_F),
            QGVAR(Item_H_Booniehat_Solid_White_hs_F),
            QGVAR(Item_H_Booniehat_ocp_F),
            QGVAR(Item_H_Booniehat_ocp_hs_F)
        };
        weapons[] = {
            // --- imported weapons: generated by tools/aegis_port, do not edit between the markers
            QGVAR(H_Helmet_FASTMT_Cover_base_F),
            QGVAR(H_Helmet_FASTMT_Headset_base_F),
            QGVAR(H_Helmet_FASTMT_base_F),
            QGVAR(H_HelmetO_oicamo),
            QGVAR(H_HelmetSpecO_oicamo),
            QGVAR(H_HelmetLeaderO_oicamo),
            QGVAR(H_MilCap_oicamo),
            QGVAR(H_PASGT_Cover_HIMF_F),
            QGVAR(H_MilCap_tachs_Jungle),
            QGVAR(H_Booniehat_jungle),
            QGVAR(H_MilCap_jungle),
            QGVAR(H_I_Helmet_canvas_Green),
            QGVAR(H_HelmetHBK_commando_F),
            QGVAR(H_HelmetHBK_commando_headset_F),
            QGVAR(H_HelmetSpecB_light_sand),
            QGVAR(H_Watchcap_camo_hs),
            QGVAR(H_Booniehat_mcamo_hs),
            QGVAR(H_HelmetSpecB_light_snakeskin),
            QGVAR(H_PASGT_Cover_base_F),
            QGVAR(H_Milcap_tachs_base_F),
            QGVAR(H_HelmetSpecB_light),
            // --- end imported weapons
            QGVAR(H_Helmet_FASTMT_Headset_Multicam_F),
            QGVAR(H_Helmet_FASTMT_Headset_Multicam_Snow_F),
            QGVAR(H_Helmet_FASTMT_Headset_A3_Multicam_Woodland_F),
            QGVAR(H_Helmet_FASTMT_Headset_US_OCP_F),
            QGVAR(H_Helmet_FASTMT_Cover_mtp_F),
            QGVAR(H_Helmet_FASTMT_Cover_tna_F),
            QGVAR(H_Helmet_FASTMT_Cover_wdl_F),
            QGVAR(H_Helmet_FASTMT_Cover_desert_F),
            QGVAR(H_Helmet_FASTMT_Multicam_F),
            QGVAR(H_Helmet_FASTMT_Multicam_Snow_F),
            QGVAR(H_Helmet_FASTMT_A3_Multicam_Woodland_F),
            QGVAR(H_Helmet_FASTMT_US_OCP_F),
            QGVAR(H_Helmet_FASTMT_Cover_Multicam_F),
            QGVAR(H_Helmet_FASTMT_Cover_Multicam_Snow_F),
            QGVAR(H_Helmet_FASTMT_Cover_A3_Multicam_Woodland_F),
            QGVAR(H_Helmet_FASTMT_Cover_US_OCP_F),
            QGVAR(H_Helmet_FASTMT_Cover_ghost_US_OCP_F),
            QGVAR(H_Booniehat_Multicam_F),
            QGVAR(H_Booniehat_Multicam_hs_F),
            QGVAR(H_Booniehat_Multicam_Snow_F),
            QGVAR(H_Booniehat_Multicam_Snow_hs_F),
            QGVAR(H_Booniehat_Multicam_Woodland_F),
            QGVAR(H_Booniehat_Multicam_Woodland_hs_F),
            QGVAR(H_Booniehat_Solid_CoyoteBrown_F),
            QGVAR(H_Booniehat_Solid_CoyoteBrown_hs_F),
            QGVAR(H_Booniehat_Solid_Ranger_Green_F),
            QGVAR(H_Booniehat_Solid_Ranger_Green_hs_F),
            QGVAR(H_Booniehat_Solid_Olive_F),
            QGVAR(H_Booniehat_Solid_Olive_hs_F),
            QGVAR(H_Booniehat_Solid_Tan_F),
            QGVAR(H_Booniehat_Solid_Tan_hs_F),
            QGVAR(H_Booniehat_Solid_White_F),
            QGVAR(H_Booniehat_Solid_White_hs_F),
            QGVAR(H_Booniehat_ocp_F),
            QGVAR(H_Booniehat_ocp_hs_F)
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "A3_Data_F_Decade_Loadorder",
            "ghost_main",
            "ace_hearing"
        };
        skipWhenMissingDependencies = 1;
        authorUrl = "https://www.ghostsofbattle.com/";
        author = QAUTHOR;
        authors[] = {""};
        VERSION_CONFIG;
    };
};

class CfgEditorSubcategories {
    class EdSubcat_Headgear {
        displayName = "Headgear";
    };
};

#include "CfgEventHandlers.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
#include "CfgGlasses.hpp"
#include "XtdGear.hpp"
