// Generated by tools/aegis_port - do not hand-edit; change the generator and re-run.
// Imported from the public Aegis, Atlas and OpF sources (APL-SA).

    class GVAR(H_Helmet_FASTMT_base_F): H_HelmetB {
        author = "jc980 and Jamie";
        scope = 0;
        displayName = "Operator Helmet";
        model = "\z\ghost\addons\headware\models\characters\Headgear\H_HelmetFASTMT_F";
        descriptionShort = "Armor Level II";
        hiddenSelections[] = {"Camo"};
        class ItemInfo: HeadgearItem {
            mass = 30;
            hiddenSelections[] = {"camo"};
            uniformModel = "\z\ghost\addons\headware\models\characters\Headgear\H_HelmetFASTMT_F.p3d";
            modelSides[] = {1, 3};
            class HitpointsProtectionInfo {
                class Head {
                    hitpointName = "HitHead";
                    armor = 6;
                    passThrough = 0.5;
                };
            };
        };
    };
    class GVAR(H_HelmetO_oicamo): H_HelmetO_ocamo {
        author = "Avery Kaiserin";
        displayName = "Protector Helmet (Desert Hex)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetO_oicamo_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_oicamo_CO.paa"};
    };
    class GVAR(H_HelmetSpecO_oicamo): H_HelmetSpecO_ocamo {
        author = "Avery Kaiserin";
        displayName = "Assassin Helmet (Desert Hex)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetSpecO_oicamo_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_oicamo_CO.paa"};
    };
    class GVAR(H_HelmetLeaderO_oicamo): H_HelmetLeaderO_ocamo {
        author = "Avery Kaiserin";
        displayName = "Defender Helmet (Desert Hex)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetLeaderO_oicamo_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\uniform\models\characters\Uniforms\Data\tech_oicamo_CO.paa"};
    };
    class GVAR(H_MilCap_oicamo): H_MilCap_ocamo {
        author = "Avery Kaiserin";
        displayName = "Military Cap (Headset, Desert Hex)";
        picture = "\A3\Characters_F\Data\UI\icon_H_Cap_patrol_ocamo_CA.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\cappatrol_oicamo_CO.paa"};
    };
    class GVAR(H_Booniehat_jungle): H_Booniehat_khk {
        author = "Avery Kaiserin";
        displayName = "Booniehat [HIMF]";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_Booniehat_jungle_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\booniehat_jungle_CO.paa"};
    };
    class GVAR(H_MilCap_jungle): H_MilCap_ocamo {
        author = "Avery Kaiserin";
        displayName = "Military Cap [HIMF] (Headset)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_MilCap_jungle_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\cappatrol_jungle_CO.paa"};
    };
    class GVAR(H_I_Helmet_canvas_Green): H_HelmetIA {
        author = "Avery Kaiserin";
        displayName = "Modular Helmet (Green)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_I_Helmet_canvas_Green_CA.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\headgear_helmet_canvas_Green_CO.paa"};
    };
    class GVAR(H_HelmetHBK_commando_F): H_HelmetHBK_base_F {
        author = "BranFlakes";
        scope = 2;
        displayName = "Advanced Modular Helmet [HIMF-C]";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetHBK_commando_F_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\H_HelmetHBK_01_commando_CO.paa"};
    };
    class GVAR(H_HelmetHBK_commando_headset_F): H_HelmetHBK_headset_base_F {
        author = "BranFlakes";
        scope = 2;
        displayName = "Advanced Modular Helmet [HIMF-C] (Headset)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetHBK_commando_headset_F_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\H_HelmetHBK_01_commando_CO.paa"};
    };
    class GVAR(H_Watchcap_camo_hs): H_Watchcap_camo {
        author = "Avery Kaiserin";
        picture = "\A3\Characters_F_Bootcamp\Data\UI\icon_H_Watchcap_camo_CA.paa";
        displayName = "Beanie (Green, Headset)";
        model = "\A3\Characters_F\Civil\headgear_beaniehat01.p3d";
        allowedFacewear[] = {"", 6, "G_Aviator", 1, "G_Bandanna_aviator", 1, "G_Bandanna_beast", 1, "G_Bandanna_blk", 1, "G_Bandanna_khk", 1, "G_Bandanna_oli", 1, "G_Bandanna_shades", 1, "G_Bandanna_sport", 1, "G_Bandanna_tan", 1, "G_Bandanna_Skull1", 1, "G_Bandanna_Skull2", 1, "G_Shades_Black", 1, "G_Shades_Blue", 1, "G_Shades_Red", 1, "G_Shades_Green", 1, 1};
        class ItemInfo: ItemInfo {
            uniformModel = "\A3\Characters_F\Civil\headgear_beaniehat01.p3d";
        };
    };
    class GVAR(H_Booniehat_mcamo_hs): H_Booniehat_mcamo {
        author = "Avery Kaiserin";
        displayName = "Booniehat (MTP, Headset)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_Booniehat_mcamo_hs_ca.paa";
        model = "\A3\Characters_F_EPB\Common\booniehat_hs.p3d";
        class ItemInfo: ItemInfo {
            uniformModel = "\A3\Characters_F_EPB\Common\booniehat_hs.p3d";
        };
    };
    class GVAR(H_PASGT_Cover_base_F): HelmetBase {
        author = "Tactical Druid";
        scope = 0;
        model = "\z\ghost\addons\headware\models\characters\Headgear\Atlas_H_PASGT_Cover_F.p3d";
        hiddenSelections[] = {"Camo", "Camo2"};
        descriptionShort = "Armor Level II";
        class ItemInfo: ItemInfo {
            uniformModel = "\z\ghost\addons\headware\models\characters\Headgear\Atlas_H_PASGT_Cover_F.p3d";
            allowedSlots[] = {901, 701, 605};
            modelSides[] = {2, 3};
            hiddenSelections[] = {"Camo", "Camo2"};
            mass = 30;
            class HitpointsProtectionInfo {
                class Head {
                    hitpointName = "HitHead";
                    armor = 6;
                    passThrough = 0.5;
                };
            };
        };
    };
    class GVAR(H_Milcap_tachs_base_F): HelmetBase {
        author = "Grave";
        scope = 0;
        displayName = "Military Cap (Tactical Headset)";
        picture = "\A3\Characters_F_Bootcamp\Data\UI\icon_H_MilCap_ocamo_ca.paa";
        model = "\z\ghost\addons\headware\models\characters\Headgear\Aegis_H_Cap_Military_TacHeadset_F";
        hiddenSelections[] = {"camo", "camo1", "camo2", "camo3"};
        class ItemInfo: ItemInfo {
            mass = 6;
            hiddenSelections[] = {"camo", "camo1", "camo2", "camo3"};
            allowedSlots[] = {901, 701, 605};
            uniformModel = "\z\ghost\addons\headware\models\characters\Headgear\Aegis_H_Cap_Military_TacHeadset_F.p3d";
            modelSides[] = {1, 2, 3, 4, 5, 6, 7};
        };
    };
    class GVAR(H_HelmetSpecB_light): H_HelmetB_light {
        author = "Avery Kaiserin";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetSpecB_light_ca.paa";
        displayName = "Light Combat Helmet (Enhanced)";
        model = "\A3\Characters_F\BLUFOR\headgear_B_Helmet_light.p3d";
        descriptionShort = "Armor Level I";
        class ItemInfo: ItemInfo {
            mass = 20;
            uniformModel = "\A3\Characters_F\BLUFOR\headgear_B_Helmet_light.p3d";
            class HitpointsProtectionInfo {
                class Head {
                    hitpointName = "HitHead";
                    armor = 4;
                    passThrough = 0.5;
                };
            };
        };
    };
    class GVAR(H_Helmet_FASTMT_Cover_base_F): GVAR(H_Helmet_FASTMT_base_F) {
        author = "jc980 and Jamie";
        scope = 0;
        displayName = "Operator Helmet (Cover)";
        model = "\z\ghost\addons\headware\models\characters\Headgear\H_HelmetFASTMT_Cover_F";
        hiddenSelections[] = {"camo", "camo1", "camo2"};
        class ItemInfo: HeadgearItem {
            mass = 30;
            hiddenSelections[] = {"camo", "camo1", "camo2"};
            uniformModel = "\z\ghost\addons\headware\models\characters\Headgear\H_HelmetFASTMT_Cover_F.p3d";
            modelSides[] = {1, 3};
            class HitpointsProtectionInfo {
                class Head {
                    hitpointName = "HitHead";
                    armor = 6;
                    passThrough = 0.5;
                };
            };
        };
    };
    class GVAR(H_Helmet_FASTMT_Headset_base_F): GVAR(H_Helmet_FASTMT_base_F) {
        author = "jc980 and Jamie";
        scope = 0;
        displayName = "Operator Helmet (Headset)";
        model = "\z\ghost\addons\headware\models\characters\Headgear\H_HelmetFASTMT_Headset_F";
        hiddenSelections[] = {"camo", "camo1"};
        class ItemInfo: HeadgearItem {
            mass = 30;
            hiddenSelections[] = {"camo", "camo1", "camo2"};
            uniformModel = "\z\ghost\addons\headware\models\characters\Headgear\H_HelmetFASTMT_Headset_F.p3d";
            modelSides[] = {1, 3};
            class HitpointsProtectionInfo {
                class Head {
                    hitpointName = "HitHead";
                    armor = 6;
                    passThrough = 0.5;
                };
            };
        };
    };
    class GVAR(H_PASGT_Cover_HIMF_F): GVAR(H_PASGT_Cover_base_F) {
        author = "Tactical Druid and Lowaltitude";
        scope = 2;
        displayName = "Basic Helmet [HIMF] (Cover)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_Atlas_H_PASGT_Cover_HIMF_F_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\Atlas_H_PASGT_Cover_tiger_CO.paa", "\A3\Characters_F_Orange\Headgear\Data\H_PASGT_olive_CO.paa"};
    };
    class GVAR(H_MilCap_tachs_Jungle): GVAR(H_Milcap_tachs_base_F) {
        author = "Ravenholme";
        scope = 2;
        displayName = "Military Cap [HIMF] (Tactical Headset)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_Atlas_H_MilCap_tachs_Jungle_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\cappatrol_jungle_CO.paa", "\z\ghost\addons\headware\models\characters\Headgear\Data\H_Headset_Tactical_grn_CO.paa", "\z\ghost\addons\headware\models\characters\Headgear\Data\H_Headset_Tactical_grn_CO.paa", "\z\ghost\addons\headware\models\characters\Headgear\Data\H_Headset_Tactical_grn_CO.paa"};
    };
    class GVAR(H_HelmetSpecB_light_sand): GVAR(H_HelmetSpecB_light) {
        author = "Avery Kaiserin";
        displayName = "Light Combat Helmet (Sand, Enhanced)";
        picture = "\z\ghost\addons\headware\models\characters\Headgear\Data\UI\icon_H_HelmetSpecB_light_sand_ca.paa";
        hiddenSelectionsTextures[] = {"\z\ghost\addons\headware\models\characters\Headgear\Data\equip1_sand_CO.paa"};
    };
    class GVAR(H_HelmetSpecB_light_snakeskin): GVAR(H_HelmetSpecB_light) {
        author = "Avery Kaiserin";
        displayName = "Light Combat Helmet (Snakeskin, Enhanced)";
        picture = "\A3\Characters_F\Data\UI\icon_H_HelmetB_light_snakeskin_CA.paa";
        hiddenSelectionsTextures[] = {"\A3\Characters_F_EPA\BLUFOR\Data\equip1_snake_CO.paa"};
    };
