// Generated by tools/gen_aceax_ammo.py - re-run rather than hand-edit.
//
// One class per family - one round type in one magazine form. `options[]`
// names the axes that family varies on; each axis class lists its
// values. This is ACEAX's schema - see the header of
// tools/gen_aceax_ammo.py for why we use it for magazines, which ACEAX
// itself does not know about.

class XtdGearModels {
    class CfgMagazines {
        class ghost_ammo_1rnd_rc40_smoke_shell_rf {
            label = "1Rnd RC40 Smoke shell RF";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "blue", "orange"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
        };
        class ghost_ammo_1rnd_smoke_grenade_shell {
            label = "1Rnd Smoke Grenade shell";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "blue", "orange", "purple"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class purple { label = "Purple"; };
            };
        };
        class ghost_ammo_33rnd_9x19_mag_rf {
            label = "33Rnd 9x19 Mag RF";
            options[] = {"finish"};

            class finish {
                label = "Finish";
                values[] = {"default", "khaki", "tan"};

                class default { label = "Default"; };
                class khaki { label = "Khaki"; };
                class tan { label = "Tan"; };
            };
        };
        class ghost_ammo_3rnd_smoke_grenade_shell {
            label = "3Rnd Smoke Grenade shell";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "blue", "orange", "purple"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class purple { label = "Purple"; };
            };
        };
        class ghost_ammo_3rnd_ugl_flare_f {
            label = "3Rnd UGL Flare F";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "ir"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_3rnd_ugl_flare_illumination_f {
            label = "3rnd UGL Flare Illumination F";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
            };
        };
        class ghost_ammo_6rnd_smoke_grenade_shell {
            label = "6Rnd Smoke Grenade shell";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "blue", "orange", "purple"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class purple { label = "Purple"; };
            };
        };
        class ghost_ammo_6rnd_ugl_flare_f {
            label = "6Rnd UGL Flare F";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "ir"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_ace_40mm_flare {
            label = "ACE 40mm Flare";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "ir"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_ace_chemlight {
            label = "ACE Chemlight";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "orange", "ir"};

                class white { label = "White"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_ace_chemlight_hi {
            label = "ACE Chemlight Hi";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "blue"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
            };
        };
        class ghost_ammo_ace_handflare {
            label = "ACE HandFlare";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
            };
        };
        class ghost_ammo_aegis_handflare {
            label = "Aegis HandFlare";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"red", "green"};

                class red { label = "Red"; };
                class green { label = "Green"; };
            };
        };
        class ghost_ammo_aegis_signalflare {
            label = "Aegis SignalFlare";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"red", "green"};

                class red { label = "Red"; };
                class green { label = "Green"; };
            };
        };
        class ghost_ammo_chemlight {
            label = "Chemlight";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"red", "green", "yellow", "blue"};

                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
            };
        };
        class ghost_ammo_fa_30rnd_556x45_ap_stanag_rf {
            label = "FA 30Rnd 556x45 AP Stanag RF";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "khaki", "tan"};

                class default { label = "Default"; };
                class khaki { label = "Khaki"; };
                class tan { label = "Tan"; };
            };
        };
        class ghost_ammo_fa_30rnd_556x45_ap_stanag_rf_mk332_ap {
            label = "FA 30Rnd 556x45 AP Stanag RF Mk332 AP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "khaki", "tan"};

                class default { label = "Default"; };
                class khaki { label = "Khaki"; };
                class tan { label = "Tan"; };
            };
        };
        class ghost_ammo_fa_30rnd_556x45_ap_stanag_rf_xm891_ctep {
            label = "FA 30Rnd 556x45 AP Stanag RF XM891 CTEP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "khaki", "tan"};

                class default { label = "Default"; };
                class khaki { label = "Khaki"; };
                class tan { label = "Tan"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65_mk328 {
            label = "FA b 100Rnd 65 Mk328";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65_mk329 {
            label = "FA b 100Rnd 65 Mk329";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65_mk331_ap {
            label = "FA b 100Rnd 65 Mk331 AP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65_mk367_pab {
            label = "FA b 100Rnd 65 Mk367 PAB";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65_xm892 {
            label = "FA b 100Rnd 65 XM892";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65_xm893 {
            label = "FA b 100Rnd 65 XM893";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_100rnd_65x39_caseless_mag {
            label = "FA b 100Rnd 65x39 caseless mag";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_130rnd_338_mk372 {
            label = "FA b 130Rnd 338 Mk372";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_556x45_box_f {
            label = "FA b 200Rnd 556x45 Box F";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_556x45_box_f_mk332_ap {
            label = "FA b 200Rnd 556x45 Box F Mk332 AP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_556x45_box_f_xm891_ctep {
            label = "FA b 200Rnd 556x45 Box F XM891 CTEP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_65_mk328 {
            label = "FA b 200Rnd 65 Mk328";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_65_mk331_ap {
            label = "FA b 200Rnd 65 Mk331 AP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_65_mk367_pab {
            label = "FA b 200Rnd 65 Mk367 PAB";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_65_xm892 {
            label = "FA b 200Rnd 65 XM892";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_200rnd_65x39_cased_box {
            label = "FA b 200Rnd 65x39 cased Box";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_556_mk327_hv {
            label = "FA b 30Rnd 556 Mk327 HV";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_556_mk332_ap {
            label = "FA b 30Rnd 556 Mk332 AP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_556_mk361_pab {
            label = "FA b 30Rnd 556 Mk361 PAB";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_556_xm891_ctep {
            label = "FA b 30Rnd 556 XM891 CTEP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_epr {
            label = "FA b 30Rnd 65 EPR";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_epr_msbs {
            label = "FA b 30Rnd 65 EPR MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk328 {
            label = "FA b 30Rnd 65 Mk328";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk328_msbs {
            label = "FA b 30Rnd 65 Mk328 MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk329 {
            label = "FA b 30Rnd 65 Mk329";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk329_msbs {
            label = "FA b 30Rnd 65 Mk329 MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk331_ap {
            label = "FA b 30Rnd 65 Mk331 AP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk331_ap_msbs {
            label = "FA b 30Rnd 65 Mk331 AP MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk367_pab {
            label = "FA b 30Rnd 65 Mk367 PAB";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "green", "black"};

                class default { label = "Default"; };
                class green { label = "Green"; };
                class black { label = "Black"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_mk367_pab_msbs {
            label = "FA b 30Rnd 65 Mk367 PAB MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_xm892 {
            label = "FA b 30Rnd 65 XM892";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_xm892_msbs {
            label = "FA b 30Rnd 65 XM892 MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_xm893 {
            label = "FA b 30Rnd 65 XM893";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "black", "khaki"};

                class default { label = "Default"; };
                class black { label = "Black"; };
                class khaki { label = "Khaki"; };
            };
        };
        class ghost_ammo_fa_b_30rnd_65_xm893_msbs {
            label = "FA b 30Rnd 65 XM893 MSBS";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_ace_10rnd_762x51_sd {
            label = "FA b ACE 10Rnd 762x51 SD";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_ace_10rnd_762x51_sd_xm751_ctep {
            label = "FA b ACE 10Rnd 762x51 SD XM751 CTEP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_ace_20rnd_762x51_m993_ap {
            label = "FA b ACE 20Rnd 762x51 M993 AP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_b_ace_20rnd_762x51_m993_ap_xm751_ctep {
            label = "FA b ACE 20Rnd 762x51 M993 AP XM751 CTEP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_ef_100rnd_65x39_caseless_mag {
            label = "FA EF 100Rnd 65x39 caseless mag";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_ef_100rnd_65x39_caseless_mag_mk367_pab {
            label = "FA EF 100Rnd 65x39 caseless mag Mk367 PAB";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
        };
        class ghost_ammo_fa_ef_30rnd_65x39_caseless_mag {
            label = "FA EF 30Rnd 65x39 caseless mag";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_ef_30rnd_65x39_caseless_mag_mk367_pab {
            label = "FA EF 30Rnd 65x39 caseless mag Mk367 PAB";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
        };
        class ghost_ammo_fa_i_200rnd_556x45_box_f_af556_hv {
            label = "FA i 200Rnd 556x45 Box F AF556 HV";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_i_200rnd_556x45_box_f_af556c_ct {
            label = "FA i 200Rnd 556x45 Box F AF556C CT";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_i_200rnd_556x45_box_f_af556p_ap {
            label = "FA i 200Rnd 556x45 Box F AF556P AP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_i_30rnd_556_af556_hv {
            label = "FA i 30Rnd 556 AF556 HV";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_i_30rnd_556_af556c_ct {
            label = "FA i 30Rnd 556 AF556C CT";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_i_30rnd_556_af556p_ap {
            label = "FA i 30Rnd 556 AF556P AP";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_jca_20rnd_762x51_pmag {
            label = "FA JCA 20Rnd 762x51 PMAG";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_300blk_emag {
            label = "FA JCA 30Rnd 300BLK EMAG";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_300blk_emag_mk335 {
            label = "FA JCA 30Rnd 300BLK EMAG Mk335";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_300blk_emag_mk336 {
            label = "FA JCA 30Rnd 300BLK EMAG Mk336";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_300blk_emag_mk337 {
            label = "FA JCA 30Rnd 300BLK EMAG Mk337";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_300blk_emag_mk342 {
            label = "FA JCA 30Rnd 300BLK EMAG Mk342";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_300blk_emag_mk343 {
            label = "FA JCA 30Rnd 300BLK EMAG Mk343";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_emag {
            label = "FA JCA 30Rnd 556x45 EMAG";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "blue", "ir"};

                class ball { label = "Ball"; };
                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_emag_mk332_ap {
            label = "FA JCA 30Rnd 556x45 EMAG Mk332 AP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "blue", "ir"};

                class ball { label = "Ball"; };
                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_emag_mk361_pab {
            label = "FA JCA 30Rnd 556x45 EMAG Mk361 PAB";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "blue"};

                class ball { label = "Ball"; };
                class blue { label = "Blue"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_emag_xm891_ctep {
            label = "FA JCA 30Rnd 556x45 EMAG XM891 CTEP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "blue", "ir"};

                class ball { label = "Ball"; };
                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_pmag {
            label = "FA JCA 30Rnd 556x45 PMAG";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "green", "sand"};

                class default { label = "Default"; };
                class green { label = "Green"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_pmag_mk332_ap {
            label = "FA JCA 30Rnd 556x45 PMAG Mk332 AP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "green", "sand"};

                class default { label = "Default"; };
                class green { label = "Green"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_pmag_mk361_pab {
            label = "FA JCA 30Rnd 556x45 PMAG Mk361 PAB";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "green", "sand"};

                class default { label = "Default"; };
                class green { label = "Green"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_30rnd_556x45_pmag_xm891_ctep {
            label = "FA JCA 30Rnd 556x45 PMAG XM891 CTEP";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "white", "red", "green", "yellow", "blue", "orange", "ir"};

                class ball { label = "Ball"; };
                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "green", "sand"};

                class default { label = "Default"; };
                class green { label = "Green"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_fa_jca_5rnd_338lm_awm_mk371_250gr {
            label = "FA JCA 5Rnd 338LM AWM Mk371 250gr";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_jca_5rnd_338lm_awm_mk371_285gr {
            label = "FA JCA 5Rnd 338LM AWM Mk371 285gr";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_fa_jca_5rnd_338lm_awm_mk371_300gr {
            label = "FA JCA 5Rnd 338LM AWM Mk371 300gr";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"blue", "ir"};

                class blue { label = "Blue"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_gx_1rnd_drone40_smoke_m203 {
            label = "GX 1RND DRONE40 SMOKE M203";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "blue", "orange", "purple"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class purple { label = "Purple"; };
            };
        };
        class ghost_ammo_gx_deployable_magazine_honeybadger_ugv_at {
            label = "GX DEPLOYABLE MAGAZINE HONEYBADGER UGV AT";
            options[] = {"finish"};

            class finish {
                label = "Finish";
                values[] = {"green", "black", "hex"};

                class green { label = "Green"; };
                class black { label = "Black"; };
                class hex { label = "Hex"; };
            };
        };
        class ghost_ammo_jca_12rnd_45acp_mk23_mag {
            label = "JCA 12Rnd 45ACP Mk23 Mag";
            options[] = {"tracer"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "ir"};

                class ball { label = "Ball"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_jca_30rnd_9x19_mp5_ir_mag {
            label = "JCA 30Rnd 9x19 MP5 IR Mag";
            options[] = {"finish"};

            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_jca_30rnd_9x19_mp5_jhp_mag {
            label = "JCA 30Rnd 9x19 MP5 JHP Mag";
            options[] = {"finish"};

            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_jca_30rnd_9x19_mp5_mag {
            label = "JCA 30Rnd 9x19 MP5 Mag";
            options[] = {"tracer", "finish"};

            class tracer {
                label = "Tracer";
                values[] = {"ball", "ir"};

                class ball { label = "Ball"; };
                class ir { label = "IR"; };
            };
            class finish {
                label = "Finish";
                values[] = {"default", "sand"};

                class default { label = "Default"; };
                class sand { label = "Sand"; };
            };
        };
        class ghost_ammo_jca_handflare {
            label = "JCA HandFlare";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"red", "green"};

                class red { label = "Red"; };
                class green { label = "Green"; };
            };
        };
        class ghost_ammo_jca_signalflare {
            label = "JCA SignalFlare";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"red", "green"};

                class red { label = "Red"; };
                class green { label = "Green"; };
            };
        };
        class ghost_ammo_smokeshell {
            label = "SmokeShell";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "blue", "orange", "purple"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class blue { label = "Blue"; };
                class orange { label = "Orange"; };
                class purple { label = "Purple"; };
            };
        };
        class ghost_ammo_ugl_flare_f {
            label = "UGL Flare F";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow", "ir"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
                class ir { label = "IR"; };
            };
        };
        class ghost_ammo_ugl_flare_illumination_f {
            label = "UGL Flare Illumination F";
            options[] = {"colour"};

            class colour {
                label = "Colour";
                values[] = {"white", "red", "green", "yellow"};

                class white { label = "White"; };
                class red { label = "Red"; };
                class green { label = "Green"; };
                class yellow { label = "Yellow"; };
            };
        };
    };
};
