// Generated by tools/gen_mod_factions.py - re-run rather than hand-edit.
//
// EVERY UNIT IS THIS FACTION'S OWN: each vehicle below is the GVAR class in CfgVehicles.hpp.

class CfgGroups {
    class West {

        class ADDON {
            name = "2040 EUDF (Arctic)";

            class Infantry {
                name = "Infantry";

                class GVAR(Inf_InfSquad) {
                    name = "Rifle Squad";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_SL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                };

                class GVAR(Inf_InfTeam) {
                    name = "Fire Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(Inf_InfSentry) {
                    name = "Sentry";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Inf_InfTeam_AT) {
                    name = "AT Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AAT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(Inf_InfTeam_AA) {
                    name = "AA Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AA_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AA_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AAA_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(Inf_InfSquad_Weapons) {
                    name = "Weapons Squad";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_SL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AAR_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                };

                class GVAR(Inf_SniperTeam) {
                    name = "Sniper Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Sniper_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Spotter_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

            };

            class SpecOps {
                name = "SpecOps";

                class GVAR(Recon_InfSquad) {
                    name = "Recon Rifle Squad";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_GL_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_LAT_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_TL_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_M_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                };

                class GVAR(Recon_InfTeam) {
                    name = "Recon Fire Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_GL_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(Recon_InfSentry) {
                    name = "Recon Sentry";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_GL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Recon_InfTeam_AT) {
                    name = "Recon AT Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_LAT_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_LAT_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(Recon_InfSquad_Weapons) {
                    name = "Recon Weapons Squad";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_TL_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_LAT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_LAT_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_Medic_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                };

                class GVAR(Recon_SniperTeam) {
                    name = "Recon Sniper Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_M_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Recon_M_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

            };

            class Motorized_MTP {
                name = "Motorized";

                class GVAR(Mot_B_EUDF35_A_Strider_GMG_F) {
                    name = "Motorized Team (Fennek GMG)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Strider_GMG_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_Strider_HMG_F) {
                    name = "Motorized Team (Fennek HMG)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Strider_HMG_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_LSV_01_armed_F) {
                    name = "Motorized Team (Prowler (HMG))";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_LSV_01_armed_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_LSV_01_AT_F) {
                    name = "Motorized Team (Prowler (AT))";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_LSV_01_AT_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_Snowmobile) {
                    name = "Motorized Team (Snowmobile)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Snowmobile);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_Quad_Bike_F) {
                    name = "Motorized Team (Quad Bike)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Quad_Bike_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_Strider_F) {
                    name = "Motorized Team (Fennek)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Strider_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Mot_B_EUDF35_A_LSV_01_unarmed_F) {
                    name = "Motorized Team (Prowler (Unarmed))";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_LSV_01_unarmed_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(MotSquad_B_EUDF35_A_Zamak_Transport_F) {
                    name = "Motorized Squad (Zamak Transport)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Zamak_Transport_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                };

                class GVAR(MotSquad_B_EUDF35_A_Zamak_Covered_F) {
                    name = "Motorized Squad (Zamak Transport (Covered))";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Zamak_Covered_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                };

            };

            class Mechanized {
                name = "Mechanized";

                class GVAR(Mech_B_EUDF35_A_APC_Wheeled_01_cannon_F) {
                    name = "Mechanized Squad (AMV-7 Patria)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_mech_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_APC_Wheeled_01_cannon_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                };

                class GVAR(Mech_B_EUDF35_A_APC_tracked_03_cannon_F) {
                    name = "Mechanized Squad (FV-720 Warrior)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_mech_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_APC_tracked_03_cannon_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_SL_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AR_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_GL_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_AT_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_TL_F);
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_M_F);
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Medic_F);
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Soldier_F);
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                };

            };

            class Armored {
                name = "Armored";

                class GVAR(TankPlatoon_B_EUDF35_A_MBT_03_cannon_F) {
                    name = "Tank Platoon (MBT-52 Leopard)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_armor.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_03_cannon_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_03_cannon_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_03_cannon_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_03_cannon_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                };

                class GVAR(TankSection_B_EUDF35_A_MBT_03_cannon_F) {
                    name = "Tank Section (MBT-52 Leopard)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_armor.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_03_cannon_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_03_cannon_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Battery_B_EUDF35_A_MBT_01_arty_F) {
                    name = "Artillery Battery (M4 Scorcher)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_art.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_01_arty_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_01_arty_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_01_arty_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                };

                class GVAR(Battery_B_EUDF35_A_MBT_01_mlrs_F) {
                    name = "Artillery Battery (M5 Sandstorm MLRS)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_art.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_01_mlrs_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_01_mlrs_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MBT_01_mlrs_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                };

            };

            class Air {
                name = "Air";

                class GVAR(AttackPair_B_EUDF35_A_WY_55_F) {
                    name = "Attack Helicopter Pair (WY-55 Wildcat)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_air.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_WY_55_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_WY_55_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Transport_B_EUDF35_A_WY_55_Unarmed_F) {
                    name = "Transport Helicopter (WY-55 Wildcat (Unarmed))";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_air.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_WY_55_Unarmed_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Transport_B_EUDF35_A_Heli_Transport_02_F) {
                    name = "Transport Helicopter (CH-49 Celt)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_air.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Heli_Transport_02_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Flight_B_EUDF35_A_Plane_Fighter_04_F) {
                    name = "Flight (A-149 Gripen)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_plane.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Plane_Fighter_04_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Plane_Fighter_04_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(UAV_B_EUDF35_A_UAV_01_F) {
                    name = "UAV (AR-2 Darter)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_uav.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_UAV_01_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(UAV_B_EUDF35_A_UAV_02_dynamicLoadout_F) {
                    name = "UAV (EQ-4E Milvus)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_uav.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_UAV_02_dynamicLoadout_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(UAV_B_EUDF35_A_UAV_06_F) {
                    name = "UAV (AL-6 Pelican)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_uav.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_UAV_06_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(UAV_B_EUDF35_A_UAV_06_medical_F) {
                    name = "UAV (AL-6 Pelican (Medical))";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_uav.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_UAV_06_medical_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(UAV_B_EUDF35_A_UGV_01_F) {
                    name = "UAV (UGV Stomper)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_uav.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_UGV_01_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(UAV_B_EUDF35_A_UGV_01_rcws_F) {
                    name = "UAV (UGV Stomper RCWS)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_uav.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_UGV_01_rcws_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

            };

            class Naval {
                name = "Naval";

                class GVAR(Boat_B_EUDF35_A_Assault_Boat_F) {
                    name = "Boat Team (Assault Boat)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_naval.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Assault_Boat_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Boat_B_EUDF35_A_Speedboat_Minigun_F) {
                    name = "Boat Team (Speedboat Minigun)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_naval.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Speedboat_Minigun_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

                class GVAR(Boat_B_EUDF35_A_SDV_01_F) {
                    name = "Boat Team (SDV)";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_naval.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_SDV_01_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Diver_F);
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                };

            };

            class Support {
                name = "Support";

                class GVAR(Support_B_EUDF35_A_Zamak_Fuel_F) {
                    name = "Zamak Fuel";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Zamak_Fuel_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Support_B_EUDF35_A_Zamak_Ammo_F) {
                    name = "Zamak Ammo";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Zamak_Ammo_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Support_B_EUDF35_A_Zamak_Repair_F) {
                    name = "Zamak Repair";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Zamak_Repair_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Support_B_EUDF35_A_Zamak_Medical_F) {
                    name = "Zamak Medical";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Zamak_Medical_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_MHMG_50_F) {
                    name = "M2 HMG .50 Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MHMG_50_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_MHMG_50_Raised_F) {
                    name = "M2 HMG .50 (Raised) Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_MHMG_50_Raised_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_HMG_01_A_F) {
                    name = "Mk30A HMG .50 Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_HMG_01_A_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_GMG_20_mm_F) {
                    name = "Mk32 GMG 20 mm Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_GMG_20_mm_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_GMG_20_mm_Raised_F) {
                    name = "Mk32 GMG 20 mm (Raised) Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_GMG_20_mm_Raised_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_GMG_01_A_F) {
                    name = "Mk32A GMG 20 mm Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_GMG_01_A_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_static_AT_F) {
                    name = "Static Titan Launcher (AT) [EUDF] Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_static_AT_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_static_AA_F) {
                    name = "Static Titan Launcher (AA) [EUDF] Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_static_AA_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_Static_Designator_01_F) {
                    name = "Remote Designator [EUDF] Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Static_Designator_01_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_Radar_System_01_F) {
                    name = "AN/MPQ-105 Radar Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Radar_System_01_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_SAM_System_03_F) {
                    name = "MIM-145 Defender Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_SAM_System_03_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

                class GVAR(Static_B_EUDF35_A_Mk6_Mortar_F) {
                    name = "Mk6 Mortar Team";
                    side = 1;
                    faction = QUOTE(ADDON);
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_support.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_Mk6_Mortar_F);
                        rank = "LIEUTENANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = QGVAR(B_EUDF35_A_support_MG_F);
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                };

            };

        };
    };
};
