#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QGVAR(E22_B_JC_W_SAM_system_01_F),
            QGVAR(E22_B_JC_W_AAA_System_01_F),
            QGVAR(E22_B_JC_W_Radar_system_01_F),
            QGVAR(Aegis_B_A_Heli_Transport_02_wdl_F),
            QGVAR(Aegis_B_T_support_CMort_RF),
            QGVAR(Atlas_B_A_Plane_Fighter_05_ard_F),
            QGVAR(Atlas_B_G_LT_01_AA_F),
            QGVAR(Atlas_B_G_LT_01_AT_F),
            QGVAR(Atlas_B_G_LT_01_cannon_F),
            QGVAR(Atlas_B_G_LT_01_scout_F),
            QGVAR(Atlas_B_G_MBT_03_cannon_F),
            QGVAR(Atlas_B_T_JSOC_F),
            QGVAR(Atlas_B_T_JSOC_JTAC_F),
            QGVAR(Atlas_B_T_JSOC_LAT_F),
            QGVAR(B_A_Plane_Transport_01_infantry_tna_F),
            QGVAR(B_A_Plane_Transport_01_vehicle_tna_F),
            QGVAR(B_Heli_Attack_01_dynamicLoadout_F),
            QGVAR(B_Heli_Attack_01_pylons_dynamicLoadout_F),
            QGVAR(B_Heli_EC_03_RF),
            QGVAR(B_Heli_EC_04_military_RF),
            QGVAR(B_Heli_Transport_01_F),
            QGVAR(B_Heli_Transport_01_pylons_F),
            QGVAR(B_Heli_Transport_01_unarmed_F),
            QGVAR(B_SDV_01_F),
            QGVAR(B_T_AFV_Wheeled_01_cannon_F),
            QGVAR(B_T_AFV_Wheeled_01_up_cannon_F),
            QGVAR(B_T_APC_Tracked_01_AA_F),
            QGVAR(B_T_APC_Tracked_01_rcws_F),
            QGVAR(B_T_Boat_Armed_01_minigun_F),
            QGVAR(B_T_Boat_Transport_01_F),
            QGVAR(B_T_Diver_Exp_F),
            QGVAR(B_T_Diver_F),
            QGVAR(B_T_Diver_TL_F),
            QGVAR(B_T_Engineer_F),
            QGVAR(B_T_MBT_01_arty_F),
            QGVAR(B_T_MBT_01_cannon_F),
            QGVAR(B_T_MBT_01_mlrs_F),
            QGVAR(B_T_MRAP_01_F),
            QGVAR(B_T_MRAP_01_gmg_F),
            QGVAR(B_T_Medic_F),
            QGVAR(B_T_RadioOperator_F),
            QGVAR(B_T_Recon_Exp_F),
            QGVAR(B_T_Recon_F),
            QGVAR(B_T_Recon_JTAC_F),
            QGVAR(B_T_Recon_LAT_F),
            QGVAR(B_T_Recon_M_F),
            QGVAR(B_T_Recon_Medic_F),
            QGVAR(B_T_Recon_Sharpshooter_F),
            QGVAR(B_T_Recon_TL_F),
            QGVAR(B_T_Sniper_F),
            QGVAR(B_T_Soldier_AAA_F),
            QGVAR(B_T_Soldier_AAT_F),
            QGVAR(B_T_Soldier_AA_F),
            QGVAR(B_T_Soldier_AR_F),
            QGVAR(B_T_Soldier_AT_F),
            QGVAR(B_T_Soldier_A_F),
            QGVAR(B_T_Soldier_Exp_F),
            QGVAR(B_T_Soldier_F),
            QGVAR(B_T_Soldier_GL_F),
            QGVAR(B_T_Soldier_LAT2_F),
            QGVAR(B_T_Soldier_LAT_F),
            QGVAR(B_T_Soldier_Repair_F),
            QGVAR(B_T_Soldier_SL_F),
            QGVAR(B_T_Soldier_TL_F),
            QGVAR(B_T_Spotter_F),
            QGVAR(B_T_Support_AMG_F),
            QGVAR(B_T_Support_AMort_F),
            QGVAR(B_T_Support_GMG_F),
            QGVAR(B_T_Support_MG_F),
            QGVAR(B_T_Support_Mort_F),
            QGVAR(B_T_Truck_01_transport_F),
            QGVAR(B_T_soldier_M_F),
            QGVAR(CF_B_AFV_Wheeled_01_cannon_F),
            QGVAR(CF_B_AFV_Wheeled_01_up_cannon_F),
            QGVAR(CF_B_AH99J_EF),
            QGVAR(CF_B_APC_Tracked_01_AA_F),
            QGVAR(CF_B_APC_Tracked_01_CRV_F),
            QGVAR(CF_B_APC_Tracked_01_rcws_F),
            QGVAR(CF_B_A_Heli_Attack_01_dynamicLoadout_F),
            QGVAR(CF_B_A_Heli_Attack_01_pylons_dynamicLoadout_F),
            QGVAR(CF_B_A_Heli_Attack_03_F),
            QGVAR(CF_B_A_JSOC_F),
            QGVAR(CF_B_A_JSOC_JTAC_F),
            QGVAR(CF_B_A_JSOC_LAT_F),
            QGVAR(CF_B_A_JSOC_UAV_F),
            QGVAR(CF_B_A_JSOC_UAV_lxWS),
            QGVAR(CF_B_CombatBoat_AT_EF),
            QGVAR(CF_B_CombatBoat_HMG_EF),
            QGVAR(CF_B_CombatBoat_Unarmed_EF),
            QGVAR(CF_B_Crew_F),
            QGVAR(CF_B_Engineer_F),
            QGVAR(CF_B_Fighter_Pilot_F),
            QGVAR(CF_B_GMG_01_F),
            QGVAR(CF_B_GMG_01_high_F),
            QGVAR(CF_B_HMG_01_A_F),
            QGVAR(CF_B_HMG_01_F),
            QGVAR(CF_B_HMG_01_high_F),
            QGVAR(CF_B_HMG_02_F),
            QGVAR(CF_B_HMG_02_high_F),
            QGVAR(CF_B_HeavyGunner_F),
            QGVAR(CF_B_Heli_Light_01_dynamicLoadout_F),
            QGVAR(CF_B_Heli_Transport_01_F),
            QGVAR(CF_B_Heli_Transport_01_pylons_F),
            QGVAR(CF_B_Heli_light_01_F),
            QGVAR(CF_B_Helicrew_F),
            QGVAR(CF_B_Helipilot_F),
            QGVAR(CF_B_LSV_01_AT_F),
            QGVAR(CF_B_LSV_01_armed_F),
            QGVAR(CF_B_LSV_01_light_F),
            QGVAR(CF_B_LSV_01_unarmed_F),
            QGVAR(CF_B_MBT_01_TUSK_F),
            QGVAR(CF_B_MBT_01_arty_F),
            QGVAR(CF_B_MBT_01_cannon_F),
            QGVAR(CF_B_MBT_01_mlrs_F),
            QGVAR(CF_B_MRAP_01_F),
            QGVAR(CF_B_MRAP_01_gmg_F),
            QGVAR(CF_B_MRAP_01_hmg_F),
            QGVAR(CF_B_Medic_F),
            QGVAR(CF_B_Mortar_01_F),
            QGVAR(CF_B_Officer_F),
            QGVAR(CF_B_Pilot_F),
            QGVAR(CF_B_Plane_CAS_01_dynamicLoadout_F),
            QGVAR(CF_B_Plane_Fighter_01_F),
            QGVAR(CF_B_Plane_Fighter_01_Stealth_F),
            QGVAR(CF_B_Plane_Fighter_05_F),
            QGVAR(CF_B_Plane_Fighter_05_Stealth_F),
            QGVAR(CF_B_RadioOperator_F),
            QGVAR(CF_B_Recon_AR_F),
            QGVAR(CF_B_Recon_CQ_F),
            QGVAR(CF_B_Recon_Exp_F),
            QGVAR(CF_B_Recon_F),
            QGVAR(CF_B_Recon_GL_F),
            QGVAR(CF_B_Recon_JTAC_F),
            QGVAR(CF_B_Recon_LAT_F),
            QGVAR(CF_B_Recon_MG_F),
            QGVAR(CF_B_Recon_M_F),
            QGVAR(CF_B_Recon_Medic_F),
            QGVAR(CF_B_Recon_Sharpshooter_F),
            QGVAR(CF_B_Recon_TL_F),
            QGVAR(CF_B_Sharpshooter_F),
            QGVAR(CF_B_Sniper_F),
            QGVAR(CF_B_Soldier_AAA_F),
            QGVAR(CF_B_Soldier_AAR_F),
            QGVAR(CF_B_Soldier_AAT_F),
            QGVAR(CF_B_Soldier_AA_F),
            QGVAR(CF_B_Soldier_AR_F),
            QGVAR(CF_B_Soldier_AT_F),
            QGVAR(CF_B_Soldier_A_F),
            QGVAR(CF_B_Soldier_CBRN_F),
            QGVAR(CF_B_Soldier_CQ_F),
            QGVAR(CF_B_Soldier_Exp_F),
            QGVAR(CF_B_Soldier_F),
            QGVAR(CF_B_Soldier_GL_F),
            QGVAR(CF_B_Soldier_LAT2_F),
            QGVAR(CF_B_Soldier_LAT_F),
            QGVAR(CF_B_Soldier_Lite_F),
            QGVAR(CF_B_Soldier_MG_F),
            QGVAR(CF_B_Soldier_PG_F),
            QGVAR(CF_B_Soldier_Repair_F),
            QGVAR(CF_B_Soldier_SL_F),
            QGVAR(CF_B_Soldier_TL_F),
            QGVAR(CF_B_Soldier_UAV_F),
            QGVAR(CF_B_Soldier_unarmed_F),
            QGVAR(CF_B_Spotter_F),
            QGVAR(CF_B_Static_AA_F),
            QGVAR(CF_B_Static_AT_F),
            QGVAR(CF_B_Static_Designator_01_F),
            QGVAR(CF_B_Support_AMG_F),
            QGVAR(CF_B_Support_AMort_F),
            QGVAR(CF_B_Support_GMG_F),
            QGVAR(CF_B_Support_MG_F),
            QGVAR(CF_B_Support_Mort_F),
            QGVAR(CF_B_Transport_03_F),
            QGVAR(CF_B_Transport_03_unarmed_F),
            QGVAR(CF_B_Truck_01_Repair_F),
            QGVAR(CF_B_Truck_01_ammo_F),
            QGVAR(CF_B_Truck_01_box_F),
            QGVAR(CF_B_Truck_01_cargo_F),
            QGVAR(CF_B_Truck_01_covered_F),
            QGVAR(CF_B_Truck_01_flatbed_F),
            QGVAR(CF_B_Truck_01_fuel_F),
            QGVAR(CF_B_Truck_01_medical_F),
            QGVAR(CF_B_Truck_01_mover_F),
            QGVAR(CF_B_Truck_01_transport_F),
            QGVAR(CF_B_UAV_01_F),
            QGVAR(CF_B_UAV_02_lxWS),
            QGVAR(CF_B_UAV_05_F),
            QGVAR(CF_B_UGV_02_Demining_F),
            QGVAR(CF_B_VTOL_01_armed_F),
            QGVAR(CF_B_VTOL_01_infantry_F),
            QGVAR(CF_B_VTOL_01_vehicle_F),
            QGVAR(CF_B_soldier_M_F),
            QGVAR(CF_B_soldier_UAV_02_LxWS_F),
            QGVAR(CF_B_soldier_UGV_02_Demining_F),
            QGVAR(CF_B_support_CMort_RF),
            QGVAR(EF_B_AH99J_NATO),
            QGVAR(qav_challenger2),
            QGVAR(qav_challenger2_e),
            QGVAR(rev_B_Plane_Fighter_04_F),
            QGVAR(C_IDAP_UAV_06_antimine_backpack_F),
            QGVAR(C_IDAP_UAV_06_antimine_F),
            QGVAR(B_Heli_Transport_01_medevac_F),
            QGVAR(Drone_Operator)
        };
        weapons[] = {QGVAR(CF_arifle_MXC_arc_F_snds),QGVAR(LMG_Mk200_black_RCO_LP_F_snds),QGVAR(MMG_02_black_RCO_LP_F_snds),QGVAR(SMG_01_black_Holo_F_snds),QGVAR(arifle_MXC_arc_ACO_F_snds),QGVAR(arifle_MXC_arc_ACO_Pointer_F_snds),QGVAR(arifle_MXC_arc_ACO_fl_F_snds),QGVAR(arifle_MXC_arc_Holo_Pointer_F_snds),QGVAR(arifle_MXC_khk_ACO_Pointer_F_snds),QGVAR(arifle_MXC_khk_Holo_Pointer_F_snds),QGVAR(arifle_MXM_arc_SOS_Pointer_F_snds),QGVAR(arifle_MXM_khk_MOS_Pointer_Bipod_F_snds),QGVAR(arifle_MX_GL_arc_ACO_Pointer_F_snds),QGVAR(arifle_MX_GL_arc_Hamr_Pointer_F_snds),QGVAR(arifle_MX_GL_khk_ACO_Pointer_F_snds),QGVAR(arifle_MX_GL_khk_Hamr_Pointer_F_snds),QGVAR(arifle_MX_SW_arc_Hamr_pointer_F_snds),QGVAR(arifle_MX_SW_khk_Hamr_Pointer_F_snds),QGVAR(arifle_MX_arc_ACO_Pointer_F_snds),QGVAR(arifle_MX_arc_Hamr_Pointer_F_snds),QGVAR(arifle_MX_arc_Holo_Pointer_F_snds),QGVAR(arifle_MX_khk_ACO_Pointer_F_snds),QGVAR(arifle_MX_khk_Hamr_Pointer_F_snds),QGVAR(arifle_MX_khk_Holo_Pointer_F_snds),QGVAR(srifle_DMR_03_AMS_LP_BI_F_snds),QGVAR(srifle_LRR_LRPS_F_snds),QGVAR(srifle_LRR_tna_LRPS_F_snds)};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main", "ghost_uniform", "ghost_vehicle"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
