#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_EUDF_arc_Aegis_B_A_Heli_Transport_02_wdl_F",
            "ghost_EUDF_arc_Aegis_B_T_support_CMort_RF",
            "ghost_EUDF_arc_Atlas_B_A_Plane_Fighter_05_ard_F",
            "ghost_EUDF_arc_Atlas_B_G_LT_01_AA_F",
            "ghost_EUDF_arc_Atlas_B_G_LT_01_AT_F",
            "ghost_EUDF_arc_Atlas_B_G_LT_01_cannon_F",
            "ghost_EUDF_arc_Atlas_B_G_LT_01_scout_F",
            "ghost_EUDF_arc_Atlas_B_G_MBT_03_cannon_F",
            "ghost_EUDF_arc_Atlas_B_T_JSOC_F",
            "ghost_EUDF_arc_Atlas_B_T_JSOC_JTAC_F",
            "ghost_EUDF_arc_Atlas_B_T_JSOC_LAT_F",
            "ghost_EUDF_arc_B_A_Plane_Transport_01_infantry_tna_F",
            "ghost_EUDF_arc_B_A_Plane_Transport_01_vehicle_tna_F",
            "ghost_EUDF_arc_B_Heli_Attack_01_dynamicLoadout_F",
            "ghost_EUDF_arc_B_Heli_Attack_01_pylons_dynamicLoadout_F",
            "ghost_EUDF_arc_B_Heli_EC_03_RF",
            "ghost_EUDF_arc_B_Heli_EC_04_military_RF",
            "ghost_EUDF_arc_B_Heli_Transport_01_F",
            "ghost_EUDF_arc_B_Heli_Transport_01_pylons_F",
            "ghost_EUDF_arc_B_Heli_Transport_01_unarmed_F",
            "ghost_EUDF_arc_B_SDV_01_F",
            "ghost_EUDF_arc_B_T_AFV_Wheeled_01_cannon_F",
            "ghost_EUDF_arc_B_T_AFV_Wheeled_01_up_cannon_F",
            "ghost_EUDF_arc_B_T_APC_Tracked_01_AA_F",
            "ghost_EUDF_arc_B_T_APC_Tracked_01_rcws_F",
            "ghost_EUDF_arc_B_T_Boat_Armed_01_minigun_F",
            "ghost_EUDF_arc_B_T_Boat_Transport_01_F",
            "ghost_EUDF_arc_B_T_Diver_Exp_F",
            "ghost_EUDF_arc_B_T_Diver_F",
            "ghost_EUDF_arc_B_T_Diver_TL_F",
            "ghost_EUDF_arc_B_T_Engineer_F",
            "ghost_EUDF_arc_B_T_MBT_01_arty_F",
            "ghost_EUDF_arc_B_T_MBT_01_cannon_F",
            "ghost_EUDF_arc_B_T_MBT_01_mlrs_F",
            "ghost_EUDF_arc_B_T_MRAP_01_F",
            "ghost_EUDF_arc_B_T_MRAP_01_gmg_F",
            "ghost_EUDF_arc_B_T_Medic_F",
            "ghost_EUDF_arc_B_T_RadioOperator_F",
            "ghost_EUDF_arc_B_T_Recon_Exp_F",
            "ghost_EUDF_arc_B_T_Recon_F",
            "ghost_EUDF_arc_B_T_Recon_JTAC_F",
            "ghost_EUDF_arc_B_T_Recon_LAT_F",
            "ghost_EUDF_arc_B_T_Recon_M_F",
            "ghost_EUDF_arc_B_T_Recon_Medic_F",
            "ghost_EUDF_arc_B_T_Recon_Sharpshooter_F",
            "ghost_EUDF_arc_B_T_Recon_TL_F",
            "ghost_EUDF_arc_B_T_Sniper_F",
            "ghost_EUDF_arc_B_T_Soldier_AAA_F",
            "ghost_EUDF_arc_B_T_Soldier_AAT_F",
            "ghost_EUDF_arc_B_T_Soldier_AA_F",
            "ghost_EUDF_arc_B_T_Soldier_AR_F",
            "ghost_EUDF_arc_B_T_Soldier_AT_F",
            "ghost_EUDF_arc_B_T_Soldier_A_F",
            "ghost_EUDF_arc_B_T_Soldier_Exp_F",
            "ghost_EUDF_arc_B_T_Soldier_F",
            "ghost_EUDF_arc_B_T_Soldier_GL_F",
            "ghost_EUDF_arc_B_T_Soldier_LAT2_F",
            "ghost_EUDF_arc_B_T_Soldier_LAT_F",
            "ghost_EUDF_arc_B_T_Soldier_Repair_F",
            "ghost_EUDF_arc_B_T_Soldier_SL_F",
            "ghost_EUDF_arc_B_T_Soldier_TL_F",
            "ghost_EUDF_arc_B_T_Spotter_F",
            "ghost_EUDF_arc_B_T_Support_AMG_F",
            "ghost_EUDF_arc_B_T_Support_AMort_F",
            "ghost_EUDF_arc_B_T_Support_GMG_F",
            "ghost_EUDF_arc_B_T_Support_MG_F",
            "ghost_EUDF_arc_B_T_Support_Mort_F",
            "ghost_EUDF_arc_B_T_Truck_01_transport_F",
            "ghost_EUDF_arc_B_T_soldier_M_F",
            "ghost_EUDF_arc_CF_B_AFV_Wheeled_01_cannon_F",
            "ghost_EUDF_arc_CF_B_AFV_Wheeled_01_up_cannon_F",
            "ghost_EUDF_arc_CF_B_AH99J_EF",
            "ghost_EUDF_arc_CF_B_APC_Tracked_01_AA_F",
            "ghost_EUDF_arc_CF_B_APC_Tracked_01_CRV_F",
            "ghost_EUDF_arc_CF_B_APC_Tracked_01_rcws_F",
            "ghost_EUDF_arc_CF_B_A_Heli_Attack_01_dynamicLoadout_F",
            "ghost_EUDF_arc_CF_B_A_Heli_Attack_01_pylons_dynamicLoadout_F",
            "ghost_EUDF_arc_CF_B_A_Heli_Attack_03_F",
            "ghost_EUDF_arc_CF_B_A_JSOC_F",
            "ghost_EUDF_arc_CF_B_A_JSOC_JTAC_F",
            "ghost_EUDF_arc_CF_B_A_JSOC_LAT_F",
            "ghost_EUDF_arc_CF_B_A_JSOC_UAV_F",
            "ghost_EUDF_arc_CF_B_A_JSOC_UAV_lxWS",
            "ghost_EUDF_arc_CF_B_CombatBoat_AT_EF",
            "ghost_EUDF_arc_CF_B_CombatBoat_HMG_EF",
            "ghost_EUDF_arc_CF_B_CombatBoat_Unarmed_EF",
            "ghost_EUDF_arc_CF_B_Crew_F",
            "ghost_EUDF_arc_CF_B_Engineer_F",
            "ghost_EUDF_arc_CF_B_Fighter_Pilot_F",
            "ghost_EUDF_arc_CF_B_GMG_01_F",
            "ghost_EUDF_arc_CF_B_GMG_01_high_F",
            "ghost_EUDF_arc_CF_B_HMG_01_A_F",
            "ghost_EUDF_arc_CF_B_HMG_01_F",
            "ghost_EUDF_arc_CF_B_HMG_01_high_F",
            "ghost_EUDF_arc_CF_B_HMG_02_F",
            "ghost_EUDF_arc_CF_B_HMG_02_high_F",
            "ghost_EUDF_arc_CF_B_HeavyGunner_F",
            "ghost_EUDF_arc_CF_B_Heli_Light_01_dynamicLoadout_F",
            "ghost_EUDF_arc_CF_B_Heli_Transport_01_F",
            "ghost_EUDF_arc_CF_B_Heli_Transport_01_pylons_F",
            "ghost_EUDF_arc_CF_B_Heli_light_01_F",
            "ghost_EUDF_arc_CF_B_Helicrew_F",
            "ghost_EUDF_arc_CF_B_Helipilot_F",
            "ghost_EUDF_arc_CF_B_LSV_01_AT_F",
            "ghost_EUDF_arc_CF_B_LSV_01_armed_F",
            "ghost_EUDF_arc_CF_B_LSV_01_light_F",
            "ghost_EUDF_arc_CF_B_LSV_01_unarmed_F",
            "ghost_EUDF_arc_CF_B_MBT_01_TUSK_F",
            "ghost_EUDF_arc_CF_B_MBT_01_arty_F",
            "ghost_EUDF_arc_CF_B_MBT_01_cannon_F",
            "ghost_EUDF_arc_CF_B_MBT_01_mlrs_F",
            "ghost_EUDF_arc_CF_B_MRAP_01_AT_EF",
            "ghost_EUDF_arc_CF_B_MRAP_01_F",
            "ghost_EUDF_arc_CF_B_MRAP_01_FSV_EF",
            "ghost_EUDF_arc_CF_B_MRAP_01_LAAD_EF",
            "ghost_EUDF_arc_CF_B_MRAP_01_gmg_F",
            "ghost_EUDF_arc_CF_B_MRAP_01_hmg_F",
            "ghost_EUDF_arc_CF_B_Medic_F",
            "ghost_EUDF_arc_CF_B_Mortar_01_F",
            "ghost_EUDF_arc_CF_B_Officer_F",
            "ghost_EUDF_arc_CF_B_Pilot_F",
            "ghost_EUDF_arc_CF_B_Plane_CAS_01_dynamicLoadout_F",
            "ghost_EUDF_arc_CF_B_Plane_Fighter_01_F",
            "ghost_EUDF_arc_CF_B_Plane_Fighter_01_Stealth_F",
            "ghost_EUDF_arc_CF_B_Plane_Fighter_05_F",
            "ghost_EUDF_arc_CF_B_Plane_Fighter_05_Stealth_F",
            "ghost_EUDF_arc_CF_B_RadioOperator_F",
            "ghost_EUDF_arc_CF_B_Recon_AR_F",
            "ghost_EUDF_arc_CF_B_Recon_CQ_F",
            "ghost_EUDF_arc_CF_B_Recon_Exp_F",
            "ghost_EUDF_arc_CF_B_Recon_F",
            "ghost_EUDF_arc_CF_B_Recon_GL_F",
            "ghost_EUDF_arc_CF_B_Recon_JTAC_F",
            "ghost_EUDF_arc_CF_B_Recon_LAT_F",
            "ghost_EUDF_arc_CF_B_Recon_MG_F",
            "ghost_EUDF_arc_CF_B_Recon_M_F",
            "ghost_EUDF_arc_CF_B_Recon_Medic_F",
            "ghost_EUDF_arc_CF_B_Recon_Sharpshooter_F",
            "ghost_EUDF_arc_CF_B_Recon_TL_F",
            "ghost_EUDF_arc_CF_B_Sharpshooter_F",
            "ghost_EUDF_arc_CF_B_Sniper_F",
            "ghost_EUDF_arc_CF_B_Soldier_AAA_F",
            "ghost_EUDF_arc_CF_B_Soldier_AAR_F",
            "ghost_EUDF_arc_CF_B_Soldier_AAT_F",
            "ghost_EUDF_arc_CF_B_Soldier_AA_F",
            "ghost_EUDF_arc_CF_B_Soldier_AR_F",
            "ghost_EUDF_arc_CF_B_Soldier_AT_F",
            "ghost_EUDF_arc_CF_B_Soldier_A_F",
            "ghost_EUDF_arc_CF_B_Soldier_CBRN_F",
            "ghost_EUDF_arc_CF_B_Soldier_CQ_F",
            "ghost_EUDF_arc_CF_B_Soldier_Exp_F",
            "ghost_EUDF_arc_CF_B_Soldier_F",
            "ghost_EUDF_arc_CF_B_Soldier_GL_F",
            "ghost_EUDF_arc_CF_B_Soldier_LAT2_F",
            "ghost_EUDF_arc_CF_B_Soldier_LAT_F",
            "ghost_EUDF_arc_CF_B_Soldier_Lite_F",
            "ghost_EUDF_arc_CF_B_Soldier_MG_F",
            "ghost_EUDF_arc_CF_B_Soldier_PG_F",
            "ghost_EUDF_arc_CF_B_Soldier_Repair_F",
            "ghost_EUDF_arc_CF_B_Soldier_SL_F",
            "ghost_EUDF_arc_CF_B_Soldier_TL_F",
            "ghost_EUDF_arc_CF_B_Soldier_UAV_F",
            "ghost_EUDF_arc_CF_B_Soldier_unarmed_F",
            "ghost_EUDF_arc_CF_B_Spotter_F",
            "ghost_EUDF_arc_CF_B_Static_AA_F",
            "ghost_EUDF_arc_CF_B_Static_AT_F",
            "ghost_EUDF_arc_CF_B_Static_Designator_01_F",
            "ghost_EUDF_arc_CF_B_Support_AMG_F",
            "ghost_EUDF_arc_CF_B_Support_AMort_F",
            "ghost_EUDF_arc_CF_B_Support_GMG_F",
            "ghost_EUDF_arc_CF_B_Support_MG_F",
            "ghost_EUDF_arc_CF_B_Support_Mort_F",
            "ghost_EUDF_arc_CF_B_Transport_03_F",
            "ghost_EUDF_arc_CF_B_Transport_03_unarmed_F",
            "ghost_EUDF_arc_CF_B_Truck_01_Repair_F",
            "ghost_EUDF_arc_CF_B_Truck_01_ammo_F",
            "ghost_EUDF_arc_CF_B_Truck_01_box_F",
            "ghost_EUDF_arc_CF_B_Truck_01_cargo_F",
            "ghost_EUDF_arc_CF_B_Truck_01_covered_F",
            "ghost_EUDF_arc_CF_B_Truck_01_flatbed_F",
            "ghost_EUDF_arc_CF_B_Truck_01_fuel_F",
            "ghost_EUDF_arc_CF_B_Truck_01_medical_F",
            "ghost_EUDF_arc_CF_B_Truck_01_mover_F",
            "ghost_EUDF_arc_CF_B_Truck_01_transport_F",
            "ghost_EUDF_arc_CF_B_UAV_01_F",
            "ghost_EUDF_arc_CF_B_UAV_02_lxWS",
            "ghost_EUDF_arc_CF_B_UAV_05_F",
            "ghost_EUDF_arc_CF_B_UGV_02_Demining_F",
            "ghost_EUDF_arc_CF_B_VTOL_01_armed_F",
            "ghost_EUDF_arc_CF_B_VTOL_01_infantry_F",
            "ghost_EUDF_arc_CF_B_VTOL_01_vehicle_F",
            "ghost_EUDF_arc_CF_B_soldier_M_F",
            "ghost_EUDF_arc_CF_B_soldier_UAV_02_LxWS_F",
            "ghost_EUDF_arc_CF_B_soldier_UGV_02_Demining_F",
            "ghost_EUDF_arc_CF_B_support_CMort_RF",
            "ghost_EUDF_arc_EF_B_AH99J_NATO",
            "ghost_EUDF_arc_rev_B_Plane_Fighter_04_F",
            "ghost_EUDF_arc_C_IDAP_UAV_06_antimine_backpack_F",
            "ghost_EUDF_arc_C_IDAP_UAV_06_antimine_F",
            "ghost_EUDF_arc_B_Heli_Transport_01_medevac_F",
            "ghost_EUDF_arc_Drone_Operator"
        };
        weapons[] = {"ghost_EUDF_arc_CF_arifle_MXC_arc_F_snds","ghost_EUDF_arc_LMG_Mk200_black_RCO_LP_F_snds","ghost_EUDF_arc_MMG_02_black_RCO_LP_F_snds","ghost_EUDF_arc_SMG_01_black_Holo_F_snds","ghost_EUDF_arc_arifle_MXC_arc_ACO_F_snds","ghost_EUDF_arc_arifle_MXC_arc_ACO_Pointer_F_snds","ghost_EUDF_arc_arifle_MXC_arc_ACO_fl_F_snds","ghost_EUDF_arc_arifle_MXC_arc_Holo_Pointer_F_snds","ghost_EUDF_arc_arifle_MXC_khk_ACO_Pointer_F_snds","ghost_EUDF_arc_arifle_MXC_khk_Holo_Pointer_F_snds","ghost_EUDF_arc_arifle_MXM_arc_SOS_Pointer_F_snds","ghost_EUDF_arc_arifle_MXM_khk_MOS_Pointer_Bipod_F_snds","ghost_EUDF_arc_arifle_MX_GL_arc_ACO_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_GL_arc_Hamr_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_GL_khk_ACO_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_GL_khk_Hamr_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_SW_arc_Hamr_pointer_F_snds","ghost_EUDF_arc_arifle_MX_SW_khk_Hamr_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_arc_ACO_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_arc_Hamr_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_arc_Holo_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_khk_ACO_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_khk_Hamr_Pointer_F_snds","ghost_EUDF_arc_arifle_MX_khk_Holo_Pointer_F_snds","ghost_EUDF_arc_srifle_DMR_03_AMS_LP_BI_F_snds","ghost_EUDF_arc_srifle_LRR_LRPS_F_snds","ghost_EUDF_arc_srifle_LRR_tna_LRPS_F_snds"};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
