#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "ghost_US_wdl_Aegis_B_W_AH99J_EF",
            "ghost_US_wdl_Aegis_B_W_CombatBoat_AT_EF",
            "ghost_US_wdl_Aegis_B_W_CombatBoat_HMG_EF",
            "ghost_US_wdl_Aegis_B_W_CombatBoat_Unarmed_EF",
            "ghost_US_wdl_Aegis_B_W_CommandoMortar_RF",
            "ghost_US_wdl_Aegis_B_W_Heli_Attack_03_F",
            "ghost_US_wdl_Aegis_B_W_Heli_EC_03_RF",
            "ghost_US_wdl_Aegis_B_W_Heli_EC_04_military_RF",
            "ghost_US_wdl_Aegis_B_W_MRAP_01_AT_EF",
            "ghost_US_wdl_Aegis_B_W_MRAP_01_FSV_EF",
            "ghost_US_wdl_Aegis_B_W_MRAP_01_LAAD_EF",
            "ghost_US_wdl_Aegis_B_W_TwinMortar_RF",
            "ghost_US_wdl_Aegis_B_W_UAV_02_lxWS",
            "ghost_US_wdl_Aegis_B_W_support_CMort_RF",
            "ghost_US_wdl_Atlas_B_W_JSOC_AR_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_Exp_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_GL_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_JTAC_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_LAT_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_M_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_Medic_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_SL_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_Sharpshooter_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_TL_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_UAV_F",
            "ghost_US_wdl_Atlas_B_W_JSOC_UAV_lxWS",
            "ghost_US_wdl_B_W_AFV_Wheeled_01_cannon_F",
            "ghost_US_wdl_B_W_AFV_Wheeled_01_up_cannon_F",
            "ghost_US_wdl_B_W_APC_Tracked_01_AA_F",
            "ghost_US_wdl_B_W_APC_Tracked_01_CRV_F",
            "ghost_US_wdl_B_W_APC_Tracked_01_rcws_F",
            "ghost_US_wdl_B_W_APC_Wheeled_01_atgm_lxWS_v2",
            "ghost_US_wdl_B_W_APC_Wheeled_01_cannon_F",
            "ghost_US_wdl_B_W_APC_Wheeled_01_cannon_v2_F",
            "ghost_US_wdl_B_W_APC_Wheeled_01_command_lxWS",
            "ghost_US_wdl_B_W_APC_Wheeled_01_medical_F",
            "ghost_US_wdl_B_W_APC_Wheeled_01_mortar_lxWS",
            "ghost_US_wdl_B_W_Crew_F",
            "ghost_US_wdl_B_W_Engineer_F",
            "ghost_US_wdl_B_W_Fighter_Pilot_F",
            "ghost_US_wdl_B_W_GMG_01_A_F",
            "ghost_US_wdl_B_W_GMG_01_F",
            "ghost_US_wdl_B_W_GMG_01_high_F",
            "ghost_US_wdl_B_W_HMG_01_A_F",
            "ghost_US_wdl_B_W_HMG_01_F",
            "ghost_US_wdl_B_W_HMG_01_high_F",
            "ghost_US_wdl_B_W_HMG_02_F",
            "ghost_US_wdl_B_W_HMG_02_high_F",
            "ghost_US_wdl_B_W_HeavyGunner_F",
            "ghost_US_wdl_B_W_Heli_Attack_01_dynamicLoadout_F",
            "ghost_US_wdl_B_W_Heli_Light_01_dynamicLoadout_F",
            "ghost_US_wdl_B_W_Heli_Transport_01_F",
            "ghost_US_wdl_B_W_Heli_Transport_01_medevac_F",
            "ghost_US_wdl_B_W_Heli_Transport_03_F",
            "ghost_US_wdl_B_W_Heli_Transport_03_unarmed_F",
            "ghost_US_wdl_B_W_Heli_light_01_F",
            "ghost_US_wdl_B_W_Helicrew_F",
            "ghost_US_wdl_B_W_Helipilot_F",
            "ghost_US_wdl_B_W_LSV_01_AT_F",
            "ghost_US_wdl_B_W_LSV_01_armed_F",
            "ghost_US_wdl_B_W_LSV_01_light_F",
            "ghost_US_wdl_B_W_LSV_01_unarmed_F",
            "ghost_US_wdl_B_W_MBT_01_TUSK_F",
            "ghost_US_wdl_B_W_MBT_01_arty_F",
            "ghost_US_wdl_B_W_MBT_01_cannon_F",
            "ghost_US_wdl_B_W_MBT_01_mlrs_F",
            "ghost_US_wdl_B_W_MRAP_01_F",
            "ghost_US_wdl_B_W_MRAP_01_gmg_F",
            "ghost_US_wdl_B_W_MRAP_01_hmg_F",
            "ghost_US_wdl_B_W_Medic_F",
            "ghost_US_wdl_B_W_Mortar_01_F",
            "ghost_US_wdl_B_W_Officer_F",
            "ghost_US_wdl_B_W_Pilot_F",
            "ghost_US_wdl_B_W_Plane_CAS_01_dynamicLoadout_F",
            "ghost_US_wdl_B_W_Plane_Fighter_01_F",
            "ghost_US_wdl_B_W_Plane_Fighter_01_Stealth_F",
            "ghost_US_wdl_B_W_Plane_Fighter_05_F",
            "ghost_US_wdl_B_W_Plane_Fighter_05_Stealth_F",
            "ghost_US_wdl_B_W_Quadbike_01_F",
            "ghost_US_wdl_B_W_Radar_System_01_F",
            "ghost_US_wdl_B_W_RadioOperator_F",
            "ghost_US_wdl_B_W_Recon_AR_F",
            "ghost_US_wdl_B_W_Recon_CQ_F",
            "ghost_US_wdl_B_W_Recon_Exp_F",
            "ghost_US_wdl_B_W_Recon_F",
            "ghost_US_wdl_B_W_Recon_GL_F",
            "ghost_US_wdl_B_W_Recon_JTAC_F",
            "ghost_US_wdl_B_W_Recon_LAT_F",
            "ghost_US_wdl_B_W_Recon_MG_F",
            "ghost_US_wdl_B_W_Recon_M_F",
            "ghost_US_wdl_B_W_Recon_Medic_F",
            "ghost_US_wdl_B_W_Recon_Sharpshooter_F",
            "ghost_US_wdl_B_W_Recon_TL_F",
            "ghost_US_wdl_B_W_SAM_System_03_F",
            "ghost_US_wdl_B_W_Sharpshooter_F",
            "ghost_US_wdl_B_W_Sniper_F",
            "ghost_US_wdl_B_W_Soldier_AAA_F",
            "ghost_US_wdl_B_W_Soldier_AAR_F",
            "ghost_US_wdl_B_W_Soldier_AAT_F",
            "ghost_US_wdl_B_W_Soldier_AA_F",
            "ghost_US_wdl_B_W_Soldier_AR_F",
            "ghost_US_wdl_B_W_Soldier_AT_F",
            "ghost_US_wdl_B_W_Soldier_A_F",
            "ghost_US_wdl_B_W_Soldier_CBRN_F",
            "ghost_US_wdl_B_W_Soldier_CQ_F",
            "ghost_US_wdl_B_W_Soldier_Exp_F",
            "ghost_US_wdl_B_W_Soldier_F",
            "ghost_US_wdl_B_W_Soldier_GL_F",
            "ghost_US_wdl_B_W_Soldier_LAT2_F",
            "ghost_US_wdl_B_W_Soldier_LAT_F",
            "ghost_US_wdl_B_W_Soldier_Lite_F",
            "ghost_US_wdl_B_W_Soldier_MG_F",
            "ghost_US_wdl_B_W_Soldier_PG_F",
            "ghost_US_wdl_B_W_Soldier_Repair_F",
            "ghost_US_wdl_B_W_Soldier_SL_F",
            "ghost_US_wdl_B_W_Soldier_TL_F",
            "ghost_US_wdl_B_W_Soldier_UAV_F",
            "ghost_US_wdl_B_W_Soldier_unarmed_F",
            "ghost_US_wdl_B_W_Spotter_F",
            "ghost_US_wdl_B_W_Static_AA_F",
            "ghost_US_wdl_B_W_Static_AT_F",
            "ghost_US_wdl_B_W_Static_Designator_01_F",
            "ghost_US_wdl_B_W_Support_AMG_F",
            "ghost_US_wdl_B_W_Support_AMort_F",
            "ghost_US_wdl_B_W_Support_GMG_F",
            "ghost_US_wdl_B_W_Support_MG_F",
            "ghost_US_wdl_B_W_Support_Mort_F",
            "ghost_US_wdl_B_W_Survivor_F",
            "ghost_US_wdl_B_W_Truck_01_Repair_F",
            "ghost_US_wdl_B_W_Truck_01_ammo_F",
            "ghost_US_wdl_B_W_Truck_01_box_F",
            "ghost_US_wdl_B_W_Truck_01_cargo_F",
            "ghost_US_wdl_B_W_Truck_01_covered_F",
            "ghost_US_wdl_B_W_Truck_01_flatbed_F",
            "ghost_US_wdl_B_W_Truck_01_fuel_F",
            "ghost_US_wdl_B_W_Truck_01_medical_F",
            "ghost_US_wdl_B_W_Truck_01_mover_F",
            "ghost_US_wdl_B_W_Truck_01_transport_F",
            "ghost_US_wdl_B_W_UAV_01_F",
            "ghost_US_wdl_B_W_UAV_02_dynamicLoadout_F",
            "ghost_US_wdl_B_W_UAV_03_dynamicLoadout_F",
            "ghost_US_wdl_B_W_UAV_05_F",
            "ghost_US_wdl_B_W_UAV_06_F",
            "ghost_US_wdl_B_W_UAV_06_medical_F",
            "ghost_US_wdl_B_W_UGV_01_F",
            "ghost_US_wdl_B_W_UGV_01_medical_F",
            "ghost_US_wdl_B_W_UGV_01_rcws_F",
            "ghost_US_wdl_B_W_UGV_02_Demining_F",
            "ghost_US_wdl_B_W_VTOL_01_armed_F",
            "ghost_US_wdl_B_W_VTOL_01_infantry_F",
            "ghost_US_wdl_B_W_VTOL_01_vehicle_F",
            "ghost_US_wdl_B_W_ghillie_spotter_wdl_F",
            "ghost_US_wdl_B_W_ghillie_wdl_F",
            "ghost_US_wdl_B_W_qav_abramsx",
            "ghost_US_wdl_B_W_soldier_M_F",
            "ghost_US_wdl_B_W_soldier_UAV_02_LxWS_F",
            "ghost_US_wdl_B_W_soldier_UAV_06_F",
            "ghost_US_wdl_B_W_soldier_UAV_06_medical_F",
            "ghost_US_wdl_B_W_soldier_UGV_02_Demining_F",
            "ghost_US_wdl_B_W_soldier_UGV_02_Science_F",
            "ghost_US_wdl_B_W_soldier_mine_F"
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        // ghost_fa_tiers IS NOT REQUIRED, DELIBERATELY. The tier
        // magazines are named as STRINGS in magazines[]; nothing here
        // inherits from them, so there is no load order to enforce.
        // Requiring it was fatal: fa_tiers requires fa_rhs, fa_sps,
        // fa_e22raf and fa_jca, which require RHS, SPS, E22 and JCA -
        // and with skipWhenMissingDependencies any one of those absent
        // dropped this whole faction out of 3DEN and Zeus in silence.
        //
        // NOTHING FROM THE SOURCE FACTION'S MOD IS REQUIRED EITHER.
        // Every parent class is forward-declared in CfgVehicles.hpp, so a
        // load order without that mod gets inert classes instead of a
        // broken config. skipWhenMissingDependencies does the rest.
        requiredAddons[] = {"ghost_main"};
        skipWhenMissingDependencies = 1;
        author = QAUTHOR;
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
