// Generated by tools/gen_himf.py - re-run rather than hand-edit.
//
// EVERY MAN IS THIS FACTION'S OWN - see CfgVehicles.hpp. The twenty
// groups are the old HIMF's, role for role.

class CfgGroups {
    class West {

        class ghost_HIMF {
            name = "2040 HIMF";

            class Infantry {
                name = "Infantry";

                class ghost_HIMF_InfSentry {
                    name = "Sentry";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Grenadier";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };
                };

                class ghost_HIMF_InfSquad {
                    name = "Rifle Squad";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_RadioOperator";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Marksman";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "CORPORAL";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = "ghost_HIMF_UAVOperator";
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };
                };

                class ghost_HIMF_InfSquad_Weapons {
                    name = "Weapons Squad";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Grenadier";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Marksman";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_HeavyGunner";
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {20,-20,0};
                    };
                };

                class ghost_HIMF_InfTeam {
                    name = "Fire Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Grenadier";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class ghost_HIMF_InfTeam_AT {
                    name = "Anti-armor Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

            };

            class Mechanized {
                name = "Mechanized";

                class ghost_HIMF_MechInfSquad {
                    name = "Mechanized Rifle Squad";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_mech_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_APC_HMG";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_RadioOperator";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_Marksman";
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "CORPORAL";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 1;
                        vehicle = "ghost_HIMF_UAVOperator";
                        rank = "PRIVATE";
                        position[] = {25,-25,0};
                    };
                };

                class ghost_HIMF_MechInf_Support {
                    name = "Mechanized Support Squad";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_mech_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_APC_HMG";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Engineer";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = "ghost_HIMF_ExplosiveSpecialist";
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };
                };

            };

            class Motorized {
                name = "Motorized";

                class ghost_HIMF_MotInf_AA {
                    name = "Motorized Air-defense Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Offroad";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AA";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AAA";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };
                };

                class ghost_HIMF_MotInf_AT {
                    name = "Motorized Anti-armor Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Offroad_AT";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };
                };

                class ghost_HIMF_MotInf_MortTeam {
                    name = "Motorized Mortar Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Offroad";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "CORPORAL";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_MortarGunner";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_MortarAssistant";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class ghost_HIMF_MotInf_Reinforcements {
                    name = "Motorized Reinforcements";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Pickup_Covered";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Pickup_Covered";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_RadioOperator";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_Marksman";
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "CORPORAL";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {25,-25,0};
                    };

                    class Unit10 {
                        side = 1;
                        vehicle = "ghost_HIMF_UAVOperator";
                        rank = "PRIVATE";
                        position[] = {-25,-25,0};
                    };

                    class Unit11 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {30,-30,0};
                    };

                    class Unit12 {
                        side = 1;
                        vehicle = "ghost_HIMF_RadioOperator";
                        rank = "PRIVATE";
                        position[] = {-30,-30,0};
                    };

                    class Unit13 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {35,-35,0};
                    };

                    class Unit14 {
                        side = 1;
                        vehicle = "ghost_HIMF_Marksman";
                        rank = "PRIVATE";
                        position[] = {-35,-35,0};
                    };

                    class Unit15 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "CORPORAL";
                        position[] = {40,-40,0};
                    };

                    class Unit16 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {-40,-40,0};
                    };

                    class Unit17 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {45,-45,0};
                    };

                    class Unit18 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {-45,-45,0};
                    };

                    class Unit19 {
                        side = 1;
                        vehicle = "ghost_HIMF_UAVOperator";
                        rank = "PRIVATE";
                        position[] = {50,-50,0};
                    };
                };

                class ghost_HIMF_MotInf_Squad {
                    name = "Motorized Rifle Squad";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Pickup_Covered";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_SquadLeader";
                        rank = "SERGEANT";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_RadioOperator";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_Marksman";
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "CORPORAL";
                        position[] = {15,-15,0};
                    };

                    class Unit6 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {-15,-15,0};
                    };

                    class Unit7 {
                        side = 1;
                        vehicle = "ghost_HIMF_AmmoBearer";
                        rank = "PRIVATE";
                        position[] = {20,-20,0};
                    };

                    class Unit8 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {-20,-20,0};
                    };

                    class Unit9 {
                        side = 1;
                        vehicle = "ghost_HIMF_UAVOperator";
                        rank = "PRIVATE";
                        position[] = {25,-25,0};
                    };
                };

                class ghost_HIMF_MotInf_Team {
                    name = "Motorized Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_motor_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Offroad_LMG";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman_AT";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class ghost_HIMF_ReconPatrol {
                    name = "Recon Patrol";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\n_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_TL";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_M";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_Medic";
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class ghost_HIMF_ReconSentry {
                    name = "Recon Sentry";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\n_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_M";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };
                };

                class ghost_HIMF_ReconTeam {
                    name = "Recon Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\n_recon.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_TL";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_M";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_Medic";
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_AT";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };

                    class Unit4 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_JTAC";
                        rank = "PRIVATE";
                        position[] = {-10,-10,0};
                    };

                    class Unit5 {
                        side = 1;
                        vehicle = "ghost_HIMF_Recon_Demo";
                        rank = "PRIVATE";
                        position[] = {15,-15,0};
                    };
                };

            };

            class Support {
                name = "Support";

                class ghost_HIMF_Support_CLS {
                    name = "Support Team (CLS)";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Autorifleman";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Medic";
                        rank = "CORPORAL";
                        position[] = {10,-10,0};
                    };
                };

                class ghost_HIMF_Support_ENG {
                    name = "Support Team (Engineer)";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Engineer";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_Engineer";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_Rifleman";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class ghost_HIMF_Support_EOD {
                    name = "Support Team (EOD)";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_inf.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_Engineer";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_ExplosiveSpecialist";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };

                    class Unit3 {
                        side = 1;
                        vehicle = "ghost_HIMF_ExplosiveSpecialist";
                        rank = "PRIVATE";
                        position[] = {10,-10,0};
                    };
                };

                class ghost_HIMF_Support_Mort {
                    name = "Mortar Team";
                    side = 1;
                    faction = "ghost_HIMF";
                    icon = "\A3\UI_F\Data\Map\Markers\NATO\b_mortar.paa";

                    class Unit0 {
                        side = 1;
                        vehicle = "ghost_HIMF_TeamLeader";
                        rank = "SERGEANT";
                        position[] = {0,0,0};
                    };

                    class Unit1 {
                        side = 1;
                        vehicle = "ghost_HIMF_MortarGunner";
                        rank = "PRIVATE";
                        position[] = {5,-5,0};
                    };

                    class Unit2 {
                        side = 1;
                        vehicle = "ghost_HIMF_MortarAssistant";
                        rank = "PRIVATE";
                        position[] = {-5,-5,0};
                    };
                };

            };

        };
    };
};
