// Generated by tools/gen_himf.py - re-run rather than hand-edit.
//
// FORWARD DECLARATIONS, NOT DEPENDENCIES. Every parent below is the
// base game's, defined in an addon that is not this one; declaring
// it is what lets this config inherit from it.

class CfgVehicles {
    class EGVAR(uniform,B_H_Crew_F);
    class EGVAR(uniform,B_H_Engineer_F);
    class EGVAR(uniform,B_H_HeavyGunner_F);
    class B_Heli_EC_03_RF;
    class B_Heli_EC_04_military_RF;
    class EGVAR(uniform,B_H_Helicrew_F);
    class EGVAR(uniform,B_H_Helipilot_F);
    class EGVAR(uniform,B_H_Medic_F);
    class EGVAR(uniform,B_H_Officer_F);
    class EGVAR(uniform,B_H_RadioOperator_F);
    class EGVAR(uniform,B_H_Soldier_AR_F);
    class EGVAR(uniform,B_H_Soldier_A_F);
    class EGVAR(uniform,B_H_Soldier_Exp_F);
    class EGVAR(uniform,B_H_Soldier_F);
    class EGVAR(uniform,B_H_Soldier_GL_F);
    class EGVAR(uniform,B_H_Soldier_LAT_F);
    class EGVAR(uniform,B_H_Soldier_SL_F);
    class EGVAR(uniform,B_H_Soldier_TL_F);
    class EGVAR(uniform,B_H_Soldier_commando_AR_F);
    class EGVAR(uniform,B_H_Soldier_commando_F);
    class EGVAR(uniform,B_H_Soldier_commando_LAT_F);
    class EGVAR(uniform,B_H_Soldier_commando_M_F);
    class EGVAR(uniform,B_H_Soldier_commando_TL_F);
    class EGVAR(uniform,B_H_Soldier_commando_exp_F);
    class EGVAR(uniform,B_H_Soldier_commando_gl_F);
    class EGVAR(uniform,B_H_Soldier_commando_jtac_F);
    class EGVAR(uniform,B_H_Soldier_commando_medic_F);
    class EGVAR(uniform,B_H_Soldier_unarmed_F);
    class EGVAR(uniform,B_H_soldier_M_F);
    class B_Boat_Armed_01_minigun_F;
    class B_CommandoMortar_RF;
    class B_G_Offroad_01_AT_F;
    class B_G_Offroad_01_F;
    class B_G_Offroad_01_armed_F;
    class B_HMG_01_high_F;
    class B_Heli_Light_01_F;
    class B_Heli_Light_01_dynamicLoadout_F;
    class B_Heli_light_03_dynamicLoadout_RF;
    class B_Mortar_01_F;
    class B_SwitchBlade_300_LaunchTube_Woodland;
    class B_SwitchBlade_600_LaunchTube_Woodland;
    class B_T_Boat_Transport_01_F;
    class B_T_HMG_01_F;
    class B_T_Mortar_01_F;
    class B_T_Quadbike_01_F;
    class B_T_UAV_03_dynamicLoadout_F;
    class B_UAV_01_F;
    class B_UAV_06_F;
    class B_UGV_01_F;
    class B_UGV_01_rcws_F;
    class B_UGV_02_Demining_F;
    class EF_B_Gyra_GEN;
    class EF_B_Gyra_HMG_GEN;
    class FA_EMB312_AT27M35_Nato_P;
    class GX_B_HUNTER_SP_LAUNCHER;
    class GX_B_MAGURA_V5_USV;
    class GX_B_RQ11B_UAV;
    class Pickup_01_Rocket_base_rf;
    class Pickup_01_aat_base_rf;
    class Pickup_01_base_rf;
    class Pickup_01_hmg_base_rf;
    class Pickup_01_mmg_base_rf;
    class Pickup_01_mrl_base_rf;
    class Pickup_01_rcws_base_rf;
    class Pickup_comms_base_rf;
    class Pickup_covered_base_rf;
    class Pickup_fuel_base_rf;
    class Pickup_repair_ig_base_rf;
    class EGVAR(vehicle,Plane_Civil_01_HIMF_F);
    class ace_dragon_staticAssembled;
    class rksla3_aeroshark_blufor;
    class rksla3_uav_rq7shadow_01_blufor;

    // ---- the uniform bodies - Atlas's HIMF paint on base-game models, see CfgWeapons.hpp ----

    // ---- the men ----
    class GVAR(Rifleman): EGVAR(uniform,B_H_Soldier_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Rifleman";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
    };
    class GVAR(Rifleman_Unarmed): EGVAR(uniform,B_H_Soldier_unarmed_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Rifleman (Unarmed)";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
    };
    class GVAR(SquadLeader): EGVAR(uniform,B_H_Soldier_SL_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Squad Leader";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_F),QEGVAR(weapons,hgun_ACPC2_black_F),"Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_F),QEGVAR(weapons,hgun_ACPC2_black_F),"Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","HandGrenade","SmokeShell","SmokeShellYellow"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","HandGrenade","SmokeShell","SmokeShellYellow"};
    };
    class GVAR(TeamLeader): EGVAR(uniform,B_H_Soldier_TL_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Team Leader";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_GL_F),QEGVAR(weapons,hgun_ACPC2_black_F),"Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_GL_F),QEGVAR(weapons,hgun_ACPC2_black_F),"Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","HandGrenade","SmokeShell","SmokeShellYellow","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","HandGrenade","SmokeShell","SmokeShellYellow","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"};
    };
    class GVAR(Autorifleman): EGVAR(uniform,B_H_Soldier_AR_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Autorifleman";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"200Rnd_556x45_Box_Tracer_Red_F","200Rnd_556x45_Box_Tracer_Red_F","200Rnd_556x45_Box_Tracer_Red_F","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"200Rnd_556x45_Box_Tracer_Red_F","200Rnd_556x45_Box_Tracer_Red_F","200Rnd_556x45_Box_Tracer_Red_F","HandGrenade","SmokeShell"};
    };
    class GVAR(AmmoBearer): EGVAR(uniform,B_H_Soldier_A_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ammo Bearer";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
    };
    class GVAR(Grenadier): EGVAR(uniform,B_H_Soldier_GL_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Grenadier";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_GL_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_GL_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","HandGrenade","SmokeShell","1Rnd_Smoke_Grenade_shell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","HandGrenade","SmokeShell","1Rnd_Smoke_Grenade_shell"};
        backpack = QGVAR(UAV_06_Bag);
    };
    class GVAR(Rifleman_AT): EGVAR(uniform,B_H_Soldier_LAT_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Rifleman (AT)";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_Grip_F),"launch_MRAWS_olive_rail_F","Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_Grip_F),"launch_MRAWS_olive_rail_F","Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"MRAWS_HEAT55_F","HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"MRAWS_HEAT55_F","HandGrenade","SmokeShell"};
    };
    class GVAR(Rifleman_AA): EGVAR(uniform,B_H_Soldier_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Missile Specialist (AA)";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        weapons[] = {QEGVAR(weapons,arifle_famasF1_F),"launch_B_Titan_F","Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_F),"launch_B_Titan_F","Throw","Put"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"Titan_AA","HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"Titan_AA","HandGrenade","SmokeShell"};
    };
    class GVAR(Rifleman_AAA): EGVAR(uniform,B_H_Soldier_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Assistant Missile Specialist (AA)";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        weapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put","Rangefinder"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put","Rangefinder"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"Titan_AA","HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"Titan_AA","HandGrenade","SmokeShell"};
        backpack = "B_Carryall_oli";
    };
    class GVAR(Marksman): EGVAR(uniform,B_H_soldier_M_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Marksman";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","HandGrenade","SmokeShell"};
    };
    class GVAR(HeavyGunner): EGVAR(uniform,B_H_HeavyGunner_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Heavy Gunner";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,200Rnd_762x51_MAG_Red_F),QEGVAR(weapons,200Rnd_762x51_MAG_Red_F),"HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,200Rnd_762x51_MAG_Red_F),QEGVAR(weapons,200Rnd_762x51_MAG_Red_F),"HandGrenade","SmokeShell"};
    };
    class GVAR(Medic): EGVAR(uniform,B_H_Medic_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Combat Life Saver";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_Grip_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_Grip_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),"HandGrenade","SmokeShell","SmokeShellRed","SmokeShellBlue","SmokeShellOrange"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),QEGVAR(weapons,25Rnd_556x45_Famas),"HandGrenade","SmokeShell","SmokeShellRed","SmokeShellBlue","SmokeShellOrange"};
    };
    class GVAR(Engineer): EGVAR(uniform,B_H_Engineer_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Engineer";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_RIS_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_RIS_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"SmokeShell","SmokeShellYellow"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"SmokeShell","SmokeShellYellow"};
    };
    class GVAR(ExplosiveSpecialist): EGVAR(uniform,B_H_Soldier_Exp_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Explosive Specialist";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_RIS_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_RIS_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"APERSMine_Range_Mag","APERSMine_Range_Mag","APERSMine_Range_Mag","SmokeShell","SmokeShellYellow"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"APERSMine_Range_Mag","APERSMine_Range_Mag","APERSMine_Range_Mag","SmokeShell","SmokeShellYellow"};
    };
    class GVAR(Officer): EGVAR(uniform,B_H_Officer_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Officer";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","SmokeShellYellow"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","SmokeShellYellow"};
    };
    class GVAR(RadioOperator): EGVAR(uniform,B_H_RadioOperator_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Radio Operator";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Red","HandGrenade","SmokeShell"};
    };
    class GVAR(MortarGunner): EGVAR(uniform,B_H_Soldier_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gunner (Mortar)";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
        backpack = "B_Mortar_01_weapon_F";
    };
    class GVAR(MortarAssistant): EGVAR(uniform,B_H_Soldier_A_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Assistant Gunner (Mortar)";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        respawnWeapons[] = {QEGVAR(weapons,arifle_famasF1_F),"Throw","Put"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
        respawnMagazines[] = {QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),QEGVAR(weapons,25Rnd_556x45_Famas_Tracer_Red),"HandGrenade","SmokeShell"};
        backpack = "B_Mortar_01_support_F";
    };
    class GVAR(Crew): EGVAR(uniform,B_H_Crew_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Crewman";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","HandGrenade","SmokeShell"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","HandGrenade","SmokeShell"};
    };
    class GVAR(Helipilot): EGVAR(uniform,B_H_Helipilot_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Helicopter Pilot";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","SmokeShellYellow"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","SmokeShellYellow"};
    };
    class GVAR(Helicrew): EGVAR(uniform,B_H_Helicrew_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Helicopter Crew";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","SmokeShellYellow"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","SmokeShellYellow"};
    };
    class GVAR(Pilot): EGVAR(uniform,B_H_Helipilot_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Pilot";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","SmokeShellYellow"};
        respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","30Rnd_9x21_Mag_SMG_02_Tracer_Red","SmokeShellYellow"};
    };
    class GVAR(Recon): EGVAR(uniform,B_H_Soldier_commando_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Scout";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
    };
    class GVAR(Recon_TL): EGVAR(uniform,B_H_Soldier_commando_TL_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Team Leader";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"hgun_P07_blk_Snds_F","Throw","Put","Rangefinder"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"hgun_P07_blk_Snds_F","Throw","Put","Rangefinder"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShellGreen","SmokeShellBlue","SmokeShellOrange","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShellGreen","SmokeShellBlue","SmokeShellOrange","Chemlight_green","Chemlight_green"};
    };
    class GVAR(Recon_AR): EGVAR(uniform,B_H_Soldier_commando_AR_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Autorifleman";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"200Rnd_65x39_cased_Box_Tracer_Red","200Rnd_65x39_cased_Box_Tracer_Red","200Rnd_65x39_cased_Box_Tracer_Red","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","SmokeShell","SmokeShell","Chemlight_red","Chemlight_red"};
        respawnMagazines[] = {"200Rnd_65x39_cased_Box_Tracer_Red","200Rnd_65x39_cased_Box_Tracer_Red","200Rnd_65x39_cased_Box_Tracer_Red","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","SmokeShell","SmokeShell","Chemlight_red","Chemlight_red"};
    };
    class GVAR(Recon_GL): EGVAR(uniform,B_H_Soldier_commando_gl_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Grenadier";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_GL_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_GL_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green","1Rnd_Smoke_Grenade_shell","1Rnd_Smoke_Grenade_shell"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","1Rnd_HE_Grenade_shell","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green","1Rnd_Smoke_Grenade_shell","1Rnd_Smoke_Grenade_shell"};
    };
    class GVAR(Recon_AT): EGVAR(uniform,B_H_Soldier_commando_LAT_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Scout (AT)";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"launch_NLAW_F","hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"launch_NLAW_F","hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","NLAW_F","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","NLAW_F","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
    };
    class GVAR(Recon_M): EGVAR(uniform,B_H_Soldier_commando_M_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Marksman";
        side = 1;
        faction = QUOTE(ADDON);
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
    };
    class GVAR(Recon_Medic): EGVAR(uniform,B_H_Soldier_commando_medic_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Paramedic";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_Grip_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShellRed","SmokeShellBlue","SmokeShellOrange","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShellRed","SmokeShellBlue","SmokeShellOrange","Chemlight_green","Chemlight_green"};
    };
    class GVAR(Recon_JTAC): EGVAR(uniform,B_H_Soldier_commando_jtac_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon JTAC";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_F),"hgun_P07_blk_Snds_F","Throw","Put","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_F),"hgun_P07_blk_Snds_F","Throw","Put","Laserdesignator_01_khk_F"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","B_IR_Grenade","B_IR_Grenade","Laserbatteries","SmokeShell","SmokeShellGreen","SmokeShellBlue","SmokeShellOrange","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","MiniGrenade","MiniGrenade","B_IR_Grenade","B_IR_Grenade","Laserbatteries","SmokeShell","SmokeShellGreen","SmokeShellBlue","SmokeShellOrange","Chemlight_green","Chemlight_green"};
    };
    class GVAR(Recon_Demo): EGVAR(uniform,B_H_Soldier_commando_exp_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Recon Demo Specialist";
        side = 1;
        faction = QUOTE(ADDON);
        weapons[] = {QEGVAR(weapons,Arifle_famasG2_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        respawnWeapons[] = {QEGVAR(weapons,Arifle_famasG2_F),"hgun_P07_blk_Snds_F","Throw","Put","Binocular"};
        identityTypes[] = {"LanguageENG_F","Head_Tanoan","G_NATO_default"};
        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","APERSMine_Range_Mag","APERSMine_Range_Mag","APERSMine_Range_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","APERSMine_Range_Mag","APERSMine_Range_Mag","APERSMine_Range_Mag","MiniGrenade","MiniGrenade","SmokeShell","SmokeShell","Chemlight_green","Chemlight_green"};
    };

    // ---- the drone bags - the base game's, assembling HIMF's own drones - see BAGS ----
    class B_UAV_01_backpack_F;
    class GVAR(UAV_01_Bag): B_UAV_01_backpack_F {
        scope = 1;
        scopeCurator = 0;
        author = QAUTHOR;
        class assembleInfo {
            primary = 1;
            base = "";
            assembleTo = QGVAR(UAV_Darter);
            displayName = "AR-2 Darter";
            dissasembleTo[] = {};
        };
    };
    class B_UAV_06_backpack_F;
    class GVAR(UAV_06_Bag): B_UAV_06_backpack_F {
        scope = 1;
        scopeCurator = 0;
        author = QAUTHOR;
        class assembleInfo {
            primary = 1;
            base = "";
            assembleTo = QGVAR(UAV_Pelican);
            displayName = "AL-6 Pelican";
            dissasembleTo[] = {};
        };
    };

    // ---- the men who carry a system instead of a rucksack ----
    class GVAR(UAVOperator): GVAR(Rifleman) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "UAV Operator";
        faction = QUOTE(ADDON);
        backpack = QGVAR(UAV_01_Bag);
    };
    class GVAR(PelicanOperator): GVAR(Rifleman) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Pelican Operator";
        faction = QUOTE(ADDON);
        backpack = QGVAR(UAV_06_Bag);
    };

    // ---- the vehicles ----
    class GVAR(APC): EF_B_Gyra_GEN {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gyra";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Crew);
        // an empty textureList stopped the game repainting a spawned vehicle, but it also emptied the appearance
        // dropdown (user, 2026-09-19: "the vechicle customation is mission all the textures"). Naming the paint
        // it wears does both jobs and keeps the parent's paints listed under it.
        textureList[] = {"ghost_paint", 1};
        hiddenSelectionsTextures[] = {
            "ef\ef_gyra_t\data\gyra_hull_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_details_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_int_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_hmg_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_rws_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_turret_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_mortar_1_olive_co.paa",
            "a3\armor_f\data\camonet_nato_green_co.paa"
        };
        class TextureSources {
            class ghost_paint {
                displayName = "Factory paint";
                author = QAUTHOR;
                textures[] = {"ef\ef_gyra_t\data\gyra_hull_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_details_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_int_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_hmg_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_rws_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_turret_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_mortar_1_olive_co.paa", "a3\armor_f\data\camonet_nato_green_co.paa"};
            };
        };
    };
    class GVAR(APC_HMG): EF_B_Gyra_HMG_GEN {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Gyra HMG";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Crew);
        // an empty textureList stopped the game repainting a spawned vehicle, but it also emptied the appearance
        // dropdown (user, 2026-09-19: "the vechicle customation is mission all the textures"). Naming the paint
        // it wears does both jobs and keeps the parent's paints listed under it.
        textureList[] = {"ghost_paint", 1};
        hiddenSelectionsTextures[] = {
            "ef\ef_gyra_t\data\gyra_hull_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_details_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_int_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_hmg_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_rws_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_turret_1_olive_co.paa",
            "ef\ef_gyra_t\data\gyra_mortar_1_olive_co.paa",
            "a3\armor_f\data\camonet_nato_green_co.paa"
        };
        class TextureSources {
            class ghost_paint {
                displayName = "Factory paint";
                author = QAUTHOR;
                textures[] = {"ef\ef_gyra_t\data\gyra_hull_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_details_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_int_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_hmg_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_rws_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_turret_1_olive_co.paa", "ef\ef_gyra_t\data\gyra_mortar_1_olive_co.paa", "a3\armor_f\data\camonet_nato_green_co.paa"};
            };
        };
    };
    class GVAR(Boat): B_T_Boat_Transport_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Assault Boat";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Boat_Armed): B_Boat_Armed_01_minigun_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Speedboat Minigun";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Mortar): B_T_Mortar_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Mk6 Mortar";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(MortarGunner);
    };
    class GVAR(HMG): B_T_HMG_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Mk30 HMG .50";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(HMG_High): B_HMG_01_high_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Mk30 HMG .50 (Raised)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Mortar_Commando): B_CommandoMortar_RF {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Commando Mortar";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(MortarGunner);
    };
    class GVAR(Mortar_Mk6): B_Mortar_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Mk6 Mortar (Olive)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(MortarGunner);
    };
    class GVAR(AT_Dragon): ace_dragon_staticAssembled {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "M47 Super-Dragon";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(LM_Tube_300): B_SwitchBlade_300_LaunchTube_Woodland {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "SwitchBlade 300 Launch Tube";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(LM_Tube_600): B_SwitchBlade_600_LaunchTube_Woodland {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "SwitchBlade 600 Launch Tube";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(UAV_Hunter_SP): GX_B_HUNTER_SP_LAUNCHER {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Hunter SP Launcher";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Heli_Transport): B_Heli_EC_03_RF {                    // Atlas left the load order (2026-10-05): its EC helicopters were built on these
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "H225M Super Cougar";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Helipilot);
    };
    class GVAR(Heli_Transport_Unarmed): B_Heli_EC_04_military_RF {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "H225M Super Cougar (Unarmed)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Helipilot);
    };
    class GVAR(Heli_Light): B_Heli_Light_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "MH-9 Hummingbird";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Helipilot);
    };
    class GVAR(Heli_Light_Armed): B_Heli_Light_01_dynamicLoadout_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "AH-9 Pawnee";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Helipilot);
    };
    class GVAR(Heli_Light_Hellcat): B_Heli_light_03_dynamicLoadout_RF {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "WY-55 Hellcat";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Helipilot);
    };
    class GVAR(Offroad): B_G_Offroad_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Offroad";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Offroad_LMG): B_G_Offroad_01_armed_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Offroad (HMG)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Offroad_AT): B_G_Offroad_01_AT_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Offroad (AT)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(Plane_Tucano): FA_EMB312_AT27M35_Nato_P {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "AT-27M35 Tucano";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Pilot);
        // an empty textureList stopped the game repainting a spawned vehicle, but it also emptied the appearance
        // dropdown (user, 2026-09-19: "the vechicle customation is mission all the textures"). Naming the paint
        // it wears does both jobs and keeps the parent's paints listed under it.
        textureList[] = {"ghost_paint", 1};
        hiddenSelectionsTextures[] = {
            "FA_EMB312\data\textures\body_grey_co.paa",
            "FA_EMB312\data\textures\body_details_grey_co.paa",
            "FA_EMB312\data\textures\body_rear_grey_co.paa",
            "FA_EMB312\data\textures\elevators_grey_co.paa",
            "FA_EMB312\data\textures\exhaust_grey_co.paa",
            "FA_EMB312\data\textures\rudder_grey_co.paa",
            "FA_EMB312\data\textures\wings_grey_co.paa",
            "FA_EMB312\data\textures\wings_details_grey_co.paa",
            "FA_EMB312\data\textures\cockpit_grey_co.paa"
        };
        class TextureSources {
            class ghost_paint {
                displayName = "Factory paint";
                author = QAUTHOR;
                textures[] = {"FA_EMB312\data\textures\body_grey_co.paa", "FA_EMB312\data\textures\body_details_grey_co.paa", "FA_EMB312\data\textures\body_rear_grey_co.paa", "FA_EMB312\data\textures\elevators_grey_co.paa", "FA_EMB312\data\textures\exhaust_grey_co.paa", "FA_EMB312\data\textures\rudder_grey_co.paa", "FA_EMB312\data\textures\wings_grey_co.paa", "FA_EMB312\data\textures\wings_details_grey_co.paa", "FA_EMB312\data\textures\cockpit_grey_co.paa"};
            };
        };
    };
    class GVAR(Plane_Civil): EGVAR(vehicle,Plane_Civil_01_HIMF_F) {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Caesar BTT";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Pilot);
    };
    class GVAR(Quadbike): B_T_Quadbike_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Quad Bike";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
    };
    class GVAR(UAV_Darter): B_UAV_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "AR-2 Darter";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UAV_Falcon): B_T_UAV_03_dynamicLoadout_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "UCAV Sentinel";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UAV_Pelican): B_UAV_06_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "AL-6 Pelican";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UGV_Stomper): B_UGV_01_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "UGV Stomper";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UGV_Stomper_RCWS): B_UGV_01_rcws_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "UGV Stomper RCWS";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UGV_Pelter): B_UGV_02_Demining_F {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "ED-1D Pelter";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UAV_Shadow): rksla3_uav_rq7shadow_01_blufor {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "RQ-7 Shadow 200";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UAV_Aeroshark): rksla3_aeroshark_blufor {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Aeroshark Mini UAV";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(USV_Magura): GX_B_MAGURA_V5_USV {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "MAGURA V5";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(UAV_Raven): GX_B_RQ11B_UAV {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "RQ-11B Raven";
        side = 1;
        faction = QUOTE(ADDON);
    };
    class GVAR(Pickup): Pickup_01_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_Comms): Pickup_comms_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Comms)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_Covered): Pickup_covered_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Covered)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_HMG): Pickup_01_hmg_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (HMG)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_MMG): Pickup_01_mmg_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (MMG)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_RCWS): Pickup_01_rcws_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (RCWS)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_AA): Pickup_01_aat_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Anti-Air)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_MRL): Pickup_01_mrl_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (MRL)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_Rocket): Pickup_01_Rocket_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Rocket)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_Fuel): Pickup_fuel_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Fuel)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
    class GVAR(Pickup_Repair): Pickup_repair_ig_base_rf {
        scope = 2;
        scopeCurator = 2;
        author = QAUTHOR;
        displayName = "Ram 1500 (Repair)";
        side = 1;
        faction = QUOTE(ADDON);
        crew = QGVAR(Rifleman);
        textureList[] = {"Jungle",1};
        animationList[] = {"hide_frame",1,"hide_shield",1};
    };
};
